### ISSUE TITLE
Spfx framework support of Sharepoint 2016 on-premises

### ISSUE THREAD

**Issue by lhoff** [SharePoint/sp-dev-docs#1102]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is Sharepoint 2016 on-premises only supported in v1.1.0 of the spfx framework and not in anything after that?

I'm asking because the discussion in [issue #1075](https://github.com/SharePoint/sp-dev-docs/issues/1075) seems to suggest that is the case. And my own experience of trying to upgrade a web part from 1.1.0 to 1.3.4 and having it break when it is deployed (see issue [#1100](https://github.com/SharePoint/sp-dev-docs/issues/1100)) to our on-premises installation bears that assumption out.

**Comment by VesaJuvonen** [comment]
That is correct, on-premises only supports v1.1 simply release logistics and this is also why there's a separate question on online/on-prem in the Yeoman flow. 

Extensions or new capabilities introduced in SPFx Yeoman templates have also server-side dependencies, so we cannot support them in on-premises until the capabilities are added to server side. This is why currently only 1.1 is supported since that support was included with the Feature Pack 2 for SP2016... FP2 SPFx capabilities were forked from the SPO code during June 2017 and then integrated to server side.
