### ISSUE TITLE
update the dataVersion

### ISSUE THREAD

**Issue by mdissel** [SharePoint/sp-dev-docs#1154]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [X ] Additional article idea

#### Question
When should we increment the dataVersion for a webpart? Is there any documentation?
Should it be updated when you add/remove an configuration item?

**Comment by manishgarg1** [comment]
Hi @mdissel, yes we do plan to provide some detailed documentation on this but here is a basic idea.

The dataVersion property is to help you manage you web parts serialized state as the code of your web part evolves due to changing functionality needs. It is yet another tool for a developer to help evolve the web part without breaking. It should be used only when needed. Here is a brief explanation. Please reply in case the usage is still not clear.

**Data Version**
Apart from code version, the web part framework also supports the ability to manage web part persisted data versions. As a developer evolves the web part code and functionality, it is imperative that they will see the need for newer properties in the web part data. A web part can override the dataVersion API from the BaseClientSideWebPart class. The default value of this property is 1.0. The developer can override this to any value in their web part code. The value of this property is persisted with the web part data. A sample is shown below. During the web part loading life cycle, the framework first deserializes the web part properties. And then calls the onAfterDeserialize API. This gives the web part developer an opportunity to update the deserialized properties to comply with the current version of the code.
// Web part persisted data format
interface IWebPartData {
	...
	dataVersion: string;
	...
}
