### ISSUE TITLE
IFieldCustomizerCellEventParameters.fieldValue data structure changed after GA release

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#1159]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

The question is related to ISVs products.
Let's say we developed a SPFx Extension and deployed it to multiple customers. This extension is based on a specific version of SPFx.
Then, you release newer version with some critical changes. And these changes are related not to the client side but back end.
And you're releasing this new version granularly, one by one. Some of customers may still use old version, some new.

How do you thing we should manage these situations?

I can provide and example.

Field Customizer.
One of initial versions had `cellValue` property in `onRenderCell` event arguments. the type of the property was `string`.
Later, you've changed the interface of the event args object, removed `cellValue` and added `fieldValue`. The type, again, was `string`.
Currently, `fieldValue` is an object and its properties depend on the type of the field.
It means that any Field Customizer for, for example, User Field will throw an error or render `[object Object]` instead of User's name...

What are your thoughts on such situation?

**Comment by waldekmastykarz** [comment]
If you ask me, as long as SPFx is in the v1.x range, it shouldn't introduce breaking changes. If it does, then the new version should follow SemVer conventions and be a major update. Additionally, both v1 and v2 should be supported for foreseeable future, giving organizations sufficient time to prepare upgrade.

@AJIXuMuK regarding the change you mentioned: was the change within the v1.x range or was it before extensions hit GA?

**Comment by AJIXuMuK** [comment]
@waldekmastykarz `cellValue` was changed to `fieldValue` with GA release. And that's fine. I included it here just for 'history' of changes :)
But the type of `fieldValue` was changed after GA. On Ignite I discussed this property with dev team and they said that it contains text that can be rendered in the cell.

Interesting thing that I can't find Release Notes for v1.3 in docs...

**Comment by waldekmastykarz** [comment]
@VesaJuvonen, any comment on this one?

**Comment by andrewconnell** [comment]
Hey @AJIXuMuK, here are the change log entries for 1.3:

## 1.3.0
Fri, 22 Sep 2017 20:19:09 GMT

### Minor changes
- Update the default group and group ID in generated web part manifests to be "Other".
- Create elements.xml file for extensions
- Support the new schema for serve.json for extensions

### Patches
- Add yeoman test for application-customizer.
- Add yeoman tests for FieldCustomizer and CommandSet extensions.
- Enable the ability to create a webpart compatible with SharePoint 2016 Feature Pack 2.
- Replace Promise.resolve() for Promise.resolve() in the templates.
- Join web part properties in the same file as the web part
- Application customizer generator provides an SPFx dialog
- Remove "Preview" from client-side extensions generator
- Update some CSS to use theming

**Comment by AJIXuMuK** [comment]
@andrewconnell thanks!
Is it published somewhere? Because on Wiki ([https://github.com/SharePoint/sp-dev-docs/wiki](https://github.com/SharePoint/sp-dev-docs/wiki)) I've found 1.2 and then 1.4 only...

Still, none of the release notes contain any information about `fieldValue`.
Good thing is that SharePoint Framework Reference documentation contains:
```
readonly fieldValue: any;
```

**Comment by andrewconnell** [comment]
@AJIXuMuK no... Microsoft isn't publishing the source to the generator which is disappointing. 

Back in June I was thinking about doing a series of posts when there was an update that picked apart what was new with each release... you can see one of those posts here: [SharePoint Framework Generator Recent Updates (v1.1.1) and Sign of On-Prem SPFx to Come?](http://www.andrewconnell.com/blog/sharepoint-framework-generator-recent-updates-v1-1-1-and-sign-of-on-prem-spfx-to-come). Think there would be interest in this going forward with each release?

I have a scheduled process that runs daily that installs the generator and it's dependencies, checking in all changes to a private git repo I have. It requires a lot of explanation so I don't make it public & instead just keep it for my purpose. It also creates a new instance of each permutation of project / artifact type... this way if something breaks in the dependency hierarchy. It's what I used when something broke one night back in March [Troubleshooting and Fixing the "Out of the Blue, My SharePoint Framework Projects Won't Build!"](http://www.andrewconnell.com/blog/troubleshooting-and-fixing-the-out-of-the-blue-my-sharepoint-framework-projects-wont-build). At some point I'd like to create a browser out of this to share with the community... alas... no time :)

The repo looks something like this:

![image](https://user-images.githubusercontent.com/2068657/34171491-771d0a18-e4bc-11e7-8420-19a34cc7197f.png)

But to your point, I do have the changelog for each release... Think it would help to post this as a blog post going forward? Not just the changelog, but picking apart what changed?

**Comment by AJIXuMuK** [comment]
@andrewconnell I think it might be helpful for the community. I was thinking about that as well, but I'm far from you in preparation and implementation :).
Also, as I know, @estruyf has something similar as well.

**Comment by AJIXuMuK** [comment]
One more thing that I've found: at some point version of lodash that is loaded to the page has been decreased.
I'm using `import * as _ from 'lodash';` in my extension and later `_.startsWith` function.
It worked fine... WORKED.

Now it's compiled but throws runtime error that `_.startsWith` is not a function.

**Comment by pgonzal** [comment]
> Field Customizer.
> One of initial versions had `cellValue` property in `onRenderCell` event arguments. the type of the  property was `string`.
> Later, you've changed the interface of the event args object, removed `cellValue` and added `fieldValue`. The type, again, was `string`.
> Currently, `fieldValue` is an object and its properties depend on the type of the field.
> It means that any Field Customizer for, for example, User Field will throw an error or render `[object  Object]` instead of User's name...

This change occurred while the FieldCustomizer API was still in preview.  We are aware that we need to improve the way that we communicate whether an API is ready for production or not.  Today, there are two ways:

1. **In the JSDoc code comment in the \*.d.ts file:** if you see `@public` then it is ready for production.  If you see `@beta` then it is for preview only.  If you see `@alpha` or  `@internal`, or if the name begins with an underscore, then it's NOT supported.  If you don't see any tag in the comment, look at the comment for the containing definition, e.g. class or interface.  (You can read more about this system in the [API Extractor docs](https://github.com/Microsoft/web-build-tools/wiki/API-Extractor-~-AEDoc-tags).)

2. **The API reference web site:**  The API reference will contain a disclaimer for any definitions that are "preview".  For example, the [SPHttpClient.beginBatch](https://docs.microsoft.com/en-us/javascript/api/sp-http/sphttpclient) entry has a blue box that says "*This API is provided as a preview*."

We understand that these annotations are very easy for developers to overlook.  The current long term plan is to remove the non-production definitions from our \*.d.ts files.  This will prevent the unsupported definitions from appearing in your VS Code IntelliSense entirely.  For people who want to try the `@beta` definitions, we will publish separate "preview" releases of the SPFx packages, so you can opt-in.

> If you ask me, as long as SPFx is in the v1.x range, it shouldn't introduce breaking changes. 

We have never intentionally introduced a breaking change since 1.0 shipped.  Well, to qualify that:

- SharePoint reserves the right to break any definitions that are not explicitly designated as `@public`

- SharePoint reserves the right to introduce compile-time breaks when you upgrade your packages. This is unavoidable whenever we upgrade our compiler or \@types dependencies.  However, it only impacts developers who are installing new NPM packages -- your already-deployed web part bundles will never be impacted by a compile-time break.

So with these qualifications, we have never intentionally introduced a breaking change.

> If it does, then the new version should follow SemVer conventions and be a major update. 

We don't follow SemVer.  For example, a patch-level increment to an SPFx package may introduce a new API.  Our versioning commitment is that as long as the manifest version number in our datacenter is greater than what you used at development time, your already-shipped web part will never stop working.

We have never introduced a breaking change, but if we did, the major version number would change, and the old library would be loaded side-by-side, so your already-shipped web part would continue to work.  (Our preference is to avoid breaking changes. Instead we prefer to deprecate the old API and introduce the new one alongside it.  If that caused a perf issue, we would still prefer to lazy-load the old API for legacy web parts, versus introducing a breaking change.)

There are obviously some rough areas in this commitment with regards to CSS styles, polyfills, certain REST behaviors, etc, but we as much as possible we aim to uphold it.  We sometimes invest nontrivial effort in compatibility hacks to this end.

> It's what I used when something broke one night back in March _Troubleshooting and Fixing the "Out of the Blue, My SharePoint Framework Projects Won't Build!"_.

This is a separate topic.  The article describes problems with "npm install" producing different results for the SPFx dependencies because the NPM versions weren't locked down enough.  We don't have a fully complete solution for this yet, but it has been largely mitigated by eliminating SemVer patterns/ranges for all direct dependencies of our own packages.  The long term solution would be to publish a something like shrinkwrap/lock file with "known good" versions for a particular SPFx release.    I'm not aware of an accepted industry solution for this problem.  The `package-lock.json` of today is insufficient.  We've been experimenting with [pnpm](https://github.com/pnpm/pnpm) which offers some new tech for an old problem.

> One more thing that I've found: at some point version of lodash that is loaded 
> to the page has been decreased.
> I'm using import * as _ from 'lodash'; in my extension and
> later _.startsWith function.  It worked fine... WORKED.
> Now it's compiled but throws runtime error that _.startsWith is not a function.

Are you referring to [@microsoft/sp-lodash-subset](https://www.npmjs.com/package/@microsoft/sp-lodash-subset)?  I don't believe `_.startsWith` was ever part of the API for that package.  

If you're finding a random **lodash** bundle on the SharePoint page, you should NOT be using that.  The SPFx explicitly calls out supported public APIs; anything else is internal and likely to break due to the rapid evolution of a cloud-hosted product.

@VesaJuvonen @patmill FYI

**Comment by AJIXuMuK** [comment]
Hi @pgonzal for such detailed response! 
It is great to learn more about your commitments and processes!

> This change occurred while the FieldCustomizer API was still in preview.
Yes, `cellValue` changed to `fieldValue` when the extensions were in preview.
But (**correct me if I wrong**) the type of `fieldValue` has been changed later. I mean the real data that you're getting from back-end.
The API is still the same: `fieldValue: any`. But now for example for Lookup field, Taxonomy field, User field it contains object, not string.
Again, I might be wrong. But it looks like the response from back end changed...

> Are you referring to @microsoft/sp-lodash-subset? I don't believe _.startsWith was ever part of the API for that package.
No, I was referencing `lodash`. If you create the SPFx project from template you can reference it without installing any additional packages.
Looking deeper in `package-lock.json` I see that it is installed as a dependency and shouldn't be used. So, here, I believe, it is my bad and lack of documentation. Because why not to use the package if it is installed and available :)

**Comment by pgonzal** [comment]
>  I might be wrong. But it looks like the response from back end changed...

Hmmm...  If so that could have been unintentional.  Let me investigate that and see what the story is.

> I see that it is installed as a dependency and shouldn't be used. So, here, I believe, it is my bad and lack of documentation. Because why not to use the package if it is installed and available 

This issue is inherent in the design of NPM, independent of SPFx.  BTW the pnpm tool would protect you against this, since it only creates node_modules symlinks for dependencies that are explicitly listed in your package.json file.

**Comment by pgonzal** [comment]
Retitling to avoid confusion about the issue being investigated.  @mpasarin FYI

**Comment by patmill** [comment]
Closing this one down.  Back Compat is crucial, and any time we change a public interface in a non-backwards compatible way should be a bug.
