### ISSUE TITLE
cannot use spfx webpart  for listform on modern list

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-docs#1165]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice.

#### Expected or Desired Behavior
I should be able to use spfx webparts on listform pages on modern lists.

#### Observed Behavior
On Modern lists there is no way to edit the new/edit/display form and add a custom SPFX listfrom webpart,
#### Steps to Reproduce
try to add a webparrt to  a list form page

**Comment by VesaJuvonen** [comment]
Hi Russell,
I would not call this specifically a bug, rather enhancement idea for the modern list and library experience. We will never have one-to-one between classic and modern, since some capabilities might be only introduced in the modern side as well. You can already today use SPFx extensions to add additional widgets/functionalities on these lists, but it's indeed true that adding custom web parts on these pages is not supported. Since this is not, however, a bug/issue on the existing dev platform, rather a clear enhancement idea, would suggest using the UserVoice for submitting this and to provide additional details on the business scenarios - like what would the 3rd party web part do in this scenario? - This way we understand better the functional requirements what you have. Closing this from here for now.

**Comment by russgove** [comment]
created uservoice at. https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/32680255-allow-spfx-webparts-to-be-used-as-listforms
