### ISSUE TITLE
Question about extension behavior on modern route change

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/sp-dev-docs#1181]
_From @Saulius-Laurinaitis on November 23, 2017 14:0_

Hi,
I have interesting use case - I'm using extensions for notifications to show some message to the user which is working fine when I do standard redirect to the page and extension is reloaded, but when I click on the link to redirect to other page in the same site then extension remains and only page content is reloaded which is expected with react (modern) routing, but I would like to call my function on each redirect (even on modern routing). Possibly it is not supported on extensions, but would you think to include such a feature in the future release - I mean some kind a function (e.g. onPageRouteChange) which would be only called in extension on modern routing, but extension would remain as is?

The issue I found is on the root site, e.g. https://tenant.sharepoint.com/SitePages/Home.aspx and then you navigate to SharePoint page (click on the link in suite bar) https://tenant.sharepoint.com/_layouts/15/sharepoint.aspx and click back button on your browser. Extension is not loaded then.

#### Category
- [ x] Question / Suggestion
- [ x] Issue

Thanks 
Saulius

_Copied from original issue: SharePoint/sp-dev-fx-extensions#74_

**Comment by VesaJuvonen** [comment]
Potential duplicate of #1042

**Comment by mpasarin** [comment]
This is not related to the placeholder explicitly (as #1042 does) but to extensions in general. This problem was addressed in #1069 

From the original response there:

> In order to modify the behavior of the application customizer I would recommend hooking up a callback to the navigated event.
In your onInit method you should add something like `this.context.application.navigatedEvent.add(this, updateData)`
>The placeholders changed event triggers when the placeholder changes, but going from one page to the other doesn't change the placeholder themselves.
The application navigated will be triggered after doing the navigation, and the context information should be now up to date.

This will work for navigation between pages.
Also, note that SharePoint home does not support extensions at the time, so the extensions will not work in that specific page. Team sites, comm sites and article pages should work properly.
