### ISSUE TITLE
So many Build errors with latest version of TS , SP frameworks

### ISSUE THREAD

**Issue by ymihir** [SharePoint/sp-dev-docs#1195]
I am practicing deploying assets to SharePoint using SPFx framework. For this I need to install 1.4.0 as latest framework of SPFx. Following image will tell you the versions that I am having in my current solution. 
![builderror](https://user-images.githubusercontent.com/7568187/34480583-475bbe92-efd3-11e7-85b8-d699d26986b9.PNG)
What could be wrong in these versions. I am nearly getting 178 errors.  Most of the errors are coming for react\index.d.ts
node_modules\@microsoft\sp-webpart-base\node_modules\@types\react\index.d.ts(3569,12): error TS2403: Subsequent
variable declarations must have the same type.  Variable 'filter' must be of type ```
**node_modules\@microsoft\sp-webpart-base\node_modules\@types\react\index.d.ts(3569,12): error TS2403: Subsequent
variable declarations must have the same type.  Variable 'filter' must be of type 'SVGProps<SVGFilterElement>', but here has type 'SVGProps<SVGFilterElement>'.**
```

**Comment by waldekmastykarz** [comment]
When you create a new project, here is the list of dependencies and dev dependencies you get:

```json
  "dependencies": {
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@types/webpack-env": ">=1.12.1 <1.14.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.0",
    "@microsoft/sp-module-interfaces": "~1.4.0",
    "@microsoft/sp-webpart-workbench": "~1.4.0",
    "gulp": "~3.9.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2"
  }
```

There are quite a few differences comparing to the dependencies you have in your project. I suggest you create a new project and compare the differences which should help you find the reason of your build errors. Also, in SharePoint Framework projects, you should not update typescript and React as SharePoint Framework projects rely on the specific versions provided when generating the project.

**Comment by ymihir** [comment]
Even if i create a new project dependencies are pointing to 1.2 version only. May be I need to update version of packages globally.
But I am afraid of update because, I am having two major solutions (contains webparts in developmnt mode) which may affect these updates.
Isn't true?

**Comment by waldekmastykarz** [comment]
If I understand it correctly, you have version 1.2 of the SharePoint Framework Yeoman generator installed globally, which is why, when you create a new project, you see v1.2 references.
Potentially you're right: updating generator to v1.4 could have negative effect on older solutions if you were to add a web part or another component. The safest way is to use different version of the generator for the different projects. You can do that in a number of ways:
- uninstall the globally installed v1.2, install v1.4 and repeat the process every time you want to use a different version of the generator
- [run SharePoint Framework Yeoman generator in Docker](https://blog.mastykarz.nl/sharepoint-framework-docker/)
- run SharePoint Framework Yeoman generator in a virtual machine
- install SharePoint Framework Yeoman generator locally in each project (following the setup instructions you run `npm install -g yo gulp` but then execute `npm install @microsoft/generator-sharepoint` without the `-g` flag in the project folder).

**Comment by ymihir** [comment]
What if I update all packages in my older versioned solution? will that work?
I will check with `npm outdated` and will update the solution locally to newer version. Globally new version is already installed.

**Comment by waldekmastykarz** [comment]
It would work, but you have to ask yourself how viable it is to always upgrade all your projects to the latest version.
Also, regarding using `npm outdated`, each version of SPFx is tied to a specific version of TypeScript and React, which could also need specific version of other packages, so you can't just update all packages to the latest versions.

**Comment by nickpape-msft** [comment]
@ymihir, it sounds like using the same version of react that SPFx is using should have solved your problem. I am going to close this issue since there hasn't been activity in over a month. Feel free to open a new issue if you are continuing to see issues.
