### ISSUE TITLE
❓🐞  Feature framework fails on AddContentTypeField (+upgrade doesn't support VersionRange?)

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#1219]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When leveraging the Feature Framework to provision assets, according to [this doc](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package#define-upgrade-actions-for-new-version), you should be able to not only apply element manifests but also add fields to existing content types.

Furthermore, while it isn't stated in the document above, it appears from testing & lack of mention in the docs that the `<VersionRange>` capability is not supported in SPFx projects... is that true?

#### Observed Behavior

No problem provisioning a new site column when applying the element manifest, but whenever using the `AddContentTypeField` element, upgrade errors out with no error details. 

Upgrade eventually completes, but the version isn't incremented. When you go to the app's detail page, you see 1 upgrade error, but clicking on it yields a blank page (_looking at the source of the page, can't see anything of merit_).

#### Steps to Reproduce

- Follow the steps in the document linked above... except instead of provisioning a list, provision a site column & content type.
- Deploy, create the app & verify presence
- Update project following the doc, except instead of creating a list in v2, provision a new site column & add it to the content type
- Deploy & force the update
- Observe error :(

**Comment by mcmynn83** [comment]
@andrewconnell  - do you mind sending us the V1 and V2 of your package that doesn't add the field? That way we can ensure we are looking at the same issue you are seeing.

**Comment by andrewconnell** [comment]
Can you provide a way to PM link to the source? What's your email alias?

What about the `<VersionRange>` question... is that supported in SPFx?

**Comment by mcmynn83** [comment]
@andrewconnell  - Sorry about that, it's grahamc at microsoft.com.

**Comment by danwatford** [comment]
Hi @GrahamMcMynn  and @andrewconnell ,

Was there any feedback regarding the possible use of (or somthing similar to) <VersionRange> (see https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537575(v=office.14)) so that we can perform different upgrade actions depending on which version a user is updating a package from?

**Comment by danwatford** [comment]
Please ignore my last comment, I've just spotted the VersionRange element referred to on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets#upgrade-sharepoint-items

**Comment by patmill** [comment]
OK, sorry for losing track of this.  I've run through a bunch of this now, and while the docs are not great (we need to improve them for sure), the VersionRange works, and the empty page on errors is due to another error (https://github.com/SharePoint/sp-dev-docs/issues/872) being worked on.  To work around it, you need to disable noscript on the site.

Here's an example of the VersionRange in the upgradeActions.xml file.  In this instance, if you are upgrading from build 1.4 or newer, the new element.xml file won't be applied.

```
<VersionRange EndVersion="1.3.0.0">
<ApplyElementManifests>
    <ElementManifest Location="fca00b63-cabc-4ade-a9fb-fb77f5dcb3bc\newElements.xml" />
</ApplyElementManifests>
</VersionRange>
```

I'll close this bug down, but if you are having difficulty, please open a new issue and we will take a look at it (much sooner than before).
