### ISSUE TITLE
Access SharePoint 2016 Audit events remotely

### ISSUE THREAD

**Issue by KoenZomers** [SharePoint/sp-dev-docs#1236]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Is there an (client.svc) API available to work with the SharePoint 2016 Audit data remotely? Or can this only be accessed using the server side object model?

**Comment by mcmynn83** [comment]
@KoenZomers - this has nothing to do with SPFX.  Please ask the auditing team.

**Comment by VesaJuvonen** [comment]
Since this has all to do with SharePoint Dev, we absolutely should find a source for this. @mcmynn83 this issue list is not ONLY for SPFx.. all SP Dev topics and this certainly qualifies for that. Now - can we find internally a team to answer this, it might be a challenge, but it's not field people's responsibility to understand our internal team structure. If there's a question/issue on SP Dev, we should help them from here.

**Comment by chackman** [comment]
Thanks for your feedback.  There is an existing UserVoice request to query audit using CSOM:
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/8967484-microsoft-sharepoint-client-auditquery-in-csom

If you would like this feature added, please vote for the request on UserVoice, and based on community interest we may or may not take the change.
