### ISSUE TITLE
JSON formatting column - Values from other columns does not work for all columns

### ISSUE THREAD

**Issue by gilroitto** [SharePoint/sp-dev-docs#1250]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Values from other columns should be possible to use in the JSON formatting of a column according to https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting

#### Observed Behavior
**Works**

```
{
    "elmType": "div",
    "txtContent": "[$customField]"
}

{
    "elmType": "div",
    "txtContent": "[$FileLeafRef]"
}

{
    "elmType": "div",
    "txtContent": "[$File_x0020_Type]"
}

{
    "elmType": "div",
    "txtContent": "[$SomeParentTextColumn]"
}

```
**Does not work**

```
{
    "elmType": "div",
    "txtContent": "[$Title]"
}
{
    "elmType": "div",
    "txtContent": "[$SomeParentChoiceColumn]"
}
```
The problematic fields seems to be:

- Some internal SharePoint fields, e.g. Title

- None-text fields (maybe those who involve some lookup mechanism) that are defined not directly in the library but declared e.g. on the Site Collection Level ($SomeParentChoiceColumn in the example above)

#### Steps to Reproduce
**Example A**
Create a column "test" and try to display the Title in that column with the following JSON:
```
{
    "elmType": "div",
    "txtContent": "[$Title]"
}
```
**Example B**
Try to display value of Choice column which is declared on the Site Collection level.
1. In the root of a Site Collection, create a Choice column SomeParentChoiceColumn
2. Create a library in a subsite
3. Add "existing column" SomeParentChoiceColumn to the library
4. Add some documents and set metadata
5. Create a column "test" and try to display the SomeParentChoiceColumn value in that column with the following JSON:

```
{
    "elmType": "div",
    "txtContent": "[$SomeParentChoiceColumn]"
}
```

**Comment by thechriskent** [comment]
I had no issues with either of the use cases you described. Are you still experiencing this issue?

Here is the JSON I used for each

*Test*
```
{
  "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json",
  "elmType": "div",
  "txtContent": "[$Title]"
}
```

*Test2*
```
{
  "$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json",
  "elmType": "div",
  "txtContent": "[$SomeParentChoiceColumn]"
}
```

![Screenshot](https://i0.wp.com/thechriskent.files.wordpress.com/2018/01/formatworking.png)

I created the site choice column as described. Choice columns (even if the options are coming from a site column) still store their value as text in the item (no lookup).

**Comment by gilroitto** [comment]
I'm checking in on this issue again. The issue remains for document Libraries and Lists alike, but is not likely to be seen on Lists due to the workaround below.

It seems that if "Title" is present in the view, it works to use it in another columns JSON formatting. So if you just add Title to the view (which is default for Lists) it will work.

![image](https://user-images.githubusercontent.com/2411144/40834429-158317a6-6591-11e8-88fc-e21d5ae91c0f.png)

**Comment by thechriskent** [comment]
You are only able to reference other columns that are being returned by the view (The ID is always returned even when not shown). This is because the formatting is applied on the client side and no additional retrieval is done beyond the initial view results.

This also explains the weird behavior you were seeing where it temporarily worked when opening the panel since this was retrieving the additional information which then makes it available to formatting.

**Comment by jsquire4** [comment]
I am facing the same issue as above when referring to a choice field, and my JSON object was copied directly and then altered to match my column titles.  Are individual choices contained as part of a larger object?

![issue](https://user-images.githubusercontent.com/17258143/42534910-fa946866-845b-11e8-952d-f0ee1d166159.PNG)

**Comment by thechriskent** [comment]
I am able to make this work using your example:
![image](https://user-images.githubusercontent.com/8364109/42535856-8e8a0376-845e-11e8-84f9-8319eec5b976.png)

Are you sure the internal name of your choice column is `ColorStatus`?

**Comment by jsquire4** [comment]
Thanks Chris, it was the internal name issue.  For future reference, is there a way to list the internal names of all columns or are they only displayed in the query string?

**Comment by thechriskent** [comment]
Often the quickest way to see the internal field name is to go to list settings and check the edit link for the query string. But you can also use the REST api and hit a URL like this: 

`https://yourtenant.sharepoint.com/sites/YourSite/_api/web/lists/getbytitle('your list')/fields?$select=DisplayName,InternalName&$filter=Hidden%20eq%20false`

It's a bit messy but you can use Ctrl+F to search by the display name and you'll see the internal name close by.

You are right that the documentation wasn't very clear on this. It was mentioned briefly in an example, but not in the section you'd expect. I have submitted a change to the documentation to make it much clearer. Thanks for this feedback!

#### "[$FieldName]" 

The column is formatted within the context of the entire row. You can use this context to reference the values of other fields within the same row by specififying the **internal name** of the field surrounded by square brackets and preceeded by a dollar sign: `[$InternalName]`. For example, to get the value of a field with an internal name of "MarchSales", use `[$MarchSales]`.

If the value of a field is an object, the object's properties can be accessed. For example, to access the "Title" property of a person field named "SalesLead", use "[$SalesLead.title]".

**Comment by ErikSavetheCrew** [comment]
Thanks @thechriskent this is really helpful.  Related question - I'm using JSON for view formatting on a Sharepoint list, and getting [Object object] as a return when calling people and lookup fields.  I was able to find documentation on object properties of the people field, but I can't find any about lookup fields.  Any idea how I can return the value of a lookup field instead of [Object object]?

**Comment by thechriskent** [comment]
Glad it helps!

For lookup columns you can get their values using the same type of dot syntax as people fields. So to get the value where the current field is a lookup column:

```
@currentField.lookupValue
```

To get it from a lookup field you are referencing:

```
[$FieldName.lookupValue]
```

`lookupId` is also available. You can find more details on referencing lookup columns (along with other fields with dot notation such as people, hyperlinks/picture here: https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#special-string-values

**Comment by egidiocs** [comment]
I'm having similar issue on view formatting when referencing lookup columns.

this works fine:
`"txtContent": "=if([$LookupColumn]=='', 'NO lookupValue', 'has lookupValue')"`

and renders as expected:
![image](https://user-images.githubusercontent.com/1933529/50497129-4553e980-0a1c-11e9-9e58-66c492badab6.png)

**However** when I rewrite to show the lookupValue, instead of 'has lookupValue' string
`"txtContent": "=if([$LookupColumn]=='', 'NO lookupValue', [$LookupColumn.lookupValue])"`

it only renders items having value set in LookupColumn
![image](https://user-images.githubusercontent.com/1933529/50497132-4dac2480-0a1c-11e9-9a12-a4d771fce1a6.png)

Any thoughts?
Thank u!

**Comment by boing0** [comment]
@egidiocs try wrapping your lookupValue with a toString() like:
"txtContent": "=if([$LookupColumn]=='', 'NO lookupValue', toString([$LookupColumn.lookupValue]))"

**Comment by rigpd001** [comment]
@thechriskent  Hi Chris, are you able to help me out with displaying taxonomy fields on a formatted view, I have tried a number of things
I've tried
 "txtContent": "[$Asked_x0020_By.label]"
 "txtContent": "[$Asked_x0020_By.title]"
 "txtContent": "[$Asked_x0020_By.Title]"
 "txtContent": "[$Asked_x0020_By.Label]"
 "txtContent": "[$Asked_x0020_By]" 

 I can't seem to get it to work, any help would be greatly appreciated.

**Comment by MacBoiler** [comment]
Any update on this?

Column formatting works fine with lookupValue but the view formatter doesn't.

Looks like only workaround is a workflow to populate a text field.

**Comment by MacBoiler** [comment]
@rigpd001 this is how it should work with view formatting. Another half baked solution from Microsoft. Take me back to SP 2007 please.:)

**Comment by thechriskent** [comment]
Sorry for the delay everyone! I don't often get notifications for closed issues. I'd suggest opening **new issues for new questions** in the future.

---

@egidiocs the issue you are seeing was related to how expressions *were* evaluated. Unlike most programming languages where conditional statements are only evaluated when they need to be, list formatting evaluated all of them regardless. So in a standard language once the lookup column was evaluated to be blank only the true parameter would be executed. However, in list formatting both the true and false conditions were evaluated prior to the if conditional itself. So your first example worked because you are just evaluating strings in the true and false. The second example failed because it is unable to get a sub property of a null object (even though it isn't needed).

However, this is no longer the case and your example should work just fine now. Here is my format:
```json
{
  "elmType":"div",
  "txtContent": "=if(@currentField=='', 'NO lookupValue', @currentField.lookupValue)"
}
```

With this result:
![image](https://user-images.githubusercontent.com/8364109/59108368-b3c0a000-8908-11e9-9902-8d378ac03f14.png)

---

@rigpd001 there is currently no support for taxonomy fields within list formatting. These values are simply unavailable to be pulled directly. This is very disappointing and I haven't seen any timeline to address them.

You can, however, access these fields when using SharePoint Framework Field Customizer extensions. That may be more than you want to take on though.

---

@MacBoiler I've seen no issues with using lookup fields in view formatting. Here is a format that worked fine for me (the internal name of my lookup field is `Lookup` and it is part of the view):

```json
{
  "rowFormatter": {
    "elmType": "div",
    "txtContent": "[$Lookup.lookupValue]"
  }
}
```

Please don't go back to SP 2007! There are definite limitations with List Formatting, but it is still far better than the dark days of XSLT. As mentioned above, you can always go the SPFx Field Customizer route if List Formatting proves too limited.

**Comment by muralikrishna0011** [comment]
> **Example A**
> Create a column "test" and try to display the Title in that column with the following JSON:
> 
> ```
> {
>     "elmType": "div",
>     "txtContent": "[$Title]"
> }
> ```
Hi Can you please Help me here,
Example i have 3 fields named title,parent and child 
copied values in to Parent replica of title using JSON  with above script.
Now to functioning i also need to use parent field values in Powerapps or for another like child from parent values, but i getting blank values.
 "txtContent": "[$parent]"
used parent with same formula instead title but i cant get values from parent its blank ...
seems like just displaying but not copying values in to parent from title.
Can any one help me how to get copy of parent values to child field...?
