### ISSUE TITLE
Inconsistent used languages in Site creation UI using Site Scripts

### ISSUE THREAD

**Issue by ypcode** [SharePoint/sp-dev-docs#1268]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
See consistent language in site creation UI with Site Designs

#### Observed Behavior
The text is mixed up in English and French even if my site is created in English
![sp-sitescripts-language](https://user-images.githubusercontent.com/8345556/35300570-24f3d878-0089-11e8-9856-db615cc0c87f.png)

#### Steps to Reproduce
Simply apply a Site Design (from tutorial)

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
