### ISSUE TITLE
SPFx package JavaScript scripts randomly loaded from CDN when includeClientSideAssets and deployed to Site Collection App Catalog

### ISSUE THREAD

**Issue by VelinGeorgiev** [SharePoint/sp-dev-docs#1309]
SPFx package JavaScript scripts are randomly loaded or not loaded when includeClientSideAssets is set to true and the package is deployed to Site Collection App Catalog. It is about client side solution deployed to SharePoint Online targeted tenant (first release tenant)

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
All the custom SPFx web part and extentions scripts have been loaded on the home page of a Communication site after the SPFx package has been deployed to a Site App Catalog.
![image](https://user-images.githubusercontent.com/1049476/35733974-6832055c-0817-11e8-8c89-83997a2f633b.png)

#### Observed Behavior
Randomly the CDN endpoint is simply not called by the SitePage server page.
![image](https://user-images.githubusercontent.com/1049476/35734115-e0f6f5a6-0817-11e8-988e-4ac0c67f3e5c.png)

#### Steps to Reproduce
Create modern site collection based on Communication site
Enable Site collection app catalog to the  site collection
Deploy SPFx client side solution with the following package configuration:
- "includeClientSideAssets": true,
- "skipFeatureDeployment": true
Add custom webparts to the homepage of the site SitePages/Home.aspx
Access few times site by url in latest Chrome or Firefox browser like https://contoso.sharepoint.com/sites/my-site

#### Submission Guidelines
Seems that the CDN https;//publiccdn.sharepoint.com/contoso.sharepoint.com/sites/my-site/ClientSideAssets has not always been called by the SitePage server page.

**Comment by AustinBreslinDev** [comment]
Hi everyone,

After discussing with Velin the below details appear to be related to this.

Reloading the page over and over again using Firefox, seems to occur more often on Mac 10.2 Safari.

![image](https://user-images.githubusercontent.com/10480670/35876257-a54aaeb2-0b69-11e8-987e-703d6506ad07.png)

As can be seen in the screen shot the sp-pages_assembly fails to load, stating that a chunk failed to load. Since I have seen a chunk technique before I'm assuming that the file is only partial downloaded and thus the error. I also see that the file appears to be time/session stamped, couldn't the file be made to have the caching header immutable so that it will cache forever?

Or the problem could be arising from the error message Loading failed for the <script> with source “https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-26.004/20.sp-pages-pagestatusnotifier_538744b0f980001e31e4.js"

Again is time/release/session stamped and could be made to have the caching header immutable to prevent the issue and to increase performance.

Here is a blog (Not mine) that describes the caching header https://www.keycdn.com/blog/cache-control-immutable/ 

Network Tab:
![image](https://user-images.githubusercontent.com/10480670/35876658-d4de17b2-0b6a-11e8-926a-133454d3a94a.png)

Reload after Failure:
![image](https://user-images.githubusercontent.com/10480670/35876781-420e4d34-0b6b-11e8-928b-24a5f1be5d44.png)

Network Tab after reload:
![image](https://user-images.githubusercontent.com/10480670/35876810-5a6e28e0-0b6b-11e8-991c-040a9ac0c779.png)

**Comment by manishgarg1** [comment]
Hi @VelinGeorgiev @AustinBreslinDev,

A few questions:
1. Looks like you have the "public CDN feature" enabled. Is that correct?
2. @VelinGeorgiev, when you say public CDN (https;//publiccdn.sharepoint.com/contoso.sharepoint.com/sites/my-site/ClientSideAssets) is not always called to download package resources, what URL is called?
3. The *sppagesstatusnotifier* js file is a Microsoft file. And the fact that it is not getting downloaded seems like a problem. Your webpart/extension js files should get downloaded from (publiccdn.sharepoint.com) if includeClientSideAssets is true and the public CDN feature is enabled. I cannot see the exact error message from this. Can you please provide more details about the error message when that file fails to load?

**Comment by VelinGeorgiev** [comment]
1. Yes, we use it for other type of assets like images, css
2. Request to the https://publiccdn.sharepoint.com/... has not been send from the SitePage. Seems that the SitePage skips that process for some reason. I can try to provide some more details later. 

I can log Office365 ticket and try to reproduce it with you or a shared session if you will.

**Comment by VelinGeorgiev** [comment]
Please find the attached page loaded twice.
- [Page fully loaded html](https://github.com/SharePoint/sp-dev-docs/files/1707930/page_fully_loaded.txt) = 1.08 MB
- [Page partially loaded](https://github.com/SharePoint/sp-dev-docs/files/1707933/page_not_fully_loaded.txt) = 854 KB

The only change in the pages is hiding company names, but can clearly be seen the difference between the size of the exact same page loaded/re-loaded twice.

Attached is also the console output when the page does not fully loads:
![console_preloaddidnotwork](https://user-images.githubusercontent.com/1049476/35985489-aa230eb2-0cee-11e8-8646-77da483522b0.PNG)

At the bottom we have some warnings that deserve attention
"The resource https://publiccdn.sharepoint.com/... was preloaded using link preload but not used within a few seconds from the window's load event". The javascripts not loaded are actually webparts/extentions from multiple .sppkg solutions deployed to Site Collection App Catalog with -
 "includeClientSideAssets": true,
 "skipFeatureDeployment": true

**Comment by VelinGeorgiev** [comment]
Potential duplicate https://github.com/SharePoint/sp-dev-docs/issues/1265

**Comment by VelinGeorgiev** [comment]
@all any progress on that?

**Comment by VelinGeorgiev** [comment]
@VesaJuvonen , @manishgarg1  fixing that one introduced different problem. Have a look at that https://github.com/SharePoint/sp-dev-docs/issues/1464.

**Comment by VelinGeorgiev** [comment]
I can confirm that that one can be closed.
