### ISSUE TITLE
No tsd.json file created with the project

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#133]
The SharePoint Framework Yeoman generator doesn't create a tsd.json file with the typings required by the project. That file is required to correctly restore required typings after getting the project from the source control.

**Comment by nickpape-msft** [comment]
Internally, we checkin the typings directly to source control, which is why we are missing the tsd.json.

Also, there are typings which are not distributed via `tsd` in that folder (e.g. `@ms/odsp.d.ts`).

We didn't find much value in downloading the typings later, as effectively tsd.json records a commit number and then `tsd install` uses that to get the typings. If it is always the same typing (which it will be if the commit # doesn't change), why even bother? Why not just check it in?

**Comment by nickpape-msft** [comment]
Update: it is now recommended to use `@types` scoped packages for typings files. This is recorded as an entry in the `package.json`.
