### ISSUE TITLE
Typings are not excluded from the source control

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#134]
By default the typings folder is not excluded from the source control. Given that all default typings are public and available centrally they shouldn't be included in the source control but listed in tsd.json so that they can be restored.

**Comment by manishgarg1** [comment]
With Typescript 2.0, the whole typings mechanism will change. SPFx will move to TypeScript 2.0 when it gets released. And hence, we do not need to fix this at the current time. Please let us know if you still think this is an issue.

**Comment by waldekmastykarz** [comment]
I guess that depends on when TypeScript 2.0 will be released. If it's released after SPFx reaches GA then this is a bug that should be fixed. If SPFx gets updated before GA to TS 2.0 then I'd say it's fine for the time being.

**Comment by pgonzal** [comment]
FYI for our internal projects, we started with the approach you described above.  However, we had problems because the tsd tool (which has now been abandoned by its author) did not always accurately recreate the typings files when you run "tsd install".  Also sometimes we needed to make local edits to the typings files.  These files are tiny, so the safest policy is simply to include them in your Git repo.
