### ISSUE TITLE
Throttling - HTTP response 429 and the ExecuteQueryWithIncrementalRetry extension method

### ISSUE THREAD

**Issue by Panoone** [SharePoint/sp-dev-docs#1412]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

We've recently hit Microsoft's new throttling limits with all our CSOM console apps that _used_ to work without any issue.

I implemented the **ExecuteQueryWithIncrementalRetry** extension method and am now continually receiving the dreaded "The property or field 'FieldName' has not been initialized..." exception after every query execution.

Putting in break points and additional delays mostly solves this but also slows execution dramatically. Has anyone else had success with this?

**Comment by mcmynn83** [comment]
@Panoone - Requests receiving a 429 due to throttling is an open issue that MS is currently investigating.

**Comment by Panoone** [comment]
@VesaJuvonen yes, I'm aware. My question was around the success of using the ExecuteQueryWithIncrementalRetry extension method.

**Comment by justviswa** [comment]
@andrewconnell It's been so long, nearly 2 years, since this issue was raised. Still it's open. As already explained in #5297, many do face this issue frequently, during which, nothing can be done other than experiencing an interruption/failure in the operations. I know you might be having a lot of other priorities but I kindly request you to please consider looking into this & fix this asap. Thanks.
