### ISSUE TITLE
Custom full bleed web parts are not visible initially

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#1428]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When editing the start page in a communications site, that has a full bleed zone at the top, I expect all full bleed web parts to be available in that zone; custom and first party. 

#### Observed Behavior

Only 1st party web parts are shown when editing the full bleed zone the first time. You have to remove the default zone and add a new zone at the top, that is full bleed, to see all (1st and 3rd party) web parts.

#### Steps to Reproduce

Create and deploy a full bleed web part. 
Create a new Comms site
Edit the start page, and remove the news web part at the top
You will only see 1st part web parts as options in that zone.

**Comment by OliverZeiser** [comment]
Same thing also does not work via code (PnP Core library) when adding a new page with a full width section. Even the code then fails to add the webpart to this section allthough the custom webpart is marked with supportsfullbleed.

**Comment by srideshpande** [comment]
@wictorwilen @OliverZeiser - Thanks for the feedback. We will look into it.

**Comment by eschrader** [comment]
Hi, I posted the issue on the supportsfullbleed MS documentation. https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/use-web-parts-full-width-column

Looks like the full width web part zone adds a Opacity: 0 and TranslateY(20px) to the parent div, forcing you to scroll down to see the content.

My SPFX web part content uses OnRender instead of OnInit, not sure if thats ok, but it use to work a few months ago (we noticed sporadic issues during development early in the year but it went away).

If I move my SPFX web part to a regular zone, it loads fine.

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
