### ISSUE TITLE
Tool to upgrade existing project

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#145]
#### Category

[] Question
[] Typo
[] Mistake
[+] Additional article idea

Existing projects can probably easily update with the following change in the package.json.

In the script section of the package.json add the following line:
`"upgrade-spfx": "npm install @microsoft/sp-client-base@latest @microsoft/sp-client-preview@latest --save && npm install --save-dev @microsoft/sp-build-web@latest @microsoft/sp-module-interfaces@latest @microsoft/sp-webpart-workbench@latest && npm update && npm prune && npm dedupe && gulp nuke"`

The script section then looks like this:
<img width="809" alt="screen shot 2016-09-02 at 18 42 46" src="https://cloud.githubusercontent.com/assets/5503835/18211270/225f8468-713d-11e6-8bfb-b0a5e4342c2e.png">

After this line have been added to the package.json. Save it and upgrade the project with the following command.

```
npm run-script upgrade-spfx
```

Unless the packages don't change I think this should work for future drops too. From my point of view to upgrade solutions such as this npm script is exactly the right tool to do this job.

**Comment by patmill** [comment]
On our radar.  @nickpape-msft was offering to do it before drop 2, but upgraders are historically tricky beasts, and an hour or two didn't quite seem like enough time.

While we are on the topic though, hypothetical question.

In drop one, there was a file (config/text.json) that we removed because it was kind of weird and not really used.  Basically, if you created a .html file in your src directory, a corresponding .tempate.html.js file would be created in the lib folder, and you could require it.  Wound up being a hacky way to require html snippets into your code.  Fast forward a week or two and let's say we get a proper way to include html files in a way that fits better, and that's what new projects use.  In another scenario, we relax (or add) tslint rules.
Should the upgrade script be "relaxed" and only do the bare minimum (package.json, fix up references maybe, etc.) or should it be more strict and replace / remove default files, etc.
Adding options is always possible, but of course every option / flag introduces a greater likelyhood of a bug, adds cost to the work item, adds complexity in understanding it, etc.

What would you lean towards?

**Comment by StfBauer** [comment]
Sorry @patmill not sure what you try to tell me with the second part. The NPM script above is just a common apporach to upgrade npm packages. What it basically does it to combine all the single steps from the [Drop 2 release](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2) not and combines it to an executable upgrade script.

What it does are actually the native NPM scripts you execute the yeoman generator. It also automatically updates the package information to the most recent on.
You can simply chain the command line case by using "&&" so no rocket science here.

### Step 1: Update and install Dependencies in package.json
```npm install --save @microsoft/sp-client-base@latest @microsoft/sp-client-preview@latest```
### Step 2: Update and install Dev Depenencies in package.json
```npm install --save-dev @microsoft/sp-build-web@latest @microsoft/sp-module-interfaces@latest @microsoft/sp-webpart-workbench@latest```
### Step 3: Execute ```npm update```, ```npm prune``` and ```npm dedupe```
### Step 4: Execute ```gulp nuke```

Those are just the common steps described in the Drop Release note and those who can be automated.
This simple npm script does all the basic steps using common package operations. Basically you can replace the manuel steps with this script. I think it is easier instead of manually modifying the package.json information.
Normally you don't touch those part instead you install and uninstall packages.

**Comment by waldekmastykarz** [comment]
What if the upgrade tool could prompt if you want to remove the obsolete file? If you used it for a legit purpose you might want to keep it, but if you didn't touch it and it's obsolete then there's no reason to keep it.

**Comment by manishgarg1** [comment]
VSO #244675

**Comment by patmill** [comment]
We have decided to not pursue an upgrade tool at this time.  We can revisit in the future if needed.
