### ISSUE TITLE
SocialBar cannot be disabled on team sites

### ISSUE THREAD

**Issue by sortegamartin** [SharePoint/sp-dev-docs#1532]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
You cannot disable the social bar on team sites. When executing the command powershell "Set-SPOSite -Identity <site url> -SocialBarOnSitePagesDisabled $true", gives the following error:

![image](https://user-images.githubusercontent.com/33054287/37832577-4a142fa6-2ea9-11e8-97f5-7131d6b6b677.png)

When I run the same powershell command for a communication site, it runs correctly.

Could it be that the SocialBarOnSitePagesDisabled property does not exist in team sites?

Thanks!

**Comment by iBrooks** [comment]
Found this open issue through [this post](https://sharepoint.stackexchange.com/questions/241102/modern-site-page-hiding-total-page-views-and-like-option-in-office-365-sp-onli).

I was able to run the command without an error, but the property change had no effect. Social bar is still on all pages. Issue still exists.

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
