### ISSUE TITLE
Removing add-in from recycle bin throws an exception when in classic mode

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/sp-dev-docs#1538]
#### Category
- [x ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I should be able to remove apps and clear recyclebin items, regardless of in which 'experience' I am in.

#### Observed Behavior

1. Add an app to the appcatalog
2. Install the app to a site.
3. App has problem. Okay, no worries. I'll delete it from Site contents
4. One is notified that you have to switch to Classic...
5. I switch to classic mode. I can remove the app.
7. Let me remove it from the recycle bin too... 
8. "An unexpected error occured"
9. Go back to site contents... click 'exit classic mode'
10. Navigate to the recycle bin. Delete app from recycle bin. Works.

#### Steps to Reproduce

See observed behavior

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
