### ISSUE TITLE
Modern Pages submenu mouseout not working?

### ISSUE THREAD

**Issue by jcosta33** [SharePoint/sp-dev-docs#1549]
#### Category
- [X ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

I'm not sure if this is a bug or if it's intended but when hovering out of a submenu it doesn't automatically close, only doing so when clicking away. This is a little counter intuitive since you end up with two different behaviors for opening and closing the menu.

**Comment by patmill** [comment]
Hi @jcosta33 - trying to narrow down what your mentioning.  Is this a general UX / user issue, or a developer / API issue?  It sounds like the former (which is outside the scope of this issues list), but just want to double check.

**Comment by jcosta33** [comment]
@patmill It's a general UX issue but I wasn't sure whether or not it's a bug of the platform or a conscious choice made by you guys. If it's not a bug then you can dismiss this but know that it was pointed out to me as a bug by a colleague. I don't think it's a very intuitive approach. 

Thank you for the quick reply!

**Comment by VesaJuvonen** [comment]
This issues should be fully solved and fixed, given the work we have done in engineering in this area. To ensure that we clean up the backlog of the issues, we will be closing this one. If you still have issues on this particular area, please open up a new issue so that we can get updated issue description and reproduce steps. We do apologize the non-optimal handling of these old issues and are looking into improving this in future.
