### ISSUE TITLE
Internet facing SP site with JSOM programming and potential DoS attacks

### ISSUE THREAD

**Issue by ashuetawah** [SharePoint/sp-dev-docs#1578]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [X] Additional article idea

#### Information
> As per the article https://blogs.msdn.microsoft.com/kaevans/2013/10/24/what-every-developer-needs-to-know-about-sharepoint-apps-csom-and-anonymous-publishing-sites/ , if SharePoint is exposed on internet and if developers are required to expose the data using JSOM to anonymous users, we need to enable 'Require Use Remote Interfaces permission' setting. 
Article also states that by doing so, there is a potential of DoS attacks. 

#### Questions
> 1. Has this changed over the years as how On-premises has evolved? 
> 2. What is recommended method to expose information via JSOM and minimize the risk of DoS attacks?
> 3. Any reference for best practices on building internet facing sites with SP and programming using CSOM/JSOM with minimized DoS attacks.

**Comment by VesaJuvonen** [comment]
This is by design and situation has not really changed. DoS comment is not really anything more than yes, if you have APIs exposed for the anonymous users, you have potential DoS surface... this though is the case also even though you would not change any settings as DoS attack can be performed for any content. In general, we do not, however, recommend using SP add-in model for anonymous usage as it was never designed for that.
