### ISSUE TITLE
HI i am new to SPFx and modern UI how would i know when DOM is fully loaded in modern UI? just like Document.ready() in jquery ? i have to hide left nav i can do it using Jquery with with SetTimeOut which is not good at all 

### ISSUE THREAD

**Issue by Asfandtnt** [SharePoint/sp-dev-docs#1597]
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>
> If you are planning to share a new feature request (enhancement / suggestion), please use SP Dev UserVoice at http://aka.ms/sp-dev-uservoice. (DELETE THIS PARAGRAPH AFTER READING)
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Expected or Desired Behavior

> If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Observed Behavior

> If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Steps to Reproduce

> If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the documents or articles, please ensure that you have clear > reference on the specific file or URL, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and > #spfx-tooling on (SharePoint StackExchange)[http://sharepoint.stackexchange.com/]. You can also > alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
>
> _(DELETE THIS PARAGRAPH AFTER READING)_
>

Thanks for your contribution! Sharing is caring.

**Comment by SathishNadarajan** [comment]
Do we got any answer for this.  I am also facing the same kind of  issue.  On the document.ready, I need to change the label of the OOB webpart title.

**Comment by waldekmastykarz** [comment]
There is no such event, because DOM manipulation is not a recommended or supported practice to change things in SharePoint. Page's DOM is not an API you can rely on, and the element you might be changing today, might look different tomorrow (different tag, class, id or be gone altogether). There are a few extensibility points like building web parts or extensions and registering them with known placeholders, but modifying elements on the page through DOM manipulation is strongly discouraged.

**Comment by SarwarRana** [comment]
Hi @waldekmastykarz , I am looking for something similar as well.

For example, I am trying to hide Edit page link for members group across all the sites rather than breaking the inheritance on every site and giving different permission to Site Pages and was thinking to do extension for that purpose but it is bit fiddly at the moment as I can't check DOM ready in extension itself?  Any suggestion would be great. Thanks

I think there could be lots of other scenarios whereby it could be really useful if there was some mechanism to check DOM ready...

**Comment by SarwarRana** [comment]
I will probably end up writing PowerShell script for this. But I still think there are lots of other scenarios where checking DOM ready will be really useful specially in custom development, when you create elements with specific ID's. Thanks.

**Comment by waldekmastykarz** [comment]
SharePoint pages' DOM is not an API and you shouldn't take dependency on it. It can change without any upfront notice, which would break your solution.

**Comment by SarwarRana** [comment]
Hi @waldekmastykarz ,

I understand your point of view but what about if you have created a web part with some elements assigning them specific IDs, surely those not going to change, are they?

**Comment by SarwarRana** [comment]
Yes thanks, so then there is actually need to check if DOM is loaded so that you can manipulate your own DOM at least when need arises. Is this something Microsoft looking into?

**Comment by waldekmastykarz** [comment]
If you define a hook in the render method of your web part, then you don't need to check if the DOM is loaded, because you can assume it is, unless you use a framework like Angular(JS) or React which has its own DOM lifecycle.

**Comment by waldekmastykarz** [comment]
The problem is that on-premises administrators control the pace of updates to SharePoint, so they can choose to update once or twice a year. SharePoint Online changes weekly so by doing what you've done in the past, you'd end up having to daily verify if your solution is still working as expected. This is exactly why it's recommended to use the public APIs and not modify page DOM.

**Comment by patmill** [comment]
Sorry for not being responsive.  I'll just respond quickly, in that this is an unsupported use of SPFx.  Modifying the DOM outside of the component is unsupported, and any code that does this may break at any time.  See the "important" callout on this page - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance#in-perspective-sharepoint-framework-in-the-broader-sharepoint-platform
