### ISSUE TITLE
Toolbox shows only the first Web Part specified in preconfiguredEntries

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#16]
If you specify multiple preconfiguredEntries, only the first Web Part is displayed in the toolbox:

```
{
  "$schema": "../../../node_modules/@microsoft/sp-module-interfaces/lib/manifestSchemas/jsonSchemas/clientSideComponentManifestSchema.json",

  "id": "cbf1c4ba-8b6c-4b45-9900-ef12815275c3",
  "componentType": "WebPart",
  "version": "0.0.1",
  "manifestVersion": 2,

  "preconfiguredEntries": [{
    "groupId": "cbf1c4ba-8b6c-4b45-9900-ef12815275c3",
    "group": { "default": "Under Development" },
    "title": { "default": "HelloWorld" },
    "description": { "default": "HelloWorld description" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "HelloWorld"
    }
  },
  {
    "groupId": "cbf1c4ba-8b6c-4b45-9900-ef12815275c3",
    "group": { "default": "Under Development" },
    "title": { "default": "HelloWorld 123" },
    "description": { "default": "HelloWorld description" },
    "officeFabricIconFontName": "Page",
    "properties": {
      "description": "HelloWorld"
    }
  }]
}
```

![screen shot 2016-08-18 at 11 23 44](https://cloud.githubusercontent.com/assets/11164679/17768839/474f548c-6536-11e6-9033-94da21400c14.png)

**Comment by patmill** [comment]
Yes - we have a work item to get that sorted out.  One question while we are on the subject though.  Currently, certain values appear on the config (like description for example) that are multi-lingual.  In general, the config options should be a starting point, with the values in the config copied to the actual webpart, after which they are no longer "connected".  The configs are really just a starting point.  You can add and delete entries in the config section, and it shouldn't affect any existing webpart that has been created.
Now, copying most of the properties is no issue at all, particularly the webpart properties.  The multi-lingual things are tricky.  We really don't want to persist a huge dictionary of translated labels into every webpart saved, and I don't like the design of keeping an index into the config section, as that entry might change over time (and you have the problem of what happens when the entry was removed completely).
One idea would be to copy the localized string from the local at creation time (and the author should be able to change those entries anyhow).

**Comment by waldekmastykarz** [comment]
What if the manifest could point to the loc file shipped with the bundle and get its strings from there on runtime? That way you would store only the keys and the values would be determined on runtime using the loc file corresponding to the current locale.

**Comment by iclanton** [comment]
We considered pointing to a "strings" file in the bundle, but that approach has a couple of issues:

1. We intentionally don't load any external scripts when listing items in the toolbox. The toolbox only looks at manifests. Loading a script for each webpart to get the title to show in the toolbox adds a lot of unnecessary complexity (for instance, we may need to wait for dozens of async callbacks to complete before we can show a "complete" toolbox vs the toolbox rendering instantly and synchronously).
2. We don't mandate any particular "strings" resource format. Having the framework load a file/script that contains a title or description string would require enforcement of a resource file format, which isn't something I think we want to impose on developers.

**Comment by waldekmastykarz** [comment]
Got it. Thank you for the explanation @iclanton. In that case what @patmill suggested would indeed be an option: copy the localized string when adding the Web Part to the page and use that from that point on.

**Comment by patmill** [comment]
Cleaning up old bugs for GA.  We show each preconfigured entry now.
