### ISSUE TITLE
A lot of 429 errors lately (past 12 hours untill now)

### ISSUE THREAD

**Issue by advdberg** [SharePoint/sp-dev-docs#1600]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Retrieve SharePoint Online list

#### Observed Behavior

An error message returned:
The remote server returned an error: (429). 

#### Steps to Reproduce
on tenant: https://ziut.sharepoint.com

```
GetList -_ctx $ctx -_webName "" -_listName $myListName

$url = "https://ziut.sharepoint.com/sites/portaal/"
$creds = Get-Credential
Connect-PnPOnline -Url $url -Credentials $creds

Get-PnPList -Identity "Lists/Schades"    
```

**Comment by advdberg** [comment]
Any news on this? It's becoming a big problem for our customer, it happens more and more on all type of queries we execute, both on PnP and custom SharePoint Client context. What's the best way of handling these errors? Just a retry after x seconds doesn't seem to solve the issue.

**Comment by VesaJuvonen** [comment]
@advdberg - I'll see what we can do here based on the tenant name. If you do also manage to get correlation ID, that would be great, so that we can understand what's going on within the tenant / farm when throttling happens. We are not currently really getting that widely reports from others, so curious on understanding what could be causing this.

**Comment by VesaJuvonen** [comment]
Hi, here's input from the people behind of this feature - "They are doing what we don’t want to happen in the future, they have an app using Admin credentials  (User only) without AppID.  The best advise for their app to get OAuth token and use that instead of using User Only. ". PnP PowerShell luckily also supports this, so you could also use app-id and secret to sign-in to your tenant. Having AppID will reduce the possibility to get throttled. PnP PowerShell does include automatically already needed http request decorations. 

Closing for now, but let's re-open if needed.
