### ISSUE TITLE
$skiptoken=Paged=TRUE&amp;p_ID=5 

### ISSUE THREAD

**Issue by abhishekseth054** [SharePoint/sp-dev-docs#1654]
i am trying to implement pagination and tried like that
<SiteCollectionURL>/_api/web/lists/getbytitle('<LIstName>')/items?$skiptoken=Paged=TRUE&p_ID=5&$top=10
but it is always returning 10 items from ID=1 to ID =10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 916d6284-9149-5d95-48d8-40c60ba9f3c7
* Version Independent ID: 9c41a103-56d6-c186-26aa-ccd098a61f7e
* Content: [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#sectionSection6)
* Content Source: [docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
The correct format for the `$skiptoken` should be `$skiptoken=Page=TRUE%26p_ID=5`

The issue is with the url encoding of the `&` before the p_ID. You can't include the `&` directly since it would then be interpreted as an additional query option rather than as part of the `$skiptoken` value. The value for the `$skiptoken` option should be url encoded. The doc indicates you can encode it as `&amp;` however, this is inaccurate. I've submitted a change to this document to reflect this (thanks for bringing it to our attention!)

So for your example query, you'll want it to look like this: `/_api/web/lists/getbytitle('YOURLIST')/items?$skiptoken=Paged=TRUE%26p_ID=5&$top=10` This should return items ID=6 to ID=15 (assuming no gaps)

**Comment by abhishekseth054** [comment]
Thank you, It worked.  👍 👍

**Comment by Yuanyingbo102** [comment]
Sorry but I have another question : Column 'ID' is default column created by Sharepoint , when I delete an item 'A' , the 'ID' of  'A' will still exist , so in this situation how can I exactly skip the right p_ID , thx.
