### ISSUE TITLE
Request to suppress SPFX logging in the browser console

### ISSUE THREAD

**Issue by johnnliu** [SharePoint/sp-dev-docs#166]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category

[ ] Question
[ ] Typo
[ ] Mistake
[x] Additional article idea
#### Expected or Desired Behavior

A way to disable or limit console.log from SPFx

http://sharepoint.stackexchange.com/questions/191607/spfx-disabling-console-traces-by-spfx-libraries

Thanks for your contribution! Sharing is caring.

**Comment by manishgarg1** [comment]
@johnnliu, if we provided ways (through query string params or console commands) to control the logging level. Would that not solve the problem of excessive logging. e.g. logLevel=Warning implies that only warnings will be logged.

**Comment by pgonzal** [comment]
I resolved issue #218 as a duplicate of this bug.  It is basically asking for the same thing -- a way to suppress the console.log() noise in the Workbench.

**Comment by bpkennedy** [comment]
My .02, instead of controlling the log level via query commands, why not simply stop the console.logs and fix the SHA-1 stuff?

**Comment by patmill** [comment]
We log errors to the console, the rest we log to the SPFX development trace.

**Comment by bpkennedy** [comment]
Sorry, I just wanted to open this back up because I don't think the need has been understood.  There is still a lot of noise in the console.

The "noise pollution" isn't providing value and is obstructing from using the console as we'd normally expect to be able to for me, John Liu - and Danny Engleman, and iOnline based on the stack overflow link in the OP's issue.

I don't mind a querystring parameter, as long as it's not something I have to do every time I refresh the page.
