### ISSUE TITLE
Unable to load external JavaScript - Non AMD

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#1664]
I am trying to load external Javascript but it doesnt work.
I actually tried the default article as well
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/basics/add-an-external-library.md#load-a-non-amd-module

Nothing works !!!

![image](https://user-images.githubusercontent.com/11780473/38791151-9fbb7bf4-4163-11e8-9e96-b655cb1d3dd4.png)

**Comment by VesaJuvonen** [comment]
@harshdamania - any change you could share the steps you performed. What do you have in the config files etc. That would help on the repro fo the issue. Thx.

**Comment by harshdamania** [comment]
Basically earlier i was trying to fetch data from userprofile for which i have created a custom js file.The value returned by this js is stored in global variable so that it can be used by other webparts on same page.
But it didnt work so i tried the sample provided in documentation.

First created a js file : 
![image](https://user-images.githubusercontent.com/11780473/38793187-d133788a-416d-11e8-825d-f1b43dd2d191.png)
then .d.ts file
![image](https://user-images.githubusercontent.com/11780473/38793200-e320617a-416d-11e8-9743-877373a0eb1f.png)

Config.json (I have uploaded file in sharepoint document library)
![image](https://user-images.githubusercontent.com/11780473/38793221-01f42302-416e-11e8-9ed8-e379cf578450.png)
In my tsx file i have imported it as 
![image](https://user-images.githubusercontent.com/11780473/38793252-23b5cf0e-416e-11e8-849a-588e0fcc571a.png)

Also i have made this change in tsconfig file
![image](https://user-images.githubusercontent.com/11780473/38793286-4278ffa6-416e-11e8-9ae5-575042124142.png)

as before that i was getting error

Let me know if anything i am missing

**Comment by patmill** [comment]
Sorry for losing track of old issues @harshdamaniahd .  Did you get this sorted out?  There are some documents around this area - 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-loading
