### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by shafaqat309** [SharePoint/sp-dev-docs#1763]
I am getting build error in render function on this line return (<DocumentCard .....  error is "type Boolean is not assignable to type Element"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f89fed-848e-50b9-6be4-657824ad262e
* Version Independent ID: 3d3c5227-7281-ef49-a2d1-686c0a049497
* Content: [Use Office UI Fabric React components in your SharePoint client-side web part](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components)
* Content Source: [docs/spfx/web-parts/get-started/use-fabric-react-components.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/use-fabric-react-components.md)
* Service: **unspecified**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
This indicates that there's something wrong with your setup and we would need to have more details on the exact environment versions in use so that we can determine what exactly goes wrong. As this is however already a quite old issue, would recommend repeating the article with latest SPFx version and then resubmit the issue with additional details, if you can reproduce this issue. Thanks for your input.
