### ISSUE TITLE
on my dev tenant https://magenicdojo.sharepoint.com, i followed all the steps to CDN enable the app catalog for new apps but they fail to appear as installable in the sites

### ISSUE THREAD

**Issue by bigpix2000** [SharePoint/sp-dev-docs#1786]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After following all the steps, ability to add the SPFX Hello World Web part appears in tenant sites

#### Observed Behavior

The App appears in the App Catalog correctly but does not appear as an App to add.

#### Steps to Reproduce

1) Insure that App Catalog exists in Tenant
2) Run via powershell or office365-cli
3) connect to site admin (-admin)
4) list cdn origins
5) noticed that */CLIENTSIDEASSETS was missing
6) Added it and waited until it was ready (20 minutes) 
7) used power shell/cli to add app catalog e.g. spo site appcatalog add --url "https://magenicdojo.sharepoint.com/sites/mmoapps" --verbose 
8) create web part yo @Microsoft/sharepoint 
9) simple web part no framework
10) gulp serve to test in local and online workbench
11) gulp bundle --ship
12) gulp package-solution --ship
13) drag and drop package into app catalog
14) confirm it is in list (optional to edit parameters to make "noteworthy") 
15) go to any site and attempt to add the web part ... all previously deployed web parts are there but any new one is not.  

Please help :( I don't mind blowing away my entire tenant to make this work since this is dev.

**Comment by patmill** [comment]
So, the CDN shouldn't be at play here.  Even if the CDN is not available, the files will just be served directly from SharePoint itself, and those files don't even need to exist in order to see the toolbox entry.  They just won't work when you put them on a page.

In order to not have to install / "add an app" in a site to see the new webpart, you need to do two things.  1 - your package-solution.json file needs an entry 
    "skipFeatureDeployment": true,

and 2 - when you activate the solution after dropping it into the app catalog, you need to select the option to make it available everywhere.

Can you confirm you've done those two things?

**Comment by bigpix2000** [comment]
so ... the last step I did just before this was a do over of "add app catalog" and after getting the email on this reply, I went back to check the status of the web part and sure enough ... it was there!  I am thinking that there was a delay involved but since I also did a "enable Private" CDN at the same time in desperation, I can't tell if that had anything to do with it ... I will test a few more times and open a fresh issue IF the problem returns or persists.  thank you!
