### ISSUE TITLE
Cannot add multiple items in list where using pnp batching

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/sp-dev-docs#1848]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I use **"sp-pnp-js": "^3.0.4"**  Where i trying to create batch for - add multiple items into a list for SharePoint On-Premise .

**This is my code:**
```
    let list = pnp.sp.web.lists.getByTitle("КИРИЛИЦА"); //cyrillic
    let batch = pnp.sp.web.createBatch();

    list.getListItemEntityTypeFullName().then(entityTypeFullName => {

      allCorectTravels.forEach((travel, index) => {

        list.items.inBatch(batch).add({
          Title: String(index)
        }, entityTypeFullName).then(b => {
          console.log(b);
        });
        
      })

      batch.execute().then(d =>
        console.log("Done")
      );

    });
```
![untitled](https://user-images.githubusercontent.com/14110861/40001358-b85d157a-5796-11e8-9c58-6abd0b2f8314.png)

**Error is:**

![untitled2](https://user-images.githubusercontent.com/14110861/40001359-b87bf22e-5796-11e8-9a95-7018fa2399cf.png)

**Comment by anomepani** [comment]
@geogikk92, @VesaJuvonen 
I have tried to reproduce the same issue using plain batch request and found that title "КИРИЛИЦА" of document or list have special characters.
So while generating a batch request body based on list title, requestURL must be encoded.
e.g. `POST https://brgrp.sharepoint.com/sites/WMAMaster/_api/Lists/gEtbytitle('%D0%9A%D0%98%D0%A0%D0%98%D0%9B%D0%98%D0%A6%D0%90')/items HTTP/1.1`
**instead of POST** `https://brgrp.sharepoint.com/sites/WMAMaster/_api/Lists/gEtbytitle('КИРИЛИЦА')/items HTTP/1.1`
