### ISSUE TITLE
Something went wrong in SPFX web part after deployment on SharePoint

### ISSUE THREAD

**Issue by rajeshlohar** [SharePoint/sp-dev-docs#1879]
Hi,

We are facing an issue. We developed a SPFX Web Part. It is working fine on local workbench. But when we deployed it on SharePoint, it is throwing error as below.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "e7fdd007-c74e-4942-8bf1-38052448d1a9" (MyWebPart).
Original error: ***Failed to load URL 'https://code.jquery.com/jquery-2.1.1.min.js/my-mywebpartstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js' for resource 'myWebPartStrings' in component 'e7fdd007-c74e-4942-8bf1-38052448d1a9' (myWebPart). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

I tried below 

gulp clean
gulp bundle --ship
gulp package-solution --ship

When I executed "gulp serve --nobrowser" then nothing happens. 

Please help.

**Comment by Debbledon** [comment]
I also have this problem...
I opened Issue: https://github.com/SharePoint/sp-dev-docs/issues/2215 

No one has responded yet. But it seems somehow related to https://github.com/SharePoint/sp-dev-docs/issues/632...  That is a server-side issue (but was not explained...)... I'm hoping to get an explanation... 

In the meantime, I did a LOT of troubleshooting and experimentation. If I carefully follow the instructions for building the hello world app with VS Code (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part), it works!  It SEEMS to be working because it's using v1.1.0 of the Microsoft modules... 

Once I upgrade the code to use version 1.4.1 or 1.5.1, it still works locally but breaks on remote systems... So, this leads me to believe something needs to be upgraded/fixed on the server to allow use of the newer code...

You put this in two months ago and never got a reply. Did you ever get it working? If so, how?

**Comment by Debbledon** [comment]
I closed my related issue... 
You might want to close this one as well... 

"On-premises only supports v1.1" (@VesaJuvonen, 2017). There should be a on-prem update late in 2018 or early 2019, but it has not been relased yet. For now, use v1.1.

Related: 

On-Prem: 
* https://github.com/SharePoint/sp-dev-docs/issues/1879
* https://github.com/SharePoint/sp-dev-docs/issues/2215
* https://github.com/SharePoint/sp-dev-docs/issues/1100
* https://github.com/SharePoint/sp-dev-docs/issues/1102
* https://github.com/SharePoint/sp-dev-docs/issues/1075

Similar via SharePoint Online: 
* https://github.com/SharePoint/sp-dev-docs/issues/632
* https://github.com/SharePoint/sp-dev-docs/issues/1920

Same error, but not sure if related:
https://github.com/SharePoint/sp-dev-docs/issues/985


References: 
#1100, #1102, #1075

Per @VesaJuvonen  on Dec 2 2017 
* That is correct, on-premises only supports v1.1 simply release logistics and this is also why there's a separate question on online/on-prem in the Yeoman flow.

* Only v1.1 is supported with SharePoint 2016 Feature Pack 2, like stated in our documentation. We will update the documentation when there will be changes for this. You can expect 1.1 support to remain with SP2016 for now (due server side dependency) and then have newer version supported with SP2019, when that's out later 2018.

Per @VesaJuvonen  on Dec 5 2017 
* Docs related on the SP2016 support are at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support and referenced also in https://dev.office.com/blogs/now-available-deploy-sharepoint-framework-web-parts-to-sharepoint-server-2016-with-feature-pack-2 where this support was announced.
