### ISSUE TITLE
Can't able to running V3 or higher of npm 

### ISSUE THREAD

**Issue by lakshmitulasi** [SharePoint/sp-dev-docs#191]
Can't able to running V3 or higher of npm by running the following command:
npm -g install npm@next

I run the script with different network but no luck.

Error:

_PS C:\Windows\system32> npm -g install npm@next
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g
 "install" "npm@next"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.20.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log_

Please help on this...

Thanks in Advance!
Lakshmi

**Comment by simkessy** [comment]
This should probably be a question related to NPM, I'd ask on Stackoverflow.

**Comment by pgonzal** [comment]
The error log above suggests that the npmjs.com server was offline, or there was a problem with your internet connection.  Since it has been 19 days, I am closing this bug.  Please reopen it if you are still having issues.

FYI the advice to run `npm -g install npm@next` is incorrect.  The correct command is:

`npm -g install npm@3`

I will  update our setup documentation to correct this.
