### ISSUE TITLE
Error: Cannot find module 'gulp-webserver'

### ISSUE THREAD

**Issue by patmill** [SharePoint/sp-dev-docs#20]
From stack exchange (http://sharepoint.stackexchange.com/questions/183925/error-cannot-find-module-gulp-webserver)

Issue - While spinning up the SharePoint framework, getting the mentioned error instead of running the gulp task which I got scaffold from the Yeoman.

Answer - Issue was with the existance of the web server. Solution: Go to gulp location within your solution and use below..Solved!

$ npm install --save-dev gulp-webserver
This would be usefull - https://www.npmjs.com/package/gulp-webserver

@SPDoctor - To help debug - any chance you could give some information on your environment, steps, etc?

**Comment by SPDoctor** [comment]
You'll need to ask the OP on SharePoint.StackExchange.com. This is old question - I tagged it (mainly in order to seed the #spfx tag ;-).

**Comment by nickpape-msft** [comment]
This seems like it is an issue with the `npm install` step, which (occasionally) won't install every dependency. In those occasions the best idea is to just run `npm install` again. If that fails, then please open a bug on us as our dependency list would be incorrect.

Closing this bug since it doesn't repro now.
