### ISSUE TITLE
unable to start chrome using existing session

### ISSUE THREAD

**Issue by peterremote1980** [SharePoint/sp-dev-docs#2049]
unable to start chrome using existing session even i comment out "-incognito" in launch.json. Chrome will start in clean, i need to re-login to sharepoint. How to fix it?
thanks

**Comment by thechriskent** [comment]
Thanks for you interest! However, this is an issue with Chrome, not SharePoint development so it will be closed for now. If you are convinced the issue is with the SPFx toolchain, please provide additional details such as the version of SPFx and the versions of your other tools (node, chrome, etc.). Thanks!
