### ISSUE TITLE
External reference tries loading from https://spoppe-a.akamaihd.net

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#207]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

I'm trying to load winston.js into the default React (hello world) component, but I cannot get it to work. When running in workbench and adding the webpart I receive the following error:

> Error: Unable to load web part script resources due to: Error: Error: https://spoppe-a.akamaihd.net/files/winston did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support. Error loading https://spoppe-a.akamaihd.net/files/winston. at https://dci5cg6011dzr:4321/node_modules/@microsoft/sp-client-preview/dist/sp-client-preview.js:17250:32
> The winston.js file is loaded correctly, as I can see in the browser's network tab, but indeed the address "https://spoppe-a.akamaihd.net/files/winston" is unreachable/invalid.

To reproduce, I performed the following:

`npm install --save winston`
`tsd install winston --save`
added the winston library as external reference in `config/config.json`
in code: `import * as Winston from "winston";` and `Winston.info("LOG TEST");`

Using Windows 10, generator v0.1.2, chrome browser

**Comment by waldekmastykarz** [comment]
You mention that you both installed Winston as a package in your project and defined it as an external resource. Typically you would do either one but not both. Would you prefer to load Winston from an external URL or have it included in your web part's bundle?

**Comment by patmill** [comment]
So as mentioned in the same Stack Exchange issue (http://sharepoint.stackexchange.com/questions/194447/loading-external-library-fails-if-loading-a-global-module-configure-the-global)

You either need to use an external CDN to load your external assemblies, or you need to bundle them.  Can you show your config.json entry?

**Comment by Trickass** [comment]
Sure, config entry is like this:

`"winston": "node_modules/winston/lib/winston.js`

So, I don't want the package included with the bundle, but don't want to uwe CDN either. Same as React and React-Dom libs?

**Comment by patmill** [comment]
OK, I see where you are at.  You want to have the module in your assets that are uploaded to a CDN (or run locally in the workbench), but not included in your webpart.bundle.js file, and you are following the guidance here - http://dev.office.com/sharepoint/docs/spfx/web-parts/basics/add-an-external-library and it's not working.

So first off, we need to improve our logging when we encounter errors when loading modules.  The error isn't that it can't find the js file.  If you look at the network tab in the debugger, you will see that it is loaded.

The problem here, unfortunately, is that winston is not compatible with the framework.  It isn't a normal AMD module, and it appears (at first glance) to be more of a node.js server component than a library that would be loaded in the browser.  The winston.js file is really just one of the numerous files that need to be loaded, and webpack has no idea that those other files exist, so they aren't included.  Moving to bundling it internally also fails, because it tries to load the FS object.

@nickpape-msft to keep me honest.

**Comment by Trickass** [comment]
So basically, my approach was correct, but I should go look for another logging solution? :) Probably one which doesn't use FS object? :)

**Comment by patmill** [comment]
Right.  Although have you tried using the Logging APIs that come with the framework?  Let me try and get a doc written up on how to use them.

**Comment by Trickass** [comment]
That would be great if you could. No idea what's in there now of how to use it. 
Just for completeness, I was looking to abstract the logging to AppInsights, which winston does quite well.

**Comment by Trickass** [comment]
@patmill thank you for the wiki.
