### ISSUE TITLE
Site Collection App Catalog - External Users

### ISSUE THREAD

**Issue by kezack** [SharePoint/sp-dev-docs#2078]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I created a site collection with external user.

I add the app catalog on the site collection (**Add-SPOSiteCollectionAppCatalog**)

I deployed an app in the site collection app catalog and I shared the site with an external user.

The external user has a blank page on the site.

when I disable the app catalog (**Remove-SPOSiteCollectionAppCatalog**), the external user see the site.

regards

**Comment by jhholm** [comment]
I've run into this same problem. There is a thread around this issue here
https://techcommunity.microsoft.com/t5/SharePoint-Developer/Site-Collection-App-Catalog-External-Users/td-p/149694

My external users can access pages that do not contain any custom webparts.

As far as I can understand, adding external user access to the tenant catalog should/could fix this issue right now. But hardly it's a good option.

The thread goes pretty well all the use cases and where the bug seems to exist.

**Comment by kezack** [comment]
Thank you, I will do some tests on different tenants

**Comment by kezack** [comment]
It's essential to share the tenant catalog for external user.

The external users have the page with the webparts, but have many times the blank page.

Do you have a solution ?

**Comment by nero120** [comment]
I've just tested this again in our tenant and I'm no longer experiencing the issue, using my guest account I can see the SPFX web parts (installed to the site collection app catalog)  just fine! Could this have been resolved but this issue not been updated @VesaJuvonen?

**Comment by PooLP** [comment]
On my tenant, i have same problem, any news ?

@VesaJuvonen : It is strange that we also have to share the application catalog for each external user.

**Comment by mcmynn83** [comment]
Yes this issue has been resolved and we didn't update this thread.  
@PooLP - Could you open a new issue and give details about your problem on that thread?  The issue of not being able to see webparts as an external user on both the tenant app catalog and the site collection app catalog has been fixed.  Therefore the problem you are seeing may be specific to your tenant.
