### ISSUE TITLE
Modern pages are not responsive anymore

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#2094]
#### Category
- [X] Bug

#### Expected or Desired Behavior

When using 2/3 left and 1/3 right section on a modern page, the columns should collapse in smaller resolutions

#### Observed Behavior
Currently the columns do not collapse. See screenshot below.

![responsive](https://user-images.githubusercontent.com/8672900/41763000-39ea175a-75ec-11e8-9725-63c5565dac68.PNG)

**Comment by rmillener** [comment]
@OliverZeiser we also have this issue. I have logged a support call and encourage you to do the same. There have recently been a high volume of issues on here and many of them aren't getting any attention.

**Comment by VesaJuvonen** [comment]
As this is indeed a non-developer issue - in oob pages - we would recommend opening the issue using the normal SPO support channels. As this is a normal UI issue, they will support it. This issue list is for the developer issues with dev platform engineering. We are trying to balance this due to the load and expertize. Closing this as a non-developer topic which we cannot tackle in the dev platform.

**Comment by mkumbhare** [comment]
I also happened to see this issue on our tenant. Please let me know if any update from Microsoft support team.

**Comment by OliverZeiser** [comment]
@VesaJuvonen it is a developer issue as well. Because we can not test our Webparts in the correct breakpoints anymore. But besides… Have you ever tried to go via the normal SPO support? They make you install Windows updates first and then have you do fiddler traces for something that is obviously an issue with SPO, before they even think about helping...

**Comment by VesaJuvonen** [comment]
I understand that it impacts also developers, but I cannot route this forward through this channel as this is non-dev issue. That's the agreement with the feature owners.
