### ISSUE TITLE
Navigating between sites breaks left navigation

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#2095]
#### Category
- [X] Bug

#### Expected or Desired Behavior
When navigating between sites, the left nav should be the correct on every site.

#### Observed Behavior
Currently when navigating between sites, the left nav does not refresh and has the old navigation from the site before. After refreshing the site it is working, but the partial MDS-like navigation between sites, does not refresh the navigation

**Comment by VesaJuvonen** [comment]
Seems to be closely related with the #1971, but as this seems not to be a dev issue, as the issue is in the oob navigation, we would ask this to be reported through the standard SharePoint Online support as the issue can be reproduced apparently also without any code. This is just internal alignment in the Microsoft so we cannot process this through dev support channels.

**Comment by rmillener** [comment]
@OliverZeiser this has been fixed in our tenancy
