### ISSUE TITLE
Tutorial 3: Error in App Package (SPFX)

### ISSUE THREAD

**Issue by dmcrock** [SharePoint/sp-dev-docs#21]
I am getting an error in tutorial 3 of the SPFX. When adding the hello-world-webpart to the app catalog. Says "There were errors when validating the App Package. The package manifest doesn't contain a StartPage element in Properties." I have followed every instruction. 

I am in my Developer tenant with first release enabled
Thank you

**Comment by patmill** [comment]
@chakkaradeep - can you take a look?

**Comment by chakkaradeep** [comment]
@dmcrock can you please confirm if you are using a dev tenant with first release enabled?

**Comment by dmcrock** [comment]
@chakkaradeep do you want me to delete my entire tenant, and start from scratch? just confirming before i do that

**Comment by patmill** [comment]
Don't delete the tenant, just create a new one.

**Comment by nickpape-msft** [comment]
@dmcrock Any updates to this? Does the dev tenant work? If so, let's close this issue.

**Comment by MaheshakaMudli** [comment]
@dmcrock : I am also getting the same error "There were errors when validating the App Package". I am having dev tenant and dev site too. Still the error while adding the app to the developer site.

**Comment by rynetate** [comment]
Any updates on this? Same problem

**Comment by pedromneto** [comment]
This error occurs because the app schema is not yet officially released. To publish you have to enable the first release. Here are some links to solving this problem:

https://dev.office.com/sharepoint/docs/spfx/set-up-your-developer-tenant

https://support.office.com/en-us/article/Set-up-the-Standard-or-First-Release-options-in-Office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47?ui=en-US&rs=en-US&ad=US

**OBS.:** This link is in Portuguese and shows in detail how to configure and enable the first release:

http://www.pedromneto.com/configurando-o-sharepoint-online-para-testar-o-sharepoint-framework/

**Comment by MaheshakaMudli** [comment]
The error gets resolved when we activate the "first release tenent wide"...

**Comment by manishgarg1** [comment]
This is also resolved.
