### ISSUE TITLE
Action Button Icon Rendering as Square Placeholder

### ISSUE THREAD

**Issue by sbglr** [SharePoint/sp-dev-docs#2101]
When using the "Add an action button to a field (advanced)" code verbatim, the "Mail" icon renders as a square placeholder in multiple tenants across all devices I've tested on. The action itself of opening a compose window works with no issue, it's just the icon seemingly failing to render. Any insight into what might be happening?

Microsoft Support was able to reproduce on their end but unable to provide any insight as to why. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by sbglr** [comment]
Following up. After screwing around with the code a little bit I figured out that removing the line below resolves the issue. Is this an edit I'm allowed to suggest to the doc?
`        "class": "sp-field-quickAction",`

**Comment by thechriskent** [comment]
Good catch! This is an issue with the `sp-field-quickAction` class. Until recently this was the definition:
```css
.sp-field-quickAction {
    font-size: 14px;
    font-weight: 400;
    padding: 0;
}
```

However, a recent change introduced the font-family attribute which is overriding the UI Fabric font.
```css
.sp-field-quickAction {
    font-family: "Segoe UI Regular WestEuropean","Segoe UI",Tahoma,Arial,sans-serif;
    font-size: 14px;
    font-weight: 400;
    padding: 0;
}
```

So, the solution is to fix this class by removing the font-family attribute. We should leave the docs alone since this was previously (and will be again) correct information.

For now, you can continue to use the `sp-field-quickAction` class and add an additional style attribute for `font-family` to the `a` element to override the issue:

```json
{
    "elmType": "div",
    "children": [
        {
            "elmType": "span",
            "style": {
                "padding-right": "8px"
            },
            "txtContent": "@currentField.title"
        },
        {
            "elmType": "a",
            "style": {
              "font-family": "FabricMDL2Icons"
            },
            "attributes": {
                "iconName": "Mail",
                "class": "sp-field-quickAction",
                "href": {
                    "operator": "+",
                    "operands": [
                        "mailto:",
                        "@currentField.email",
                        "?subject=Task status&body=Hey, how is your task coming along?.\r\n---\r\n",
                        "@currentField.title",
                        "\r\nClick this link for more info. http://contoso.sharepoint.com/sites/ConferencePrep/Tasks/Prep/DispForm.aspx?ID=",
                        "[$ID]"
                    ]
                }
            }
        }
    ]
}
```

**Comment by sbglr** [comment]
Right on! Glad to hear I'm not crazy and this really did change under my nose. 

I've gone ahead and implemented the enclosed bit of code. Thanks for the background on this, it makes a ton of sense.

**Comment by rbert83** [comment]
When do they think this will be fixed?

**Comment by arneivar** [comment]
sp-field-quickAction is unusable, but sp-field-quickActions (with plural s) works nicely...

**Comment by arneivar** [comment]
@thechriskent, Thank you for the clarification. I was tricked by the icon that rendered correctly.

**Comment by spurr82** [comment]
@thechriskent , any idea how i can can get this working?

**Comment by thechriskent** [comment]
Not all icons listed on the UI Fabric site are supported in the list views (or SharePoint Framework) because of differing versions of UI Fabric being used (the site always represents the latest release). This is extremely frustrating and something I've personally complained about to the UI Fabric guys. A simple version selector that adjusted the list of icons and the documentation would be very helpful.

Unfortunately, the only way to tell for now is trial and error. Most of them work (and the others will eventually work). So, do as you've done, and verify a known icon like `Mail` work in your format then switch them for the others (they are case sensitive) to see if they will work.
