### ISSUE TITLE
List of permissible values missing

### ISSUE THREAD

**Issue by mairaw** [SharePoint/sp-dev-docs#2227]
Original Github issue https://github.com/dotnet/docs/issues/6426 from @Toonshorty 

The documentation for site designs (https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-json-schema#configure-regional-settings) links to this page for displaying a list of permissible values, but no values are shown in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac08219-6183-0904-50e6-682d748946fb
* Version Independent ID: 549cb147-3696-9a9a-f22e-ee76decf6e59
* Content: [SPRegionalSettings.TimeZones Property (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spregionalsettings.timezones?redirectedfrom=MSDN&view=sharepoint-server#feedback)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPRegionalSettings.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by kottogriffitheduau** [comment]
I got this from our On-Prem farm (Typical MS doco lacking useful information especially since moving to github):
39 (UTC-12:00) International Date Line West                     
 95 (UTC-11:00) Coordinated Universal Time-11                    
 15 (UTC-10:00) Hawaii                                           
 14 (UTC-09:00) Alaska                                           
 78 (UTC-08:00) Baja California                                  
 13 (UTC-08:00) Pacific Time (US and Canada)                     
 38 (UTC-07:00) Arizona                                          
 77 (UTC-07:00) Chihuahua, La Paz, Mazatlan                      
 12 (UTC-07:00) Mountain Time (US and Canada)                    
 55 (UTC-06:00) Central America                                  
 11 (UTC-06:00) Central Time (US and Canada)                     
 37 (UTC-06:00) Guadalajara, Mexico City, Monterrey              
 36 (UTC-06:00) Saskatchewan                                     
 35 (UTC-05:00) Bogota, Lima, Quito                              
 10 (UTC-05:00) Eastern Time (US and Canada)                     
 34 (UTC-05:00) Indiana (East)                                   
 88 (UTC-04:30) Caracas                                          
 91 (UTC-04:00) Asuncion                                         
  9 (UTC-04:00) Atlantic Time (Canada)                           
 81 (UTC-04:00) Cuiaba                                           
 33 (UTC-04:00) Georgetown, La Paz, Manaus, San Juan             
 65 (UTC-04:00) Santiago                                         
 28 (UTC-03:30) Newfoundland                                     
  8 (UTC-03:00) Brasilia                                         
 85 (UTC-03:00) Buenos Aires                                     
 32 (UTC-03:00) Cayenne, Fortaleza                               
 60 (UTC-03:00) Greenland                                        
 90 (UTC-03:00) Montevideo                                       
103 (UTC-03:00) Salvador                                         
 96 (UTC-02:00) Coordinated Universal Time-02                    
 30 (UTC-02:00) Mid-Atlantic                                     
 29 (UTC-01:00) Azores                                           
 53 (UTC-01:00) Cape Verde Is.                                   
 86 (UTC) Casablanca                                             
 93 (UTC) Coordinated Universal Time                             
  2 (UTC) Dublin, Edinburgh, Lisbon, London                      
 31 (UTC) Monrovia, Reykjavik                                    
  4 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna 
  6 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
  3 (UTC+01:00) Brussels, Copenhagen, Madrid, Paris              
 57 (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb                 
 69 (UTC+01:00) West Central Africa                              
 83 (UTC+01:00) Windhoek                                         
 79 (UTC+02:00) Amman                                            
  5 (UTC+02:00) Athens, Bucharest, Istanbul                      
 80 (UTC+02:00) Beirut                                           
 49 (UTC+02:00) Cairo                                            
 98 (UTC+02:00) Damascus                                         
 50 (UTC+02:00) Harare, Pretoria                                 
 59 (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius    
101 (UTC+02:00) Istanbul                                         
 27 (UTC+02:00) Jerusalem                                        
  7 (UTC+02:00) Minsk (old)                                      
104 (UTC+02:00) E. Europe                                        
 26 (UTC+03:00) Baghdad                                          
100 (UTC+03:00) Kaliningrad, Minsk                               
 74 (UTC+03:00) Kuwait, Riyadh                                   
 56 (UTC+03:00) Nairobi                                          
 25 (UTC+03:30) Tehran                                           
 24 (UTC+04:00) Abu Dhabi, Muscat                                
 54 (UTC+04:00) Baku                                             
 51 (UTC+04:00) Moscow, St. Petersburg, Volgograd                
 89 (UTC+04:00) Port Louis                                       
 82 (UTC+04:00) Tbilisi                                          
 84 (UTC+04:00) Yerevan                                          
 48 (UTC+04:30) Kabul                                            
 87 (UTC+05:00) Islamabad, Karachi                               
 47 (UTC+05:00) Tashkent                                         
 23 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi              
 66 (UTC+05:30) Sri Jayawardenepura                              
 62 (UTC+05:45) Kathmandu                                        
 71 (UTC+06:00) Astana                                           
102 (UTC+06:00) Dhaka                                            
 58 (UTC+06:00) Ekaterinburg                                     
 61 (UTC+06:30) Yangon (Rangoon)                                 
 22 (UTC+07:00) Bangkok, Hanoi, Jakarta                          
 46 (UTC+07:00) Novosibirsk                                      
 45 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi            
 64 (UTC+08:00) Krasnoyarsk                                      
 21 (UTC+08:00) Kuala Lumpur, Singapore                          
 73 (UTC+08:00) Perth                                            
 75 (UTC+08:00) Taipei                                           
 94 (UTC+08:00) Ulaanbaatar                                      
 63 (UTC+09:00) Irkutsk                                          
 20 (UTC+09:00) Osaka, Sapporo, Tokyo                            
 72 (UTC+09:00) Seoul                                            
 19 (UTC+09:30) Adelaide                                         
 44 (UTC+09:30) Darwin                                           
 18 (UTC+10:00) Brisbane                                         
 76 (UTC+10:00) Canberra, Melbourne, Sydney                      
 43 (UTC+10:00) Guam, Port Moresby                               
 42 (UTC+10:00) Hobart                                           
 70 (UTC+10:00) Yakutsk                                          
 41 (UTC+11:00) Solomon Is., New Caledonia                       
 68 (UTC+11:00) Vladivostok                                      
 17 (UTC+12:00) Auckland, Wellington                             
 97 (UTC+12:00) Coordinated Universal Time+12                    
 40 (UTC+12:00) Fiji                                             
 99 (UTC+12:00) Magadan                                          
 92 (UTC+12:00) Petropavlovsk-Kamchatsky - Old                   
 67 (UTC+13:00) Nuku'alofa                                       
 16 (UTC+13:00) Samoa

**Comment by andrewconnell** [comment]
Here's the correct list: https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ms453853(v=office.15)?redirectedfrom=MSDN

Looks like links are pointing to the wrong things. Will look into this...
