### ISSUE TITLE
Whay are the localization files in JavaScript format?

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#225]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Why do we have the localization files xx-yy.js in JavaScript format and not a JSON file or similar (that is transpiled to a js file during build)? I think a json file would make it less error prone. Thoughts? All other files looks neat and nice with TypeScript and JSON schemas - but these files are pure AMD JavaScript files

**Comment by patmill** [comment]
@nickpape-msft - can you shed some light?

**Comment by iclanton** [comment]
The short answer is that we haven't finished building the tooling around using JSON or other formats for localized resources, so we opted to use something robust and usable, albeit rough, for now.

The longer answer is that we internally use RESX files, but that's mostly due to the requirements of our translation pipeline. Eventually we're going to release our RESX tooling, but what we're using internally isn't flexible enough to really be usable by third parties yet. Our goal is to let you basically use any format you want (RESX, JSON, etc...) and we'll either provide tooling for you (for some formats like plain JSON and RESX) or let you write your own adapter for other formats.

**Comment by wictorwilen** [comment]
Thanks a bunch!

**Comment by pgonzal** [comment]
My 2 cents:  For small config files JSON and XML are basically equivalent.  However, for the scenario of large, human-authored config files, XML has a number of advantages:

- Support for comments
- Opening/closing tags that make it easier to navigate large hierarchies
- Better syntax error messages due to a better lexical analyzer (e.g. that can report line numbers) and a parser that has more grammatical context
- The [XML schema](https://en.wikipedia.org/wiki/XML_schema) is more powerful and more widely adopted than [JSON schema](http://json-schema.org/)

That said, we do plan to open up the tooling to allow developers to implement custom localization file formats.

**Comment by pgonzal** [comment]
I'm closing this because I believe the question was answered. If not, please reopen the bug.
