### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by Shamrh** [SharePoint/sp-dev-docs#2268]
When I generated a web part solution there are vulnerable packages installed. Any guidance on how to fix them. using NPM audit fix will not fix until you fix them forcefully. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part#preview-the-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
We do fix these as part of the new SPFx releases, but there's no specific guidance from Microsoft for these directly as they are not owned by us, so we cannot really fix them either. With the upcoming 1.6 release, we have once again removed all vulnerable packages, but as we do not control all packages which we have dependencies, we can't guarantee that there will not be new findings in future. It's also important to notice that the level of vulnerability is always different. Any real security issues in the framework for runtime issues will be fixed in the SPO and in the Yeoman as fast as possible.
