### ISSUE TITLE
Is it possible to deploy SPFX extension(ListView Command Bar) to only one communication site instead of App Catalog ?

### ISSUE THREAD

**Issue by pkrsingh86** [SharePoint/sp-dev-docs#2314]
Is it possible to deploy SPFX extension(ListView Command Bar) to only one communication site instead of App Catalog ?

#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
#SPFX #SharePointOnline #SharePointFramework #CommunicationSite

**Comment by pkrsingh86** [comment]
@frnk01

**Comment by frnk01** [comment]
You always need to deploy your app package to the app catalog.

If I understand you correctly you want to restrict users from adding the app to multiple site collections?

If my assumption is correct you can answer ‘No’ on the option for tenant scoped in the yeoman setup, this will force you to enable the feature on the specific site before the app becomes available on the site.

**Comment by gautamdsheth** [comment]
You can make use of the Site collection app catalog.

You first need to activate the Site collection app catalog on your communication site and then deploy your extension there instead of the tenant app catalog. To activate site collection app catalog requires SharePoint tenant admin permissions.

Reference  - [Use the site collection app catalog](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog)

**Comment by anupJag** [comment]
Hi, Since your requirement is very specific for a solution to be made available for only 1 communication site, instead of making the solution available across the entire tenant. In this particular scenario, as @gautamdsheth has pointed out, make use of Site Collection app catalog.

**Comment by pkrsingh86** [comment]
@gautamdsheth @anupJag - Thanks. This is new feature to deploy app directly in the app catalog of the site collection itself. I need to check how to do the deployment and use CDN. Do you think it is same way we deploy to site app catalog ? I will go through the article though. @frnk01 - thanks for your help.

**Comment by gautamdsheth** [comment]
Yes, it is the same way as we do on the tenant app catalog.
