### ISSUE TITLE
[HTTP]:500 -  [CorrelationId]:ce55829e-50e8-6000-366c-8ca50e594c4f [Version]:16.0.0.7925 - The requested operation is part of an experimental feature that is not supported in the current environment.

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#2320]
Unable to access link : https://mylinkapps-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/WebApiPermissionManagement

**Comment by gautamdsheth** [comment]
This most likely means that your tenant is not in the targeted release mode.

You can setup your tenant to be in the targeted release by following [this link](https://support.office.com/en-us/article/set-up-the-standard-or-targeted-release-options-in-office-365-3b3adfa4-1777-4ff0-b606-fb8732101f47)

Once you change to targeted release, you need to wait for a few hours to receive the updates and after that it will start working.

**Comment by harshdamaniahd** [comment]
@gautamdsheth  Thanks.
These settings are already in place, but still it is not working
Are there any prerequisites for this.

**Comment by gautamdsheth** [comment]
Did you set target release to all users ?

**Comment by harshdamaniahd** [comment]
yes..this is already in place

**Comment by harshdamaniahd** [comment]
There is something wrong wit this page
![image](https://user-images.githubusercontent.com/11780473/43894699-8ae0a5b4-9bf0-11e8-8afd-5b506a52ae92.png)

**Comment by VesaJuvonen** [comment]
This is indeed the tenant level targeted release setting. Notice that it takes up to 24 hours for that take into effect, so you will need to be patient after changing the setting. It also needs to be the full tenant setting, not just in individual persons.

If that is not working, we would need to get more details on the issue. This means that you should go to the page again, copy the exception with the Correlation ID. Share then timing, tenant name, and correlation ID with us, so that we can have a closer look at what goes wrong. Thanks for the additional details advance.

**Comment by harshdamaniahd** [comment]
ok, I will wait and if not working I will provide the details.
@VesaJuvonen :-)

**Comment by harshdamaniahd** [comment]
Yes, it works now (tenant settimg needs to be full tenant and not individual persons)
Thanks @VesaJuvonen
