### ISSUE TITLE
Knockout web part with properties fails when running in SharePoint

### ISSUE THREAD

**Issue by davros85** [SharePoint/sp-dev-docs#233]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea
#### Expected or Desired Behavior

That after building a new project based on the knockout template you should be able to run it in the Workbench within SharePoint. 
#### Observed Behavior

When running in the local workbench, web part renders and custom properties are fine. When running in the Workbench in SharePoint, errors are logged below the web part. With a new, untouched project this is "Cannot read property 'description' of undefined".
#### Steps to Reproduce

Yo a new project using knockout, (fix the _description bug), and run it in the Workbench in a SharePoint dev tenant.

**Comment by manishgarg1** [comment]
Thanx for reporting. We will look into this.

**Comment by patmill** [comment]
This is fixed in the next drop.  For now, you can replace the _description variable in the generated code with _koDescription, and that will fix the issue.

**Comment by davros85** [comment]
@patmill - this is not the same issue as already logged, it's when using any properties in the knockout template, then running it in the SharePoint workbench.

**Comment by manishgarg1** [comment]
Great.

**Comment by patmill** [comment]
@davros85 - Got it, thanks.  I read Knockout and Description, and jumped to the wrong answer.

**Comment by patmill** [comment]
OK, picking up on this.  The first issue is that the this.properties does not exist in the constructor, as we have not yet deserialized them.  We added an extra step here to handle issues around persisted data schema drift (version 2 of the webpart expects data in a different format, so we need to give the developer a change to fix up the data that they were handed).

The right place to do most of this is in onInit.  However, for some reason the compontentElement doesn't have the template HTML in it when it is being set.  I'm not exactly a knockout expert, so having a bit of difficulty sorting out what the issue here is.

At any rate, to move to the next step, pull everything out of the constructor after 
    super(context);
    this._id = _instance++;
and put it into onInit like so - 

  protected onInit<T>(): Promise<T>
  {
    const tagName: string = `ComponentElement-${this._id}`;
    const componentElement: HTMLElement = this._createComponentElement(tagName);
    this._registerComponent(tagName);
    this.domElement.appendChild(componentElement);

    const bindings: IHelloWorldBindingContext = {
      description: this.properties.description,
      shouter: this._shouter
    };

    ko.applyBindings(bindings, this.domElement);

    this._koDescription.subscribe((newValue: string) => {
      this._shouter.notifySubscribers(newValue, 'description');
    });

    return Promise.resolve(null);
  }

**Comment by patmill** [comment]
OK, more information.  Here's the workaround, as well as what the underlying bug is.

The underlying issue for why onInit() isn't working is that there is logic to handle onInit() taking too long that involves modifying the DOM to show a spinner.  The spinner is supposed to be an overlay that is cleared, but currently is deletes the contents of the DOM, which wipes out the knockout stuff.  So for now, do this:

0 - Update your constructor to look like this

    public constructor(context: IWebPartContext) {
      super(context);
      this._id = _instance++;
    }

1 - Create a new function

        private doInitStuff() : void
        {
          const tagName: string = `ComponentElement-${this._id}`;
          const componentElement: HTMLElement = this._createComponentElement(tagName);
          this._registerComponent(tagName);
          this.domElement.appendChild(componentElement);

          const bindings: IHelloWorldBindingContext = {
            description: this.properties.description,
            shouter: this._shouter
          };

          ko.applyBindings(bindings, this.domElement);

          this._koDescription.subscribe((newValue: string) => {
            this._shouter.notifySubscribers(newValue, 'description');
          });
        }


2 - Update your Render method to look like this

    public render(): void {
      if ( !this.renderedOnce )
      {
        this.doInitStuff();
      }

      this._koDescription(this.properties.description);
    }

**Comment by davros85** [comment]
Brill - thanks - tried it and it works, fixes the undefined property issue as well as the web part disappearing.

**Comment by manishgarg1** [comment]
This is fixed now.
