### ISSUE TITLE
.ms-Fabric strange behavior on dark theme

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#2350]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Observed Behavior

When use Office UI Fabric components in a web part and set site theme to one of the dark. Some text  especially in plain html tags like h3, h4 and icons doesn't turn into contrast look, even some elements of the page like 'Likes' and 'Views' at the bottom. I found a way to solve this issue with elements on my web part (used theme color) but don't think should touch those 'Likes' and 'Views' at the bottom.

This is how problem looked initially
![image](https://user-images.githubusercontent.com/22150933/44021518-b4843020-9eed-11e8-92a8-4f87a9d15dac.png)

After applying theme to elements still icons are black
![image](https://user-images.githubusercontent.com/22150933/44021549-ca5b0cfc-9eed-11e8-9a58-ca72b7d13591.png)

Disabling '#333' color which comes from .ms-Fabric shows what is the cause
![image](https://user-images.githubusercontent.com/22150933/44021685-13f8b79c-9eee-11e8-8be5-974a37faa7bc.png)

Also tried to repeat that with another project the same happens

#### Steps to Reproduce

When have just applied a dark theme all works fine but after a refresh the problem is noticable

**Comment by dzearing** [comment]
@phkuo Is there something wrong with dark theming?

**Comment by phkuo** [comment]
Theming issues are dependent on the control itself.

For icons, it could be this bug: https://github.com/OfficeDev/office-ui-fabric-react/issues/5910

For the ms-Fabric class, yes, it is bad because it's not marked up for theming, and because we don't guarantee CSS load order, we can't tell which one will win.

@dzearing didn't we deprecate the .ms-Fabric class?? It's REALLY bad for theming because it has the specificity of a class, which equals the specificity of the majority of styles for any web component, in which case you're completely dependent on load order to get the proper behavior....

**Comment by elearningforce-vk** [comment]
I have the same issue but without Office UI Fabric components (just JavaScript web part). Web part is created using 1.5/1.7 version of frameworks. It is web part created by default. I deleted all dom elements and styles but result the same.

With web part:
![image](https://user-images.githubusercontent.com/25579934/48534380-00835180-e8b9-11e8-9a74-cf7f9986afde.png)

Without web part:
![image](https://user-images.githubusercontent.com/25579934/48534412-1abd2f80-e8b9-11e8-8344-e95296ef28ca.png)

Several weeks ago behavior was correct.
