### ISSUE TITLE
Questions for upgrading to SPFx 1.6 with globally deployed extensions

### ISSUE THREAD

**Issue by SPParseError** [SharePoint/sp-dev-docs#2371]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

We actually deploy our SPFx extension using the globally deploy setting in the app catalog. We then activate it site by site using scripts. It allows us to activate our solution per site collection, but update it globally, without going into each site collection and hitting the update button.

As I understand, if we upgrade to version 1.6 of SPFx and add an <ClientSideComponentInstance> element to our package, our extension will be activated in every site collection.

We need to prepare for this update and offer the best choices to our clients.

If we don't add the <ClientSideComponentInstance> element but still upgrade to 1.6, will something change compared to the actual deployment method ? (deploying globally and activating on a site by site basis by script)

If we add the <ClientSideComponentInstance> element but stop using the deploy globally method, will our activated sites still have the extension ? I feel like it won't.

Thanks !

**Comment by VesaJuvonen** [comment]
There are no changes to existing supported methods with 1.6. We simply will add a new option to your toolbelt to use tenant wide deployment, which means that you do no longer need to enable extensions one by one in site level after they've been deployed using tenant deploy option in app catalog... you can simply add an entry to a list, from where you can control how extension is enabled. 

You do NOT need to use tenant wide deployment and you can simply use the existing model, if you prefer to do so... or if you want to use the tenant wide deployment option, you implement a script which removes the currently UserCustomAction settings from existing sites and you use the centralized list in the app catalog to enable the extension in all of your sites (filtering based on site template available). If you only add an entry to the tenant wide deployment list, you will end up having extension rendered twice - once due to the site level registration and once due the global registration.

Upgrading to 1.6 does not add by default anything in your solution. Sure - we show how to add the tenant wide list option in default scaffolding, but it's up to you if you want to use that xml file or now. 

For those who might be reading this and missing context - we demonstrated tenant wide extension in the August 2018 SharePoint Dev monthly community call - https://developer.microsoft.com/en-us/sharepoint/blogs/sharepoint-dev-community-pnp-august-2018-monthly-community-call-recording/.
