### ISSUE TITLE
sp-http does not support Batches - index-internal"' has no exported member 'ISPHttpClientBatchCreationOptions'.

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/sp-dev-docs#2385]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by gautamdsheth** [comment]
Looks like you are not using the `--plus-beta` flag.

When generating your SPFx solution via the Yeoman generator, you need to add the `plus-beta` flag since SPHttpClientBatch is currently in preview. Since SPFx 1.5, the preview packages have been removed from the default installation. To use these packages, you need to explicitly request them using this flag.

So, create a new solution and in the generator add the flag as:

`yo @microsoft/sharepoint --plusbeta`

After that, you can import them in your webpart as:

`import { SPHttpClient, ISPHttpClientBatchOptions, ISPHttpClientBatchCreationOptions, ISPHttpClientBatchConfigurations, SPHttpClientResponse, SPHttpClientBatch } from '@microsoft/sp-http';`

**Comment by VesaJuvonen** [comment]
Clientbatch functionality will move away from beta status to production status with the 1.6 version coming soon. Until then @gautamdsheth's comment is 100% valid. Closing as answered.

**Comment by kchiragowni** [comment]
@VesaJuvonen looks like this is excluded from 1.6 release right? 
Thanks!

**Comment by nikolayyordanov** [comment]
Yes, it is only in plusbeta.

**Comment by schinna** [comment]
Hi All, Any update on the the ISPHttpClientBatchCreationOptions, SPHttpClientBatch release?
