### ISSUE TITLE
Adding spfx extension automatically when creating subsite in sites collection.

### ISSUE THREAD

**Issue by Lepruz** [SharePoint/sp-dev-docs#2418]
I want to add spfx extension automically, when I create subsite in sites collection. I created one and it works correct, but only in "main pages" in my site collection. I used tenant-scoped deployment and I also tried to deploy it globally using [this way](https://youtu.be/YMyZHtE5IbI?t=30m10s), but it seems nothing changes after updating TenantWideExtensions list. The main goal is just to add simple js script on all "modern" pages in certain sites collection.

**Comment by nsksaisaravana** [comment]
We are also having the same issue.... please fix this issue guys.

**Comment by carolynreoyo** [comment]
Hello @Lepruz, @VesaJuvonen  and @nsksaisaravana,
I am also experiencing this issue. I have tried using PnP and while that applies the app to existing subsites it doesn't automatically add it to newly created subsites because it scopes to web and doesn't allow scope to site as described in this other issue https://github.com/SharePoint/PnP-PowerShell/issues/2345  
I'm hoping you all have found a solution or some other workaround now that over a year has passed.

**Comment by justin0522** [comment]
[here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions#controlling-tenant-wide-deployment-from-app-catalog-site-collection) is the Controlling tenant wide deployment from App Catalog site collection docs

**Comment by VesaJuvonen** [comment]
Sorry for the massive delay on processing this properly - Guidance on the [Tenant-wide Deployment of SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions#controlling-tenant-wide-deployment-from-app-catalog-site-collection) article should absolutely work properly for the sub sites as well.

If there are any bugs on this, let's open a new issue so that we can track that properly. It was no longer quite clear if this is still an issue or not.
