### ISSUE TITLE
SharePoint returns TOO MANY REQUESTS for 401 HTTP code

### ISSUE THREAD

**Issue by Vasyl18** [SharePoint/sp-dev-docs#2547]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I develop simple application for fetching data in SharePoint sites. I use requests from [SharePoint REST API][1] for getting SharePoint Sites info (both for Team Sites and Communication Sites). Also I use such API for getting info about [files and folders][2] in SharePoint document libraries.

  [1]: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service
  [2]: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest

#### Expected or Desired Behavior
Sometimes I get throttling responses from Microsoft with 429 HTTP code and  
"429 TOO MANY REQUESTS" message in reply body.

#### Observed Behavior
But recently I noticed strange behavior: "429 TOO MANY REQUESTS" message returned in reply body but HTTP status code is 401 (which status for UNAUTHORIZED request). However I handle 401 HTTP status code in different way and this totally break the logic of my service and 401 HTTP status code in general.

I think it's not normal behavior, is it? How can I determine if 401 HTTP status code states for throttling of for unauthorized request? Straightforward reply body parsing is not a good approach as I think.

**Comment by patmill** [comment]
Just to help diagnose this, what REST end point were you calling that returned a 401?

**Comment by Vasyl18** [comment]
I can see this problem for requests related to all REST endpoints no meter if I work with [files and folders]( https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest) or with [lists](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest): e. g. I can get this "bad" reply when I fetch folders in doc lib using this endpoints
http://<site_url>/_api/web/GetFolderByServerRelativeUrl(<folder_url>)
http://<site_url>/_api/web/GetFolderById(<folder_guid>)/Folders

**Comment by Vasyl18** [comment]
I see this problem more often than before. Any progress on this?

**Comment by TheMiao** [comment]
For 429 error, it definitely is throttling issue. You can have look [throttling docs](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)

From developer point of view. The reason you have received 401 error might be you have too many 429 request, and your IP is temporarily blocked by Server. ( That's my guess, because I've read some article online)


Each server has dynamic monitoring function and each server contains few tenants. 
For example we have 3 tenants in current Server, and 2 tenants don't have that much request atm, and you will have higher trigger point to retrieve 429 error than the normal time. 
However, if other 2 tenants are calling REST APIs, the server will dynamic distribute resources to other tenants. If currently you are still having a lot APIs request, the server will block your request for a while than unblock it later when it doesn't have too much pressure. 

I can't find url the article I read, but hopefully you can understand my example from my understanding in the article. 

I think you should optimize your code to avoid getting throttled or blocked in SharePoint Online. 
Or you can contact MSFT to add your tenant in white board to get more API calling usage.

**Comment by frodale** [comment]
Good afternoon!, is there any update on this? We are getting more 401 errors now, and the only way to past through them is to wait a while and retry
