### ISSUE TITLE
Run with AppOnly permissions

### ISSUE THREAD

**Issue by ravick4u** [SharePoint/sp-dev-docs#2556]
This example shows that provisioning job can run with service account but is it ok to run with AppOnly permissions? We have a PnP Template with AddIn and would like to use App only permissions to run this job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e581d3f-a187-b893-70e3-4c3ab5d45936
* Version Independent ID: d2316e36-fa51-f00e-26eb-5a1efaa0213d
* Content: [Provisioning console application sample](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/provisioning-console-application-sample)
* Content Source: [docs/solution-guidance/provisioning-console-application-sample.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/provisioning-console-application-sample.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Basically the answer is yes. You can run provision console app in an app-only permission. However you’ve mentioned there is a PnP template and Addin, depend on their functionality there are limition needs follow in order to run in app-only permission.

App-Only does not work in following cases:

•	Updating taxonomy service entries (write) - read works
•	Creating modern team sites does not support app-only when you use the SharePoint API for it. When modern team sites are created using Microsoft Graph to create the group then app-only is a supported scenario
•	Creating communication sites currently does not support app-only using the SharePoint API
•	Search when using SharePoint On-Premises. SharePoint Online support for it has been added (blog post)
•	User Profile CSOM operations, except that the User Profile Bulk Update API can be used with app-only permissions
•	Manipulating files via WebDav protocol and CSOM (using File.SaveBinaryDirect) does not work with app-only

If the above scenarios are critical for you to define a service account, grant that one permissions and then use it in your application. Reference [here](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly).
