### ISSUE TITLE
Obtaining full HTML of SPO Site Pages programmatically

### ISSUE THREAD

**Issue by GLubomirov** [SharePoint/sp-dev-docs#2612]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
In a SPFx Web Part I need to obtain full HTMLs of SPO Site Pages programmatically and display them in a list.

#### Observed Behavior

Obtaining ClientSidePage with PNPJS doesn't seem to return the full page (web parts are missing). I tried also with Search (CanvasContent1OWSHTML) and the REST API (getbytitle('Site Pages')/Items?$select=CanvasContent1). 

All three seem to return the same content which is not the full content of the page.

Is there a way to obtain the full pages without resorting to iFrame?

Thanks,
George Lubomirov

**Comment by StfBauer** [comment]
You don't get the web parts because they are only stored as references to the actual JavaScript files that load then the web part. Without a full page load as you mentioned in through an IFRAME you wont see anything of the actual content.

You might be able to scale down the page through some CSS tricks using zoom or transform:
https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

It has not really a standard support but most browser supports it.
