### ISSUE TITLE
how to use HTTP/2 protocol for O365 CDN Traffic?

### ISSUE THREAD

**Issue by annigam01** [SharePoint/sp-dev-docs#2657]
Even though the O365 CDN support HTTP/2 protocol, i couldnt see anywhere in SPFx or any setting where we can "request" content via HTTP/2 protocol. https://developer.microsoft.com/en-us/office/blogs/general-availability-of-office-365-cdn/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb134fd8-6880-360a-faea-7eb0eedca2d9
* Version Independent ID: 16f799b7-deff-b125-ceed-343933bcbe79
* Content: [Use the site collection app catalog](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/site-collection-app-catalog)
* Content Source: [docs/general-development/site-collection-app-catalog.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/site-collection-app-catalog.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by StfBauer** [comment]
You cannot force to use HTTP/2 because this is something the browser and the server handles. 

If you browser is capable of HTTP/2 this does not mean that the traffic use HTTP/2 when the server does not support it.
On the other hand when your **browser** does **not** support HTTP/2 but your server does you cannot force to everything transferred via HTTP/2.

This basically mean that you cannot "Request" HTTP/2 your browser have to request. You see this in only in the network trace of you browser.

<img width="546" alt="screenshot 2018-10-01 at 09 44 25" src="https://user-images.githubusercontent.com/5503835/46275874-a889c900-c55e-11e8-8b96-f16844d5c2df.png">

This for example shows the traffic and protocols used to a communication site in SharePoint.
More on that: https://ma.ttias.be/view-http-spdy-http2-protocol-google-chrome/

It can even happen that you see assets requested via HTTP/1.1 in there.
