### ISSUE TITLE
SPFx and/vs WebComponents?

### ISSUE THREAD

**Issue by Danny-Engelman** [SharePoint/sp-dev-docs#266]
#### Category
- [X] Question

**3** years ago I was excited to see HTML evolve: https://www.youtube.com/watch?v=fqULJBBEVQE&feature=youtu.be

Note: It is not so much about the technology perse,  
it is about the concept that the **Client**(Browser) is 100% in control,  
and the **Back-end** is only a data container.

Which makes me think, what if we could do:

```
<WEBPART [property=value]*></WEBPART>
```

Store Components/Widgets/Webparts as files in a Library,  
SharePoint would be a container only.

Would be a whole lot simpler for Generation J (query) than the current SPFx stack
Which still relies on SharePoint (Back-end) being in control.

Is this the CEWP on steroids?

Thoughts?

**Comment by patmill** [comment]
For context to the rest of the group, this is coming from a discussion on stackexchange here - http://sharepoint.stackexchange.com/questions/197612/content-editor-webpart-vs-spfx

I'm not exactly sure what you are referring to though.   Do you mean that you want people to write arbitrary javascript code anywhere?

**Comment by StfBauer** [comment]
@patmill He is refering to Ploymer or the Microsoft sponsored X-Tag or whatever you use to write [web components](http://webcomponents.org). It's not again another framework. It is a web standard document on the following page.
[W3C Spec on GitHub](https://github.com/w3c/webcomponents)
While Chrome is currently the only browser that full supports web components, this will take some time to be supported in the current browsers.

Definitly a hot topic for the future but for now React, Angular2 and others follow some similar approaches.

**Comment by andrewconnell** [comment]
Not sure it will take that much time for web components to take hold. Web components is a collection of 4 specs... Chrome is the closest to implementing all four, but all browser manufacturers (Apple / Mozilla / Microsoft / Google) have all stated they will support web components. My understanding (as of a month ago) is that MSFT is the only one that doesn't have active dev working on it now for Edge / IE.

IMHO, web components are the ideal solution for web parts as everything about that component is 100% isolated from the rest of the page thanks to the shadow DOM thus neither external nor its resources (JS, CSS, HTML) can mutate the rest of the page or be mutated by something else on the page. Thus, no need for random CSS class suffixes.

**Comment by StfBauer** [comment]
It all depends on how long it takes to get the other three specification out of the draft status.
Internet Explorer team is betting on this as well and already have implemented the `<template>` part. 
Currently the only one that is not draft anymore.
There was a good article by the [IE Team on web components](https://blogs.windows.com/msedgedev/2015/07/15/microsoft-edge-and-web-components/#7wXkML0x2BU9OgZv.97) but it is from July 2015.

The only browser that fully supports this nativly, according to [caniuse](http://caniuse.com/#search=web%20components), is Chrome because it was their idea.

**Comment by chakkaradeep** [comment]
We looked into web components when we started planning SPFx and we did not go that route just because it is not yet ready for prime time. Instead, we chose to build a system that is agnostic of framework and can also be used to also load web components if developers wish to do so. 

Not to mention that there is complexity if you specifically want to use Shadow DOMs yet get the same capabilities that web parts offer like page interactions, web part to web part communication etc., 

From where it is today, web components will certainly play a role in web parts in the future. However, it may not be the only thing, rather an option, that developers can choose (which I believe you can do it today too).

**Comment by mike-morrison** [comment]
Just wanted to add here that my pubsec customers are very slow to update to the latest browser.  So whatever it is we do, it should be addititive if possible.

**Comment by patmill** [comment]
I'm going to close this down for now.  We're not saying No to the future, just not in the next while.
