### ISSUE TITLE
Should I use this undocumented api "/_vti_bin/homeapi.ashx/sites/suggested?start=0&count=100&acronyms=true"

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#2717]
I need to get list of sites which I have access to , Is it appropriate to use this api.Also Can i fetch more than 5000 items using this api

**Comment by Seiyasu** [comment]
![homeapi](https://user-images.githubusercontent.com/42561668/46644597-925db780-cbb3-11e8-907f-17832050095e.PNG)
Yes, you can use this api to get list of sites which I have access to. 
You cannot fetch more than 5000 items, we must limit the count to less than 5000. Otherwise, you will be throttled by SharePoint and will get a throttle exception.

#1689
