### ISSUE TITLE
How we can create Custom master page using Sharepoint framework

### ISSUE THREAD

**Issue by pvijay84** [SharePoint/sp-dev-docs#2721]
I want to create custom master page with my style sheet,Project specific images, fonts and my custom java script files.
Also i need to provision my site.

Thanks
Happy SharePoint Framework revolution !!!

**Comment by Seiyasu** [comment]
On a modern site (team site) currently the recommended way to add JavaScript to the page would be using SPFx.
Otherwise to modifiy a theme or create one and applying it to a modern site would require powershell.
More could be found here:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites

So you cannot use SPFx create custom master page. Provison site can be done by Pnp PowerShell or PnpCore.
