### ISSUE TITLE
dataVersion property not supported by Web Part Manifest schema

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#2810]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expect the Web Part manifest JSON schema to allow me to set the `dataVersion` property, since it is a documented feature in SPFx (see https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries)

#### Observed Behavior

Visual Studio code shows the squiggly thingie when using the `dataVersion` property.

![image](https://user-images.githubusercontent.com/5854279/47365734-7f330780-d6dc-11e8-9d35-e3aa84837682.png)

When packaging the solution you also get this error - but it works during dev (`gulp serve`)
![image](https://user-images.githubusercontent.com/5854279/47369092-35015480-d6e3-11e8-8278-23a5c408c941.png)

#### Steps to Reproduce

Add the `dataVersion` property to any `preconfiguredEntries` object in your web part manifest file.

**Comment by Seiyasu** [comment]
**dataVersion** property have been move to the code(So the docs is out of Date with the latest content.):
`protected get dataVersion(): Version {
    return Version.parse('1.0');
  }`

**Comment by wictorwilen** [comment]
@Seiyasu - that sounds like a bad design! Then it makes `onAfterDeserialize` totally useless, since it will always give you version 1.0 when you add the web part to the page.

**Comment by Seiyasu** [comment]
@wictorwilen  Just like you can change the dataVersion to 2 in the preconfigured-entries.  Similarly, you can change the value in the  dataVersion() function too.  Some one like the declarative preconfigured-entries, some one like the programmatic configuration.

**Comment by VesaJuvonen** [comment]
Thx @wictorwilen and sorry for the delay. This is now in relatively high in the work pipeline.

**Comment by srideshpande** [comment]
@wictorwilen - I am sorry for all the confusion, the only supported way of changing the data version of a web part is through the protected getter field, as suggested by @Seiyasu .

~~~
protected get dataVersion(): Version { return Version.parse('1.0'); }
~~~

I have also checked internally, that when we change the data version through the above mentioned way, it reflects rightly in `onAfterDeserialize` method. If you are not seeing that, then that would be bug.

However, considering that this bug was opened long ago and I am not reproing the bug in-house, I am closing the bug, but please feel free to re-open it or create a new issue for the problem you see.

I am not sure if really want that flag in the manifest, at all. I will talk to the team internally and decide on that part. Meanwhile, keep using the getter field and let us know of any issues.

Thanks again and sorry for the confusion,
Sri
