### ISSUE TITLE
Items Pagination

### ISSUE THREAD

**Issue by DanishIslam07** [SharePoint/sp-dev-docs#2844]
How Items pagination is handled. I set the items limit to 1 item per page and applied the view formatting. My list has 3 items and after view formatting it still displays 3 items not 1 with pagination.
Please advise,
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Pagination in Modern list views (regardless of view formatting) works very differently than in classic. Setting the page limit (not the total limit, but the number shown per page) does not limit the view to only showing that many results at once (as it did in classic). Rather, that is the number of items it will retrieve at a time as you scroll through the view.

Modern list views enable users to scroll through all items in a view without the need to page. So as you scroll down, more items are loaded. For small page sizes, these end up getting loaded one after another since these items should already be visible based on the scroll position. This becomes more obvious in a list of 20+ items with a paging size of 5. you can see the initial 5 when you refresh and then very quickly items appear 5 at a time.

I recommend not changing the paging default of 30 items for modern list views since you're just increasing the amount of requests as a user scrolls.

All of the above is how Modern list views handle paging and has nothing to do with View Formatting. Hopefully, that helps clear things up. Thanks for your comment!
