### ISSUE TITLE
New documentation is lacking basic descriptions

### ISSUE THREAD

**Issue by codepounder** [SharePoint/sp-dev-docs#2860]
This new documentation is almost worthless at present. There's no description of the purpose of the method or any of the parameters. While the list of overloads is important, I can get that without this documentation. Until you at least fill in the basic descriptions that the SharePoint documentation previously had, this documentation is pointless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58861aad-3321-c766-62f7-c06beafa71fd
* Version Independent ID: 686412d6-93ce-cbb4-dd7c-b6cec5450967
* Content: [SPFileCollection.Add Method (Microsoft.SharePoint)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spfilecollection.add?redirectedfrom=MSDN&view=sharepoint-server#Microsoft_SharePoint_SPFileCollection_Add_System_String_System_IO_Stream_Microsoft_SharePoint_SPUser_Microsoft_SharePoint_SPUser_System_DateTime_System_DateTime_)
* Content Source: [sharepoint-server/xml/Microsoft.SharePoint/SPFileCollection.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/live/sharepoint-server/xml/Microsoft.SharePoint/SPFileCollection.xml)
* Product: **sharepoint**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **o365devx**

**Comment by Seiyasu** [comment]
The docs is not latest.  You can submit your pull request to update it. Not all docs updated by MS, many one are submitted by community.

**Comment by crtjr64** [comment]
Regardless of who submits it, it does us no good and is a greater hindrance than help as it wastes time. Many of us, like myself are here to resolve time sensitive bugs... you all may not give 2 cents, but for us it could be mission critical. For example, I keep getting a special characters error for the urlOfFile string and the forward slash is among the rejected list of special characters... now please tell me what url do you know of does NOT have a forward slash? So I come here to find out how is this parameter to be filled out and I get nothing but an excuse from the contributors... well surprise, my customer is not interested in your excuse but that the bug is fixed. So if you don't know how the parameter is used can you at least point us to someone who does?
