### ISSUE TITLE
No Images on HighlightedContent with caroussel display

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/sp-dev-docs#2883]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Images should be displayed whatever the chosen display on HighlightedContentWebpart.

#### Observed Behavior
When the chosen display mode is Carroussel, images are not displayed...
On other modes, images show fine.
![carddisplay](https://user-images.githubusercontent.com/35366413/48050537-7b09ee00-e1a2-11e8-9a60-a798b95894ca.png)
![filmstrip](https://user-images.githubusercontent.com/35366413/48050547-8230fc00-e1a2-11e8-992d-0f51739ca5a2.png)
![carousseldisplay](https://user-images.githubusercontent.com/35366413/48050551-83fabf80-e1a2-11e8-8ad5-eb2a3364b813.png)

#### Steps to Reproduce
Change display mode of highlightedContent webpart to Caroussel.

Thanks for your contribution! Sharing is caring.

**Comment by Seiyasu** [comment]
Do you have tried use pure image list?

**Comment by BraunJonathan** [comment]
> Do you have tried use pure image list?

I'm not sure i understand what you mean there...
I've got a Highlighted content that shows News pages with images.
Until monday, images showed fine and now they don't.

I must add that this is a production tenant with thousands of users and the problem occurs on the intranet homepage...

**Comment by VesaJuvonen** [comment]
Thanks, @BraunJonathan for reporting this. As this is out-of-the-box capability, which has an issue, you should be reporting this through the SharePoint admin UI (tenant admin UI) using the standard SharePoint Online support channels. We are not allowed to re-route issues and bugs through this process if it's not related to the development or customization topics. Sorry for the inconvenience, but let's get this reported using the right channel so that you get it fixed asap. Thx.
