### ISSUE TITLE
JSON row formatting bug - modern sharing links

### ISSUE THREAD

**Issue by chrisobriensp** [SharePoint/sp-dev-docs#2903]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When I use the JSON row formatting feature on a list, I should be able to use a field of type URL and use the standard "modern sharing link" format. 

#### Observed Behavior

If a modern sharing URL is used, in fact the list item is not displayed at all in a view which uses JSON row formatting. It appears there is a bug in the rendering model - an empty DIV is rendered, which effectively means the item does not display at all. However, the list item is valid and will show in the "All items" view for example.

#### Steps to Reproduce

Using a list which has a URL column, apply the row formatting feature using appropriate JSON. Add a list item, and use a modern sharing link in the URL column value. Observe that the item does not display in the formatted view, but does in other views.

#### Video to illustrate issue

![json row formatting bug](https://user-images.githubusercontent.com/3117185/48215233-ba3e6780-e379-11e8-87ef-944bf80a7542.gif)

**Comment by thechriskent** [comment]
The problem appears to be with how the data is delivered. It is cutting off the value as seen here:
![image](https://user-images.githubusercontent.com/8364109/48227972-e0f8a000-e371-11e8-85ee-c57f86c0cebe.png)

Then the CustomFormatter is flagging this as an invalid protocol (`"debugMode":true`):
![image](https://user-images.githubusercontent.com/8364109/48227996-f241ac80-e371-11e8-8aa5-23f06710d73c.png)

So, it looks like (from an outside perspective) that this is an issue with how the data is returned on the modern list view (links are returned correctly via REST, etc.) rather than a direct issue with List Formatting.

**Comment by thechriskent** [comment]
I'm no longer seeing this issue. Not sure when it was fixed. @chrisobriensp can you confirm if this issue is resolved for you? Thanks!
