### ISSUE TITLE
Delay between first page render and SPFx Application Customizer availability

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#2909]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

On our application customizer extension we always have a ugly delay that is caused by the loading sequence of the modern page. First the page displays some HTML elements and after a few seconds our application customizer page is loaded and the header appears. This leads to a poor user experience because elements of the page jump around.

#### Observed Behavior

Please see a simple example here, where we only do a console log in the constructor.

![image](https://user-images.githubusercontent.com/31658807/48265007-aeab7900-e42b-11e8-88ee-230cb97c5897.png)

![image](https://user-images.githubusercontent.com/31658807/48265042-c256df80-e42b-11e8-9491-0e05c30312b9.png)

There are at least 2-4 seconds where the user sees the vanilla modern layout, before the app customizer renders.

Is there any best practice or example, how to speed up the loading time / sequence of SPFx app customizer components? Within the old world (classic pages) we had direct influence on the sequence scripts are loaded (e.g. Custom Actions loaded in header).

Any hints how to improve this would be appreciated. Thanks in advance!

**Comment by Seiyasu** [comment]
Due to the customizer is worked on the DOM element, so it should have not any best UX solution now. Maybe we can try add some mask to notified user before the customizer finishes loading.

**Comment by netti01** [comment]
Actually we have the same problem with loading delay of app customizers. Even if we add some kind of loading overlay to notify the users, this overlay will appear with a delay so that the underlying modern page is visible for a few seconds. Quite confusing for our users.

**Comment by VesaJuvonen** [comment]
This is technically by design due to the way how the JavaScript files are loaded. Now - we are working on a capability where application customizers can "book" space from the page, which will then reduce the flickering effect when placeholders are rendered. Due to the client-side rendering logic, that's the best short term solution, which in pipeline for 2019.

**Comment by bigpix2000** [comment]
bringing this back for just a moment to see if the bits suggested by @VesaJuvonen have come through yet.  My current hypothesis is that it has come through for SP Online pieces (in the more recent framework updates) but those updates do not apply to SP On Prem (SP 2019 which is on Framework 1.4.x).  And just a question if this is the case, will there be any effort to help the On Prem case.  Thanks!

**Comment by jcosta33** [comment]
I think we observed the web parts starting to load faster than the extensions. That's definitely not due to the way javascript files are loaded, it seems to be a deliberate decision. IMO we should be able to set a priority value for the loading of any given web part or extension, that'd be incredibly useful!

**Comment by jithil89** [comment]
Is this resolved yet ? I created a SPFx app customizer to hide a certain section in the pages. But due to the delay, the sections load first and then get hidden. I believe this is a replacement for custom action. In that case, this should load first. I read that the onInit() function is fired before DOM is loaded.
