### ISSUE TITLE
tested SPFX 1.7 with teams deployment, getting Deployment failed. Correlation ID: 3b5ea19e-f0c2-0000-37a5-6e7aae287d84

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-dev-docs#2926]
## Category

- [X ] Bug

## Expected or Desired Behavior

Deploy the sppkg to sharepoint

## Observed Behavior

1/ In the site collection app catalog I get : 

Deployment failed.  Correlation ID: 3b5ea19e-f0c2-0000-37a5-6e7aae287d84

## Steps to Reproduce

1/ Follow this tutorial : https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab

Select react,
after gulp bundle --ship, drag and drop the sppkg to the dev tenant O365 site collection app catalog, deploy it

Ive also submitted a Microsoft Ticket.

**Comment by seaSide974** [comment]
suddenly after redoing the operation, it works

**Comment by himanshuchuriwala** [comment]
SPFx webpart for MS Teams

[Cannot find module '@microsoft/sp-build-web' error ] Question
While developing spfx solution for ms teams, I am receiving error related to sp-build-web module. I followed the msdn article but still the issue is bothering.

I tried to install the dependencies but still no luck.

can anyone help on this one ?
