### ISSUE TITLE
🐞 SPO triggering throttling errors (429's) on OOTB telemetry logging

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#2964]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

MSFT to not trigger 429's on OOTB pages.

#### Observed Behavior

Just confirmed this in 3 different SPO tenants... haven't noticed this in the past. There's some call to what appears to be a telemetry collector... it's spamming itself non-stop. All these failure calls are 429's.

![image](https://user-images.githubusercontent.com/2068657/48629753-81f5e500-e988-11e8-996d-e019d9bdc3fb.png)

#### Steps to Reproduce

Specifically seeing in SPO hosted workbench, but others seeing it off the workbench.

**Comment by patmill** [comment]
Hey AC, can you clarify how often those requests are getting sent?  Are the 15 or so that you show over the span of a second or two, or a minute, or ?

Trying to figure out if there is an issue on the front end sending too much information, or on the back end where they are sending 429's.

**Comment by patmill** [comment]
Do you also see calls to ?qsp=true... every 2 seconds as well?  If you do, can you look at the payload, and let me know what you see?  In the network tab, the RequestPayload will have a bunch of somewhat packed data.  Feel free to strip out any PII information like URLs, ids, etc.

If you wish, you can send it to me on email.  My user name here, at microsoft.com

**Comment by andrewconnell** [comment]
Yup... seeing the `?qsp=true` every 2s as well... I'll send you a screencast offline.

**Comment by patmill** [comment]
(sorry for the delay)
Thanks for bringing this up.  Turns out that the telemetry to make sure that auto-save worked didn't work, causing more telemetry calls to say the telemetry didn't work.  The telemetry system then sends information to make sure that the telemetry system is working (I can't make this stuff up), and that system didn't quite work (429s).  The work-bench (which generally defaults to edit mode) runs through this codepath.  We're going to remove that first telemetry call, which should clear everything else up.  (writing this explanation reminds me of the møøse credits in the Holy Grail)

**Comment by andrewconnell** [comment]
@patmill **EPIC** issue closing comment!

![image](https://user-images.githubusercontent.com/2068657/49095782-844e1e00-f269-11e8-84cc-46b7aea37f77.png)
