### ISSUE TITLE
Napa

### ISSUE THREAD

**Issue by jlemoo** [SharePoint/sp-dev-docs#2990]
This document references Napa, an in-the-browser version of visual studio which has been discontinued. You can still use the code here - just not in Napa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45522c04-dae3-6c03-176b-b36cdfd17c9e
* Version Independent ID: 11c9ed85-9535-8a1a-fd03-54e1f004ae80
* Content: [Use the client-side People Picker control in SharePoint-hosted SharePoint Add-ins](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-client-side-people-picker-control-in-sharepoint-hosted-sharepoint-add-in)
* Content Source: [docs/sp-add-ins/use-the-client-side-people-picker-control-in-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/use-the-client-side-people-picker-control-in-sharepoint-hosted-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Seiyasu** [comment]
Some SharePoint docs are maintained by the community, so they won't the latest in time. You are welcomed to submit any contribution on the docs content by submitting pull request.

**Comment by VesaJuvonen** [comment]
This issue is closed as there has not have been any activity on it within the past 2 months. If the issue is still valid, please submit a new issue with updated details. Sorry for the Inconvenience. We are perform this cleaning operation for all inactive issues in this repository to be able to improve our support model in future.
