### ISSUE TITLE
Non destructive is misleading

### ISSUE THREAD

**Issue by Aschlender** [SharePoint/sp-dev-docs#2993]
In my scenario the site script assigned to the sign creates a new document library, names it and assigns a content type.  Every time I re-associate the site design with the site the scripts creates a new copy of the library and just adds an increment to the library name.  My expectation was that the script will ignore this set of actions as the library already exists in this configuration.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site design and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by iamguptarishi** [comment]
Is site created with a different language or with English as default language? There is currently an issue when the site is created with different language. It creates a duplicate library in that case.

**Comment by MikeBass13** [comment]
Does that include "English - Canada (4105)"? I am also eperiencing the list duplication issue. If I have a List with the URL "MyList" it will create "MyList1" when re-applying. Both lists will have the same title (e.g. "My List").

**Comment by JarbasHorst** [comment]
@iamguptarishi  I've been facing the same issue, although my site's default language is English (1033). The problem seems to be related to the listName property. If list name changes, site design creates a new list instead of updating/skipping it. The unique identifier for the createSPList seems to be the listName property. I believe that this issue could be fixed if Site Designs would provide an URL property for the createSPList verb.
