### ISSUE TITLE
 error [SPWebPartErrorCode.ScriptLoadError] when adding webpart to sitepage

### ISSUE THREAD

**Issue by ilyhel** [SharePoint/sp-dev-docs#309]
#### Category
- [ ] Question
- [ ] Typo
- [ X ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

Hello. I'm getting an error when adding my custom webpart to sharepoint online sitePage.

#### Expected or Desired Behavior
webpart added to page but it display this message.

[SPWebPartErrorCode.ScriptLoadError] :: We can not load the Web Part script resources WebPart.OfficewpWebPart.39948641-1f86-4f9d-94e8-0128fb7ab733, Error for the following reason: undefined. CallStack :: Error at t (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-client-base_fr-fr_1c7464f24ac86edf90e2dac612102ab8.js:48:12232) at t (https: // Static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_en-en_8c771129e3f93d80f26ed86cbfc3aa61.js:47:21042) at t.create (https://static2.sharepointonline.com/files/sp -client-prod_2016-11-28.015 / sp-web part-base_fr-fr_8c771129e3f93d80f26ed86cbfc3aa61.js: 47: 21450) at Anonymous function (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp -webpart-base_fr-fr_8c771129e3f93d80f26ed86cbfc3aa61.js: 47: 30966)

[SPWebPartErrorCode.ScriptLoadError]:: Nous ne pouvons pas charger les ressources de script du composant WebPart WebPart.OfficewpWebPart.39948641-1f86-4f9d-94e8-0128fb7ab733,Error pour la raison suivante : undefined. CALLSTACK:: Error at t (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-client-base_fr-fr_1c7464f24ac86edf90e2dac612102ab8.js:48:12232) at t (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_fr-fr_8c771129e3f93d80f26ed86cbfc3aa61.js:47:21042) at t.create (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_fr-fr_8c771129e3f93d80f26ed86cbfc3aa61.js:47:21450) at Anonymous function (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_fr-fr_8c771129e3f93d80f26ed86cbfc3aa61.js:47:30966)

#### Observed Behavior
whene i run console in browser is see this errors  
HTTP500: ERREUR DE SERVEUR. Le serveur ne peut pas exécuter la requête, car il a rencontré une condition inattendue.
GET - https://spaf.sharepoint.com/SitePages/%3C!--%20PATH%20TO%20CDN%20--%3E/office-dev-officewpstrings_en-us_536e65149b0acf4d52c0043073b9fc59.js
HTTP500: ERREUR DE SERVEUR. Le serveur ne peut pas exécuter la requête, car il a rencontré une condition inattendue.
GET - https://spaf.sharepoint.com/SitePages/%3C!--%20PATH%20TO%20CDN%20--%3E/officewp.bundle_8ce1ba88cebd3290b07fc681ceba1368.js

#### Steps to Reproduce
each time i adding the webpart.

**Comment by vinsaTimeparity** [comment]
Hi Ia ma facing a similiar issue when i try to open the Workbench.aspx, there as no code change from my side ,a nd the page was working fine till recenly. 

`[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.undefined.11ea1f2c-7b6c-4555-a63a-eb4dea248459,TypeError: Cannot read property 'type' of undefined script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-client-base_en-us_3905c4052541a53999f37e2fdf2a5095.js:48:12396) at new t (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_en-us_f7093ab84c53aa61efb4e34b889d1df4.js:47:21044) at Function.t.create (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_en-us_f7093ab84c53aa61efb4e34b889d1df4.js:47:21457) at https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_en-us_f7093ab84c53aa61efb4e34b889d1df4.js:47:30989`

**Comment by godwin3737** [comment]
Hi , even we are noticing this issue. Till recently the webpart use to work fine in the workbench.aspx. However if we try to add the webpart now in the workbench.aspx page we see the below error:

`[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.undefined.11ea1f2c-7b6c-4555-a63a-eb4dea248459,TypeError: Cannot read property 'type' of undefined script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-client-base_en-us_3905c4052541a53999f37e2fdf2a5095.js:48:12396) at new t (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_en-us_f7093ab84c53aa61efb4e34b889d1df4.js:47:21044) at Function.t.create (https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_en-us_f7093ab84c53aa61efb4e34b889d1df4.js:47:21457) at https://static2.sharepointonline.com/files/sp-client-prod_2016-11-28.015/sp-webpart-base_en-us_f7093ab84c53aa61efb4e34b889d1df4.js:47:30989`

**Comment by frankchen76** [comment]
I guess you guys hit the problem that [Drop 6](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-6) changed the way to determine the environment type. the code was `if (this.context.environment.type === EnvironmentType.Local)`, now changed to `if (Environment.type == EnvironmentType.Local)`. you also need to include them by adding the following 
`import {
  Environment,
  EnvironmentType
} from '@microsoft/sp-client-base'
`
I hope it helps.

**Comment by ilyhel** [comment]
Hi, i resolve the issue by enable First Release for everyone , turning on scripting capabilities and resolving an issue with certificate of the localhost workbench.

**Comment by godwin3737** [comment]
@frankchen76 thanks for that . I had to make my code compliant to Drop 6 ...
