### ISSUE TITLE
Two SPFX Packages - Consume the same custom Azure AD secured APP / EndPoint

### ISSUE THREAD

**Issue by jay-enc** [SharePoint/sp-dev-docs#3103]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
We have two SPFX packages which consume a generic AAD secured Web API service. The AAD app has been setup and the first SPFX package has been deployed, approved via API management... all working fine.

We want to use the same service within the second SPFX package...

#### Observed Behavior / #### Steps to Reproduce

The package.json for both SPFX packages contains the same webApiPermissionRequests entry, example below:
"webApiPermissionRequests": [
      { 
        "resource": "Windows Azure Active Directory", 
        "scope": "User.Read" }, 
        {
          "resource": "name-of-aad-app",
          "scope": "user_impersonation"
        }
    ],

So... after deploying via the AppCatalogue the API management requests are added, however we cannot approve them as it states that entries already exists, example error below:

[HTTP]:400 -  [CorrelationId]:xxxxxxxxx [Version]:16.0.0.8328 - An OAuth permission with the resource name-of-aad-app and scope user_impersonation already exists. Parameter name: permissionRequest
[HTTP]:400 -  [CorrelationId]:xxxxxxxxx [Version]:16.0.0.8328 - An OAuth permission with the resource Windows Azure Active Directory and scope User.Read already exists.
Parameter name: permissionRequest

I'm guessing we're doing something a little silly and there is a quick fix (fingers crossed!)?

#spfx #spfx-tooling #api-management

**Comment by VesaJuvonen** [comment]
As long as you have approved the permission already for the same resource and permissions, things should work still fine even though the pending request is not approved, as these permissions are NOT by default provided for a solution... all solutions are sharing the same permission set (unless you are using preview of isolated web parts). 

This means that the issue is mainly cosmetic on having additional permission request pending in the Admin UI, but it has no impact on the functionality as such. You could also just drop the permission request and then grant it directly using Approve-SPOTenantServicePrincipalPermissionGrant cmdlet (https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/approve-spotenantserviceprincipalpermissiongrant?view=sharepoint-ps). 

UI exception is clearly an issue which we need to fix, but it's not technically blocking you to use the API in either of your solutions.

**Comment by jay-enc** [comment]
Thanks Vesa, we'd wondered as the API management requests are package name and package version specific which implies that the approval is only specific to a particular app package... we're not using isloated web parts. 

We'll tick this one of the list as a possible source of the problem we have.

**Comment by VesaJuvonen** [comment]
They are not package specific, unless sppkg file has the isolated setting enabled. This is isDomainIsolated setting in the package-solution.json file. If that's set as 'true', then permissions are solution specific, if it's not set, then setting is false and permissions are shared.

Please do let us know if you can solve the difference or confusion here so that we can potentially close the issue or alternatively investigate more if needed.

**Comment by jay-enc** [comment]
I understand ref the isolated setting, I was more commenting on what's implied by how the API management screen works within SharePoint Admin.
Happy for this to be closed, but I think there's probably some changes required to the management pages as this is a little misleading and a fairly common use case. 
We've fixed our issue (AAD permissions) and totally un-related to this, but really useful to clarify. thanks
