### ISSUE TITLE
Update command set button based on async REST calls

### ISSUE THREAD

**Issue by frnk01** [SharePoint/sp-dev-docs#3256]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
It should be possible to render the command set button based on external conditions. Lets say we want to add a "Add favourite" button to a document library, and if a document library is already a favourite the button should say "Remove as favourite".

As far as I have experienced it is not possible to do a REST call to the SharePoint API, retrieve some information and set the button based on this. Is that a fact, or am I missing something? Given it is not possible, is it something you are planning to fix?

In my opinion this is an important feature and I am hoping you will prioritise this functionality.

**Comment by andrewconnell** [comment]
The name used on a command set button is specified in the manifest. You can localize it, but you can't make it dynamic based on conditions as you describe... this works by design. Changing how it works would be a feature request submitted to UserVoice.

One way you could achieve what you're looking to do though is to create two buttons, then handle the `visible` property on them based on the values returned from your REST call. This could be done on the event within the command set action that gets called when each item is updated.
