### ISSUE TITLE
Sync issue with SPFx using PnPjs

### ISSUE THREAD

**Issue by Rani86** [SharePoint/sp-dev-docs#3353]
Hi Team,

I have an issue in saving the data in list which has more than 1000 records . We have multiple lists that needs to updated before the form submission process . I have used "then" but still the data are not getting saved in list before the page navigation .Can you please help me 

Thanks,
Rani

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Rani86** [comment]
Hi, Any updates on this ?

**Comment by andrewconnell** [comment]
This question isn't related to this Hello World doc. Your question seems more generic about working promises in JavaScript [TypeScript] (*in that case, since it's not a SharePoint dev question, 
 you should post it to a forum like stackoverflow*), or with the PNPJS library (*which should be posted to [that project's repo](https://github.com/pnp/pnpjs)*).
