### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by uhudlukey** [SharePoint/sp-dev-docs#3358]
I've been following this guide and everything worked fine until step 5 above; when I upload the sppkg created by the `gulp package-solution --ship` command it overwrites, I click on 'Deploy' (SharePoint Online is showing) but there is a message saying 'Deployment Failed';

Deployment failed.  Correlation ID: a91dbb9e-20e2-7000-6eae-95464a4bfc32

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by nikskhubani** [comment]
This usually comes when you have freshly created App Catalog site collection. Giving it some time would fix the issue

**Comment by uhudlukey** [comment]
> This usually comes when you have freshly created App Catalog site collection. Giving it some time would fix the issue

The App Catalog site collection was created some time ago; the first modified date for other apps I can see on there is August 3, 2018.

**Comment by nikskhubani** [comment]
And in deployment errors do you see anything there?

**Comment by uhudlukey** [comment]
Where can I find deployment errors?

**Comment by nikskhubani** [comment]
![deployment_errors](https://user-images.githubusercontent.com/29400321/52042243-1ae2d800-2556-11e9-9571-44a13dc2addb.png)

**Comment by uhudlukey** [comment]
- It's a valid app package; this shows 'Yes'
- There is an error in the App Package Error Message column; this is the one I posted in the original message (Deployment failed. Correlation ID: a91dbb9e-20e2-7000-6eae-95464a4bfc32)

I have tried refreshing that one this morning, and using the 'Deploy' option in the FILES ribbon menu this morning and it did not work. I deleted the app and tried uploading again, same problem, just with a different correlation ID. As far as I can tell, I cannot search for Correlation IDs in the SP Online logs like I would be able to in an on premise SharePoint. 

In the properties section of the app, the External Content Domains (as this worked fine in the tutorial before and I am trying to get it working with the Office 365 CDNs) I can see;

`External Content Domains  HTTPS://SPCLIENTSIDEASSETLIBRARY/`

Does that look correct?

**Comment by andrewconnell** [comment]
Yes, that's a normal URL (its the placeholder for the O365 CDN). Is the O365 enabled in your tenant? Have you verified the CLIENTASSETS library is listed as an origin? Although I don't think these are the root cause as files are only deployed on app install, not on deploy.

Can you post your project to your own GitHub account for others to take a look? Seems like something is incorrect in your project if you get errors on upload.

**Comment by uhudlukey** [comment]
Hi Andrew,

Yes I believe the O365 CND is enabled;

![image](https://user-images.githubusercontent.com/46317280/52120477-5643dc00-2614-11e9-80e4-ffe148d31904.png)

Just to be sure I used

`Set-SPOTenantCdnEnabled -CdnType Public`

again this morning to accept the prompts. 

Here is my project in a Repository; [https://github.com/uhudlukey/HelloWorldWebPart](https://github.com/uhudlukey/HelloWorldWebPart.git)

**Comment by uhudlukey** [comment]
The `gulp build` command is missing from the tutorials so I got a but excited there but alas it still won't depoy. I am presuming I don't actually need this if I am just building and deploying solutions to our own tenancy?

**Comment by andrewconnell** [comment]
You definitely need to run `gulp build`. The command `gulp serve` does this for you as indicated in step 4's explanation of what it does here in step 2 of the tutorial: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint#get-access-to-page-context

**Comment by patmill** [comment]
Following up on this, as it was referenced from another bug.  You do need to bundle and package, even if it is only for your tenancy.

**Comment by loflet** [comment]
Hello,

I am also facing the same issue. The issue is not at all consistent in my scenario. This is what I am doing: -
I am uploading a sppkg file in the site collection app catalog using OfficeDevPnP. My function is suppose to upload the same package to 5 different site collection app catalog. Out of the 5 site collection it is uploading to 2 or 3 site collection. Each time it is failing for one or many site collection. The same package if I try to upload again deploys successfully sometimes and sometimes it doesn't. 

Not able to understand what is causing this issue. Following are my details: -
![image](https://user-images.githubusercontent.com/7891707/58262876-b06dd600-7d98-11e9-8ef5-07d796936731.png)

**Comment by patmill** [comment]
Can you send me your tenant url?  my user name at microsoft.com.  Also - you should open up a new issue, since this seems different than the closed issue.

**Comment by loflet** [comment]
@patmill thank you for replying. I have opened a new issue #4022. Also I have sent out an email to you.
