### ISSUE TITLE
Isolated React Web part disappears

### ISSUE THREAD

**Issue by spgregory** [SharePoint/sp-dev-docs#3417]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

I am using SP Framework 1.7 and React 16.3 and using the new isolated web part feature to talk to a custom API. The web part loads correctly when editing the page and after saving the draft. If I reload the page the web part disappears. The Office 365 cdn is serving the files correctly.

**Comment by srideshpande** [comment]
Hi @spgregory,

Apologies for the delay in responding to the issue. Thanks for bringing the issue to our notice.

This should be fixed with the SPFx 1.8 release. I am closing the issue for now and please feel free to re-open this or create a new one, if you see the issue in 1.8 release.

Thanks for understanding!
Sri

**Comment by TarundeepTheta** [comment]
Hi @srideshpande,

I am facing this issue. The web part is not visible after a refresh.
Please suggest.

Thanks in advance.
