### ISSUE TITLE
1000 log msg"Icon being re-registered. Ignoring duplicate registration." using Fabric React in SPFX webpart solution

### ISSUE THREAD

**Issue by MaheshakaMudli** [SharePoint/sp-dev-docs#3441]
#### Category
- [x] Bug

We are facing this issue now in our tenant. In Edge, the browser hangs while this logs are been printed. We are using spfx 1.6 with react 15 and office fabric 5. Can this be resolved at our end in any way. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/23700986/52715252-f3fabc00-2fc1-11e9-8583-06326dabe875.png)

Reference:
https://github.com/SharePoint/sp-dev-docs/issues/2867

**Comment by andrewconnell** [comment]
I'm not sure this is a SharePoint/SPFx issue as it's related to Fabric React. As such, this should be posted to the Fabric React issue list (not trying to "_pass the buck_", but there's nothing the SharePoint side can do to address this.

With that being said, I can't tell if it was fixed in Fabric React v5 from @dzearing's [comment](https://github.com/SharePoint/sp-dev-docs/issues/2867#issuecomment-442649562)...
