### ISSUE TITLE
A different version of this App is already installed with the same version number.

### ISSUE THREAD

**Issue by whatlove** [SharePoint/sp-dev-docs#3454]
After re-deploying the package, I kept getting an error when trying to add the app to my site.

"A different version of this App is already installed with the same version number."

I had to update the version number in the package-solution.json file, re-package and re-deploy in order to get it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
This is working as expected.  Whenever you update an app (Add-in or Spfx) on a site through the site contents page,  it is required that you augment the version number.

In your case however,  it sounds like you are using SharePoint Framework... when deploying a SharePoint Framework Solution, there is no requirement to "update" your solution on the site it's being used. This is because the moment you upload the .sppkg file to the SharePoint App Catalog, it's immediately updated on all sites that are using that solution.
