### ISSUE TITLE
Duplicate Top navigation

### ISSUE THREAD

**Issue by Mandylf** [SharePoint/sp-dev-docs#3551]
Category
- [ ] Question
- [ ] Typo
- x Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

A site collection linked to a HUBsite should only have the top navigation displayed once

#### Observed Behaviour

I have created over 20 sites and linked them to the HUBsite, but there is one that has the top navigation - which is correct, but under that (or on top of the landing page) is another row of the navigation

#### Steps to Reproduce

I have checked the Navigation settings and they seem to be fine, I removed the link to the hub, and the site still showed the navigation bar - (not the hub one) - then I added it back to the hub, and now it displays both again.

I have not done anything in Powershell to cause this :( so any guidance is greatly appreciated

Many thanks
Mandy
![dubnav](https://user-images.githubusercontent.com/44191278/53939059-f96f9180-40a9-11e9-9448-1b226a2924ca.PNG)

**Comment by bcameron1231** [comment]
It looks like the navigation in your picture is a bit different. The hub navigation has "Departments" and the Top navigation does not, which seems to me it's not duplicate.

Is this a Team Site or a Communication site? It looks like a Team site... which means navigation was added from a classic page to the top navigation. Because it already has this is the top navigation of the site, It will continue be there, and also include the hub navigation. You should remove the site's top navigation from the settings page.

**Comment by Mandylf** [comment]
Hi Beau

Thank you for the feedback

It is a team site – but I never changed it to the classic site look ??

How do I remove the site navigation?

When I go to the Site settings – this is what I see
[cid:image002.jpg@01D4DE29.5BB83010]

**Comment by bcameron1231** [comment]
Hi @Mandylf  The image you sent was unable to load, could you try to load it again from the Github interface or link to it?

**Comment by Mandylf** [comment]
Hi Beau

Thank you for your reply .. I managed to find the site settings and I've deleted the links

Many thanks
Mandy


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bcameron1231** [comment]
@andrewconnell  This ticket can be closed as it has been resolved.
