### ISSUE TITLE
Changes in source code are not affecting in SharePoint (AzureCDN)

### ISSUE THREAD

**Issue by knalbandianbrightgrove** [SharePoint/sp-dev-docs#3592]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Source code changes are affecting on SharePoint when run "gulp deploy-azure-storage" using AzureCDN without re installing *.sppkg

#### Observed Behavior

Source code changes are not affecting on SharePoint when run "gulp deploy-azure-storage" using AzureCDN without re installing *.sppkg

#### Steps to Reproduce

1. Specify blob config in "deploy-azure-storage.json"
2. In package-solution "includeClientSideAssets: false"
3. Run `gulp bundle --ship`
4. Run `gulp package-solution --ship`
5. Run `gulp deploy-azure-storage`
6. Install your *.sppkg in SharePoint App Catalog
7. In SharePoint Add your app in site
8. Make any changes in your typescript files
9. Run `gulp bundle --ship`
10. Run `gulp deploy-azure-storage`

Changes are not affecting in SharePoint

#### Description

I was able to successfully build the package and deploy it to CDN and Sharepoint, it's working fine for the first release. If i want to update the typescript code to change my UI/logic and release a next version "gulp --ship" creates a new bundled file under "temp/deploy" if i deploy the new file to azure CDN changes are not affecting in my Sharepoint page. The changes are affected only when i update the .sppkg file.

**Comment by andrewconnell** [comment]
>Source code changes are affecting on SharePoint when run "gulp deploy-azure-storage" using AzureCDN without re installing *.sppkg

Your assumption is the issue. When you change the source code, a new bundle is created with a different hashed suffix in the filename. The hash is generated from the contents of the bundle. When you do this, you need to reinstall the *.sppkg to update the references in the manifest of the deployed component so it's pointing to the new files.

Without doing this, you're effectively creating new bundles, deploying them to Azure, but not telling the existing install in SharePoint about the new bundles so it's still calling the old bundles.

**Comment by knalbandianbrightgrove** [comment]
@andrewconnell Thank you for the answer!

Two quick questions
1. If above is by design then what is the benefits using CDN mode?
2. What is the reason of creating <componentId>.json file with correct manifest of new bundle in temp/deploy folder?

We can have thousands of customers and we cannot update them one by one

**Comment by andrewconnell** [comment]
This can get into a huge debate, but consider the scenario you're trying to implement: 

If you could update your code by deploying a new file and your "thousands of customers" would immediately get the new code, then your customers have put a tremendous amount of trust in you. Why?

Because once the component has been deployed & installed in their SharePoint environments, if those components are using the Azure CDN (or any other external CDN), they are loading external scripts into their tenant. Those scripts will execute under the context of the current user on their site. Those scripts are not things they control... you control them.

So consider the scenario where your script was updated, without one of your customer's knowledge, and it is now looking at all the lists in all sites within the current site collection for a list with the word **confidential** in the title. When it finds it, it grabs all the files in it and sends them to another location outside their SharePoint environment. All this can be done without their knowledge... 

Microsoft took the stance of "nope, not going to allow this" so the current setup requires the installer of the SharePoint package to reinstall to get the new files.

Now... with that being said, you could always still do this by deploy your SPFx bundle as a shim that dynamically loaded another file that you could update over and over without your customers having to be involved. Technically it's possible... but I'd **STRONGLY** recommend you discuss this with your customers before doing it as any competent corporate security department is going to freak out if they discovered this AFTER the fact.

@knalbandianbrightgrove said:
> If above is by design then what is the benefits using CDN mode?

Initially, SPFx didn't have the `includeClientAssets` option that lets you include the files in the `*.sppkg` and deployed to the Office 365 CDN, so you had to put the files somewhere that you could access.

Then the Office 365 CDN was introduced, so the need for leveraging a 3rd party CDN diminished, but some still favor it. 

The Office 365 CDN is fully managed by Office 365... while it is an Azure CDN, you don't have any access to the advanced features and options it provides... those are all managed by Office 365. So maybe you do want to use them in your scenario (geo restrictions based on IP, cache controls, etc).

**Comment by knalbandianbrightgrove** [comment]
@andrewconnell Thank you for that more than full answer!
