### ISSUE TITLE
When to use the new SharePoint Framework

### ISSUE THREAD

**Issue by Fareedbaba** [SharePoint/sp-dev-docs#3594]
I would like to know for what scenarios should i opt for development using SPFx and some scripting language.

Here my Requirement is to build a custom form with few input fields (text/dropdown/people picker etc.,). My intention is to learn SPFx and the scripting tool. I tried to build a form using angular +SPFx and deployed it in app gallery. 

I don't see this as a good approach for developing the application using SPFx. If this is not a good applicable area, then in what scenarios should i go for Custom app development using SPFx.

Thanks in Advance.

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Comment by PopWarner** [comment]
Great question @Fareedbaba! :)

My personal feedback is there is no real single yes or no answer to your question regarding if your requirements are a good fit for SPFx. 

Each scenario has unique needs, expectations, time to deliver and details, etc that might determine if the use of SPFx (or any additional framework, such as angular) is the right solution or if another technology choice might serve as a better option.

For example, you mentioned a form. I don't know if this is for populating a list, but if it is, there is also the option of using PowerApps to provide an enhanced or custom form.

If you are looking to learn more about SPFx, there is a fantastic and recently updated training package available here: https://aka.ms/spfx-training.

Hope this helps! :)

**Comment by andrewconnell** [comment]
The scenario you selected is a bit of a stretch for a "good fit" for SPFx.

SPFx is a framework that allows you to build two types of components: web parts & extensions. 
- **Extensions** _extend_ the existing UI by adding buttons to list toolbars & context menus, change how a cell is rendered and add a header/footer to a page.
- **Web Parts** allow you to build reusable controls that end users/page designers can drop on a page.

Anything more than that and you're stretching. Custom form solutions are intended to be solved with PowerApps. 

With that being said, could you use it to create custom forms? Sure... look into the feature that enables full page apps (currently in dev preview). You could create _one big web part_, put it on the page and use it as a form. Then create a link in your site pointing to the form. Will it work? Sure... is it ideal... that's in the eye of the beholder.

@Fareedbaba said:
> I tried to build a form using angular +SPFx and deployed it in app gallery.

I'll be direct: **you're going to have challenges using Angular with SPFx**. I've written about it a bunch in the past ([good summary here](http://www.andrewconnell.com/blog/using-angular-elements-in-sharepoint-framework-projects)). While it's possible, why is it a challenge? Because **you're trying to combine two very opinioned frameworks, project types & build processes** (Angular & SPFx) that want their project structures & build processes to follow a very prescribed recipe. 

As we all know, putting two very opinioned ~people~ 😄 frameworks together can be challenging. There's nothing that Microsoft / SharePoint / Google can do to make this easier... it's just a byproduct of the decisions of the frameworks. It's one reason why React wrks so well with SPFx: React is very _unopinionated_.

**Comment by Fareedbaba** [comment]
> Great question @Fareedbaba! :)
> 
> My personal feedback is there is no real single yes or no answer to your question regarding if your requirements are a good fit for SPFx.
> 
> Each scenario has unique needs, expectations, time to deliver and details, etc that might determine if the use of SPFx (or any additional framework, such as angular) is the right solution or if another technology choice might serve as a better option.
> 
> For example, you mentioned a form. I don't know if this is for populating a list, but if it is, there is also the option of using PowerApps to provide an enhanced or custom form.
> 
> If you are looking to learn more about SPFx, there is a fantastic and recently updated training package available here: https://aka.ms/spfx-training.
> 
> Hope this helps! :)

Thanks Pop Warner for suggestions

**Comment by Fareedbaba** [comment]
> The scenario you selected is a bit of a stretch for a "good fit" for SPFx.
> 
> SPFx is a framework that allows you to build two types of components: web parts & extensions.
> 
> * **Extensions** _extend_ the existing UI by adding buttons to list toolbars & context menus, change how a cell is rendered and add a header/footer to a page.
> * **Web Parts** allow you to build reusable controls that end users/page designers can drop on a page.
> 
> Anything more than that and you're stretching. Custom form solutions are intended to be solved with PowerApps.
> 
> With that being said, could you use it to create custom forms? Sure... look into the feature that enables full page apps (currently in dev preview). You could create _one big web part_, put it on the page and use it as a form. Then create a link in your site pointing to the form. Will it work? Sure... is it ideal... that's in the eye of the beholder.
> 
> @Fareedbaba said:
> 
> > I tried to build a form using angular +SPFx and deployed it in app gallery.
> 
> I'll be direct: **you're going to have challenges using Angular with SPFx**. I've written about it a bunch in the past ([good summary here](http://www.andrewconnell.com/blog/using-angular-elements-in-sharepoint-framework-projects)). While it's possible, why is it a challenge? Because **you're trying to combine two very opinioned frameworks, project types & build processes** (Angular & SPFx) that want their project structures & build processes to follow a very prescribed recipe.
> 
> As we all know, putting two very opinioned people 😄 frameworks together can be challenging. There's nothing that Microsoft / SharePoint / Google can do to make this easier... it's just a byproduct of the decisions of the frameworks. It's one reason why React wrks so well with SPFx: React is very _unopinionated_.

Thanks for answering with all the necessary Information Andrew. 
I thought these were the answers that were running through my thoughts and raising few other questions. I believe all my questions will find answers from your answer taken as reference.
