### ISSUE TITLE
Unable to create sites from Provisioning Service

### ISSUE THREAD

**Issue by DeanGross** [SharePoint/sp-dev-docs#3613]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I expect new sites to be created from the SPO Provisioning service

#### Observed Behavior

I clicked on Add to your Tenant, a new browser tab opened and after several minutes a Login dialog box displayed. I reentered my global admin credentials and could not log in. I'm using a demos.microsoft. com tenant

#### Steps to Reproduce

I tried several different samples, none of them worked

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
If you are still having issues with the service, please share details on the exact exceptions which you are getting either in UI or in the result email. We know that the service works by default for the demos.microsoft.com sites, but as there are no details on what you are experiencing here, we can't really work on fixing anything.

Please share the stack trace and what template was selected, so that we can investigate further. Closing this for now as there's nothing we can work on in this issue, so if you still are experiencing issues, please open a new issue with sufficient amount of details for us to investigate what goes wrong. Thx.
