### ISSUE TITLE
How to localize sharepoint assets with sharepoint framework

### ISSUE THREAD

**Issue by cpradog** [SharePoint/sp-dev-docs#3645]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I should be able to use resx or another method to localize sharepoint assets like content types, fields or lists, the same way I can localize web parts or extensions.

**Comment by patmill** [comment]
Have you read this post - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts ?

**Comment by patmill** [comment]
The assets follow the same format as sharepoint add-ins.  Have you looked at documents like this - https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins ?  I don't believe we have as SPFx document explicitly for this.

**Comment by lucabandMSFT** [comment]
hey @cpradog, was Pat's answer useful to unblock you?

**Comment by cpradog** [comment]
I readed that, but I don't understand hoy to deploy the resx files with a spfx package.

**Comment by Chouille** [comment]
I'm also interested on a solution for that. (FYI, i'm newbie on spfx)
In my case, i would like to deploy basic lists in sharepoint sites.

Code in schema.xml
`<List xmlns:ows="Microsoft SharePoint" Title="Basic List" EnableContentTypes="TRUE" FolderCreation="FALSE" Direction="$Resources:Direction;" Url="Lists/Basic List" BaseType="0" xmlns="http://schemas.microsoft.com/sharepoint/">
  <MetaData>
    <ContentTypes>
    </ContentTypes>
    <Fields></Fields>
    <Views>
      <View BaseViewID="1" Type="HTML" WebPartZoneID="Main" DisplayName="$Resources:core,objectiv_schema_mwsidcamlidC24;" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" SetupPath="pages\viewpage.aspx" ImageUrl="/_layouts/images/generic.png" Url="AllItems.aspx">
        <XslLink Default="TRUE">main.xsl</XslLink>
        <JSLink>clienttemplates.js</JSLink>
        <RowLimit Paged="TRUE">30</RowLimit>
        <Toolbar Type="Standard" />
        <ViewFields>
          <FieldRef Name="LinkTitle"></FieldRef>
        </ViewFields>
        <Query>
          <OrderBy>
            <FieldRef Name="ID" />
          </OrderBy>
        </Query>
      </View>
    </Views>
    <Forms>
      <Form Type="DisplayForm" Url="DispForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="EditForm" Url="EditForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
      <Form Type="NewForm" Url="NewForm.aspx" SetupPath="pages\form.aspx" WebPartZoneID="Main" />
    </Forms>
  </MetaData>
</List>`

mystrings.d.ts
`declare interface IHelloWorldWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  ProjectAreaListName: string;
}

declare module 'HelloWorldWebPartStrings' {
  const strings: IHelloWorldWebPartStrings;
  export = strings;
}
`

en-us.js
`define([], function() {
  return {
    "PropertyPaneDescription": "Deploy project stuff.",
    "BasicGroupName": "Customer Lifecycle Tools",
    "DescriptionFieldLabel": "Description Field",
    "ProjectAreaListName": "Project Area"
  }
});`

fr-fr.js
`define([], function() {
    return {
      "PropertyPaneDescription": "Deploie les éléments de projet.",
      "BasicGroupName": "Customer Lifecycle Tools",
      "DescriptionFieldLabel": "Description Field",
      "ProjectAreaListName": "Zone du projet"
    }
  });`

I think the question is what to write in elements.xml in order to used localization file

elements.xml :
`<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">

    <ListInstance
            CustomSchema="schema.xml"
            FeatureId="00bfea71-de22-43b2-a848-c05709900100"
            Title="Project phases"
            Description="List of project phases."
            TemplateType="100"
            Url="Lists/ProjectPhases">
    </ListInstance>

    <ListInstance
            CustomSchema="schema2.xml"
            FeatureId="00bfea71-de22-43b2-a848-c05709900100"
            **Title="???What to use here ???"**
            Description="List of project phases."
            TemplateType="100"
            Url="Lists/ProjectArea">
    </ListInstance>
</Elements>`

I try following : 

- {string.ProjectAreaListName}
- "{string.ProjectAreaListName}"
- $Resources:ProjectAreaListName
- "$Resources:ProjectAreaListName"

Thanks for your help :)

**Comment by LTgz** [comment]
Hi, there still is no documentation on this process.
Is it actually supported? 
If so can anyone point me to some resources on how this might work?
The Add-In documentation does not account for a spfx project, you just end up provisionning a list with "$Resources:ListTitle" as title.

**Comment by AJIXuMuK** [comment]
Hello @cpradog - sorry for the long delay.

The localization of Feature Framework assets (lists, fields, etc.) is available using the similar approach to SharePoint Add-ins (as @patmill mentioned before).

Here is how it works.

You need to add your `resx` files to `sharepoint\feature_xml` folder.

The file with name `Resources.resx` will be considered the default resource file.
More than one `Resources.resx` file will end up in an error.
All files following `Resources.??-??.resx` (such as `Resources.en-US.resx`) will be considered as localized resources.

Next, you can use resources placeholder for in your `elements.xml`, for example like that:
```
Description="$Resources:String1;"
```

The localization will be applied when the solution is installed (Add an app) to the specific site based on its language.
