### ISSUE TITLE
Incorrect placement of rowIndex sample

### ISSUE THREAD

**Issue by shagra-ms** [SharePoint/sp-dev-docs#3677]
The rowIndex sample is for View Formatting. This should rather be in View Formatting topic. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Hey @thechriskent, can you confirm this is a doc bug?

**Comment by bcameron1231** [comment]
rowIndex is a valid property for row formatting.

**Comment by thechriskent** [comment]
The @rowIndex magic string is valid in both Column and View Formatting. However, I understand the concern since we've divided the documentation into View Formatting and Column Formatting. However, you'll notice that the bulk of the documentation lives with Column Formatting because View Formatting is a superset of this functionality. the View Formatting rowFormatter property can use any valid Column Format.

The way the documentation is structured, the magic strings are all defined with examples on the Column Formatting doc so this is currently the best spot for @rowIndex. Since the best example for @rowIndex is still the sample view format included it makes sense to keep it there. However, I think restructuring these docs to be more unified and to make it more obvious how things work is a great idea!

I'll go ahead and close this issue for now (feel free to reopen if you disagree), but will talk with the team about restructuring.
