### ISSUE TITLE
Problems reading folder content with code snippets

### ISSUE THREAD

**Issue by code2expert** [SharePoint/sp-dev-docs#3681]
I am working on an instance of SharePoint Online and we have created some folders with files inside them, some folders have no files. I want to check folders with no file and return a message which shouldn't be a problem. I am using VBScript for these checks and no matter how I try, I get an error 403 or access denied response.  I have checked stack overflow and nothing seems to be there for this problem. 

Please note that I am a developer and not the admin. I can also view these folders directly through the browser with no problems. The application I am updating is a legacy application and the environment needs to be classic ASP with vbscript. 

NB: I am open to other options though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da51381a-7a39-8c31-8af8-b05ecafc377a
* Version Independent ID: 693ecf1c-8e75-1f61-0264-fbdefaff0968
* Content: [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest)
* Content Source: [docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
If work when you're using the browser because you have logged into SharePoint and your session is cookie'd with your successful auth details.

403 = forbidden which implies you aren't passing any credentials along in your request. 

How are you making the request? What API are you using? How are you authenticating?

The recommended way to do this remotely is to use the SharePoint REST API or Microsoft Graph API to query the contents of the doc library. When submitting that request, you need to include an OAuth token for your application in the HTTP Authorization request header.

A few links to get you started:

- https://docs.microsoft.com/en-us/graph/auth-overview?toc=./ref/toc.json&view=graph-rest-1.0
- https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0
