### ISSUE TITLE
Cannot provision a "modern" site to the "tenant.sharepoint.com" URL.

### ISSUE THREAD

**Issue by Svek** [SharePoint/sp-dev-docs#3693]
**Category**

- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

**Expected or Desired Behavior**

It is not possible to provision a "modern" site using the "root" or default "mytenant.sharepoint.com" URL. I attempted to do this using the PnP PowerShell commands and also using the "Create a site" wizard on the new admin portal, both with similar (failed) results.

**Steps to Reproduce**
Using PnP PowerShell, with the following commands

    Connect-PnPOnline -Url https://mytenant-admin.sharepoint.com
    New-PnPSite 
        -Type CommunicationSite 
        -Title "Communication Site" 
        -Description "Communication Site" 
        -Url "https://mytenant.sharepoint.com" 
        -Classification "classification" 
        -SiteDesign Showcase

The response message I got was

    New-PnPSite : {
        "error": {
            "code" : "-2147024894, System.IO.FileNotFoundException",
            "message" : "File Not Found."
        }
    }

I also attempted to do this via the new admin portal, with no success. It seems there is no way to define the URL and you are forced to only add new sites under the `/sites` or `/teams` paths. Here is a screenshot of it:

![bug-report-1](https://user-images.githubusercontent.com/25241292/55084093-33471d00-50d7-11e9-87e7-423f0c6a372e.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1114c203-314e-f97a-a8a4-d4f5ec73af0e
* Version Independent ID: 79c90765-56a2-9d05-9ace-83cd71fc0fde
* Content: [Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites)
* Content Source: [docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by VesaJuvonen** [comment]
This is indeed by design as it's also not supported to delete the root site collection from your tenant as that will cause long-lasting issues. We will be releasing new cmdlet and CSOM APIs to modernize your classic root site collection. Also - all new tenants have already communication sites created to the root site collection. If you have already deleted the root site collection using some method, please contact support using the tenant admin support pages to get your situation resolved.

![image](https://user-images.githubusercontent.com/7446437/55103654-8f0ea780-50d1-11e9-9033-f6fb89f7c918.png)
