### ISSUE TITLE
error no-unused-variable module 6

### ISSUE THREAD

**Issue by bvdinesh** [SharePoint/sp-dev-docs#37]
I was trying "Using Office UI Fabric Components" example, but I have received below errors from DocumentCardExample.tsx file

![image](https://cloud.githubusercontent.com/assets/21132206/17835453/789e5a08-6732-11e6-924b-cd37a18b02a9.png)

**Comment by patmill** [comment]
We'll clean these up.  Thanks for pointing it out.

**Comment by nickpape-msft** [comment]
Related to #27, the lint rules need to be relaxed.

**Comment by nickpape-msft** [comment]
As of [drop 2](https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-Drop-2). We have added support for the following in TSLint:
* Option to display tslint violations as warnings, instead of errors
* Option to disable all default lint rules
* Relaxed tslint rules

These are all included in the new generator. [Simply update `config/tslint.json` with this gist.](https://gist.github.com/nickpape-msft/b3a0e0a4d64c029794eb4d2318d54308).

**Also, **the sample was also updated to mention removing the unused imports, and the lint errors were fixed.
