### ISSUE TITLE
Workbench doesn't load when using @microsoft/rush with SPFx 1.8

### ISSUE THREAD

**Issue by NickSevens** [SharePoint/sp-dev-docs#3736]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When using `@microsoft/rush` as monorepo manager, I expect to be able to test my web parts on the **local workbench**.

#### Observed Behavior

When using `@microsoft/rush` as a monorepo manager and adding just a single SPFX 1.8 webpart project, the local workbench does not work. When running `gulp serve` the build completes and the browser is started, but the **page stays blank**. There are JS issues showing up:
```
[1554362242164][SPComponentLoader.loadScript] [SPLoaderError.urlStatusLocalhostFileNotFoundError]:
***Failed to load URL 'https://localhost:4321/../../common/temp/node_modules/@microsoft/decorators/dist/decorators.js' for resource 'decorators' in component 'f97266fb-ccb7-430e-9384-4124d05295d3' (Decorators). The file was not found in the server.
Make sure that you are running 'gulp serve'.

***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:8390:24)
    at new SPLoaderError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:4036:28)
    at Function.ErrorBuilder.buildErrorWithErrorLog (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3801:21)
    at Function.ErrorBuilder.buildUrlStatusLocalhostFileNotFoundError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:3735:21)
    at Function.ResourceUrlChecker._throwUrlStatusError (https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:6119:59)
    at https://localhost:4321/temp/workbench-packages/@microsoft_sp-loader/dist/sp-loader-assembly_default.js:6110:43
    at async Promise.all (index 0)
```

Judging by the error message, the workbench tries to load from `common/temp/node_modules/...` which is indeed the path where the node modules are saved by `@microsoft/rush`. However, the path is not served by the server.

This used to work perfectly in SPFx 1.6/1.7, so I wonder what has changed for SPFx 1.8.

#### Steps to Reproduce

- Create a new `@microsoft/rush` repository: `rush init`
- Add an SPFx project (e.g. `apps/my-demo-app`)
- Add the project to the `rush.json` config
- Run `rush update`
- Run `rush build`
- Run `gulp serve` in the `apps/my-demo-app` directory

**Comment by NickSevens** [comment]
@patmill is this something that falls withing supported scenarios? Or is this too much of an edge-case?

**Comment by NickSevens** [comment]
@VesaJuvonen is there any progress around this?

**Comment by Js-Brecht** [comment]
I figured out the solution to this.  The issue is caused by the dependencies for each workspace being symlinked to `/common/temp/node_modules`.  The trick is to get `gulp-connect` to serve files from that directory.

To do this, I used [`st`](https://www.npmjs.com/package/st) with `gulp-connect` [here](https://github.com/microsoft/rushstack/blob/master/core-build/gulp-core-build-serve/src/ServeTask.ts#L138-L147)
```js
// Spin up the connect server
const st = require('st');
gulpConnect.server({
  https: httpsServerOptions,
  livereload: true,
  middleware: (): Function[] => [this._logRequestsMiddleware, this._enableCorsMiddleware, st({ path: path.resolve('../../common/temp/node_modules'), url: '/common/temp/node_modules', dot: true })],
  port: port,
  root: path.join(rootPath, this.taskConfig.rootFolder || ''),
  preferHttp1: true,
  host: hostname
});
```

This is in the npm package/file `@microsoft/gulp-core-build-serve/lib/ServeTask`.  

> path.resolve('../../common/temp/node_modules')

This part will differ depending on the structure of the repo, so there would need to be something that knows where the `common/temp/node_modules` directory is in relation to your workspace, or knows how to find it.

@NickSevens yours is interesting because it is using URL `../../`, which may cause additional problems.   Could try like this:
```js
st({ path: '../path/to/common/temp/node_modules', url: '/../../common/temp/node_modules', dot: true })
```

Mine tries to access it as though it's located under the root, so my url looks like `https://localhost:4321/common/temp/node_modules`.  Could be because I'm using SPFx 1.9.1, with `pnpm` version 4.1.7 🤷‍♂ 

An alternative is to hard link all of the dependencies into the workspace's `node_modules`, but changing `gulp-connect` settings results in a much faster operation (since hardlinking all of those dependencies takes time), plus its a lot easier to accomplish.  At first I wrote a script that would do exactly that, but this solution aligns better with the whole concept of centralized dependencies.

**Comment by Js-Brecht** [comment]
Taking that a short step further, this is what I did:

```js
...
        const { rootPath, properties: { commonPath } } = this.buildConfig;
...
        let commonNodeModules = '';
        if (commonPath)
            commonNodeModules = path.resolve(path.join(commonPath, 'temp/node_modules'));
        const middlewareCollection = [
            this._logRequestsMiddleware,
            this._enableCorsMiddleware,
            commonNodeModules && st({ path: commonNodeModules, url: '/common/temp/node_modules', dot: true })
        ].filter(Boolean);
        gulpConnect.server({
            https: httpsServerOptions,
            livereload: true,
            middleware: () => middlewareCollection,
            port: port,
            root: path.join(rootPath, this.taskConfig.rootFolder || ''),
            preferHttp1: true,
            host: hostname
        });
```

And then in my `gulpfile.js`:
```js
const build = require('@microsoft/sp-build-web');
const config = build.getConfig();
let isServeTask = false;

if (config.args['_'].indexOf('serve') > -1) {
    isServeTask = true;
    build.task('configure-common-path', build.serial({
        execute: async (buildConfig) => {
            buildConfig.properties.commonPath = path.resolve('../../common'); // This is where you would put the path to your repository root/common folder
        },
    }));
}

build.initialize(gulp);

if (isServeTask) {
    gulp.task('serve', ['configure-common-path'], gulp.tasks.serve.fn);
}
```

The reason I did it this way is because it's much more portable.  I'm sure there are better ways, though 🤷‍♂ 

This part
```js
if (isServeTask) {
    gulp.task('serve', ['configure-common-path'], gulp.tasks.serve.fn);
}
```
Is pretty hacky, but there's not really an official way to inject a task _**before**_ the serve task yet, or even a subtask at the beginning of the chain ([I've created a new suggestion in uservoice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/38940562-add-pre-post-task-hooks-for-gulp-build-rig), but I have my doubts about that getting any traction).  I experimented with this for a bit, and this was the best method I came up with for running tasks before `serve`.  Plenty of alternatives, including rebuilding the entire `gulp serve` task chain in a new, custom task (that can be tricky, though), and even creating a custom task that runs a series of tasks, then runs `gulp.start('serve')` at the end (but that starts a whole new gulp chain....).

**Comment by Js-Brecht** [comment]
@NickSevens I submitted a PR to address this issue, but chances are probably close to 100% that Microsoft will not patch the older versions of SPFx.  Check out [Js-Brecht/static-paths-1.8.2](https://github.com/Js-Brecht/static-paths-1.8.2) for an example of how to implement a patch to make this work with SPFx 1.8.2.

If you wanted to use SPFx v1.9.2, the steps are pretty much identical.  You should probably use the `rush` libraries that it uses, though, instead of the ones in that repo (some minor version differences).  You can find patched versions of them  [here](https://github.com/Js-Brecht/rushstack/tree/static-paths-spfx-1.9.1/dist).

The changes I made for each version of SPFx are in these branches of my `rush` fork:

* `v1.8.2`: <https://github.com/Js-Brecht/rushstack/tree/static-paths-spfx-1.8.2>
* `v1.9.1`: <https://github.com/Js-Brecht/rushstack/tree/static-paths-spfx-1.9.1>

There's no guarantee that the implementation will remain the same.  They may choose to deny my PR over at `Rush`, or they may want the implementation changed.  I can, however, say that this works.

**NOTE:** It's probably not a good idea to trust tarballs that people link to, including mine.  If you don't trust them, you're free to examine the source code in the branches above.  If it were me, I'd probably go as far as to generate a diff between my changes, and the same branch in the official repository (original branches are below).  Once you know you can trust it, you can `rush build` the changes yourself, and use that instead.

_Original rush branches_
* `v1.8.2`: <https://github.com/microsoft/rushstack/tree/%40microsoft/gulp-core-build-serve_v3.3.26>
* `v1.9.1`: <https://github.com/microsoft/rushstack/tree/%40microsoft/gulp-core-build-serve_v3.3.29>

**Comment by NickSevens** [comment]
Thanks for the effort @Js-Brecht, but indeed, it probably won't be implemented in an older SPFx version. I'd be happy however if it would be considered to be patched in any future release. :)

**Comment by Js-Brecht** [comment]
I agree, that would be nice.  Almost more work than it's worth, building webparts without the local workbench  😅

**Comment by NickSevens** [comment]
To be fair, I almost never use the workbench either... But it'd be nice if I _could_ :)

**Comment by kemesfun** [comment]
@NickSevens  Can you open this issue in the microsoft/rushstack repo ?
