### ISSUE TITLE
SPFx  Header and Footer occupying the real estate area

### ISSUE THREAD

**Issue by srisspfx** [SharePoint/sp-dev-docs#3738]
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Header and Footer developed through SPFx extensions are occupying the screen space even on scrolling the page. This has reduced the readable area on the page, as i don't want header and footer information all the time. Any help to make the header, footer scrollable with the content area would be much useful.

Thanks.

**Comment by andrewconnell** [comment]
This is by design... the SPFx extension application customizer placeholders are "sticky". They cannot be made scrollable at this time... that would fall into the "feature request" category and should be submitted to user voice: https://aka.ms/sp-dev-uservoice. There may already be a request for this that you can vote on.
