### ISSUE TITLE
loadTheme method no longer working

### ISSUE THREAD

**Issue by Promhize** [SharePoint/sp-dev-docs#3782]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

>We were using the loadTheme method from `import * as styling from "@uifabric/styling"` to apply theme colors on Modern pages
>
>

#### Observed Behavior

> But now it's breaking with the following error:
`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in response to a mutation?`
![image](https://user-images.githubusercontent.com/20524675/56050639-54994180-5d44-11e9-8dc9-9c9eecd68575.png)

>Are we using the correct method? Would appreciate any prompt response, keep up the great work 🙏

**Comment by patmill** [comment]
Using LoadTheme is unsupported (for the reason you are seeing).  It is only the parent/host application that can call it.  as per the docs - "The host app is responsible for getting the theme and then applying it to the page by calling loadTheme()"

Are you trying the change the theme of the whole page, or just customize the theme for your webpart?

**Comment by Promhize** [comment]
@patmill we are trying to change the theme of the whole page

**Comment by patmill** [comment]
I see.  This will require a feature request from the product group, as a) the theme is pretty integral to the overall page and b) as the app changes what versions of fabric, etc. are being used, the underlying definition of theme will likely (and already has) changed, breaking either the page, or your code.  userVoice is probably your best bet.  Alternately, I don't know if you can programatically change the theme information on the server, so that when the page is requested again it has the new theme.  That will apply to all users of the site though.
