### ISSUE TITLE
Link in DocumentLibrary ClientSideWebPart not working

### ISSUE THREAD

**Issue by robinmeure** [SharePoint/sp-dev-docs#3804]
#### Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When clicking on a link in a document library webpart, the link should open the document. 

#### Observed Behavior

Instead of opening the document, the link is sent as a download to the browser.

#### Steps to Reproduce

1. Add a link to a document library
2. Add a Document Library Clientside WebPart to a page
3. Click on the link from the WebPart, download prompt shows

**Comment by patmill** [comment]
So this isn't really the correct place to report this.  But let's see if we can help.  What kind of document are you clicking?

**Comment by robinmeure** [comment]
Not a document but a link to a document


________________________________

**Comment by patmill** [comment]
What kind of document, and what is actually downloaded?  The document itself, or a link to it?

**Comment by robinmeure** [comment]
The link itself, just try the repro steps, it's pretty easy to reproduce


________________________________

**Comment by andrewconnell** [comment]
I'm not able to repro this... I added a Document Library CSWP to a page, selected the doc library, and clicked the link to a page. Worked as expected... the page opened in a new tab. 

Can you verify the browser & SharePoint env you're in?

**Comment by robinmeure** [comment]
Hey Andrew, sure, I tested (just now) with both Edge versions on the MSFT tenant and it still repro's.

**Comment by andrewconnell** [comment]
@robinmeure said
> MSFT tenant

? You mean SharePoint Online?

Have you tried other browsers? I'm not seeing the same with Chrome / FF (I'm on MacOS so no Edge to repro for me).

**Comment by robinmeure** [comment]
Correct, SPO (microsoft.sharepoint.com), FF also repro's.
1. Create communication site
2. Add link to document library
2. Add a news article page
3. Add document library webpart to the page
4. Click on link from the doclib webpart

**Comment by KoenZomers** [comment]
I can repro it here as well on my own Targeted Release tenant. Repro steps were a bit fuzzy for me. To reproduce:

1. Go to a Modern Comms site
2. Go to the default Documents library in the site
3. Using the New menu create a new Link and point it to any Word or PDF document you have
4. Click on the link you just created in the document library and notice how it opens the document you linked to in your browser
5. Create a new page in the comms site
6. Add the Document Library webpart to the page and point it to the default Documents library in the site
7. Publish the page
8. Click on the link you added to the document library in step 3 and notice how it now downloads a .URL file first. Not until you open this downloaded file, it will open the document it points to. This behavior is different from opening the same link in the same document library directly, without being on a site page, where it will directly open the document without downloading the .URL first. This issue is about this inconsistency.
