### ISSUE TITLE
Custom Feature to upload files to SP gets an error installing. 

### ISSUE THREAD

**Issue by taykunats** [SharePoint/sp-dev-docs#382]
#### Category
- [x ] Question

I have followed the steps in adding custom features. I can get it to work on the <ListInstance> element. However, when I use module and even if i include the files, I always get an error installing the sppkg. Source path "Features\1ba2337a-f185-46c7-8757-35ab065f5dc7\magazine-webpart.bundle_7033685d66f90553a80ccedbf4e8e399.js" not found. I have plced the file in both the feature folder and even created a redundant Features folder. Are modules unsupported currently. 

Thanks

**Comment by mcmynn83** [comment]
Hi Taykunats,
It is difficult to help diagnose the issue with out having the actual sppkg file.   Could you send me the sppkg file to grahamc at Microsoft.com or by making it accessible online?

Thanks,
Graham

**Comment by mcmynn83** [comment]
Hi Taykunats,
Modules is a supported element and it works.  Just so other people running into similar problems can be able to fix the issue the following problems were found:
1.  You need to reference your files being added in a rels file when you add a new one.  The relationship type should be a feature-elementfile.  As far as SharePoint is concerned the file doesn’t exist if it’s not referenced 
2.  If you include a file of a different extension type you need to ensure that it is included in the [Content_Types].xml.  Since this is a js file and we didn't include that by default your file is not picked up.

Could you please give feedback on the process you went through to create your package?  We'd like to make sure that if using the tools these things are done automatically.  However, if manually modifying a package you would just have to know to do these things.

Thanks,
Graham

**Comment by chakkaradeep** [comment]
We will soon be publishing docs around how to deploy lists, libraries, fields and content types along with your .sppkg. It is a cumbersome process without the proper support in the build tools support. So, it would be helpful if you can give us some time to have the proper docs out on this topic.

Thanks!

**Comment by VesaJuvonen** [comment]
Since documentation around the feature framework capability is out in the dev.office.com/sharepoint, closing this one. 

- https://dev.office.com/sharepoint/docs/spfx/toolchain/provision-sharepoint-assets
- https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/provision-sp-assets-from-package
