### ISSUE TITLE
SPFx Web Part: Serialize web part properties' changes in Read mode?

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#3878]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Is there a way to correctly serialize web part properties in 'Read' display mode?
Use Case:
web part with dynamic tabs. User adds a new tab. Properties should be saved.

**Comment by patmill** [comment]
Not that I am aware of, no.  Although if one user adds a tab, do you expect all the other users to see it?  If not, then the WP properties probably aren't the right place to store them.

**Comment by AJIXuMuK** [comment]
@patmill 

> Although if one user adds a tab, do you expect all the other users to see it? 

well, it depends...
I can always store a user id-tabs mapping as well.
But I was more thinking about future in SPFx - MS Teams. 
If at some point we have access to "static" tabs that are specific to each user, it would be great to do all (or part of) configurations right in Read mode. 
For example, dashboards or something. All drag-n-drops, etc.
It would be great to have some kind of API that we can use to serialize settings from code at any point of time. And of course we as devs will be responsible for the results.

**Comment by patmill** [comment]
Static tabs are interesting.  They all have to share the same URL, and that URL doesn't understand "configurable".  My currently thinking is that a static tab would simply load the teams host app w/ the component ID parameter and no config flag.  For configuration settings, I think the way to do that will be to have a per-user (or per-site) configuration file that is stored when you modify the tab by interacting with it.  Maybe store it at the root of the teamsite or user site?

**Comment by AJIXuMuK** [comment]
File stored somewhere in a team site is a good solution. At least for now :).
But it would be great if you discuss such scenario when (or if) you'll be thinking of exposing SPFx in static tabs. :)

**Comment by patmill** [comment]
We are thinking of it, and that's the current thinking :).  The problem is that there is only a single URL that we can have.  In the normal case with a configurable tab, we start with the single config URL, but then create a list item (and possibly a list if it is the first time), and update the URL to point to the new entry.  Static tabs don't expose any flow like that.  If you just stored everyone's config in a single entry, a sufficiently popular solution could have thousands of user entries in it.  Loading that would be gross, and more importantly probably fraught with conflicting updates (or clobbering someone else's update).  We'll think about it some more though if/when we go down that path.

**Comment by AJIXuMuK** [comment]
Cool! Thank you for the insights, Pat!
I'll close this one as I've received the answer to the question.
Thanks again!
