### ISSUE TITLE
target property for a tag is being injected

### ISSUE THREAD

**Issue by LEPhillipP** [SharePoint/sp-dev-docs#3920]
#### Category
- [X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
#### Expected or Desired Behavior
Custom code that is embedded is what is uploaded with no changes - the issue is the anchor tags are getting the target="_blank" injected into them when it shouldnt be?

#### Observed Behavior
when i upload the code it seems target="_blank" is being added to each anchor tag, this only happens in our prod site, not our qa

#### Steps to Reproduce
upload the code, visit the live site, click on link, it opens in a new window.

We are using sharepoint 2013
My question is - is there a setting that controls whether sharepoint adds this property, or is it an automatic addition when it parses the code that it will always add target="_blank" to an anchor tag that doesnt have a target set up? I am a beginner sharepoint dev, so any hints or information would be greatly appreciated.

**Comment by andrewconnell** [comment]
@LEPhillipP hard to answer as you're working on a SharePoint release that's 6yrs old / 2 releases back from current (since then, SP 2016 & SP 2019 have been released). If memory serves me correct, there's no setting for this... it just happens.

Maybe if you can provide your code and explain with more detail & descriptive repo steps rather than just "upload the code" (ie: where? how are you adding to the . page? JS / HTML / ?) it would help...
