### ISSUE TITLE
WebParts React version is overwritten in tenant, (targeted release to selected users)

### ISSUE THREAD

**Issue by MathiasFl** [SharePoint/sp-dev-docs#3951]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Webpart dependency versions are kept the same as described in package.json.

Example:

` "dependencies": {
    "react": "16.7.0",
    ....
}`

a when running in tenant workbench the webpart should have React version `16.7.0`

#### Observed Behavior

React package is overwritten in Targeted Release tenant. 

- local workbench `16.7.0` 
- standard tenant `16.7.0`
- targeted release tenant workbench `16.8.5`
- deployed solution on targeted release tenant `16.8.5`

#### Steps to Reproduce

1. Generate new react project with `yo @microsoft/sharepoint` - (no tenant wide deployment/ no isolation)
2. Test package version i.e `console.log(React.version);` in the render function of HelloWorld component.
3. Serve or deploy to a targeted release tenant

**Comment by MathiasFl** [comment]
To clarify, tenant that is overwriting the packages is using targeted release to selected users, and changes the version to both targeted release users and regular users alike.

**Comment by patmill** [comment]
This is by design.  Each component that uses a particular major version of a library shared the same (current) version of that library.  So all components that built against react 15 share a single react 15 library, and all components that build against react 16 share a single react 16 library.

Are you seeing backwards compatibility issues with react 16.8 vs. 16.7, or just wondering what is going on?

**Comment by MathiasFl** [comment]
Both, was struggling with a react wrapper for a canvas framework, but since it's minor reliant i guess that is out of the picture if i can't rely on stable versions in my solutions. Thank you for clearing this up :)
