### ISSUE TITLE
Please sync content with https://docs.microsoft.com/office365/enterprise/use-office-365-cdn-with-spo

### ISSUE THREAD

**Issue by kelleyvice-msft** [SharePoint/sp-dev-docs#4003]
The topic https://docs.microsoft.com/office365/enterprise/use-office-365-cdn-with-spo has been broadly updated with up-to-date guidance and procedures related to the guidance in this topic. Please review for possible updates, and add a "See also" link.

Thanks! 

- Kelley

**Comment by andrewconnell** [comment]
Which content needs to be sync'd? Can you be more specific as there are _hundreds_ of docs in this repo...

**Comment by kelleyvice-msft** [comment]
Sorry, @andrewconnell! The doc I'm referring to is https://docs.microsoft.com/en-us/sharepoint/dev/general-development/office-365-cdn. It's essentially the same information that was just updated in https://docs.microsoft.com/office365/enterprise/use-office-365-cdn-with-spo, so you could simply redirect to it.

**Comment by andrewconnell** [comment]
Ah ok... so this issue seems to be a dupe from #4002... I already submitted a PR #4083 that deals with this so I'm going to close this issue.

Instead of simply redirecting (which I don't think we can do in the docs), I just updated the doc to point to the one you reference so we don't have anyone hit a 404 from existing search hits / references.

**Comment by kelleyvice-msft** [comment]
That's great, Andrew. Thank you!
