### ISSUE TITLE
Additional lookup fields with REST gives encoded titles

### ISSUE THREAD

**Issue by JakeStanger** [SharePoint/sp-dev-docs#4009]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Selecting the `DependentLookupInternalNames` key on a field, while performing a request on `_api/web/lists/getByTitle('List')/fields`, returns a list of internal names for additional fields.

In the case of the example below, I would expect to see `["AreaCode"]`.

#### Observed Behavior

The server responds with a list of encoded column titles, prefixed with the lookup field title.

For example:

I have a lookup internally named `Area`, with an additional lookup to a column with the internal name `AreaCode`. They have both been renamed so their titles are `Stage` and `Stage Code` respectively. 

The server response is `["Stage_x003a_Stage_x0020_Code"]`. Decoded this is `Stage:Stage Code`. 

Since these are titles, they're basically useless as is.

#### Steps to Reproduce

Add an additional field to a lookup column, then perform a GET request on that field using the REST API, with `DependentLookupInternalNames` in the select paramenter.

**Comment by andrewconnell** [comment]
I'm not clear what the error is... 

When you request the internal name, you'll get the unicode version of the field's internal name. Unicode values are surrounded with underscores, so `_x0020_` is what you'd see for a space.

The display name would not have these unicode values...

**Comment by JakeStanger** [comment]
What you have explained is the expected behavior. The server is not returning internal names. Instead, it is returning an encoded version of the display name (including the lookup column display name).

**Comment by andrewconnell** [comment]
Noticing this was still open & trying to clean up old stuff. Outstanding open issues

I'm not able to repro what you're saying. My repro:

- created two lists: Test & Area
- created lookup column from Test => Area... named the column **area code** & selected the field **Code** in list **Area**
- executed **_api/lists/getbytitle('Test1')/fields?$select=DependentLookupInternalNames**... notice the field's internal name is: **area_x0020_code_x003a_Code**
- renamed the field **area code** on list **Test** => **stage code**
- executed **_api/lists/getbytitle('Test1')/fields?$select=DependentLookupInternalNames**... notice the field's internal name is: **area_x0020_code_x003a_Code**

That's what I described above and what I'm seeing in my test.

**Comment by JakeStanger** [comment]
I'm definitely still getting the issue. I created a list called "Lookup Column Test", which has a lookup column which primarily looks up to 'Title', and has an additional lookup to a column internally called 'OriginalName' (with a title of `renamed`). Here's the response with the odata tags stripped:
```
>> await fetch("/_api/lists/getByTitle('Lookup Column Test')/fields?$filter=InternalName eq 'Test'&$select=Title,DependentLookupInternalNames", { headers: {Accept: "application/json" }}).then(r => r.json())

{
  "value": [
    {
      "Title": "Test",
      "DependentLookupInternalNames": [
        "Test_x003a_renamed"
      ]
    }
  ]
}
```

`Test_x003a_renamed` here is not correct as `renameed` is the column title, and *not* the internal name. I'd expect to see `Test_x003a_OriginalName` going by the weird double-encoding, or ideally for parity with `LookupField`, I'd hope to see just `OriginalName`.

**Comment by andrewconnell** [comment]
Where are you seeing this... SPO/onprem 2016/2019? My test was in SPO. 

If you're also SPO, there's not much more I can do here as I can't repro what you're seeing. From testing two tenants, it's behaving as expected from my POV.

**Comment by JakeStanger** [comment]
Yeah this is on SPO. We're experiencing this on every tenant we've tested.

**Comment by JakeStanger** [comment]
From re-reading your test it looks like you've perhaps misunderstood still. In your example, did you rename the column **Code**? 

If you rename this column, you will see that the value in the returned response for `DependentLookupInternalNames` will also update to match the new title, when it should remain static.

**Comment by andrewconnell** [comment]
Sorry... I'm not clear... not sure why this is so confusing :)

Do you mean to update the target field in the list that is the source for the lookup column?

**Comment by JakeStanger** [comment]
That would be the lookup column's `LookupField`. This key works as intended, and returns the internal name of the lookup field.

The problem is going to the list the lookup column points to, and changing the *title* of a column. The data on the parent's `DependentLookupInternalNames` (the key for additional lookups) returns an array of column *titles*.

Let me add some actual data to hopefully clear things up.

If we have a child list, and a parent list which includes a lookup (with additional fields) to the child:
![image](https://user-images.githubusercontent.com/5057870/65878536-383aa100-e386-11e9-92f4-e41360273c1a.png)

![image](https://user-images.githubusercontent.com/5057870/65878554-412b7280-e386-11e9-95a4-9b7fc75bb400.png)

Where the title of `New Name` does not match its internal name:
![image](https://user-images.githubusercontent.com/5057870/65878762-b7c87000-e386-11e9-8681-9559f930278d.png)

The value of `DependentLookupInternalNames` on `LookupToChildList` does not give the internal name, but instead a shortened and encoded version of the `Column/Title`

![image](https://user-images.githubusercontent.com/5057870/65878931-0d9d1800-e387-11e9-9636-390874e6e277.png)

You would expect DependentLookupInternalNames to contain `LookupToChildList/OriginalName` or ideally, to be consistent with `LookupField`, to just contain `OriginalName`.

**Comment by andrewconnell** [comment]
OK, now I see what you're saying. 

When it comes to lookup fields, the only data stored in the list contains the lookup field is the key. The other fields selected are _projections_ that are added only when the list is evaluated. Therefore, that's not surprising that the values change when you change the underlying columns when you query the list.

Keep in mind lookup columns were introduced to the platform _long_ before we were doing client-side dev & the client-side APIs were made available. Furthermore, lookup columns aren't intended to be used for referential integrity, rather they were more of a nice end-user feature.

It very well may be that what you're looking to do with them is not what was envisioned when the feature was implemented.

**Comment by JakeStanger** [comment]
May I ask what the purpose of the `DependentLookupInternalNames` key if this is the case then, since the values it returns are entirely useless in their current state?

Is there a recommended better approach to dealing with selecting multiple keys from a foreign list if not using lookups and additional fields?

**Comment by andrewconnell** [comment]
Sorry... been a LONG time since I've done anything with lookup columns and the docs aren't current... don't even recall this property.

@JakeStanger said:
> Is there a recommended better approach to dealing with selecting multiple keys from a foreign list if not using lookups and additional fields?

Sorry, I've got nothing on this. Without knowing your scenario, the fact you're mentioning "keys" and "foreign list" raises the "referential integrity" flag in me which we've always said in SharePoint, lists aren't for that. If that's what you need, you need to look at a different data storage option (ie: DB).

**Comment by JakeStanger** [comment]
Is there any official guidance or documentation on the purpose of lists in reference to what you just said? 

It's a little disappointing how underdeveloped the REST API is considering the time they've existed. The fact a large number of out ofthe box parts of the site are still using Caml and endpoints like `renderListDataAsStream` is testament to that. 

Regardless, thank you for answering everything.

**Comment by andrewconnell** [comment]
@JakeStanger said:
> Is there any official guidance or documentation on the purpose of lists in reference to what you just said?

Not sure what you're looking for. Lists are end user constructs used to store & collaborate on data. Yes, you can use them as a place to store data for custom solutions, but...

_<this is where IMHO starts, but it's one that's generally held>_

When you really start to push it for a custom app, you can find where it's not meant to be a replacement for a database.
</>

@JakeStanger said:
> It's a little disappointing how underdeveloped the REST API is considering the time they've existed.

I don't follow... the REST API is pretty darn robust. I assume you're talking about the classic web parts, not modern, correct? Microsoft has been trying to move to classic for many years & that's where the investments are, not in classic.

**Comment by JakeStanger** [comment]
To clarify, we work exclusively with modern. The modern list view still loads data using `renderListDataAsStream`, which takes Caml View XML.

**Comment by CPritch** [comment]
I'm sorry but if I'm following correctly:

1. We're not sure what the endpoint is for/used at all
  a. Why is it described or available if it's permanently an issue?
2. The endpoint will not be fixed even if it's broken/useless
  a. This leads to lots of wasted time now restructuring to use CAML as renderListDataAsStream is the only functional endpoint for lookups. We have been repeatedly instructed to move to oData filtering.
3. Don't use Lists for any relational db structures (In your opinion?)
  a. How do we get any official guidance from MS on this?
  b. As far as I'm aware it's not described that additional lookup fields were essentially defunct for REST. How could we have planned for this from official documentation?

Just seems rather insane to me that we don't have any proper schema for this endpoint or any others; it's called `dependentLookupInternalNames` and doesn't use the internal names of fields. This just seems like a bug but the answer to inherent issues like this is 'tough, work around it.' 

I can see why you've formed the opinion on not trusting any relational data structure in SPO. Just seems like developers can't discover this unless by experiencing undescribed structural issues with REST and service reliability.

**Comment by andrewconnell** [comment]
Whoa... slow down :) I don't think that isn't an accurate evaluation of my response. 

First, if you have an issue about the specific property in the docs, please feel free to open an issue to it. This issue was more about understanding how the property works.

@CPritch said:
> We're not sure what the endpoint is for/used at all
> a. Why is it described or available if it's permanently an issue?

It's a property that was documented in the docs, but when the docs were migrated from the old MSDN platform => docs.microsoft.com, there were some issues such as some information that was lost. It's a known issue and long-ongoing one (_mentioned numerous times in this issue list_)... they are trying to resolve. My point is that it's bigger than this one property.

There's nothing in this thread that confirms it's broken, useless or there's an issue. I was simply saying the listing of the property in the docs is void of a description, and because it's been a long time, I can't recall exactly what it was at the time. That's just being honest & up-front... 

@CPritch said:
> "Don't use Lists for any relational DB structures (In your opinion?)" & "I can see why you've formed the opinion on not trusting any relational data structure in SPO."

That's not what I said... you're being _much more_ absolute than what my statement said. 

This topic has been debated for ~10yrs in SharePoint, going wall the way back to when people were building sophisticated applications on top of SharePoint & using lists as database tables. Like everything, you live & learn and realize this isn't the best approach. [You'll find TONS of writings on this with a simple search...](https://www.google.com/search?q=sharepoint+list+vs+relational+database)

In no way did I say, or am I saying, I don't trust the data structures in SPO. What I am saying is that lookup fields were not introduced to enforce relational integrity between lists. While lookup columns do have some capabilities that mirror or closely mimic what relational integrity features do in true relational systems offer (eg: cascading deletes). They were introduced as an end-user feature. There are plenty of things in place where they differ from a true relationship (eg: lists have a hard limit on how many lookups they can have without throwing an error).

_putting my consulting hat on..._

Think of my statement more like this: if you came to me and asked "can I take my sports car out in the sand dunes if I make some modifications to it?" My answer is "yes, but that's not what it's intended for... there is a different tool for that."

Further, not every single "don't use it like this" is enumerated in any docs. Technically can you use lookups for relationships? Sure... my point: you can do this only to a point and not with the expectation they are true SQL relationships. That's all I was saying. There's a very good reason why you don't see the phrases "referential integrity" or "relationships" or "foreign keys" anywhere in the docs for lookup columns.

@CPritch said
> How do we get any official guidance from MS on this?

I'm sure you can google around and find numerous statements on this from both the community & Microsoft, but if you want something from this list, open an issue with an explicit question. I'll happily triage it like others and leave it for someone from Microsoft to answer.

**Comment by CPritch** [comment]
> First, if you have an issue about the specific property in the docs, please feel free to open an issue to it. This issue was more about understanding how the property works.

I believe the point of this issue was to determine if this is a broken endpoint or not. The endpoint does not return internal names and is therefore impossible to determine additional lookup fields for a column by REST. The answer appears to be that this is not possible by REST at all since it only comes through with a projected title field. This feel my griping about REST schema applies, it's been years and the REST endpoints haven't exactly changed.


> That's not what I said... you're being much more absolute than what my statement said.
The issue is that we have an undescribed REST schema with an unknown number of limitations on what is very simple relational behaviour. Just additional columns for a lookup, I don't see this as complex architechture. The guidance on oData filtering directs developers down a path that leads in dead ends from my perspective.

> This topic has been debated for ~10yrs in SharePoint, going wall the way back to when people were building sophisticated applications on top of SharePoint & using lists as database tables.
We are building a component library and pulling through additional fields for a column seems like something that should be possible. We are building something to integrate with SPO and OOTB list behavours. The impact of this means we have to migrate entirely to renderListDataAsStream for our library. Unfortunately best practices about building applications in SP doesn't feel super relevant to this issue. We still have to deal with the problem as we don't determine list structure for all clients necessarily.

> Further, not every single "don't use it like this" is enumerated in any docs. Technically can you use lookups for relationships? Sure... my point: you can do this only to a point and not with the expectation they are true SQL relationships.
I feel the question is how to determine which fields are additional lookups for a column. Any form of workaround other than, 'don't do this', would suffice. Unfortunately, we will have to describe this relationship elsewhere or determine where it's being pulled from when viewing the edit column form otherwise.


> I'm sure you can google around and find numerous statements on this from both the community & Microsoft.
I mean't official guidance/documentation from Microsoft on the purpose of dependentLookupInternalNames or whether this is possible at all via REST. Thank you though for the time spent.
