### ISSUE TITLE
Field Customizer:  onInit when navigating between lists

### ISSUE THREAD

**Issue by AJIXuMuK** [SharePoint/sp-dev-docs#4061]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

`onInit` is called once (and every time) when navigating to the list with column that has field customizer.

#### Observed Behavior

**Standard Release**
1. Called once after full page refresh
2. Called n+1 times when navigating to the list where n - number of times we navigated back.
More details on the 2d one.
Let's say there are List1 and List2. Field Customizer is applied to the column in List2.
Initial state - List2 AllItems.aspx, page refreshed.
Navigate to List1 and back to List2 using left nav - `onInit` called twice
Navigate to List1 and back to List2 using left nav once again - `onInit` called 3 times
and so on...

**Targeted Release**
1. Called once after full page refresh
2. **Not called at all** when navigating between lists.

Related to #3236 as well as #4057, #4056, #4054  

I think all these issues are related to some fundamental problems with lifecycles.

#### Steps to Reproduce

1. Create simple Field Customizer
2. in `onInit` add `alert`
3. Create List1
4. Create List2
5. Create test column in List2 and apply field customizer to it
6. Test scenarios mentioned above

**Comment by patmill** [comment]
So, not sure if this is necessarily incorrect or not.  With the targeted release list views, the view is cached when you navigate back and forth, so the intialization is done on the first load, but then the components should be kept and reused when you navigate back to the list.  Previously there was less caching, and the controls would be torn down then recreated (and reinitialized).

Is there an actual bug here, in that your code can't function correctly? (Let's ignore the dispose issue for now).

**Comment by AJIXuMuK** [comment]
@patmill - good question. If it's cached, and if I look at this issue with no connection to others... then, probably, Targeted Release behavior is correct. And should not lead to bugs, if 3d party code is written correctly. 
#3236 is more important as Field Customizer can have logic based on current view.
So, I would say in terms of Field Customizer for me correct lifecycle behavior:
1. call `onInit` when switching to list/view
2. if the customizer is cached for list/view - onInit can be skipped
3. call `onDispose` at the moment when the cached object will be disposed

Let me know what you think

**Comment by AJIXuMuK** [comment]
Added some details to #3236  as well.

**Comment by patmill** [comment]
Sorry for the delay - working with the dev who is fixing a variety of the list customizer related issues.  The plan is that onInit will fire only when the component is initialized.  If you switch back and forth between multiple lists, and the "fast nav" type of navigation occurs, the onInit will not fire if you return to the original list (or any list where onInit has fired).  This is because the objects will be initialized once and be reused when you return to the list.  However - switching between lists should fire onNavigate events, the context should always be correct when in the context of a given list, and the items selection change should fire when switching lists.  Dispose should be called when the whole app is torn down.

Does that match with your requirements?

**Comment by AJIXuMuK** [comment]
Hey @patmill - yes, I think it will work for me.

**Comment by AJIXuMuK** [comment]
@patmill - any updates on this one and related issues? :)

**Comment by BarGiraffe** [comment]
Has anyone come across a solution?  This is happening when I navigate between two specific libraries.  I am using the OOB Quick Launch exclusively to navigate.  There is no other custom navigation created. Thank you.

**Comment by AJIXuMuK** [comment]
`onInit` fires when the customizer should be initialized. For example, when you navigate to the list or view with the field for the first time.
It will not fire again if you come back to the same list as the "state" is cached and there is no need to reinitialize it.
