### ISSUE TITLE
App does not appear in site after deploying sppkg to app catalog

### ISSUE THREAD

**Issue by evlo** [SharePoint/sp-dev-docs#4095]
![app catalog](https://user-images.githubusercontent.com/8813196/58960010-8825a480-87a6-11e9-9c85-a7a385738017.png)
![apps](https://user-images.githubusercontent.com/8813196/58960012-88be3b00-87a6-11e9-8da4-357d19f3bdee.png)

I have deployed sppkg to app catalog in sharepoint online, but when i go to my dev sitecol i don't see the app in "add app", there were no errors during deployment and it works in both local and online workbench.

This is regarding step 3 in spfx tutorial.

I think apps don't use features, but anyway no features in  in both sitecollection or site apps that are named hello"something"

Here is the manifest file:
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "helloworld-webpart-client-side-solution",
    "id": "850d8bda-4dcc-4f53-9360-9c8db4ad741d",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    **"skipFeatureDeployment": true,**
    "isDomainIsolated": true
  },
  "paths": {
    "zippedPackage": "solution/helloworld-webpart.sppkg"
  }
}

**Comment by evlo** [comment]
When I removed lines
```
"skipFeatureDeployment": true,
"isDomainIsolated": true
```
from the manifest it does deploy.

Please mention this in tutorial so it does match latest app templates, it is confusing, i guess it would be confusing for other people not only me.

**Comment by andrewconnell** [comment]
The reason you didn't see it listed is because when you created the project, you elected to "skip feature deployment" hence the `skipFeatureDepoyment:true` setting. This means the web part was automatically installed in the site collection and if you edited a page, it would appear.

Not sure what tutorial you're referring to, but the very [first one here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) explicitly says to answer **no** to that question in the generator (see step 4).

> Select **N** to allow solution to be deployed to all sites immediately.
