### ISSUE TITLE
Lookup Fields in SharePoint Online not Working Correctly

### ISSUE THREAD

**Issue by nettlej** [SharePoint/sp-dev-docs#4170]
This is to reopen [this issue.](https://github.com/SharePoint/sp-dev-docs/issues/4154) First time posting so please forgive any error - I am still having the same problem. 

**Category**

- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

**Expected or Desired Behavior**
When a file is uploaded to Sharepoint,, you should be able to use the details pane to select any value from a lookup table and save the correct value.

**Observed Behavior**

Sharepoint 365 fields are defaulting to the first value in the list, no matter what is selected. When you try to correct it within the details pane, it opens an "edit" dialog and any change is made to the lookup table itself.  If you select "Edit all" to get the full pane then you can make the proper change but it is not possible from the details pane. 

**Steps to Reproduce**

1. Add a list with a few test items, titles only is fine.
2, Create a column in a document library with type "Lookup".  Under "Get Information from", select the list from step 1.
3. Upload a document to the library.
4. Attempt to set lookup column to anything EXCEPT first item.
5. Sharepoint uses the first value, no matter what you selected, and autosaves.
6. Go back to try to change - drop down will not show up but an Edit dialog box will show up tied to the lookup table itself. 

Work around - Select Edit all.

**Comment by lucabandMSFT** [comment]
Thank you for your submission. This GitHub issue list is targeted only for developer issues. As your issue is related on out-of-the-box capabilities or features, we cannot unfortunately process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
