### ISSUE TITLE
Convert framework to use TypeScript 2.0 style typings

### ISSUE THREAD

**Issue by wictorwilen** [SharePoint/sp-dev-docs#42]
As TSD is deprecated (https://github.com/Definitelytyped/tsd), will future SPFx be moved over to Typings (https://github.com/typings/typings) for TypeScript definitions.

**Comment by chakkaradeep** [comment]
This is in our todo list already along with moving to TypeScript 2.0.

**Comment by mike-morrison** [comment]
@wictorwilen @chakkaradeep Typings is basically deprecated too.  @types is the recommended path forward.  I don't believe you have to use TS 2.0.  vscode and sublime already know how to act right.  Not sure about atom though.  The @types packages may not be ready for primetime yet, but it might be worth investigating.  One less moving part.  👍 

**Reference:**  [_The Future of Declaration Files_](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)

#### _Notes and Acknowledgements_
_For those wondering, DefinitelyTyped will still be the place to author new declaration files. We’ll soon be providing a greatly expanded set of documentation aimed at .d.ts authors in the near future. Tools like Typings and tsd will continue to work, and we’ll be working alongside those communities to ensure a smooth transition._

**Comment by wictorwilen** [comment]
@mike-morrison - awesome info. As long as the dependency is taken on something that is not in a beta state.

**Comment by pgonzal** [comment]
FYI we are starting work now to upgrade our Developer Preview to use TypeScript 2.0 Beta.  2.0 has some important features that we would certainly want to incorporate before we freeze our API signatures (e.g. read-only properties, private constructors, strict null checks, etc).  If we do encounter any incompatibilities, it will be easier for the compiler team to fix them before the 2.0 release rather than after.

The aforementioned typings issue is very important to me.  My team works on around 40 TypeScript projects that export/import each others typings, and the old model seems to require (1) an extra build step to strip the typings from a library's exports, and then (2) for each consuming project to have the superset of all typings exposed by its dependencies, even if it doesn't use them directly.  This is not very scalable.  I believe the @types feature that Mike linked above should be a huge improvement.  AFAIK it does require the TypeScript 2.0 compiler, though.

**Comment by pgonzal** [comment]
VSO 239959

**Comment by pgonzal** [comment]
Update: David has completed the TypeScript 2.0 upgrade for the underlying [gulp-core-build](https://github.com/Microsoft/gulp-core-build/commits/master) system, and @lahuey is now working on converting **sp-build-web**.

**Comment by patmill** [comment]
This has been converted.
