### ISSUE TITLE
Library Component: Can it be deployed at site collection level only?

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-docs#4208]
#### Category
- [ x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

**Version**
SPFX version 1.8.2-plusbeta

**Question:** 
I've implemented a Library Component to share code between webparts and it works very well. 
From testing it seems that this is only a tenant level mechanism as I tried deploying at the site collection level only by using ` "skipFeatureDeployment": false` and it didn't work (Unable to find the Library Component). I know this is at preview right now but will this be something that will be enabled in later releases?

Thank you,
Gary

**Comment by PopWarner** [comment]
@gbminnock, I believe there has been mention that it can be used at a site collection app catalog, but the documentation shows deployment specifically for the tenant app catalog. I believe early in the preview I did not have much success in using a site collection app catalog, but can test again.

Here is the documentation where it references using the tenant app catalog:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-tutorial#how-to-deploy-and-consume-a-3rd-party-spfx-library-from-tenant-app-catalog

**Comment by gbminnock** [comment]
@PopWarner Yes its working fine for me at tenant app catalog. Guess I'll have to wait and see...
Tks.

**Comment by gbminnock** [comment]
Another question: If I deploy the Library Component I wonder would it be possible to ensure its only run at the site collection I intend? 

@PopWarner

**Comment by PopWarner** [comment]
Hi @gbminnock.... :)

Can you help me understand a little better the scenario you are using it for? 

Ultimately even though it may be tenant deployed, the LC will only run on a site where it's functions are being requested and executed via another SPFx solution, such as a web part or extension.

It's not like a tenant wide deployed extension, where the init function will fire anywhere the extension is loaded. Since the LC functions would only fire when a WP or Ext is created that specifically imports and then, in turn, calls the LC function(s), the LC's running is much more deliberate...hope that makes sense.. :)

**Comment by gbminnock** [comment]
Hey @PopWarner, I guess that has answered my question. It will only be run when requested. 

I wanted to ensure that other site collections would not have the ability to call this library unless explicitly given permission to do so (it seems like they could at the minute, but wouldn't do them much good as document libraries and such would exist over there). 

I'm thinking in terms of operations guys being nervous about deploying tenant wide. 

Tks,
Gary
