### ISSUE TITLE
SPFx gulp serve issue in workbench.html

### ISSUE THREAD

**Issue by vkselvaa** [SharePoint/sp-dev-docs#4254]
Can’t connect securely to this page
This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.

Your TLS security settings aren’t set to the defaults, which could also be causing this error.
Try this:
Go back to the last page

As per some reference i have updated the "Use SSL 3.0" and "Use TLS 1.0" in the Internet Options, but issue not yet resolved

**Comment by andrewconnell** [comment]
Did you install the development SSL cert after creating the first project? If so, try uninstalling & reinstalling it.

**Comment by vkselvaa** [comment]
@andrewconnell I am doing the POC project in my end. Is it necessary to my local environment?

**Comment by andrewconnell** [comment]
Yup... it's a self-signed cert that's used to host the local server that serves up the local workbench. Because it's a self-signed cert, it's not in any machine's trusted root authority (TRA). Therefore you must manually do that first, before your browser will respect the SSL cert.

See:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#trusting-the-self-signed-developer-certificate

**Comment by vkselvaa** [comment]
I have done as per the instructions mentioned in the "Unable to Trust the Self-signed Development Certificate" section, but my issue not yet resolved.

**Comment by andrewconnell** [comment]
Need more details to better help... can you share:
- the console output of `gulp trust-dev-cert`
- the console output of `gulps serve` when you start up the dev experience as well as what is in the console when the workbench attempts to load?

**Comment by vkselvaa** [comment]
I have faced this kind of issue, While cloning the solutions from **github**. here i cloned it from "https://github.com/SharePoint/sp-dev-fx-webparts.git". 
But i am not facing any issue of my own development.

**Comment by vkselvaa** [comment]
Is there anything i want update after cloning the solution from Github.

**Comment by andrewconnell** [comment]
Please see my last comment... https://github.com/SharePoint/sp-dev-docs/issues/4254#issuecomment-509616406

**Comment by dimportfolio** [comment]
@andrewconnell 

I am running into what I believe is the same issue on this post. I have attached the requested console output of running GULP trust-dev-cert && serve. Please let me know if you're able to view the output & if it is what you need.

https://imgur.com/a/KVDHomA

Steps I took to remedy the issue but failed:

I attempted to follow the troubleshooting steps from the Microsoft documentation but I don't believe it applies to my situation. The NODE version I am running is 10.16. I am using 0365 and followed the steps of setting up the Office 365 tenant & Development Environment.

_Troubleshooting
SPFx Development for SharePoint Server 2016
SharePoint Server 2016 uses the SharePoint Framework (SPFx) v1.1. Around this the time of the v1.1 release, NodeJS was transitioning from NodeJS v6.x to v8.x. In this update, NodeJS introduced a change where the default changed from HTTP1 to HTTP2. For some, this caused issues with SPFx. A later version of SPFx resolved these issues, but those who are still working with SPFx v1.1 (such as those working with SharePoint Server 2016) may run into issues.

To resolve this, set the following environment variable to instruct NodeJS to use HTTP1 instead of the default HTTP2: NODE_NO_HTTP2=1.

For more information, refer to issue #1002.

Unable to Trust the Self-signed Development Certificate
In some cases, executing the command gulp trust-dev-cert, does not have the desired effect of trusting the self-signed development certificate on your machine. In rare cases such as these, you may need to delete a hidden folder that's generated in your profile folder. Locate & delete the folder <homedir>/.gcb-serve-data and then try to trust the self-signed development certificate again._

**Comment by andrewconnell** [comment]
@dimportfolio said:
> I am running into what I believe is the same issue on this post. 

Please share what you are having an issue with... what is your problem / error? _"I think I am getting the same issue."_ isn't enough info... please describe your problem. If it's not identical, please open a new issue to not fragment the issue.

@vkselvaa has been specific about the error he's having and to better understand his/her situation, he/she needs to provide more detail.

**Comment by andrewconnell** [comment]
@vkselvaa said:
> I have faced this kind of issue, While cloning the solutions from github. here i cloned it from "https://github.com/SharePoint/sp-dev-fx-webparts.git". But i am not facing any issue of my own development.

So you're having an issue with projects in the **sp-dev-fx-webparts**... not with a new project? 

That repo contains many sample projects provided by the community. Some are quite old and need to be updated. You run each project individually, not the repo as a whole. 

If the issue is with a specific sample, then you should post the issue to that repo's issue list

**Comment by vkselvaa** [comment]
Yes i am facing same issue for all of the cloned projects. Not sure why this error is coming "**This might be because the site uses outdated or unsafe TLS security settings**" and don't know how to identify the root cause of this issue as i am new to the SPFx.

**Comment by dimportfolio** [comment]
@andrewconnell 

Sorry. The issue is identical because when I execute " gulp serve" The page that is provided says 

"This site can't provide a secure connection" 
ERR_SSL_PROTOCOL_ERROR

**Comment by andrewconnell** [comment]
@vkselvaa can you provide additional context? SPFx version installed, environment, Node version, specific project in that repo you are testing in that repo.

I suspect it may be because you're trying to test an older project that used an older version of SPFx that only supported Node v6 or Node v8...

**Comment by andrewconnell** [comment]
@dimportfolio please open a new issue... @vkselvaa is specific and it's going to be better to isolate the two. When you post it, provide as much context as possible (same stuff I just asked @vkselvaa for in my last comment).

**Comment by dimportfolio** [comment]
@andrewconnell Should I be opening a new issue when this is the same issue?

**Comment by andrewconnell** [comment]
If it's literally the exact same (new projects work fine, cloning from the sample web parts repo fails), then no new issue needed. If it's not the exact same, yes you should create a new issue and provide as much context as possible.

**Comment by dimportfolio** [comment]
@andrewconnell Ah thank you. I guess mine applies to new projects not working.
