### ISSUE TITLE
Supported column types

### ISSUE THREAD

**Issue by awacsmod** [SharePoint/sp-dev-docs#4269]
I just tried to hide some text from Date/Time columns in a calendar list. This should be rather simple, but whenever I add some code to the column formatting window, I already see the hint "This formatting JSON will be discarded", despite the fact that in the "Supported column types" section of this document, you report Date/Time columns as supported. 

In addition, despite you claiming that Calculated columns are not supported, I had no problem inserting formatting JSON code into such a column.

You may probably want to update the "Supported column types" section of this document or adjust it to make clear which columns are supported in which types of lists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#feedback)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
Thanks @awacsmod for pointing out that the Supported Columns section was out of date! Yes, calculated columns are now supported. In addition, other types like Location were not listed either way. I've submitted a pull request to address this gap.

**Date/Time columns are fully supported.** Date/Time columns now come with design mode support (quick format wizard). When you switch to Advanced mode in order to enter JSON directly, because this column type supports design mode, there is a "Switch to design mode" link near the bottom:
![image](https://user-images.githubusercontent.com/8364109/63445982-67650680-c407-11e9-8e7d-55e5c5f43e02.png)

The text underneath "This formatting JSON will be discarded" only applies if you click the Switch to design mode link. The intent is to communicate that the design mode wizard will overwrite any JSON formatting you have edited in Advanced Mode - not to indicate that all formatting will be discarded for the Date/Time column type.
