### ISSUE TITLE
Out of the box fields like Title field if made mandatory, don't show up in "Files that need attention" view 

### ISSUE THREAD

**Issue by vtikam** [SharePoint/sp-dev-docs#4270]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Lets take 2 fields, 'Title' which is available out of box and 'Category' which we have created as custom field. Category is set as mandatory field. Title field is also set as mandatory field by going to advance content type, enabling the option and then open the Title field from content type and select it as mandatory.
After this, upload a document in library and edit properties, in modern view.
While modifying properties it will show Title and Category with asterisk mark to show it as mandatory.But if we have left both fields empty, and open all documents view, only Category comes highlighted, Title field doesn't show up.
In files that need attention view, only Category missing comes up, but not Title. Same issue with other ootb fields.

Edit Properties Pane
![image](https://user-images.githubusercontent.com/14929827/60906414-af373080-a294-11e9-8109-28730b122fcf.png)

All Documents View on Document Library
![image](https://user-images.githubusercontent.com/14929827/60906453-c83fe180-a294-11e9-8825-960741120f16.png)

Files that need attention view
![image](https://user-images.githubusercontent.com/14929827/60906511-e7d70a00-a294-11e9-810a-2d8d87c3a99d.png)

**Comment by andrewconnell** [comment]
Can you be more specific & provide some context where you are seeing this? Is this OOTB functionality or is this an issue when deploying custom components in `*.sppkg` files, or column formatting?

Sorry, but the issue isn't clear.

**Comment by bcameron1231** [comment]
Reviewing this - It does seem to be a bug to me. The issue seems to be that the view "Files that need attention" is ignoring required **Title** field, however the details pane works fine.

Details Pane showing the item is missing a value for Title
![image](https://user-images.githubusercontent.com/7944457/60913614-07dedd00-a245-11e9-9a92-a4cec034336b.png)

"Files that need attention" view is not picking this up.
![image](https://user-images.githubusercontent.com/7944457/60913694-29d85f80-a245-11e9-89df-44b5d562c4c3.png)


**Expected Behavior**
I would expect the "Files that need attention" view would include the file where **Title** is missing

**Comment by vtikam** [comment]
> Can you be more specific & provide some context where you are seeing this? Is this OOTB functionality or is this an issue when deploying custom components in `*.sppkg` files, or column formatting?
> 
> Sorry, but the issue isn't clear.

This is on a normal document library. I have updated screenshot with titles. Please ignore *.sppkg files, I am trying to upload a document in Document Library and then checking the Files that need attention view and All Documents View

**Comment by andrewconnell** [comment]
Thanks for the additional details @vtikam ... this doesn't seem like a development issue, this seems like it is more of an issue with the OOTB functionality as @bcameron1231 also suggested. 

If so, this isn't the place to submit this issue as this GitHub issue list is targeted only for SharePoint development issues. Unfortunately, as your issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
