### ISSUE TITLE
Details Pane not shown on Uploading Files in Modern Library

### ISSUE THREAD

**Issue by kmprasad4u** [SharePoint/sp-dev-docs#4289]
In Modern Library, after uploading a document, the properties pane used to open by default. The below user voice also confirms the functionality has been present. This behavior seems to be not happening recently. I am unable to find any relevant information regarding the change. 

https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/7192842-enable-the-edit-properties-dialog-when-uploading-d

Also, is it possible to detect file(s) being uploaded to the document library in JavaScript and show a page allowing people to edit the properties for it ?

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The details pane should open after uploading a document in Modern Doc Library

#### Observed Behavior
The details pane is not opening after uploading a document. (Even with required field in the library)

#### Steps to Reproduce
Upload a document/drag and drop a document to Modern Document Library

**Comment by andrewconnell** [comment]
Thank you for your submission. This GitHub issue list is targeted only for SharePoint development issues. Unfortunately, as your issue is related to out-of-the-box capabilities of SharePoint or not related to SharePoint, we cannot process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.

**Comment by kmprasad4u** [comment]
@andrewconnell 
Thanks Andrew. Is there any way to detect item added event in SPFx so that we can redirect to a page to edit properties or try to show the properties panel ?

**Comment by andrewconnell** [comment]
No... SPFx is only client side.... AFAIK, there's no client-side event that's raised when an item is created.
