### ISSUE TITLE
PropertyPaneDropdown selected text required

### ISSUE THREAD

**Issue by Mahesh3439** [SharePoint/sp-dev-docs#4361]
#### Category
- [ X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [x] Example checked item (*delete this line*)

Hello Team,
Is there any way that we can get the PropertyPaneDropdown text rather than Key?

Example:
PropertyPaneDropdown('test2', {
            label: 'Dropdown',
            options: [
              { key: '1', text: 'One'},
              { key: '2', text: 'Two' },
              { key: '3', text: 'Three' },
              { key: '4', text: 'Four'}
            ],
            selectedKey: '1',
        })

What I need is when I say **this.properties.test2** it should show me **One(text)** rather than this.properties.test2 as 1(Key)

please suggest me, thank you in advance.

**Comment by andrewconnell** [comment]
That's how all dropdown selectors have worked for the longest time (.NET, JS, etc)... the text field is always used for presentation, not programmatic use. 

Instead of setting the options the way you're setting them in the example in your OP, set them using a collection, then when you get the key of the selected item, you can look up the matching item in your collection.
