### ISSUE TITLE
iOS/Safari: AADSTS50058

### ISSUE THREAD

**Issue by mirkori** [SharePoint/sp-dev-docs#4363]
### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Users get the Error **AADSTS50058: A silent sign-in request but none of the currently signed in user(s) match the requested login hint.**

![image](https://user-images.githubusercontent.com/46990834/61889274-7094ad80-af05-11e9-88c8-79ef9852026f.png)

#### Expected or Desired Behavior

After a user clicks OK on the alert "To view the information on this page, you need to verify your identity" this error should not appear again after the user verified his identity and reloads the page.

#### Observed Behavior

The popup appears again after the user successfully logged and verified his identity after clicking OK on the alert leading to a login loop on iOS/Safari.

#### Steps to Reproduce

SharePoint Online
SPFx WebPart fetching data from AadHttpClient, SPO search, lists, ms graph.

The issue occurs on our own production and test environment spo tenants and our customers using iOS/Safari and switching between different accounts on different tenants.
To some users this happens a lot. Clearing cache and cookies seems to only temporarily fix the issue.
Sadly we can not reproduce this behaviour consistently and could not reproduce this at all in incognito windows.

**Comment by wpo365** [comment]
I can confirm this issue. We have a webpart which is using MSGraphClient. Everything is working as expected, except if you don't empty the safari cache explicitely on an iPhone or Mac, after a while - say 24 hours but maybe sooner - the user will be presented a popup that tells him/her **To view the information on this page, you need to verify your identity. Click Here**. So far - according to this issue [https://github.com/SharePoint/sp-dev-docs/issues/2685](https://github.com/SharePoint/sp-dev-docs/issues/2685) - this is by design. However, when the user clicks the button / link and after the user is redirected, unfortunately the popup re-appears. And more in general, the work-around also negatively impacts the performance (due to a number of redirects being added to the request). This error can also be reproduced on a Mac when browsing with Safari. In the developer console the following error is logged: **Error: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).**

Even though it says "no user is signed in" it is possible to browse every sharepoint online site without hitting a login screen.

As the webpart is embedded on a sharepoint site, there should be no error saying "no user signed in". The MSGraphClient should handle this error internally by initiating all steps necessary to log in the user again and possible use a refresh token.

**Comment by andrewconnell** [comment]
@lahuey seems you requested people submit a new issue if this was still going on in your comment here https://github.com/SharePoint/sp-dev-docs/issues/2685#issuecomment-513048328 ...

**Comment by lucabandMSFT** [comment]
Folks, just for investigation purposes, can you please check if disabling ITP in Safari would remove the issue? https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari

**Comment by wpo365** [comment]
@lucabandMSFT I have received indeed the same request from Microsoft Premier Support. I will try on Monday when I have the necessary devices to test again available. Having said that, is it really a solution to require your users to go into their settings and make changes?

**Comment by NathanBCE** [comment]
We are also seeing this issue on Mac and Windows 10.

Mobile devices as well.

**Comment by jagdish-nasit** [comment]
Yes Its working after disabling ITP. But it would be difficult for all users to communicate or alerting user to disable that settings... specifically for top leadership.
