### ISSUE TITLE
Drag and drop not working when opening an empty folder in iframe

### ISSUE THREAD

**Issue by chrisfriz** [SharePoint/sp-dev-docs#4525]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Drag and drop functionality and Upload button should appear even if the folder is empty.

#### Observed Behavior

I am currently developing a solution that uses an IFramePanel to show a folder within a document library in the same site. If the folder is empty the upload button is not present and the drag and drop function is not doing anything. However, if a file or another folder exists within, or if I create one in the folder I'm targeting, the drag and drop functionalitiy works. By browsing to folder directly (without iframe) it will work.

#### Steps to Reproduce

1. Open a folder within a library with no content in an iframe
2. Try to upload a file with drag and drop
3. If a file already exists in the library, or if you create a file or a folder within the folder, the drag and drop functionality and upload button will appear and start working.

**Comment by VesaJuvonen** [comment]
This issue is closed as there has not have been any activity on it within the past 2 months. If the issue is still valid, please submit a new issue with updated details. Sorry for the Inconvenience. We are perform this cleaning operation for all inactive issues in this repository to be able to improve our support model in future.
