### ISSUE TITLE
Navigation in mobile does not apply ".mobile" class name in the body

### ISSUE THREAD

**Issue by keeneyemedia** [SharePoint/sp-dev-docs#4546]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

On a mobile device, when clicking any normal navigation, the `.mobile` class disappears from the `body`.

Similar to #3554, but we aren't using "spfx-navigation". No public solution was posted to that issue.

#### Steps to Reproduce

Create a new site. Add a test page and link to it. Navigate on a mobile device or emulator so you can inspect the body - notice how the `mobile` class disappears from the `body` when you navigate to any pages within the site.

Thanks!

**Comment by GrahamMcMynn** [comment]
Thank you for your submission. This GitHub issue list is targeted only for developer issues. As your issue is related on out-of-the-box capabilities or features, we cannot unfortunately process is through this channel. Please submit your finding using the Tenant administrator support channels in your tenant or using Premier support, if that’s available for you. Sorry for the inconvenience.
