### ISSUE TITLE
SP Online Spfx React-big-calendar not working in IE11: Minified React error #31

### ISSUE THREAD

**Issue by dibpra** [SharePoint/sp-dev-docs#4571]
IE11 browser changing to blank screen after 1/2 sec of page loaded completely. It is working in IE11/Chrome workbench properly.
![ie11blankissue](https://user-images.githubusercontent.com/54761969/64073720-2dc1b480-ccbf-11e9-9e95-377352913964.JPG)
**Error** 
![ie11issue](https://user-images.githubusercontent.com/54761969/64073520-d589b300-ccbc-11e9-95f6-060d98daa042.JPG)

**There is no issue in Chrome browser and working properly.** 

**System Versions:**
React calendar version in package.json: "react-big-calendar": "^0.22.0",
spfx version: 1.9.1

**Added polyfills:**
import "core-js/es6/object";
import "core-js/es7/object";
import "core-js/es6/number";
import "core-js/es6/array";
import "core-js/es6/symbol";
import "core-js/es7/symbol";
import "@pnp/polyfill-ie11";

Imported babel-polyfill also but no luck.

**Comment by andrewconnell** [comment]
Unclear... you say it isn't working in IE11, but then you say it's working in IE11/Chrome. Can you please elaborate?

Verify this component works in IE11 outside of a SharePoint Framework component first... I didn't find anything on that component's project page indicates browser compatibility. Microsoft (and this issue list) isn't going to provide support for a specific 3rd party component not working in SPFx.

Also, suspect your issue is going to be with the polyfills... see #888

**Comment by dibpra** [comment]
Thank you for your reply..
React big calendar was not supporting in IE 11 but i have achieved it using React FullCalendar v4.
