### ISSUE TITLE
Subscribe to SP list changes from spfx extension

### ISSUE THREAD

**Issue by holylander** [SharePoint/sp-dev-docs#4588]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Be able to subscribe to a sharepoint document list changes from a spfx extension

#### Observed Behavior

Can only subscribe from a spfx webpart, when calling 
`    listSubscriptionFactory = new ListSubscriptionFactory(this);`
method request to provide a **webpart** and not a **BaseApplicationCustomizer**

#### Steps to Reproduce

Create a spfx extension and try to subcribe to some sp list

**Comment by CPritch** [comment]
Taken from [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/subscribe-to-list-notifications#get-notified-of-changes-to-documents-stored-in-a-sharepoint-document-library):

```
At this moment, you can subscribe only to changes in SharePoint Document Libraries. If you try to subscribe to changes in SharePoint List, you will get an error.
```

So it seems List subscriptions aren't working currently. We have opted for a timed refresh of data until this feature is released.

**Comment by holylander** [comment]
@CPritch  I know that already ;)

The question I have is **how** I can **subscribe from** an **extension** ( an application customizer ). The existing demo only explains how to subcribe from a webpart. If I use the same procedure from an extension, it just doesn't work.

**Comment by andrewconnell** [comment]
_So I've got good news & bad news_ 😜😜

### The good news: 

The constructor for `ListSubscriptionFactory` takes a single parameter, `BaseComponent`. This is the shared object for web parts & extensions.

This means it's the same code for an extension.

### The bad news:

When looking into this, notice this doesn't work in the latest version of SPFx (v1.9.1) due to a regression. It's bugged #4592. If you are using SPFx v1.8.2, you can use it.

**Comment by andrewconnell** [comment]
Ignore my **bad** news, amateur mistake. The same code for an extension should work.
