### ISSUE TITLE
In ListView WebPart How to Get List Id in command Extension

### ISSUE THREAD

**Issue by vivekagrawal1110** [SharePoint/sp-dev-docs#4687]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
- [ ] Example checked item (*delete this line*)

How to Get Current List Id in Oninit Method?

Please help, Thanks

**Comment by bcameron1231** [comment]
You would grab it from the page context. 

`this.context.pageContext.list.id`

**Comment by tobiaswest83** [comment]
This issue has come up a few times (#1201 & #4238), `this.context.pageContext.list.id` reports back the list id of the page you're on, so using this when your command extension is in a webpart page reports back the ID of the Site Pages library, which is incorrect. 

We're coming up against this issue and there seems to be no documented, or undocumented way to reliably get the list ID for a command extension, which makes building any customisation which relies on the list ID impossible - seems quite a gap to me. 

@patmill, you were quite involved in the discussion in #1201. This thread got quite messy with various different bugs being reported, it then fell by the wayside, Hopefully this will help...in this instance, it's a specific use case, steps to repro are: -

1. Create a new Command Extension
2. Create a basic command to output  `this.context.pageContext.list.id` 
3. Observe the GUID in the console/dialog when you're in a specific list. The ID appears to be correct
4. Observe the GUID in the console/dialog when the command extension is part of a document webpart in a page library, the GUID will be that of the list the current page is hosted on. 

I take @andrewconnell's point that `this.context.pageContext.list.id` isn't wrong, but there's a fairly large gap in not giving the developers the ability to get the GUID of the list a command extension is currently in.

**Comment by tobiaswest83** [comment]
@andrewconnell, should this have been marked as answered? @bcameron1231's answer isn't quite right based on the repro steps & other issues. Should I raise a new bug?

**Comment by andrewconnell** [comment]
Sorry... I guess it wasn't now that I see the nuance of the question. 

However, it does appear like this is covered in #1201. Another issue with the same topic doesn't really help the situation. This is now more of a dupe... we're trying to keep issues consolidated instead of fragmented in multiple places. Just because the discussion on a thread slowed down doesn't mean it's forgotten... that issue is already tracked which means it's in MSFT's tracking system.

So, this was answered, but it's more of a dupe to an existing issue (#1201) so I'm going to mark it as such.
