### ISSUE TITLE
Intermittent error: "Connection to SPO DS failed."

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/sp-dev-docs#4710]
4682
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

This is basically a re-open of ticket #4682, which supposedly was fixed but we've seen the error again.
New tracelog information:
```
Message: Connection to SPO DS failed.
ServerErrorTraceCorrelationId: 47db099f-90f5-1000-c959-83250bca6159
ServerErrorCode: -1
Source: Microsoft.SharePoint.Client.Runtime
StackTrace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Vooruitzicht.Provisioning.Core.SharePointWorker.CreateSite(CreateSiteRequest requestData, ConnectionSettings settings, ILogger log)
   at Vooruitzicht.Provisioning.AzureFunctions.Functions.CreateSite.<DoWorkAsync>d__2.MoveNext()
```

cc: @VesaJuvonen , @advdberg

#### Expected or Desired Behavior
We use SharePoint CSOM and PnP Core C# client side libraries to provision new site collection and configure them. I expect these calls to work.

#### Observed Behavior
Since a week or so, some of our calls fail sometimes with the error message "Connection to SPO DS failed". This may run for hours without a problem, then fail a couple of times and then start working again.

**Comment by VesaJuvonen** [comment]
Thx @YannickRe for reporting and we'll look into this right away. If anyone else is seeing similar issues, please do let us know, so that we can investigate the scale of this. Thanks for the additional information advance.

**Comment by advdberg** [comment]
@YannickRe Haven't seen this issue recently, but the customer which had these kind of issues hasn't been that active in creating new sites as they did before, so I assume that reduces the chance of getting the issue...

**Comment by rubenvw** [comment]
We currently experience the same issue at this moment. We are using a provisioning engine to provision  multiple (communication) sites. Our client is at this moment actively creating new sites.

**Comment by YannickRe** [comment]
@rubenvw thank you for replying, at least I'm not the only one experiencing this.

**Comment by advdberg** [comment]
@YannickRe @VesaJuvonen we have just re-opened the MS ticket (16467790) while we see the same issue appearing again this morning.

**Comment by advdberg** [comment]
@VesaJuvonen For what it's worth, an example of the correlation id
ServerErrorTraceCorrelationId: d82f0c9f-0069-1000-c959-89f2cd951ffc

Will also share this with MS support

**Comment by VesaJuvonen** [comment]
Thanks everyone for the updates. We'd need to have correlation ID and the tenant name where the issue is happening for closer look. You can share that details for example to me by using MS tech community. Thanks for the details advance. 

Also - like seems to be already done, please re-open tickets with official channels as this is not really a dev issue as such... it's just visible in the API as there's a back end connectivity issues, which we need to absolutely fix.

**Comment by VesaJuvonen** [comment]
@rubenvw - please share the correlation ID which you are getting and happy to have a look on the issue. Thx.

**Comment by rubenvw** [comment]
Hi @VesaJuvonen , I am a colleague of @advdberg . You could the correlation ID he has mentioned.

**Comment by DaytaMOD** [comment]
I get this error in PowerShell unless I add the -Wait to the Add-PnPTenantSite command.

**Comment by YannickRe** [comment]
@VesaJuvonen any updates on this?

**Comment by advdberg** [comment]
@YannickRe @VesaJuvonen just got a call from MS support about the ticket we created. There's no support from them anymore on this while all teams who investigated the issue and the corresponding correlations ID's we provided were not able to provide more info or a fix for it. We end up in just retry-ing a couple of times untill the creation succeeds which will hopefully deal with this issue most of the times. It would be nicer if this issue is handled internally and retried without having to implement this when calling the API.

**Comment by VesaJuvonen** [comment]
Just to follow up on this - anyone seeing this anymore or not? There should have been a fix applied on the farm level to fix this, so we should be good, but would like to get your input and confirmation on this.

**Comment by YannickRe** [comment]
We’re not seeing this anymore, but you can be sure I’ll reopen if it reoccurs 😉
Thank you for the follow up and the escalation, I’ll wait for some feedback from the others before I close it.

**Comment by YannickRe** [comment]
No one responded within a week, closing now.
