### ISSUE TITLE
Grammer

### ISSUE THREAD

**Issue by FoldZero** [SharePoint/sp-dev-docs#4712]
I dont understand this sentence;
// Note that the web.Update() does not trigger a request to the server
// because the client library until ExecuteQuery() is called. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306bdabe-3314-0f4d-9199-1be256fd58de
* Version Independent ID: e99a275e-bd93-ef8c-6fe6-ff81065e5f42
* Content: [Complete basic operations using SharePoint client library code](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code)
* Content Source: [docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dennis-LZ** [comment]
@FoldZero The sentence mean, if we update the web properties using Client Side Object Model(CSOM) C#, the web.Update() does not send a request to SharePoint server(because the code run in client side), we need use context.ExecuteQuery() to complete this update process. 

We can debug the code and use [Fiddler](https://www.telerik.com/fiddler) to monitor this process.

**Comment by andrewconnell** [comment]
Wording is a little messed up... will add that to get fixed, but @Dennis-LZ's reply is correct.
