### ISSUE TITLE
Partial navigation not reload the page content in targeted release tenant when change querystring value in the URL

### ISSUE THREAD

**Issue by sortegamartin** [SharePoint/sp-dev-docs#4717]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

For a few days, when a [partial navigation](https://github.com/estruyf/spfx-navigation) is done in a "targeted release" tenant, the content of the page is not reloaded when only the querystring of the url changes. The same if it currently works in a "standard" tenant, that is, reloads the content of the page.

Surely something related to routing has been changed internally. I think that some type check has been added: if it is the same page, do not reload the page content

This is a critical change for our clients because we have webparts that update their information based on the querystring of the url.

We would like to know if this change will be deployed in the "standard" tenants or not. In case of yes, we would need an event in the webparts to know that a partial navigation has been done, just like the this.context.application.navigatedEvent that the ApplicationCustomizer have.

Please we would need an answer on this topic.

Thank you!

**Comment by xdelgado** [comment]
Same is happening to me when using a page with query string parameters. Previously the page was reloaded and the web parts update, now this behavior stops working.

**Comment by cmasonrp** [comment]
We are experiencing the same issue as well but on a standard tenant

**Comment by paulwillen** [comment]
I've got the same issue on a dev-tenant. Need some further investigation if it's also an issue on our production tenant, but is there any update on this issue?

**Comment by kmprasad4u** [comment]
We are also having the same issue (in Production Tenant) with custom web parts even with different page names.  

We have created pages based on template, as well as using Copy of this page features, and the methods (constructor, oninit, render, dispose) methods of the custom webpart in the page is not getting called when navigating from one page to another page that is created with the same template / copy.  OOTB webparts (like Hero, Text, Button) seems NOT to have such issue. 

We had seen this issue earlier with Hero / Button web parts, but it got fixed after a while. Now the issue is with custom webparts alone. 

On a side note, the render method of custom webpart is not getting called when creating a page from page template

**Comment by kmprasad4u** [comment]
We are also having the same issue (in Production Tenant) with custom web parts even with different page names.

We have created pages based on template, as well as using Copy of this page features, and the methods (constructor, oninit, render, dispose) methods of the custom webpart in the page is not getting called when navigating from one page to another page that is created with the same template / copy. OOTB webparts (like Hero, Text, Button) seems NOT to have such issue.

PS: We had seen this issue earlier with Hero / Button web parts, but it got fixed after a while.
