### ISSUE TITLE
Default Save Location?

### ISSUE THREAD

**Issue by PrinceJasbo** [SharePoint/sp-dev-docs#4759]
Hi, 

I left this tool running on a large Site, I came back on the command line window had closed, nothing open in Excel.

Is there a default save location?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9d928d-fab5-99af-105f-86cb0520dcfa
* Version Independent ID: ded494e8-1cc3-04bb-fec9-1c44e7231d06
* Content: [The SharePoint modernization scanner](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner#feedback)
* Content Source: [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/transform/modernize-scanner.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by jansenbe** [comment]
Hi @princeJasbo,

When the tool runs in creates a folder in the folder where the .exe was and all reports are created in that folder. The tool will not automatically open the created reports.

**Comment by Jabeenbegums** [comment]
Hi @jansenbe ,

We ran the tool and the tool is struck at **Launching Wizard** screen. Could you please lets us know if it is a bug?
![Wizard](https://user-images.githubusercontent.com/10357406/74109487-bcdecc80-4b7b-11ea-80a3-e2a17f056f7e.PNG)

**Comment by jansenbe** [comment]
Sometimes in indeed takes a while for the wizard to show...I'm experiencing similar things and haven't pinpointed the root cause. I'm suspecting Anti-virus soft to cause the delay in loading as on machines with no specific AV software (like servers) it loads without delay. Can try and wait longer or possibly create an exclusion in your AV soft for this .exe and see if that resolves the issue?

**Comment by B3J** [comment]
No folder was created in the folder were the .exe was, cannot find the repot... annoying
