### ISSUE TITLE
Difference version of this app already installed in OnPrem (SP 2019)

### ISSUE THREAD

**Issue by shahulcode** [SharePoint/sp-dev-docs#4779]
I have created a SPFx extension and deployed it to the app catalog in On-Prem (SP 2019). For some of the time, when I install the app to site it throws an error "**Difference version of this app already installed**", but I did not install the app to that erroring site. When i installing the same app to different site collection it was installing. I have checked the Recycle bin (Admin, Secondary recycle bin) also. There is no reference to my app in the site. Can anyone please help!!!!

**Comment by shahulcode** [comment]
> I have created a SPFx extension and deployed it to the app catalog in On-Prem (SP 2019). For some of the time, when I install the app to site it throws an error "**Difference version of this app already installed**", but I did not install the app to that erroring site. When i installing the same app to different site collection it was installing. I have checked the Recycle bin (Admin, Secondary recycle bin) also. There is no reference to my app in the site. Can anyone please help!!!!

**Comment by shahulcode** [comment]
Is there any update on this!!!!

**Comment by johnguy0** [comment]
Are there repro steps? More details about the SPFx version being used?

**Comment by shahulcode** [comment]
Steps to Reproduce:
1) Create site with 3 Level subsites ex. Site A -> Subsite A-1 -> Subsite A-1-1
2) Create SPFx app and deploy to farm (App catalog) and add to site (Site A and Subsite A-1)
3) Change SPFx some code  or files (don't change the version)
4) Redeploy App to App catalog
5) Add app to the Subsite A-1-1 (Throws error "**Difference version of this app already installed**"), If it is success change the code(don't change the version) redeploy.

SPFx Libraries Version : ~1.4.1

**Comment by GrahamMcMynn** [comment]
@shahulcode  - The issue you are seeing is because what you are doing is not supported.  This will happen in SharePoint online as well.  When you modify your package you MUST update the version number.  When you install a package it creates a hash of the package and saves it as a fingerprint.  If this fingerprint changes but the version has not, and you have previously installed the solution already on that site collection (why this only happens using multiple webs), you will receive this error.  This can be easily fixed by just modifying the version number when updating a package.

**Comment by shahulcode** [comment]
if i doing so, should i need to update the app version all sites?
