### ISSUE TITLE
"Using this principal in your application without using the PnP Sites Core library"

### ISSUE THREAD

**Issue by vaderj** [SharePoint/sp-dev-docs#4811]
If the example given is WITHOUT the PnP library, where does the TokenHelper come from?

such as TokenHelper.GetRealmFromTargetUrl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3017a-6d6c-237f-fc57-94247a8f7bf6
* Version Independent ID: 93413445-18fa-9245-ea64-1c1d789dce1e
* Content: [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)
* Content Source: [docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/security-apponly-azureacs.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Please see the bottom of the documentation in purple. It tells you how to use the TokenHelper class.

![image](https://user-images.githubusercontent.com/7944457/67422254-4ea3d900-f58f-11e9-8d42-c14609d982dd.png)

**Comment by Ofer-Gal** [comment]
I installed AppForSharePointOnlineWebToolkit 3.1.5 but did not get TokenHelper.cs 
What am I doing wrong?

**Comment by bcameron1231** [comment]
@Ofer-Gal I just created a new solution, installed the package and I have TokenHelper.  By chance is your application .NET core?

**Comment by Ofer-Gal** [comment]
It is  .NET core 2.2
Is there a version for that too?

**Comment by bcameron1231** [comment]
Not from Microsoft. The CSOM SDK is built on .NET Framework, so they don't work in .NET core.

There is an Open Source Pnp Sample, with the TokenHelper ported over that you  could try.... It's been a while since it's been used and probably isn't maintained, but might get you where you need to go.

https://github.com/SharePoint/PnP/tree/master/Solutions/AspNetCore.Authentication

**Comment by Ofer-Gal** [comment]
I keep getting warnings:
Warning	NU1701	Package 'Microsoft.SharePointOnline.CSOM 16.1.19404.12000' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.2'. 
Both in Core 2.2 project and in .NET 4.6.1. Doesn't it tell you you should be in Core 2.2?
OfficeDevPnP.Core.AuthenticationManager compiles in Core 2.2 but errors at runtime.
I tried your suggestion but it did not work in Core 2.2
Welcome back to DLL hell 👎 Deja vu from the '90s

**Comment by bcameron1231** [comment]
You could try and submit an issue on the PnP issues list and see if they can help. Unfortunately, what you are trying to do isn't technically supported at this time.

**Comment by Ofer-Gal** [comment]
I did with a few other guys.
