### ISSUE TITLE
Sync SPFx solution package with extensions and webparts to Teams

### ISSUE THREAD

**Issue by NicolajHedeager** [SharePoint/sp-dev-docs#4817]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi,

I have an existing SPFx solution package which contains both WebParts and Extensions. Now I want the WebParts to be avaiable in Teams.
I have added TeamsTab to supportedHosts in the manifest for my WebParts and packaged the solution again. After I update the package in the tenant app catalog in SharePoint, the "Sync to Teams" button becomes available. When I press the button the following error is returned:

{"error":{"code":"-1, Microsoft.SharePoint.Client.UnknownError","message":{"lang":"en-US","value":"Unknown Error"}}}

I found that if I remove the Extensions from my solution package and package it again, the "Sync to Teams" button works and the WebParts becomes available in Teams.

Is it by design that Extensions is not allowed in the SPFx solution package when you sync the package to teams? I have'nt been able to find documentation for this.

**Comment by seriewe** [comment]
The same behavior on my tenant. As soon as I remove all extensions the sync to teams works. Otherwise I get a 500 error

`VM6329:31 POST https://mcag03.sharepoint.com/sites/apps/_api/web/tenantappcatalog/SyncSolutionToTeams 500`

unfortunately no further information.

**Comment by johnguy0** [comment]
This is currently by design. We do have a backlog item to eventually enable the scenario where a solution could have a mix of Teams components and other components. 

As your submission is an enhancement on existing feature or a feature request, we cannot process it through this channel. Please submit your feedback and suggestion using UserVoice, so we can take your suggestion into account in our future planning. Thank you for your input in advance.
