### ISSUE TITLE
PUT/DELETE requests using aadHttpClient is nowhere documented

### ISSUE THREAD

**Issue by andreschmid8** [SharePoint/sp-dev-docs#4846]
I have to to PUT and DELETE requests to my custom api.
I know, that I can do that with the fetch() function.

I am allready using .get like following (example code):
`  this.props.context.aadHttpClientFactory
    .getClient('https://graph.microsoft.com')
    .then((client: AadHttpClient) => {
      // Search for the users with givenName, surname, or displayName equal to the searchFor value
      return client
        .get( 
          `https://graph.microsoft.com/v1.0/users?$select=displayName,mail,userPrincipalName&$filter=(givenName%20eq%20'${escape(this.state.searchFor)}')%20or%20(surname%20eq%20'${escape(this.state.searchFor)}')%20or%20(displayName%20eq%20'${escape(this.state.searchFor)}')`,
          AadHttpClient.configurations.v1
        );
    })`

But how would I use fetch or post instead of .get()?
I mean, how do I have to pass the body parameters?

**Comment by andrewconnell** [comment]
The HTTP-based APIs in SPFx are all based on the browser **fetch** API. This has three methods: `get()`, `post()` and `fetch()`. The `fetch()` method allows you to do anything... the `post()` method automatically uses the HTTP POST method.

They are all based on the [SpHttpClient](https://docs.microsoft.com/en-us/javascript/api/sp-http/httpclient?view=sp-typescript-latest) object, which is documented.

All three methods have three parameters, the last one being optional. That lets you customize anything... this is the [IHttpClientOptions](https://docs.microsoft.com/en-us/javascript/api/sp-http/ihttpclientoptions?view=sp-typescript-latest) interface. It's not documented on the SPFx docs because it's not necessary to duplicate what's already documented in the fetch API.

This object has properties for headers to set, the body, and more.

**Comment by andreschmid8** [comment]
there is not documented, how I have to pass the paramethers.
I only get following from my editor:
(method) AadHttpClient.fetch(url: string, configuration: AadHttpClientConfiguration, options: IHttpClientOptions): Promise<HttpClientResponse>
Performs a REST service call.

@remarks — Although the AadHttpClient subclass adds additional enhancements, the parameters and semantics for HttpClient.fetch() are essentially the same as the WHATWG API standard that is documented here: https://fetch.spec.whatwg.org/

@param url — The endpoint URL that fetch will be called on.

@param configuration — Determines the default behavior of HttpClient; normally this should be the latest version number from HttpClientConfigurations.

@param options — Additional options that affect the request.

@returns — A promise that will return the result.




So far so good... but what is AadHttpClientConfiguration?? The [documentation ](https://docs.microsoft.com/en-us/javascript/api/sp-http/aadhttpclientconfiguration?view=sp-typescript-latest) doesn'thelp me alot here. 
Same with options...
Where do I have to pass my http method, the body etc?

**Comment by andrewconnell** [comment]
@andreschmid8 said: 
> what is AadHttpClientConfiguration

It sets the default configuration of the client, like setting headers such as `accept:application/json` and others. You will always use `AadHttpClientConfiguration.configuration.v1` because that's the only one available.

> Where do I have to pass my http method, the body etc?

That's the `options` parameter. If you look at the definition of it's type `IHttpClientOptions`, you'll see it has properties for `body` (a string), `headers` (object of name-value pairs) and `method` (a string).
