### ISSUE TITLE
Workbench prioritises deployed version when package.json version >= 1

### ISSUE THREAD

**Issue by JakeStanger** [SharePoint/sp-dev-docs#4862]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

All the relevant JavaScript files for the app and its strings are requested from localhost when adding the app to the Workbench, no matter the contents of `package.json`.

#### Observed Behavior

As soon as the version field in `package.json` is greater than or equal to `1.0.0`, the only file ever requested is `/temp/manifest.js`

#### Steps to Reproduce

This is possibly the most bizzare bug I have ever encountered. I have managed to replicate it on multiple machines and with multiple apps across multiple tenants (both TR and SR). All testing was done with SPFx 1.9.1.

- Gulp serve an app where the version field in `package.json` is < `1.0.0`
- Add the app to a workbench on a site where the app is installed
- Notice the files are correctly requested:

```
  Request: '/temp/manifests.js'
  Request: '/lib/webparts/admInfoCentre/loc/en-us.js'
  Request: '/node_modules/@adm/persona/lib/loc/en_us.js'
  Request: '/node_modules/@adm/webpart-library/lib/admWebpartLibrary/loc/en-us.js'
  Request: '/node_modules/@pnp/spfx-controls-react/lib/loc/en-us.js'
  Request: '/node_modules/@pnp/spfx-property-controls/lib/loc/en-us.js'
  Request: '/dist/adm-info-centre-web-part.js'
```

- Stop serving the app
- Edit the version field in `package.json` to be anything >= `1.0.0`
- Gulp serve the app again and refresh the workbench
- Notice the JS files for the app are never requested
```
 Request: '/temp/manifests.js'
```

- Decrease the version number again, re-serve, refresh and notice the files are once again requested.

Completing these steps on a site where the app is **not** installed works as expected. It seems the Workbench is incorrectly using the deployed version of an app rather than the served version.

The version number being set in `package.json` is pulled through into `/temp/manifests.json` correctly.

I have also tested changing the `name` field. This does not cause the problem.

It's possibly also worth noting that I have never changed the `package.json` version number for a **deployed** version of an app. It's possible changing this to > 1 could also cause issues...

It also seems apps that had their version set to >= `1.0.0` at some point in the past are not affected.

**Comment by CPritch** [comment]
If anyone has this issue, here's a workaround until the it's fixed. Stick this in your `gulpfile` where appropriate.

```JS
const fs = require('fs-extra');

build.setConfig({
  onTaskEnd: async (taskName) => {
    if (taskName == "write-manifests") {
      const pkg = await fs.readJson('./package.json');
      let manifests = await fs.readFile('./temp/manifests.js').then(b => b.toString());
      manifests = manifests.replace(`"version": "${pkg.version}"`, '"version": "0.0.1"');
      return fs.writeFile('./temp/manifests.js', manifests);
    }
  }
});
```

**Comment by andrewconnell** [comment]
@JakeStanger said
> It's possibly also worth noting that I have never changed the package.json version number for a deployed version of an app. It's possible changing this to > 1 could also cause issues...

That could be part of your problem. By default, & on build, the component version (not the solution, but the specific component) is set from the **package.json** file's `version` property. This is stated in the comments of a component's manifest file's `version` property:

```json
// The "*" signifies that the version should be taken from the package.json
"version": "*",
```

Note the above (pulling the version from package.json), *only* happens at build time, not runtime.

Therefore, what you have previously deployed is one component version, while what you are trying to use in the workbench is a different version, and things are all confused. This seems to be validated by what @CPritch posted as a workaround.

Furthermore, testing a SPFx solution on the hosted workbench in the same site where a previous version was installed (thus you have two instances of the same with the same ID thing installed in the same context) has always caused issues. This is because the workbench is showing you a mashup of multiple **manifest.js** files: the SharePoint generated one for system stuff, the SharePoint generated one for deployed / installed stuff in the tenant+site collection & the one served up by localhost. Thus, you've got two entries for the same thing, within the combined **manifest.js**.

If the above is correct, it isn't surprising to me things are behaving screwy... but I'm not sure that means this is a bug. Version conflicts would not surprisingly cause issues...

**Comment by JakeStanger** [comment]
I'm *kind of* following but there's still a few oddities.

You might be onto something with the version mismatching, but if that is an issue it's only part of the problem. I should absolutely stress that the workbench will serve *any* version number in `package.json` less than 1 (`0.0.1` works, `0.0.2` works, `0.1.1` works, `0.9.9` works...), while *any* version greater than or equal to `1.0.0` breaks (`1.0.0`, `1.0.1`, `1.1.1`, `2.0.1`, `3.3.4`, you get the point...)

To quote myself:
> It's possibly also worth noting that I have never changed the package.json version number for a deployed version of an app. It's possible changing this to > 1 could also cause issues...

I phrased this poorly. I have, in the past, updated `package.json` version numbers along-side the `package-solution.json` version numbers as I've deployed apps. What I meant by this is I have not *deployed* an app after increasing its `package.json` version that is *specifically* having this issue on the workbench. If it is having this issue on the workbench, it could possibly result in the same issue when deployed.

If you do not believe this to be a bug, then what is the correct procedure for correcting this (ie so I can keep package.json and package-solution.json version numbers equal)?

**Comment by andrewconnell** [comment]
First of all, my general response is 🤷‍♂️. I still am of the opinion of my theory above. 

But I'll throw these things in as they may help pull things out of the weeds and shed some light on the situation...

- the version in **package.json** is used as the component version by default, which is listed in the **\*.manifest.json** file... not the **package-solution.json**... the latter is for the package/solution version
- the version numbers in components & packages mean _absolutely nothing to SPFx_... they are used for documentation only... with one exception...
- the exception is that the increase of a version in the solution (defined in **package-solution.json**) tells SharePoint to activate/reactivate features on the solution when the solution is upgraded
  - IOW, the change in the package version is what triggers "there's a new version of this app available" in the installed instances of the app... this is the only process that will reactivate a feature or activate newly added features
  - any change in the component version within a solution is irrelevant... when a new SP package is deployed, the JS files are updated & overwritten

In general, I've found trying to test SPFx components within a package in a site collection where a prior instance of the same package has been deployed either via tenant/spsite app catalog, to be problematic due to my above comments. Thus, my personal guidance is to always test new versions of already deployed packages in a different environment. Otherwise, YMMV, which is what I see is going on with your experience.

It's because of this, that as it stands, I don't see anything that's saying this is a bug... 🤷‍♂️

**Comment by JakeStanger** [comment]
I've just taken one of my packages which I initially deployed at `0.0.0.1` in `package-solution` (with `0.0.1` in the `package.json), and where I've been upping the package-solution version but never the package.json version (and the manifest version has always remained `*`) and upped the version number to match the package-solution version (now `1.40.3`).

Initially in the workbench, this still did not work as expected. I then re-deployed the app, and the workbench sprung into life.

A lot of what you said is very useful but I still feel like something is slightly off. The workbench obviously definitely cares about the manifest version number, and it feels like the logic determining which version of a package to use gets muddled when the deployed version is <1. This may explain why any local version <1 worked but any >=1 did not.

**Comment by johnguy0** [comment]
@JakeStanger Thanks for all the information. Sounds like you and @andrewconnell have already pieced together why this doesn't work. This is unfortunately by design. Our loading logic uses semantic versioning from the manifest to determine if modules loaded are compatible, which is why there are incompatibilities between an installed < 1.0.0 solution and a served > 1.0.0 solution. 

Using a different site where the solution is not installed is the easiest workaround. We'd be happy to take a user voice request around this requirement, but it's not something we support currently.
