### ISSUE TITLE
How to load arbitrary UMD module

### ISSUE THREAD

**Issue by johannes-z** [SharePoint/sp-dev-docs#4873]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

I'm trying to load an UMD module like this:

```ts
SPComponentLoader.loadScript('https://<my.sharepoint>/sites/<site>/Style%20Library/<file>.umd.min.js').then(console.log)
```

This file has a dependency to `vue`, which I also added to `config.json` under `externals`:

```json
  "externals": {
    "vue": {
      "path": "https://cdn.jsdelivr.net/npm/vue@2.6.0",
      "globalName": "vue"
    }
  }
```

#### Observed Behavior

I get this error:

```
VM2887:5 Uncaught (in promise) Error: Error loading https://relative-path.invalid/vue as "vue" from https://<my.sharepoint>/sites/<site>/Style%20Library/<file>.umd.min.js
	Unable to load script https://relative-path.invalid/vue
    at HTMLScriptElement.p (eval at <anonymous> (sp-webpart-workbench-assembly_de-de_1e9fe286bc7e801fceddfb0a3b3517b8.js:20), <anonymous>:5:377)
```

**Comment by johannes-z** [comment]
I tried a simple test, using `SPComponentLoader.loadScript...`:

```js
;(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define(['vue'], factory);
  } else if (typeof exports === "object") {
    module.exports = factory();
  } else {
    root.c4_form__c4itworkdocuments = factory(root.$, root._);
  }
}(this, function (Vue) {
  console.log(Vue);
  var a = 1
  var b = 3
  function c (a) {
    console.log(a, 5);
  }
  c(a)

  return {
    a, b, c
  };
}));
```

Loading it works fine until I add `define(['vue']...)`. I t hen get the error message in my original post.

I also tried registering `vue` (`externals` seems to be ignored by the `SPComponentLoader`) like this:

```js
window['System'].register('vue', ['https://cdn.jsdelivr.net/npm/vue@2.6.0'])
```

It circumvents the error above, but I get a new error:
VM5802:5 Uncaught (in promise) TypeError: Error loading https://<my.sharepoint>/sites/<site>/Style%20Library/<file>.umd.min.js
	Cannot read property 'call' of undefined

**Comment by patmill** [comment]
How are you loading the vue library?

**Comment by johannes-z** [comment]
@patmill well, this is where I'm stuck. I tried loading it in the webpart using `require('vue')` or even with a conventional `import Vue from 'vue'` - which works, but the UMD module still *requires* `vue` which fails because it's not registered in SystemJS as `https://relative-path.invalid/vue` but as `https://component-invalid..../GUID-VERSION/vue`.

I have the same problem for libraries I want to register globally, i.e. [`vuetifyjs`](https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js). It also has a `require`-dependency on `vue` which would fail like the simple example from above.

I have also tried using the `SPComponentLoader` in various ways, and even tried adding entries to `System.meta` (because `System.config` is disabled by SPFx). Nothing worked.

**Comment by andrewconnell** [comment]
Unclear as to what exactly the problem is that you're having. Are you just trying to create a SPFx project that leverages Vue? If so, check this sample out: 

https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/vuejs-todo-single-file-component

Or check out how the project is created using the PnP generator:

https://pnp.github.io/generator-spfx

**Comment by johannes-z** [comment]
@andrewconnell No, vue has nothing to do with it, it just serves as an example. It seems impossible to load an UMD/AMD module that has *named* dependencies. It currently doesn't seem possible to register a path for a name, e.g. a `unpkg..`-reference for `vue` (or any other library).

**Comment by andrewconnell** [comment]
I'm confused then... why are you using Vue as an example? I read the above as you were saying it's impossible to use Vue (as an example) in a web part due to named dependencies, but that's not the case. You can do that. 

In your initial post you're mixing SPComponentLoader & the externals... one (**config.json**'s `externals` declarations) happens prior to loading your web part, the other (`SPComponentLoader`) happens at runtime. The name you're defining in `externals` has nothing to do with naming the component outside of the build process; it's *only* used by webpack during the bundling process.

So, I'm not clear what the problem is without an example... maybe if you created a public GH repo with a  repro it would help articulate the problem you're having?

**Comment by johannes-z** [comment]
@andrewconnell Because I'm using it in my current project.
I couldn't, for example load this library [vuetify](https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js), because its dependency `vue` can't be resolved. And I found no possiblity in spfx to specific how to load `vue`. In `requirejs` I would do something like this:

```
{
  vue: 'https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue',
  vuetify: 'https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify'
}
//...

require(['Vuetify'], function (Vuetify) { ... })
```

How do I do that in spfx? Using `SPComponentLoader` throws the error above:

```
// works
SPComponentLoader.loadScript('https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue', {
  globalExportsName: 'Vue'
})
// doesn't work, because vue can't be found
SPComponentLoader.loadScript('https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify')
```

**Comment by olehansen** [comment]
I think there is 2 solutions to your problem.

One is to define vue with a name, this works but I don't think it is the recommended solution and you have to declare the define function yourself, because I could not find a support api / module for this in spfx:

```
const vue = await SPComponentLoader.loadScript('https://cdn.jsdelivr.net/npm/vue');
define("vue", [], () => vue);
const` vuetify = await SPComponentLoader.loadScript('https://cdn.jsdelivr.net/npm/vuetify');
```

Recommended solution is likely to add it to config.json as a externals

```
"externals": {
       "vue": "https://cdn.jsdelivr.net/npm/vue",
        "vuetify": https://cdn.jsdelivr.net/npm/vuetify"
}
```
path and globalName is not for amd modules, and will in some versions of sharepoint not load the module correct.
....

And then use like import Vue from 'vue'. Remember npm install vue and vuetify or declare a module for them.

Hopes this help

**Comment by andrewconnell** [comment]
Personally I wouldn't do it with the component loader... that's going to happen at runtime when you web part loads. I'd make them required BEFORE the web part bundle is loaded.

I'm not as familiar with Vue, so I can't speak too much to it, but what you're trying to do from what I understand is ensure one is loaded before the other. This is common when it comes to jQuery & plugins. For example, you'd do it like this with jquery:

**config.json**
```json
"externals": {
  "jquery": {
    "path": "https://code.jquery.com/jquery-1.12.4.min.js",
    "globalName": "jQuery"
  },
  "datatables": {
    "path": "https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js",
    "globalName": "jQuery",
    "globalDependencies": [
      "jquery"
    ]
  }
},
```

Notice that jQuery, while it's a module, is referenced as a non-module. This is so we can give it a name. The values of the keys in the key:value pair is only used by webpack when it checks to see if it should bundle it. So... I'd guess it would be something like this (again, not 100% sure as I'm not familiar with Vue):

```json
"externals": {
  "vue": {
    "path": "https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js",
    "globalName": "vue"
  },
  "vuetify": {
    "path": "https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js",
    "globalDependencies": "vue",
    "globalName": "vuetify"
},
```
