### ISSUE TITLE
Why Can't I have a Group for content types and site columns in Site Script

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/sp-dev-docs#4893]
#### Category
- [ X] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea
#### Expected or Desired Behavior

When using "Get-SPOSiteScriptFromWeb  -IncludedLists xx" I expected the resulting site columns and content types, will keep the groups they belong to.

#### Observed Behavior

Turns out there is no "Group" definition in the schema. 
The applied design's  Site Columns and Content types do not have the group the original had.

**Comment by bcameron1231** [comment]
The reason it's not being extracted/included is because the JSON schema for Site Designs and Site Scripts doesn't include **Group** for **CreatContentType** action. 

This is an enhancement, so I would head over to UserVoice and help upvote this!
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/36320569-enhance-createcontenttype-with-group-property-to-d
