### ISSUE TITLE
Group Name and Employee column not available .

### ISSUE THREAD

**Issue by djlotus** [SharePoint/sp-dev-docs#4898]
Under "Create the custom content type" step 5, Employee Orientation is not available in the drop-down box for Group Name.
Also, The column name Employee is not a valid column name.
I have followed all the steps up until here and have tried with the GitHub project as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c171d98-9191-ec66-8332-b096e9c78744
* Version Independent ID: 5b6c1748-b125-1cca-cfe0-209b3c1e07c9
* Content: [Add a custom content type to a SharePoint-hosted SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-custom-content-type-to-a-sharepoint-hosted-sharepoint-add-in#feedback)
* Content Source: [docs/sp-add-ins/add-a-custom-content-type-to-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/add-a-custom-content-type-to-a-sharepoint-hosted-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Dennis-LZ** [comment]
In steps 5, we can enter the "Employee Orientation" in the drop-down box for the Group Name, if your site don't have this content type group, we can't see in this drop-down box.

The column name "Employee" is not a valid column name, because you can't create site column in the add-in, please add custom site column before create content type.

![Untitled](https://user-images.githubusercontent.com/55479607/68820947-d29d3c80-06c7-11ea-9cfe-6592eb7510d4.png)
