### ISSUE TITLE
Not supported: Site Collection App Catalog

### ISSUE THREAD

**Issue by TashunkoWitko** [SharePoint/sp-dev-docs#4967]
Library components are not supported when solution is deployed using site collection app catalog

Which solution exactly? 

- Do you mean that if the library solution is deployed to the site collection app catalog it will not work? (...which makes sense, one per tenant)
- Do you mean that if another solution is deployed to the site collection app catalog and wants to consume the library this is not supported?

Maybe this could be written more clearly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b431da26-3a26-bab5-1af4-a151d9e50f2e
* Version Independent ID: 50656bd9-3514-ae39-0805-0927d30e4355
* Content: [Using library component type in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview#feedback)
* Content Source: [docs/spfx/library-component-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/library-component-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
The first understanding is correct. Library Componements needs to be deployed in Tenant App Catalog instead of Site Collection Level App Catalog.
When creating the solution, The 4th option will be Yes:
![LWebPart-1024x634](https://user-images.githubusercontent.com/28797671/70222177-95871000-1784-11ea-97fa-043922f98e08.png)

Reference:

[Building my first Library component using SharePoint Framework](http://jenkinsblogs.com/2019/07/25/building-my-first-library-component-using-sharepoint-framework/)
