### ISSUE TITLE
Azure CDN - related error while loading the web parts.

### ISSUE THREAD

**Issue by ahamedfazil** [SharePoint/sp-dev-docs#5052]
Hi,
I have following error while loading SPFx webpart, I have some resources in Azure CDN but it fails to load the URL. It happens for few users not for everyone. I checked from Azure CDN side and it looks fine. Not sure what's causing the issue in SPFx webpart.

> SPLoaderError.loadComponentError]:
> ***Failed to load component "5xxx-xxx-xxx-xx-5" (xxxxxWebPart). Original error: ***Failed to load URL 'https://xxxxxxxxx.azureedge.net/xxxxxxx/xxxxxxxx.min.js' for resource 'jquery' in component '5xxx-xxx-xxx-xx-5' (xxxxxWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

![image](https://user-images.githubusercontent.com/21005625/71349992-91bf0000-2570-11ea-931d-3c9e4c6b9da6.png)

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Any suggestion on how I can resolve this??

**Comment by andrewconnell** [comment]
Have you verified the file is present in the CDN and accessible by everyone?

Have you isolated it to specific users, browsers, environments? 

Do you have any special content restrictions on the CDN? For the users having issues, have you had them try to load the file directly using the URL to verify they can access it? Because it's a client-side request, if they can access it directly via the browser, SPFx's loader should be able to load it.

**Comment by ahamedfazil** [comment]
Yes, the file is available in CDN and the user can access it directly using the CDN url.
Actually this issue not only happens to Azure CDN but also publiccdn (I have some other webparts in the page which doesn't have any content in Azure CDN). 

After page refresh by a user, everything looks fine (all webparts load perfectly). This mostly happens when the users opens the site for the first time of that day and it doesn't happen to all the user but some.

**Comment by andrewconnell** [comment]
OK... so it's not an issue with accessing the file... sounds like things work once the file has been cached on the user's machine. 

Is it your web part bundle that's not loading, or a dependency?

In your OP it looks like it might be jquery... is that correct, or is it all JS files (including the component bundle)? If it's the dependencies, how are you loading them in your component? Do you have the right dependency chain setup? 

_I'm thinking this sounds like you might not and the web part bundle is loading before all dependencies are loaded on the page. It works the 2nd time because they are cached and they don't need to wait for them to load._

**Comment by ahamedfazil** [comment]
This issue also happens for other webparts which doesn't have any dependency. Ya, you are right I was referring to jquery and its referred in config/config.json -> "externals". The below attached screenshot is from another webpart. It seems webpart bundle itself not loading
![somethingwentwr](https://user-images.githubusercontent.com/21005625/72533890-34b82080-3876-11ea-8cbb-e157ffd5ce0d.png)

**Comment by ahamedfazil** [comment]
Also we noticed this happens to the user in particular geo location.

**Comment by andrewconnell** [comment]
Being no one else is reporting CDN issues like this, I'd open a ticket within your M365 portal. You say this happens to users in specific geo... that sounds like there are networking/connectivity issues there.
