### ISSUE TITLE
Adding a new column in modern list view maps to wrong type

### ISSUE THREAD

**Issue by KEMiCZA** [SharePoint/sp-dev-docs#5060]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Selecting the **hyperlink** column type when adding a new column (in modern list view) should be reflected in the side pannel to add a new column of type **hyperlink**.

#### Observed Behavior

The type **picture** is selected as default instead of **hyperlink**. 

#### Steps to Reproduce

- Go to a modern list view 
- Click the "+ Add column v" button in the header of the view and Select the **hyperlink** type
![image](https://user-images.githubusercontent.com/3862716/71468527-93820100-27c6-11ea-8f65-2a5469a8063b.png) 
- Side pannel will pop-out and will show that the type **Picture** is selected
![image](https://user-images.githubusercontent.com/3862716/71468457-4b62de80-27c6-11ea-9a5e-f5d35f37f7cf.png)

This bug is unforgiveable. I will carry this scar for the rest of my life and hope my life can only go uphill from now.

Kind regards

**Comment by Jerry0527** [comment]
This shoule be a by design action in SharePoint Online, as the field type is "Picture or Hyperlink“:
![QQ截图20200101161050](https://user-images.githubusercontent.com/28797671/71639468-081adb00-2cb2-11ea-8202-7ff854803ba3.png)
![QQ截图20200101161633](https://user-images.githubusercontent.com/28797671/71639470-1832ba80-2cb2-11ea-9760-324bcf9af03e.png)

Now you can select the hyperlink instead of default picture format, if you want the default format as hyperlink rather than Picture, I suggest you could submit a Service Request for this.
