### ISSUE TITLE
Helloworld gulp trust-dev-cert does not work in Edge but does in IE when testing in SharePoint tenant

### ISSUE THREAD

**Issue by timleveritt** [SharePoint/sp-dev-docs#5065]
Category
- [ ] Question
- [ ] Typo
- [x ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

After working through the [Build your first SharePoint client-side webpart (Helloworld part 1)](https://docs.microsoft.com/en-au/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part) in Edge (41.16299.1004.0) I was able to successfully open the webpart in localhost:4321 and then modify the webpart and retest in localhost:4321. However, when I tried to use the webpart while gulp serve was processing in the https://<tenant>.sharepoint.com/_layouts/15/workbench.aspx it was not available. The following message was always presented:

> Warning
> 
> Your web part will not appear in the toolbox. Please make sure "gulp serve" is running in a web part project. Please refresh the page once "gulp serve" is running.
> Click here for more information.
> 

Looks like it's the same issue as https://github.com/SharePoint/sp-dev-docs/issues/441 but have opened a new one as it is closed.

#### Observed Behavior

Troubleshooting I tried deleting the <homedir>/.gcb-serve-data as mentioned in https://github.com/SharePoint/sp-dev-docs/issues/395.
I also recreated the project with the same error. Finally I opened the workbench page in IE (11.1087.16299.0) and it works without a problem.

#### Steps to Reproduce

Follow instructions in the Helloworld part 1 tutorial and use MS Edge as your browser.

**Comment by andrewconnell** [comment]
This sounds like your self-signed cert was not properly trusted on your local machine. A few things:

- the workbench is not fully supported with IE... either the local workbench or hosted workbench... there are known issues
- the message fro because the hosted workbench is reporting the dialog you mention, that implies it isn't getting a response from your local web server running on https... because it isn't seeing the cert as valid
- try other browsers and see if you are having an issue
- untrust & re-trust the cert using an administrative command prompt

If you continue to have issues please provide more context:
- your environment (operating system, version, etc)
- target environment (sp2016/2019/spo)
- versions of node, npm & SPFx generator installed
- version of the SPFx component
- show the output from the console when you run **gulp trust-dev-cert** & when you run **gulp serve** including when you navigate to the local workbench
