### ISSUE TITLE
api/search/suggest?querytext='*' returns empty result using azure AD authention

### ISSUE THREAD

**Issue by pravin080317** [SharePoint/sp-dev-docs#5068]
Iam calling the search api "_api/search/suggest?querytext='*" using httpclient in azure functions. Authentication is done via azure ad application. Application permissions sites.fullcontrol is provided. But when ever i tried to call this suggest api, it returns empty results.

i can able to retreive the results of suggest api using username and password but using the azure ad app auth it gives the empty results.

whether we can able to call this suggest api using application permissions set in azure ad ? kinldy let me know if there are any alternatives

**Comment by andrewconnell** [comment]
I believe that's by design. The Search API implements security trimming for the current user. When you are using an app permission, there is no context of the user and thus, all results are security trimmed.

/cc @wobba to confirm...

**Comment by wobba** [comment]
It's not security trimmed really, but it blocks anonymous calls, and as @andrewconnell mentions it does relay on a user context to execute. So by design. Also, searching using app-only permissions is super scary imo, as you have access to absolutely all content. I'd be very very careful of granting search rights to an app-only application.
