### ISSUE TITLE
SPFX WebPart not working when the Enabled property is disabled in app catalog 

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-docs#508]
#### Category
- [ ] Enhancement / Suggestion

#### Expected or Desired Behavior
Is it possible to make the SPFX WebPart work even when we disable the Enabled property in app catalog for a particular app? 

This is very important because if we have to install a SPFX app only for a specific site and hide the app for the rest of the sites. This functionality is working for SharePoint and Provider hosted app as we are configuring the permission and the trust is getting created when we install the app. 

#### Observed Behavior
The SPFX WebPart will not work when we disable the Enabled property in app catalog for the app item. 

#### Steps to Reproduce
1. Upload the SPFX App in app catalog
2. Make sure Enabled property to **true** in the app item properties 
3. Install the app in a site 
4. Add the WebPart in a page and make sure it is working 
5. Go back to app item properties in app catalog --> Set the Enabled property to **false**
6. Go back to the page where you added the WebPart  
7. The WebPart will not work 

Error: 
![snip20170323_4](https://cloud.githubusercontent.com/assets/21008316/24271020/8fb4fc22-0fe5-11e7-8e53-8b2075473867.png)

**Comment by sprider** [comment]
@VesaJuvonen / @waldekmastykarz : Any guidance for this?

**Comment by mpasarin** [comment]
In order to address your needs you can use Site Collection App Catalog ( https://support.office.com/en-us/article/Manage-the-Site-Collection-App-Catalog-928b9b61-a9de-4563-a7d1-6231aa9d4d19 )
Recently both @VesaJuvonen and @waldekmastykarz published a webcast talking about this: https://www.youtube.com/watch?v=ZfUKkdMnSYQ

For the specific question, when a package is not Enabled it can't be used anywhere. That is by design.
