### ISSUE TITLE
New GUID is creating while creating new bundles Issue in SPFx

### ISSUE THREAD

**Issue by VidhiBartariya** [SharePoint/sp-dev-docs#510]
#### Category
- [ ] Question
- [ ] Bug
#### Expected or Desired Behavior
After replacing the bundle files in library,web part should refer to New GUID  not  old GUID.
#### Observed Behavior
The issue we are facing is every time we are updating the web parts and generating the package, it is creating bundle file with new GUID. And after replacing the bundle files in site library we are getting error. This error is because web part is still referring to old GUID bundle file.

#### Steps to Reproduce
We have created couple of web parts using SPFx for our new release. We have developed them and deployed to the site. Now we are doing updates in web part for bug fixes and creating bundle, packaging solution and deploying it in tenant using the below commands.
gulp clean
gulp bundle --ship
gulp package-solution --ship
 
The issue we are facing is every time we are updating the web parts and generating the package by using above commands, it is creating bundle file with new GUID. And after replacing the bundle files in site library we are getting error. This error is because web part is still referring to old GUID bundle file.

**Can anyone please aware me why GUID is changing every time when we update anything on webpart and after all the deployment  why it's referring old one GUID ?**

**Comment by iclanton** [comment]
When you say "it is creating bundle file with new GUID," do you mean that the JS file that's produced by the build has a different GUID at the top here?:

```JavaScript
define("<guid>", ...
```

Do you have your component's ID set in its manifest? The GUID at the top of the produced file should be the same as the ID you have set in your manifest.

**Comment by russgove** [comment]
I'm not sure if its the same issue, but I noticed that if I  rebuild my app to fix some bugs, I need to deploye BOTH the SPPkg file to the catalog AND upload my bundle to the CDN. 

It would be nice if we could just upload the bundle.
I do have my  id set in my package-solution:
{
  "solution": {
    "name": "xxx",
    "id": "12dac38e-b255-44ce-9f06-050571b34d39",
    "version": "1.0.0.0"
  },

**Comment by shaipetel** [comment]
I think you mean the hash that is added to the bundle.js file name when you do gulp --ship ?
It is not a guide, it is a hash calculated from the checksum of the file content, meant to mark that the JS file was modified or not (sort of a cache-buster.

I also dislike it very much! I would rather have the version number appended, or non at all.

But to answer your question, your web part stops working since the web part package that you install in your app catalog is pointing to the bundle file as it was built with and looking for it in the CDN.

Now, if you did upload a new package to the catalog and dragged it over the existing one clicking "replace" - there is a bug I already reported that this doesn't work.

Instead you have to delete the package from the catalog BEFORE you upload the new package and then it will take the new file from the CDN.

very annoying and would be a disaster comes production if it is not fixed SOON.

Side note: if you don't like that hash in the file name, since you won't be able to push minor fixes without requiring your customers to install updates all the time, here is a little trick I found:
1. run gulp --ship
2. visit temp/deploy folder and rename your bundle.js file to what ever you want.
3. rename the same file inside the JSON file also in the temp/deploy folder
4. run gulp package-solution --ship

this will now build you package with the name you edited in step 2, so it won't point to that long name with the hash.

**Comment by shaipetel** [comment]
related issue regarding the update of the package not working and having to delete it first:

https://github.com/SharePoint/sp-dev-docs/issues/550

gone 2 weeks now without a single comment...

**Comment by frnk01** [comment]
Totaly agree on this. New hash is generated and I have to update both app and bundle files on cdn.

**Comment by iiunknown** [comment]
When will fix it？It's very expensive in dev life-cycle.

**Comment by shaipetel** [comment]
Latest spfx now supports a flag to say you don’t want the hash to be added to the bundle files. 

Also you can check my blog KWizCom.blogspot.com on how to manually replace the hash with the package version number. 

Sorry I don’t have the links available but should be simple enough to find.

**Comment by VidhiBartariya** [comment]
That issue has resolved. 
package was refering old GUID so i have changed manually
