### ISSUE TITLE
Gulp Serve throws error: “Error - [tslint] No valid rules have been specified for TypeScript files”

### ISSUE THREAD

**Issue by lancebitner** [SharePoint/sp-dev-docs#5121]
I get through the setup and Yo builds my web part. When I run `gulp serve` it throws error: “Error - [tslint] No valid rules have been specified for TypeScript files”

![error2](https://user-images.githubusercontent.com/24795799/72224043-e20ff900-3543-11ea-873a-ab174b2690f2.PNG)

**Comment by Dennis-LZ** [comment]
Download the solution from here: [React Aggregated Calendar Webpart](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-aggregated-calendar).

Then in the command line run:
```
npm install
gulp serve
```
![Capture](https://user-images.githubusercontent.com/55479607/72230592-7c7a4600-35f1-11ea-910d-e195b93dd51e.PNG)

If still get the same issue, please check the SharePoint Framework development environment following the article below.

[Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

**Dennis Guo
Microsoft SharePoint Community Support**

**Comment by andrewconnell** [comment]
@lancebitner Need more context... what version of SPFx you're using, version of Node installed, etc...

**Comment by lancebitner** [comment]
SharePoint Online, SPFX 1.10.0, gulp 3.9.1, CLI 2.2.0, Yo 3.1.1, npm 6.13.4, and node 10.18.1 (tried 8.11.1, 8.16, and 10.3)...I ran `npm list -g --depth=0` and it revealed some things attached:
![eroor3](https://user-images.githubusercontent.com/24795799/72264419-be52be80-35e8-11ea-81d5-f687f1b4d55d.PNG)

Once I ran nodejs v 10.3.0 I longer had the error and I was able to do a Helloworld web part! That works but I cant get any of the web parts running from SharePoint Github site. The only thing I can see is the typescript v is 3.2.4 in the web parts that aren't working, and 3.3.4000 v in the helloworld web part that is working..

I suppose I should close this because this problem is out of the scope of the project....

**Comment by andrewconnell** [comment]
@lancebitner it seems like you are saying you have it working, but sample web parts from the "SharePoint Github site" aren't working... 

If you have issues with another project in another repo, you should post there... not here. This issue list is for general SharePoint dev issues.

_FYI, if you are referring to the **[sp-dev-fx-webparts](https://github.com/SharePoint/sp-dev-fx-webparts)** repo, that is simply a collection of community-contributed samples... many are old & outdated and need work in order to build using the latest tools. No one manages those... the are just community samples. Feel free to post to that repo's issue list if you have problems with a specific one, but like I said, no one really monitors those._
