### ISSUE TITLE
isDomainIsolated: true causes x-frame-options error

### ISSUE THREAD

**Issue by Ballzer0** [SharePoint/sp-dev-docs#5140]
If i follow these steps but leave **isDomainIsolated: true** in the  **package-solution.json, it will cause an error saying: 

**Refused to display 'https://myorg-app.sharepoint.com/_forms/spfxsinglesignon.aspx... ... ...' in a frame because it set 'X-Frame-Options' to 'sameorigin'.**

This only happens if i have logged in with 2 diffcerent AAD accounts in the same webbrowser. So it looks like its tyring to prompt for an account selection, but its getting blocked. Preferably it would use the same account  that im logged into sharepoint with, but i dont really know the possibilities here.

The spesific API im trying to consume is the Dynamics CRM API, and like i said earlier. this only triggers if i have logged into two different AAD accounts in the same browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aef3458-ceae-6f4b-8b81-a8351185a1ce
* Version Independent ID: feb02688-2e08-8345-bd5c-98d80b47c2cf
* Content: [Consume enterprise APIs secured with Azure AD in SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi)
* Content Source: [docs/spfx/use-aadhttpclient-enterpriseapi.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
There's a very active issue #4892 that mentions this header value. MSFT, in a comment on that issue, has ack that there's a race condition when obtaining an access token from AzureAD that appears to be impacting a few things. 

I believe your issue is directly related to that issue... which means this is a dupe. We try to keep issues/bugs consolidated into a single issue for tracking so we'll flag it as a dupe & close.

Can you please review that issue and verify? If you feel its entirely different, please feel free to follow up and we can reopen this.
