### ISSUE TITLE
Why isn't the manifest.json file automatically created anymore? (Using SPFx 1.10)

### ISSUE THREAD

**Issue by Languafe** [SharePoint/sp-dev-docs#5152]
I just stumbled upon this YouTube video, https://youtu.be/4kSRmetB4vA, from 2018 where seemingly the manifest.json is automatically created with the rest of the project. This was in 1.7. What happened?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10039675-218b-bd24-3b48-c95becf367fa
* Version Independent ID: 4186095d-c6d3-8773-4855-3c5d0e59bfb1
* Content: [Create Microsoft Teams manifest manually for a web part and deploy it to Microsoft Teams](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart#feedback)
* Content Source: [docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The manifest is generated on the fly when the package is deployed to Microsoft Teams using the **Sync to Teams** button in the app catalog. This is a preferred option because any changes to your SPFx component (like the name) is automatically picked up without having to remember all the places to update it, including the **manifest.json**.

If there is already a **manifest.json** in the folder, that is used rather than one that is created on the fly.
