### ISSUE TITLE
QuickApps

### ISSUE THREAD

**Issue by shelbylanderson** [SharePoint/sp-dev-docs#5196]
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Looking for any advice/tips for using QuickApps for SharePoint 2013, specifically qListForm. There isn't much on the web regarding QuickApps in general...so I'm wondering if anyone has had any luck figuring this beast out. The company I work for is wanting to move away from InfoPath forms and are leaning heavily on utilizing QuickApps. Any info or leads you have is greatly appreciated.

**Comment by PrasadKasireddy** [comment]
Instead of going for 3rd party tool, choose Microsoft Power Apps(https://powerapps.microsoft.com/en-us/blog/support-for-sharepoint-on-premises/)

Why should I choose Microsoft Powers Apps:
1. It is code free and It is a software-as-a-service (SaaS) comprised of connectors, services, apps and data platforms designed to quickly and seamlessly build business applications according to specific business needs.
2. In future If business want to move from SharePoint 2013 to higher version of SharePoint, 
     - You need to redesign / upgraded server and 3rd party tool which involves Cost. However, Power Apps as a PaaS server so it will upgraded automatically. it is easy to integrate with SharePoint on premises / SharePoint online
