### ISSUE TITLE
Search Query with Query text and document library path does not return all results

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [SharePoint/sp-dev-docs#5391]
I'm experiencing issues when I search with a query text and document library path along with selected properties. I have re-indexed the site and the document library as well, waited for 15 minutes until the next day, still no results.

Below is my query :-
/_api/search/query?querytext='` + queryText + `*+path:"` + window.location.origin + folderUrl + `"'` + `&selectproperties='ListItemID,Path,Url,Title,Size,LastModifiedTime,ParentLink,IsDocument,FileType,OriginalPath'&sortlist='Created:descending'`;

folderUrl  value is like /sites/site-name/DocumentLibrary

When searched for certain keywords, the results are getting displayed and when searched for another set of keywords , nothing is getting displayed.

A file uploaded on ‎10‎/‎24‎/‎2019‎ ‎11‎:‎02‎:‎01‎ ‎AM show up in the search where as a file uploaded on ‎10‎/‎24‎/‎2019‎ ‎11‎:‎02‎:‎59‎ ‎AM does not show when searched and considering the file names are unique in 7000+ items in the document library. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#feedback)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Ping @wobba ... ideas?

**Comment by wobba** [comment]
I have ideas :) @Naveen-Rangarajan can you say something about what documents are not returned? Specific types for example? Non-Office documents are served by their DispForm.aspx url for example. (Yes, I know this is weird). If you use `documentlink:<url>` instead, your results might be better.

I cover this some in my Troubleshooting Search book ;)

Also, make sure to turn off duplicate trimming, and ensure no query rules/default result sources are interfering with the query.

**Comment by Naveen-Rangarajan** [comment]
Hi @Wobba, thank you for the reply :) 

I search for office files like docx, xlsx, pptx, txt's and pdf's.  Duplicate trimming is set to false. There are no query rules/default result sources. 

Some documents are returned and others don't find their way in the search results. 

"Allow this site to appear in search results" has been set to "Yes".

Hope this helps.

**Comment by wobba** [comment]
Can you find the files by filename? If so, debug and figure out the Path value to troubleshoot.

It's impossible to troubleshoot without having access and looking at what is being returned. I suggest you use the SharePoint Search Query Tool or check the crawl log using PnP Powershell to troubleshoot, as there is probably a good reason why some items are not coming back.

* Path contains DispForm url instead of full URL
* Item is only in a minor version
* query term is in a hidden column
* etc...

If the files are not coming back at all, it's a support matter - not a KQL question :) And I recommend going thru the steps in https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/search-results-missing or https://www.amazon.com/Troubleshooting-Search-SharePoint-Online-solving/dp/1080506411
