### ISSUE TITLE
Creating a Flow using the HTTP Request trigger requires premium licensing

### ISSUE THREAD

**Issue by airdouglas** [SharePoint/sp-dev-docs#5415]
Creating a Flow using the HTTP Request trigger now requires premium licensing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1afac891-6cf5-1746-6392-8cb61a441770
* Version Independent ID: b5d1f95b-f40b-8d0c-7334-7608a3add9ff
* Content: [Using site designs and Power Automate to track site creation requests](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-trigger-flow-tutorial?source=docs)
* Content Source: [docs/declarative-customization/site-design-trigger-flow-tutorial.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-trigger-flow-tutorial.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @airdouglas 

we have already had discussions around the premium licensing topic (#4467). According to @andrewconnell, licensing isn't a dev issue that should be pointed out. For instance, in other places in the docs, it refers to using Azure Functions, but it doesn't go into the licensing / costs on it.

You could consider using Logic Apps instead of Power Automate. I've written a [blog post](https://www.devjhorst.com/2019/10/integrate-azure-logic-apps-with-sharepoint-site-designs.html) that explains how to integrate Logic Apps with SharePoint Site Designs.

I hope it helps.

Regards,
Jarbas

**Comment by airdouglas** [comment]
I had considered that as well.  Thanks for your response.  I see now (I didn’t see it before) that the docs page does mention that the connector is premium.

Sincerely,

Sean

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
