### ISSUE TITLE
same property pane control doesn't behave reactive in Online like on-premises

### ISSUE THREAD

**Issue by dips23** [SharePoint/sp-dev-docs#5418]
## Category

- [x] Bug

## Describe the bug

In my web part, property pane control (Dropdown list) reacts as expected in SharePoint 2019 on-premises environment, while for SharePoint Online, it only reacts after the property is saved -> Page is refreshed.

Is it happening because of the following alert mentioned here - [https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties]

"In drop 6 of the SharePoint Framework, there is a bug in the Office UI Fabric React Dropdown component that causes the dropdown control to work incorrectly. A temporary workaround is to edit the **node_modules/@microsoft/office-ui-fabric-react-bundle/dist/office-ui-fabric-react.bundle.js** file and change line 12027 from"

OR

Am  I missing anything in the code?

## Steps to reproduce

I have executed the web part with the following code in on-premises and online workbench, where property behaves as expected in on-premises while in online, it is not reactive.

**On Property Change Method:**
if (propertyPath === 'ViewName' && (newValue && newValue != oldValue)){     
      super.onPropertyPaneFieldChanged(propertyPath, oldValue, newValue);
      const previousItem: string = this.properties.ViewName;           
      this.onPropertyPaneFieldChanged('ViewName', previousItem, newValue);debugger;    
      this.context.propertyPane.refresh();     
      this.context.statusRenderer.displayLoadingIndicator(this.domElement, 'items');      
      this.context.statusRenderer.clearLoadingIndicator(this.domElement);         
      this.render();         
      this.context.propertyPane.refresh();     
    }

**Propertybindmethod:**
    public componentDidMount(){
    this.bindViewer();   
  }

## Expected behavior

Dropdownlist property should be reactive. [ I assume "this.context.propertyPane.refresh();" is not making a call to "componentDidMount()" method, that triggers this issue]
Would you please suggest the resolution?

**Comment by andrewconnell** [comment]
Unfortunately, as the docs mention, there's an issue with the version of Office UI Fabric React that's used on-prem. Because the version on-prem is not updated like the SPO versions, you should follow the guidance in the docs (*sorry, can't find the specific link*) and make sure the version of Fabric React is included in your bundle if you intend to use it in both SP2019 on-prem & SPO. This way you aren't impacted by different versions.

Yes, that means you're "pinned" to an older version of OUIFR that has that bug that you'll have to implement the work around.
