### ISSUE TITLE
Column formatter: min-width is ignored

### ISSUE THREAD

**Issue by MrTantum** [SharePoint/sp-dev-docs#5442]
## Category
- [x] Question

## Question

We have created a column formatter which renders a custom "View" and an "Edit" button (see image below). The problem is that the width of the column is always to small. Therefore the second button is cut off. 

How can I prevent this? Or do I need to set something in the View Formatter on top of the column formatter options?

![image](https://user-images.githubusercontent.com/31658807/76439333-897ea000-63bc-11ea-8028-a184196ef92c.png)

Column formatter Example JSON:

```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/column-formatting.schema.json",
  "elmType": "span",
  "style": {
    "width": "350px"
  },
  "children": [
    {
      "elmType": "button",
      "txtContent": "View",
      "style": {
        "border": "none",
        "background-color": "#002d64",
        "border-color": "#002d64",
        "height": "32px",
        "color": "#ffffff",
        "cursor": "pointer",
        "min-width": "80px"
      },
      "customRowAction": {
        "action": "defaultClick"
      }
    },
    {
      "elmType": "span",
      "attributes": {
        "iconName": "Separator"
      },
      "style": {
        "height": "12px"
      }
    },
    {
      "elmType": "button",
      "txtContent": "Edit",
      "style": {
        "border": "none",
        "background-color": "#002d64",
        "border-color": "#002d64",
        "height": "32px",
        "color": "#ffffff",
        "cursor": "pointer",
        "min-width": "80px"
      },
      "customRowAction": {
        "action": "editProps"
      }
    }
  ]
}
```

**Comment by CPritch** [comment]
If you use the slider to increase the column width manually and then save the view the column widths will be preserved.

**Comment by MrTantum** [comment]
This won't help because this workaround only lasts until the user closes his browser.

Furthermore, the suggestion that users have to repair a broken layout manually does not raise trust in the system.

**Comment by CPritch** [comment]
Yes, unfortunately this is not a change that's visible to all users at the moment. I think it used to but it appears this may have changed. Each user would have to save the view which is not realistic for most systems.

Can I suggest popping them out into two different columns? One for edit and one for view?

Modifying and saving the view doesn't affect JSON View formatting so that won't change anything there as expected. You also cannot affect the min-width of a column from column formatting. If you use view formatting you have to implement the entire view yourself also.

Another possible route would be to use an application customiser to inject CSS but that is something ill-advised due to how unreliable targeting HTML can be.

**Comment by MrTantum** [comment]
Yes the two columns are a good workaround then. An application customizer would be overkill for such a small task.

Lets hope microsoft will update the field formatter logic in the future to make the width-attribute somehow.
