### ISSUE TITLE
When is it necessary to update SPFx version for existing web-parts

### ISSUE THREAD

**Issue by dudelis** [SharePoint/sp-dev-docs#5449]
## Category
- [x] Question
- [ ] Typo
- [ ] Additional article idea
## Question
The question came from the customer and I did not manage to find any governance regarding the necessity to upgrade the SPFx version for already developed web-parts.
So basically, the customer would like to know, if the new versions of SPFx available for SharePoint Online can break the existing web-parts, which were developed some time ago with a lower version, how to track this, what is the correct governance approach to this.
Please, point me to MS docs, if i missed this.
thanks in advance!

**Comment by Jerry0527** [comment]
This will depend on SPFX Release Note for each version.
For example, if you want to use MSGraphClient object, you will need to upgrade SPFX to v1.4.1. As this is the New API since 1.4.1.
You can refer SPFX Release Note below about what's New and Fixes for each SPFX Version:
[Welcome to the SharePoint Framework!](https://github.com/SharePoint/sp-dev-docs/wiki)
And for upgrading version for a existed solution, you could refer this example:
[How to update SharePoint Framework for an SPFx webpart?](https://www.koskila.net/how-to-update-your-spfx-webpart-to-a-new-version-of-sharepoint-framework/)

**Comment by dudelis** [comment]
@Jerry0527, thanks a lot.
I do understand, that when we need new features, the spfx should be a new one. But can this happen that with the release of the SPFx something might get changed on SP Online itself and old web-parts will stop working? So not the new features, but existing ones.
The customer would like to avoid the fact, that a new SPFx release stops previous ones from working correctly.

**Comment by Jerry0527** [comment]
@dudelis I can just say this could happen since there is still bugs in SPFX solution.
If want to avoid new unknown issue , just stay in the current version if all is working.

**Comment by andrewconnell** [comment]
@dudelis said:
>  if the new versions of SPFx available for SharePoint Online can break the existing web-parts

1. All versions of SPFx are deployed in SharePoint Online.
1. The way SPFx works is that when you create and deploy a project it's manifest defines all its dependencies.
1. New versions are not automatically used for existing components.
1. Regressions can always happen, but the above is how SPFx works by design.

For instance, if you built & deployed a project with SFPx v1.8.2, and now SPFx v1.10 is released, nothing changes with your component. If you want to use the v1.10 core libraries, you have to upgrade your project.

With that being said, the version number of your component (*set in the **\*.manifest.json** of your component*) will have no impact on anything related to deployment. That's simply used for your documentation.

**Comment by dudelis** [comment]
Thanks @andrewconnell ! That explains a lot.
So I also asked this question, because I read the following in the SPFx 1.10 Release Notes:

> Accessing Microsoft Teams context using this.context.microsoftTeams property has been deprecated, you should be using this.context.sdks.microsoftTeams property instead.

So let's imagine I used that in my Web-Part. This does not mean that with the new version of SPFx released, my old Web-part, that uses _this.context.microsoftTeams_, will stop working some time in the future after deprecation takes place?

**Comment by andrewconnell** [comment]
@dudelis said:
> This does not mean that with the new version of SPFx released, my old Web-part, that uses this.context.microsoftTeams, will stop working some time in the future after deprecation takes place?

No... as I said above, with no changes you'll continue to use the libraries you reference.

**Deprecated** = we're changing this API going forward, so you should start using the new one. But SPFx doesn't go back and retroactively change things out of the blue.

The exception to this are (1) breaking changes & (2) regressions. The former is well communicated in advance & intentional... the later is never intended :)

**Comment by dudelis** [comment]
@andrewconnell Thanks a lot.  This answers all my questions.
