### ISSUE TITLE
Web Parts suddenly broken on classic pages - "Module exports cannot be changed externally"

### ISSUE THREAD

**Issue by RishanM** [SharePoint/sp-dev-docs#545]
Hello,

I had some SharePoint Framework web parts on classic pages working properly up until sometime on April 12th. Now all web parts on my classic pages display an error similar to the one below. The web part src files have not been modified for 2 weeks.

**Web Part Error**
[SPWebPartErrorCode.ScriptLoadError]:
Unable to load web part WebPart.Accordion.g_e917a42f_85c1_40e2_b2d6_f7e0240c7621,Error: ***Failed to load component "89d609dd-9fb6-4353-aab4-6215ac1bb7f6" (Accordion).
Original error: ***Failed to load entry point from component "89d609dd-9fb6-4353-aab4-6215ac1bb7f6" (Accordion).
Original error: Error loading https://component-id.invalid/89d609dd-9fb6-4353-aab4-6215ac1bb7f6_0.0.1
	**Module exports cannot be changed externally. script resources due to: {1}.**

***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/classic-pages-assembly_en-us_d4cfb9b364d8f92f51e075c1eb2ddb73.js:109:25211)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/classic-pages-assembly_en-us_d4cfb9b364d8f92f51e075c1eb2ddb73.js:102:98685)
    at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/classic-pages-assembly_en-us_d4cfb9b364d8f92f51e075c1eb2ddb73.js:102:99126)
    at e._handleModulePromiseRejection (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/classic-pages-assembly_en-us_d4cfb9b364d8f92f51e075c1eb2ddb73.js:109:906628)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-31.004/classic-pages-assembly_en-us_d4cfb9b364d8f92f51e075c1eb2ddb73.js:109:896758

**Console errors:**
Uncaught (in promise) undefined
(anonymous) @ classic-pages-assembly_en-us_d4cfb9b….js:109

**Comment by manishgarg1** [comment]
@RishanM , Thanx for the info. We are looking into the matter ASAP.

**Comment by iclanton** [comment]
This issue appears to be because you're using `office-ui-fabric-react` in your Webpart without updating your build tools. You need to update your version of `@microsoft/sp-build-web` to at least version 1.0.1.

When you change it in your `package.json`, make sure you re-run `npm install`, and from there you'll be able to rebuild and re-deploy your Webpart.

You can confirm that you picked up the necessary changes by looking at the build output in the `dist/` folder. If your Webpart bundle starts with something like this (including the `office-ui-fabric-react`), the problem is still there and you'll need to rebuild and ensure that you're using the latest version of the tools:

```JavaScript
define("<your-component-id>_<your-component-version">, [ /* ... dependencies ... */, "office-ui-fabric-react", /* ... dependencies ... */], function ... 
```

I'm going to update the [documentation](https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/use-fabric-react-components) to make it clear you need to update your build tools.

Let me know if that doesn't work.

**Comment by iclanton** [comment]
When we published [the office-ui-fabric-react guidance](https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/use-fabric-react-components), it accompanied a patch release of the SPFx build tools. We weren't clear enough about this, but you need to update your version of `@microsoft/sp-build-web` to at least version 1.0.1 in order for the steps in that article to work correctly. I've submitted an update to the article to make that more clear.

When you update `@microsoft/sp-build-web` to version `1.0.1` in your `package.json`, make sure you re-run `npm install`, and from there you'll be able to rebuild and re-deploy your Webpart.

You can confirm that you picked up the necessary changes by looking at the build output in the `dist/` folder. If your Webpart bundle starts with something like this (specifically including the `office-ui-fabric-react` dependency), the problem is still there and you'll need to rebuild and ensure that you're using the latest version of the tools:

```JavaScript
define("<your-component-id>_<your-component-version">, [ /* ... dependencies ... */, "office-ui-fabric-react", /* ... dependencies ... */], function ... 
```

Let me know if that doesn't work.

**Comment by RishanM** [comment]
Thanks @iclanton, that resolved the issue!
