### ISSUE TITLE
Unable to access an Excel file via the Excel Services REST API

### ISSUE THREAD

**Issue by AndyH47-SUP** [SharePoint/sp-dev-docs#5473]
## Category
- [x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question

When trying to access an Excel file ”2019 Renewal Guide - KC Construction.xlsx” via the [Excel Services REST API](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-rest-api), I either get the 404 error message or that the file does not exist/is deleted.

Based on the Excel Rest Services API documentation [here](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/resources-uri-for-excel-services-rest-api), I have tried the URI-s as below.

1 - https://imacorporation.sharepoint.com/_vti_bin/ExcelRest.aspx/ClientX/EditableDocuments/Archived Renewal Trackers/2019 Renewal Guide - KC Construction.xlsx/Model/Tables?$format=json

2 - https://imacorporation.sharepoint.com/teams/_vti_bin/ExcelRest.aspx/ClientX/EditableDocuments/Archived Renewal Trackers/2019 Renewal Guide - KC Construction.xlsx/Model/Tables?$format=json

3 - https://imacorporation.sharepoint.com/teams/ClientX/_vti_bin/ExcelRest.aspx/EditableDocuments/Archived Renewal Trackers/2019 Renewal Guide - KC Construction.xlsx/Model/Tables?$format=json

From the browser I can access the Excel file in question using the URL as below:

https://imacorporation.sharepoint.com/:x:/r/teams/ClientX/EditableDocuments/Archived Renewal Trackers/2019 Renewal Guide - KC Construction.xlsx?d=w1c32b60f1caa4826b368a0683907791a&csf=1&e=TgifaX

The folder URL is as below:

https://imacorporation.sharepoint.com/teams/ClientX/EditableDocuments/Forms/AllItems.aspx?viewid=db12dc48-fc35-417f-aad9-177769e92fd2&id=/teams/ClientX/EditableDocuments/Archived Renewal Trackers

Can anyone please advise what would be a correct Excel Services URL for the Excel file “2019 Renewal Guide - KC Construction.xlsx”?

Note that the URL-s are decoded to make things easier to understand, the original URL-s I've tried were correctly encoded. I’m also experiencing the same issue for the file with the URL below.

https://imacorporation.sharepoint.com/teams/ClientX/EditableDocuments/Forms/AllItems.aspx?viewid=db12dc48%2Dfc35%2D417f%2Daad9%2D177769e92fd2&id=%2Fteams%2FClientX%2FEditableDocuments%2FArchived%20Renewal%20Trackers

## Environment details
 - OS: Windows 10
 - Browser(s): Chrome v80
 - Tooling:  Custom API JDBC Connector: https://www.cdata.com/drivers/excelservices/jdbc/
 - Sharepoint Version: Sharepoint Online

**Comment by bcameron1231** [comment]
Hi there. 3 looks to be right. I did a test to make sure it works.

Here was my process

1. I created a site collection called "ClientX"
2. Created a Library called "EditableDocuments"
3. Created a folder called "Archived Renewal Trackers"
4. Added an xlsx file called 2019 Renewal Guide - KC Construction.xlsx inside folder

![image](https://user-images.githubusercontent.com/7944457/77078571-6192cc00-69bc-11ea-96da-b56add5dc9a1.png)

5. I used the following URL https://BeauCameron.sharepoint.com/sites/ClientX/_vti_bin/ExcelRest.aspx/EditableDocuments/Archived%20Renewal%20Trackers/2019%20Renewal%20Guide%20-%20KC%20Construction.xlsx/model/Tables?$format=json

It was an empty work book, but it returned the data sucessfully.
![image](https://user-images.githubusercontent.com/7944457/77078645-7d966d80-69bc-11ea-8623-b3f912df47be.png)

A couple of notes
1. **I would confirm that you haven't mispelled anything, either in your URL or in your library or folder name.**
2. **In SharePoint Online, it is recommended you use the[ Microsoft Graph](https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0) endpoints instead of the Excel Services API.**
