### ISSUE TITLE
What order are requests made?

### ISSUE THREAD

**Issue by jason-russell** [SharePoint/sp-dev-docs#5476]
If I put three "Create List Item" POST requests in a batch, is there any specific order in which the items are created? I'd like to create the items in a specific order to control the List Item ID (this is part of a migration from another environment)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f963c2-441f-8f40-9c2a-3d31f4a79b1f
* Version Independent ID: d4a6f050-b632-a5a0-1814-33699760fccb
* Content: [Make batch requests with the REST APIs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis)
* Content Source: [docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
No, there is no guarantee of the order they are executed on the server. Batch support with the REST API is not transactional... the only way to do what you describe is with three independent requests.

**Comment by semopz** [comment]
You could call the [reserveListItemId](https://pnp.github.io/pnpjs/sp/lists/#reserve-list-item-id-for-idempotent-list-item-creation) method on a list in batch and then use the returned IDs to update the relevant items in any order you like (in batch or otherwise).

Instead of simply creating items in order, you'd have to take a two-step (reserve + update) approach but the benefit is that this is a more reliable way of creating the items and the order doesn't matter.

You could look into the SharePoint Migration API as well that covers this use case. I've only used it as part of ShareGate but the underlying API should be available to anyone I think.
