### ISSUE TITLE
Rich text column links is not open in new tab in spfx

### ISSUE THREAD

**Issue by ranjitpokale09** [SharePoint/sp-dev-docs#5478]
I am facing issue for anchor tag is not open in new tab in spfx,
**Details**:
I have a list with custom PowerApps form rich text column, in spfx I am sanitize-html as per MS guidelines.
In sanitize-html html I also allow attribute like href and target.
Here I am facing issue where some of links will open in new tab but other may open in same window.

**Comment by andrewconnell** [comment]
This is due to the page router. See these links for details on how to address this:

- https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking
- https://julieturner.net/2019/09/sharepoint-framework-application-customizer-cross-site-page-loading/
- https://www.eliostruyf.com/navigating-to-other-pages-in-sharepoint-framework-from-code/

**Comment by ranjitpokale09** [comment]
Hello andrewconnell,
In my scenario the sanitize rich text html links not have  __target="_blank" data-interception="off" these attribute.
In sanitize-html I am allow attributes like href, target and data-interception but nothing will happen.
