### ISSUE TITLE
SPFX extension ribbon custom button trigger flow

### ISSUE THREAD

**Issue by spo365** [SharePoint/sp-dev-docs#5540]
I am unable to call flow form  SPFX externsion custom button on ribbon in order to trigger a flow.

**Comment by bcameron1231** [comment]
Hi, can you provide more information as to what the issue is and what your environment is like? We are unable to provide any help with the information provided. 

1. What version of SPFx are you using?
2. What version of SharePoint are you using?
3. Can you provide your sample source code for the request you are trying to make?

**Comment by spo365** [comment]
What version of SPFx are you using?
1.9
What version of SharePoint are you using?
Online
Can you provide your sample source code for the request you are trying to make?
i am refer below link in order to archive my functionality.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api 
question :- Is there any way we can update record to sp library using pop-up extension which can help me trigger flow.

**Comment by andrewconnell** [comment]
When creating an issue, please use the template provided to complete context information that is needed to help...

**Comment by andrewconnell** [comment]
There's not enough information provided to understand or troubleshoot... please provide more context on your question.
