### ISSUE TITLE
Re-rendering of custom web-part is not happening while navigating between two similar pages

### ISSUE THREAD

**Issue by nithincvpoyyil** [SharePoint/sp-dev-docs#5604]
## Category

- [x] Bug

## Custom web-part component is not re-rendering when navigating between two similar pages

I have created **3 SharePoint site pages** from a **custom template**, which has a custom web-part that fetches title of the current page. Also, these 3 pages has tabbed button which links these 3 pages for navigation. 

### scenario: 
When I open the **page-1**, my web-part showing correct **page title-1**, but if I navigated to **page-2**  web-part will show the old title value **page title-1**, same happens if I navigated to page-3 as well. This is happening because React component's `componentDidMount `lifecycle method is not being called while navigating between these pages.

**My observations:**

1. Webpart's render method is not called when navigating from **Page-1** > **Page-2**

2. Webpart's onDispose method is not called when navigating from **Page-1> Page-2** OR **Page-2> Page-3**

Pseudo code:
```
export default class SiteWebPart extends BaseClientSideWebPart<Props> {
  public async onInit(): Promise<void> {
    return super.onInit().then(() => {
      console.info("web-part", ` onInit ${this.context.pageContext.listItem.id}`);
      sp.setup({
        sp: {
          baseUrl: this.context.pageContext.web.absoluteUrl,
        },
      });
    });
  }

  public render(): void {
    const { pageContext } = this.context;
    console.info("web-part", `render `); 

    /*
    SiteComponent is very simple react component,
    in which a list API call happening @ componentDidMount
   */

      const element: React.ReactElement<IProps> = React.createElement(SiteComponent, {
        pageContext: this.context.pageContext,
      });
      ReactDom.render(element, this.domElement);
  }

  protected onDispose(): void {
    console.info("web-part", `dispose`);
    ReactDom.unmountComponentAtNode(this.domElement);
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: []
        }
      ]
    };
  }
```

## Steps to reproduce

1. Create 3 pages from same template OR use **copy of the page**  feature to create the pages, add above custom webpart to the page and add navigation links between these pages using anchor tags/links. **Note**:  Do not ad any extra web-parts of information in these pages, content should be exact or similar. 
2. Open the page-1, click and navigate to Page-2 using the link  
3. Check console logs for render and dispose values of webpart
4. Similarly navigate between Page-2 and page-3, check the console logs of the webpart.

## Expected behaviour

1. For every page navigation, webpart **rendering** method should be called
2. For every page navigation, webpart **onDisopose** method should be called

**OR** 

Need a **navigationChange** event method in webpart to detect the navigation change

## Developer environment

- OS: Window 10
- Browser(s): Chrome >= v79 ,  Chromium Edge >= v79
- Tooling:  VS Code, SPFx v1.10.0

### Additional context

Due to this issue we are not able provide any solution the business and customers are highly impacted, they are now refreshing this page. I have seen similar issues are https://github.com/SharePoint/sp-dev-docs/issues/5352 listed in the GitHub but nothing is solved or closed by answering. Thanks for the help and support, looking for your reply.

**[EDIT]**
This issue is not happening regularly, but frequently. 

*Thanks for your contribution! Sharing is caring.*

**Comment by andrewconnell** [comment]
Seems you're running into issues with the page router. That sits between you and SharePoint. It decides how much of the page needs to be re-rendered when you navigate from one page to another instead of the entire page being rendered.

There's a way to opt out of it when using custom links to navigate from one page to another (`data-interception="off"`) *[see more in this post](https://julieturner.net/2018/08/spfx-anchor-tags-hitting-the-target/)*, and there's a way to hook into the navigation event with app customizers [see this post](https://www.eliostruyf.com/handling-navigation-in-a-sharepoint-framework-application-customizer/), but I don't think either of these apply to your case.

When you say "same page template", are these regular pages or single part app pages you're creating? Would help in setting up a repro. 

You also removed important parts of the **Developer environment** section in the issue template… specifically what SharePoint environment are you targetting & Node version.

There are a bunch of known/outstanding navigation related issues for these types of pages at this time: https://github.com/SharePoint/sp-dev-docs/issues?q=is%3Aissue+is%3Aopen+single+part+
