### ISSUE TITLE
Add Custom font to SPFX not working

### ISSUE THREAD

**Issue by EmadKhella** [SharePoint/sp-dev-docs#5608]
I want include custom fonts (Pharma-regular Condensed ) to my SPFX
I changed gulpfile.js as to add additional rule:
build.configureWebpack.mergeConfig({
additionalConfiguration: (generatedConfiguration) => {
      generatedConfiguration.module.rules.push(
        {   
            test: /\.(woff(2)?|ttf|eot|otf)?(\?v=\d+\.\d+\.\d+)?$/,
            loader: 'file-loader?name=/fonts/[name].[ext]',
        }
      );
      return generatedConfiguration;
    }
I created module .scss contains font-face 

@font-face {
	font-family: 'PharmaCond';
	src: url('/assets/fonts/Pharma-BoldCond.eot'),
	url('/assets/fonts/Pharma-BoldCond.woff') format('woff') ,
	url('/assets/fonts/Pharma-BoldCond.ttf') format('truetype');
  font-style: normal;
  font-weight: bold ;
  font-weight: 400 ;
}

@font-face {
	font-family: 'PharmaCond';
	src: url('/assets/fonts/Pharma-RegularCond.eot'), 
	url('/assets/fonts/Pharma-RegularCond.woff') format('woff'),
	 url('/assets/fonts/Pharma-RegularCond.ttf') format('truetype');
	font-weight: normal ;
	font-style: normal;
}
when I run gulp bundle, I couldn't find file on dist folder
does anyone have idea what is the missing part ?

**Comment by StfBauer** [comment]
There are some missing parts:
- In order to get recognised by webpack, the font files need to be in the lib folder first. This could be accomplished by defining a [copy-static-asset.json](https://n8d.at/how-to-copy-files-from-src-to-lib-folder-in-spfx/)
- The path in your SCSS seem to point to the wrong location
- The webpack file loader needs to come after the webpack scss loader

The best way to load custom fonts is to reference them from a CDN and not bundle them in. Especially it is likely that you have more the one solution/webpart that references to those font files and it can drain the performance on your frontend dramatically.

**Comment by EmadKhella** [comment]
> There are some missing parts:
> 
> * In order to get recognised by webpack, the font files need to be in the lib folder first. This could be accomplished by defining a [copy-static-asset.json](https://n8d.at/how-to-copy-files-from-src-to-lib-folder-in-spfx/)
> * The path in your SCSS seem to point to the wrong location
> * The webpack file loader needs to come after the webpack scss loader
> 
> The best way to load custom fonts is to reference them from a CDN and not bundle them in. Especially it is likely that you have more the one solution/webpart that references to those font files and it can drain the performance on your frontend dramatically.

I created copy-static-assets.json file and added extension of the files I need and it came in lib folder now 
![image](https://user-images.githubusercontent.com/54295822/79945558-59451980-84b1-11ea-8fe8-b21d16cdb179.png)

![image](https://user-images.githubusercontent.com/54295822/79945213-aeccf680-84b0-11ea-8dcb-07663752a54a.png)

How can I point them in scss module ?
![image](https://user-images.githubusercontent.com/54295822/79945368-f18ece80-84b0-11ea-82a5-1b27e73dcca5.png)

because it points to sharepoint server /assets/fonts 
![image](https://user-images.githubusercontent.com/54295822/79945646-927d8980-84b1-11ea-880e-27e789335270.png)

**Comment by StfBauer** [comment]
In your case, you still try to load the font from an absolute URL event if you do not explicitly include protocol and hostname. The slash always refers to the root of the website, where your fonts are not located.

In order to make this work, it needs to be relative like:

```css
src: url("./assets/fonts/pharma-boldcond.eot")
```

This should then load via webpack the font relative to your output styles. So in your case when you really like to load it from within your bundle you have to configure it like this:

[Loading fonts with webpack](https://chriscourses.com/blog/loading-fonts-webpack)

**Comment by EmadKhella** [comment]
> In your case, you still try to load the font from an absolute URL event if you do not explicitly include protocol and hostname. The slash always refers to the root of the website, where your fonts are not located.
> 
> In order to make this work, it needs to be relative like:
> 
> ```css
> src: url("./assets/fonts/pharma-boldcond.eot")
> ```
> 
> This should then load via webpack the font relative to your output styles. So in your case when you really like to load it from within your bundle you have to configure it like this:
> 
> [Loading fonts with webpack](https://chriscourses.com/blog/loading-fonts-webpack)
==============================================
now on webpack it is loaded fonrs :
![image](https://user-images.githubusercontent.com/54295822/79955351-0cb60a00-84c2-11ea-94f0-1c6a36d927a0.png)
but still not reflected my form 

I am working on workbench.aspx and it shows the links of fonts is localhost:4321
![image](https://user-images.githubusercontent.com/54295822/79955189-c496e780-84c1-11ea-99b0-f040a54a2d7a.png)

is that will be fixed when I deploy to Tenant ?

**Comment by David74000** [comment]
Hi all,
I reply to this post because I am struggling with a similar issue. I want to add a custom font ('Aktiv Grotesk') in my spfx project but in my workbench the font cannot be displayed.

Here are the steps I followed:
1- I copied woff and woff2 files in the same folder than my .scss module.
2- In the .scss module, I added the font-face as following:
`@import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss';

@font-face {
  font-family: 'Aktiv Grotesk';
  src: url('./AktivGrotesk_W_Rg.woff') format('woff'),
  url('./AktivGrotesk_W_Rg.woff2') format('woff2')
}

.myComponent {

  .row {
    @include ms-Grid-row;
    padding: 20px;
  }

  .column {
    @include ms-Grid-col;
    @include ms-sm12;
  }
....`

3-I used the 'Aktiv Grotesk' font family in a office ui fabric component (Pivot). Please note that if I use a classic font-family like 'Comic sans MS' it works.

At this step my webpart should correctly display the font, right ?

Just to be sure, I followed current post and applied the following steps (but I guess these steps are only relevant for the build ?)
4- Added the following lines in the gulpfile.js
build.configureWebpack.mergeConfig({
    additionalConfiguration: (generatedConfiguration) => {
    generatedConfiguration.module.rules.push(
    {
    test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
    loader: 'file-loader?name=/fonts/[name].[ext]',
    }
    );
    return generatedConfiguration;
    }
})

5- I added the following lines in the copy-static-assets.json
{
    "includeExtensions": [
      "woff2","woff"
    ]
  }

gulp serve show no error

I realy appreciate your help.

Cheers

David

**Comment by StfBauer** [comment]
I wrote a blog post on how to [deal with custom fonts in web pack](https://n8d.at/how-to-bundle-and-use-custom-web-fonts-in-spfx-projects/). There are some things I recognised that it is crucial where you place your font files with my setup it worked without any problem.
