### ISSUE TITLE
Are shared documents Lists?

### ISSUE THREAD

**Issue by madhavsankar** [SharePoint/sp-dev-docs#5618]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
In the doc https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks, it has been mentioned that webhooks can only be applied to lists. But currently we are uploading our data to the Site's root Documents (in a folder within Shared Documents). When I search for all lists in the site through a Graph Explorer, it seems to have one as Shared Documents as well. So are these shared documents a list as well and can I apply webhooks on these items?

**Comment by JarbasHorst** [comment]
Hello @madhavsankar 

in SharePoint, the term list means document libraries and lists (e.g. custom lists). The documentation says that webhooks are only enabled for SP list items which doesn't exclude document libraries! Since Shared Documents is a document library, you can also apply webhooks on these items.

I hope it helps to clarify your question.

Regards,
Jarbas
