### ISSUE TITLE
Classic Deprecate timeline

### ISSUE THREAD

**Issue by AshishOnGit** [SharePoint/sp-dev-docs#5672]
Is the statement about classic site and page deprecation still valid? This statement is used by a lot of customer as an excuse to remain on classic. Can someone provide little more insight on this as its been one year of this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0589135-7828-0e78-2368-a2ce7d24837d
* Version Independent ID: fba97516-ac39-df40-b1cd-71b509eec7c0
* Content: [Customizing the ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations#feedback)
* Content Source: [docs/solution-guidance/modern-experience-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/modern-experience-customizations.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @AshishOnGit 

thanks for your question. I can't give you insights on this since I don't work at Microsoft. However, I can tell you from my experience. I don't believe, that Microsoft will retire SharePoint classic in the upcoming months or even years. Several business applications have been built on top of SharePoint classic and haven't been migrated yet to SharePoint modern. We all have customers still using SharePoint classic because of different reasons. However, SharePoint modern is definitely the way to go! Several new enhancements (for instance view formatting, embedding a SharePoint list or page as a Teams tab etc.) are only available in SharePoint modern. 

From my point of view, Microsoft demonstrates a very good business management. So, I believe they will be monitoring the usage of SharePoint classic and retire it at some point if there is no usage for it anymore. Dialogue might be a good way to convince customers to move to SharePoint modern.
 
I hope I could help to clarify your question. Maybe someone else from the community or Microsoft can give more information.

Regards,
Jarbas
