### ISSUE TITLE
Clarification on limits

### ISSUE THREAD

**Issue by sparkitect** [SharePoint/sp-dev-docs#5678]
When the document mentions "we have bumped this limit to 300 actions", does that mean 300 actions for EACH Site _Script_ included in a Site Design, or the total number of actions across all Site Scripts included in a single Site _Design_?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f52c85-8e87-991f-5002-149f011fe8d0
* Version Independent ID: 352955bd-4e1a-126a-a026-440d2b62de38
* Content: [SharePoint site design and site script overview](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview)
* Content Source: [docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by JarbasHorst** [comment]
Hello @sparkitect 

300 means the total count of all actions across all Site Scripts included in a single Site Design. Running for instance Add-SPOSiteDesignTask with a Site Design which has more than 300 actions associated to it, results in the following exception: Operation is not valid due to the current state of the object.

Regards,
Jarbas
