### ISSUE TITLE
Why does Search REST API add an IsDocument=True constraint to my query?

### ISSUE THREAD

**Issue by nozhT** [SharePoint/sp-dev-docs#5735]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

I wanted to use the Search REST API to search for websites in a Sharepoint Online tenant, so I called the API with QueryText `contentclass:STS_Site contentclass:STS_Web` and the QueryTemplate empty.

The search result was empty despite the tenant having thousands of sites.

Inspecting the response I found out that the `QueryModification` contained an additional constraint:
`contentclass:STS_Site contentclass:STS_Web IsDocument=True`
which explains why there was nothing returned.

Why is there an additional `IsDocument=true` constraint in the query modification? Is it some setting that I can turn off?

**Comment by andrewconnell** [comment]
ping @wobba... do you know?

**Comment by wobba** [comment]
**Answer:** Because someone configured a default result source or query rule on the site you query against (for some reason) which adds this.

**Solution:** Pass in `sourceid=8413cd39-2156-4e00-b54d-11efd9abdb89&enablequeryrules=false` to ensure no one is messing up your intended behavior :)

Covered in my writing on search troubleshooting 😉
