### ISSUE TITLE
Empty div is making modals fail

### ISSUE THREAD

**Issue by LuisEnMarroquin** [SharePoint/sp-dev-docs#5738]
## Category

- [x] Bug

## Describe the bug

There is an empty div that does nothing over any webpart

It has 2 classes `.o365cs-base` and `.gHOeSZuAX3PGA1RB_C2ju`

![bug-image](https://user-images.githubusercontent.com/35376824/81944250-18c55100-95c2-11ea-90d2-7b2aa7254b63.png)

Note: I added the `/* display: none */` in the image

## Steps to reproduce

1. Create a modal that goes over sharepoint properties
2. Add some buttons to it
3. Try to click it and you won't be able to

## Expected behavior

This `div` serves no purpose, it shouldn't be there

## Environment details (*development & target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10
- **Browser(s)**: Any

**Comment by andrewconnell** [comment]
@LuisEnMarroquin said:
> Create a modal that goes over sharepoint properties

What do you mean by this... create a dialog using the dialog framework? Can you provide a repo?

**Comment by LuisEnMarroquin** [comment]
If you create a [modal](https://www.w3schools.com/bootstrap/bootstrap_modal.asp), dialog box/popup window that is displayed on top of the current page some parts of my webpart won't be clickable

Can't provide a repo because is property of the business that i work at, but you can see it on any business sharepoint site: `https://<site>.sharepoint.com/sites/home/SitePages/MYSITE.aspx`

```html
<html dir="ltr" lang="es-ES">
<body style="margin: 0; padding: 0" class="ms-font-m ms-Fabric--isFocusHidden">
<div tabindex="0" class="o365cs-base gHOeSZuAX3PGA1RB_C2ju" style="right: 0px; top: 50px; position: fixed;">
<div class="_2e6Jr4XQ3rylcOpRs_4y3I" id="popupContent" aria-live="polite" aria-relevant="additions"></div>
</div>
</body>
</html>
```

**Comment by LuisEnMarroquin** [comment]
I found out that it's the div that you use for notifications, you could do something better like `display: none` and when a notification arrives you can display it for a few seconds

![image](https://user-images.githubusercontent.com/35376824/82060343-dfa5e300-968c-11ea-8b2e-150f33d3ff9e.png)

**Comment by LuisEnMarroquin** [comment]
> Thanks for sharing the diagnosis, but can you share a screenshot of it happening? Show what the effect is? You can mask out anything that's private to your employer.

Sorry, can't provide more help, I already shared 2 screenshots of it happening, explained what that div is used for and even shared the full html code, this should be more than enough for anyone working on it to understand whats happening 

> Also, are you aware of the Dialog framework in SPFx? That's the recommended way to do dialogs/modals.
I am ussing office-ui with react and typescript as advertised on Microsoft official docs

**Comment by andrewconnell** [comment]
@StfBauer Does this make sense to you?

**Comment by StfBauer** [comment]
From the link before @LuisEnMarroquin try to implement a [Bootstrap 3](https://getbootstrap.com) modal dialogue which causes issue cause there are some things in SPFx that block you from doing that.

**Issue 1:** Global Styles - SharePoint Web Parts scopes the classes only way around is load it from CDN that might break SharePoint or load it from the [SharePoint Web Part](https://n8d.at/how-to-use-bootstrap-in-sharepoint-framework-projects/)

**Issue 2:** The modal script provided by [Bootstrap](https://getbootstrap.com) use global style sheet classes and fail to do anything because they might not be on the page.

The easy solution is to use what @andrewconnell proposed to use the available modal [dialog framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx) or provide a sample solution where just a bare-bone implementation without the specifics to the solution is included. A solution that for example just try to open https://www.microsoft.com in a modal dialogue. I can then take a look into it.

**Comment by andrewconnell** [comment]
Thanks for jumping in @StfBauer ... wasn't aware of the issues with the Bootstrap dialog.
