### ISSUE TITLE
PnP JS Get items by filter from Larg list

### ISSUE THREAD

**Issue by Sendil85** [SharePoint/sp-dev-docs#5755]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Hi,
I have list around 10000 items,
I wanted to fetch 10 rows based on a  value in the column, which means
sp.web.lists.getByTitle("Dummy").items.select("Id","Title","Name","Age")
  .filter(`Title eq 'Title5001'`).top(10) .getAll()

it fails,
I refereed many issues in github, i couldn't find any solution to this problem.
My basic need is to get items from large list with filter, my result doesn't exceed more than 10 items.
I don't have any complex type columns, list has only 3 text columns all are indexed.

## Environment details (*development & target environment*)

I tried with SPFX Rest and PmP js.

*Thanks for your contribution! Sharing is caring.*

**Comment by Jerry0527** [comment]
Tested to filter a indexed "Title" column with the same endpoint (5300 total items in list):

```
   let items =  sp.web.lists.getByTitle("CamlList").items.select("Id","Title").filter("Title eq 'Test Item 0'").top(10) .getAll();
    console.log(items);
```
![Image 2](https://user-images.githubusercontent.com/28797671/82309814-30536e00-99f6-11ea-8b99-b889dec6b937.png)


![Image 3](https://user-images.githubusercontent.com/28797671/82309861-3ea18a00-99f6-11ea-93d1-549034010d46.png)

Here is similiar issue posted in the past, the indexed column shoule be able to fix the issue, if the issue still existed, please recreate the indexed column for the one used in CAML:

[GetAll() doesn't work with filter and with big data list](https://github.com/pnp/pnpjs/issues/400)

**Comment by andrewconnell** [comment]
Couple of things...

- The `$top` operator on a REST query doesn't get around the issues of having large lists and the results being throttled. That's because SP still has to generate a result set before it can grab the top # results & that's expensive. The only way around the large list queries is to filter i first, as @Jerry0527 said.
- This question is more suited for the PnPJS repo as it's specific to that library, not a general SharePoint dev question which is what this forum is for.
