### ISSUE TITLE
Problem Installing SPFx app to sub sites

### ISSUE THREAD

**Issue by jaredbuttars** [SharePoint/sp-dev-docs#580]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
An SPFx Web Part is installed in a site collection. A new sub site should allow for the installation of the same web part.

#### Observed Behavior
There is an error when attempting to install to a subsite.

`A different version of this App is already installed with the same version number.  You need to delete the app from the site and the site recycle bin to install this version.`

#### Steps to Reproduce
Install an SPFx web part to a site collection. Create a new sub site. Install the app to the sub site. 

The only way I have been able to get around this is to version up the web part and redeploy it to the store.

**Comment by jonathanhotono** [comment]
I did encountered this issue a few times.

**Comment by nickpape-msft** [comment]
Thanks for the feedback. We will investigate the issue and get back to you.

**Comment by mchsudhakar** [comment]
I too have this issue. Is this fixed?

**Comment by brendon111** [comment]
Is there any update on this issue. We need to add multiple custom spfx web parts to sub sites and can't increment every web part each time we create a sub-site.

**Comment by BigEaseGueldi** [comment]
Same here. This is a show stopper for quite a few scenarios. I know that we're moving away from sub sites, but there are still plenty of customers that have them (I guess 99%) ...

**Comment by mchsudhakar** [comment]
@BigEaseGueldi Hi there, I remember we were able to resolve the issue after deleting everything and then upgrading to the latest version 1.4.1 Please refer to  https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-for-SPFx-Package-Version-1.4.1

**Comment by BigEaseGueldi** [comment]
Thanks @mchsudhakar, but in this case we started with 1.4.1. The thing is that it works for one site or sub site in a site collection, but not for more.

**Comment by BigEaseGueldi** [comment]
To clarify things a bit:
Once "Add an app" has worked, the Web Part will show up (thanks to solving 775). But in this case, "Add an app" does not work in case you have added the app on another sub site within the same site collection.

**Comment by BigEaseGueldi** [comment]
Hi @nickpape-msft - Should this be fixed already? In my opinion it isn't, but maybe I'm doing something wrong here. The sub site support is essential for the classic model. Without it, SPFx will have a hard time in classic...

Thanks!
Dirk

**Comment by RaspeR87** [comment]
If you want to install spfx web parts for on-prem too please take a look at my blog post -> [https://rasper87.wordpress.com/2018/04/26/provision-spfx-web-parts-to-classic-sites-part-3-install-spfx-web-part-to-sharepoint-site-web/](https://rasper87.wordpress.com/2018/04/26/provision-spfx-web-parts-to-classic-sites-part-3-install-spfx-web-part-to-sharepoint-site-web/)

**Comment by patmill** [comment]
Trying to tease this apart.  Here's what I have done and what I see.

Create a new solution with a webpart with 1.4.1, and upload it to the app catalog.  Make sure that global deployment is not enabled.
Create an SPSite with 3 subwebs sub1, sub2, and sub1/sub1
Activate the app on Sub 1.
    I can now add the webpart to pages in Sub1, but not Sub2, and not Sub1/Sub1
Activate the app on Sub 2.
    I can now add the webpart to pages in Sub2, as well as Sub1.


Are you folks seeing something different?

Is the issue that you want to add it at the root web, and have it available to all subwebs?

**Comment by RaspeR87** [comment]
Yes, with my solution above you can install it programmatically (or with web template automatically) in any kind of sub webs

**Comment by saulpreciado** [comment]
We are seeing the same behavior on SharePoint Online.

**Comment by patmill** [comment]
@saulpreciado - what exact behaviour are you seeing?  Can you confirm / deny each point I mentioned in my reply?

**Comment by saulpreciado** [comment]
@patmill, it's slightly different but same symptoms. We have a global solution with both extensions and web parts. What we have noticed is that when we use the solution with the extensions we are able to use the web parts only on the root site, not the sub sites. I'm not sure if there is already a thread for this particular scenario.

**Comment by JiyangXu** [comment]
Still experiencing issues when deploying the app on subsites, I am using the latest version of SharePoint Framework solution 1.6.0

**Comment by sudarshanreddy-thotapalli** [comment]
I had same issue, deleted the SPFX app from root site as well as all subsites under it and cleared from primary and secondary recylce bin and tried to add app it keeps throwing error
"A different version of this App is already installed with the same version number.  You need to delete the app from the site and the site recycle bin to install this version."

but there is no app in recycle bin as well as site collection, may I know how I can add the app again and get out of this issue?

**Comment by dg2000r** [comment]
Did anyone get a solution to this? - we're still experiencing the same thing in SP Online in May 2019. We have an app customizer deployed to a Modern Communication site, but can't add it to a Team subsite. We get the same error as the OP about version numbers, saying it's already installed.

**Comment by kadu-jr** [comment]
I just ran into this issue and, following [this](https://sharepoint.stackexchange.com/questions/207614/a-different-version-of-this-app-is-already-installed-with-the-same-version-numbe) post, I changed de version in my config/package-solution.json from "1.x" to "2.0". After redeploying it, I was able to add my webpart to a subsite. I am not sure if I will be able to upgrade the version in my parent site so I would say this is rather a workaround.

**Comment by patmill** [comment]
@dg2000r - Just to confirm the scenario - can you answer these questions when it isn't working?
1 - Did you deploy the solution to the tenant app catalog, or does your com site have a site-collection app catalog?
2 - Does your solution support tenant wide deployment, or do you need to 'add an app' on a site to use it?
3 - Do you have anything in the /sharepoint/assets folder in your development environment?  If so, what does it look like?
4 - What do you get from this API call (just type it into the browser)  https://yourtenant.sharepoint.com/comsitepath/_api/web/usercustomactions  ?
5 - What do you get from this API call
https://yourtenant.sharepoint.com/subwebpath/_api/web/usercustomactions  ?

4 and 5 would look like this for a comsite called 'comsite' with a sub site called 'subteamsite':
https://contoso.sharepoint.com/sites/comsite/_api/web/usercustomactions  and
https://contoso.sharepoint.com/sites/comsite/subteamsite/_api/web/usercustomactions

**Comment by dg2000r** [comment]
Thanks Pat - responses below:

1 - Did you deploy the solution to the tenant app catalog, or does your com site have a site-collection app catalog? Tenant app catalog

2 - Does your solution support tenant wide deployment, or do you need to 'add an app' on a site to use it? We used “Add an App” to add App to site then ran following to activate custom action:
At the root site: https://yourtenant.sharepoint.com/comsitepath :
Add-PnPCustomAction -ClientSideComponentId "<ID>" -Location ClientSideExtension.ApplicationCustomizer -ClientSideComponentProperties: '{<Properties>}' -Scope site
And at the subsite: https://yourtenant.sharepoint.com/comsitepath/subsite :
Add-PnPCustomAction -ClientSideComponentId "<ID>" -Location ClientSideExtension.ApplicationCustomizer -ClientSideComponentProperties: '{<Properties>}' -Scope web

3 - Do you have anything in the /sharepoint/assets folder in your development environment? If so, what does it look like? No, we don’t even see that folder in the site

4 - What do you get from this API call (just type it into the browser) https://yourtenant.sharepoint.com/comsitepath/_api/web/usercustomactions ?

A working communications site has: <?xml version="1.0" encoding="utf-8"?><feed xml:base="https://yourtenant.sharepoint.com/comsitepath/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</id><title /><updated>2019-05-13T08:59:57Z</updated><entry><id> https://yourtenant.sharepoint.com/comsitepath/_api/Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')</id><category term="SP.UserCustomAction" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DescriptionResource" type="application/atom+xml;type=entry" title="DescriptionResource" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ')/DescriptionResource" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/TitleResource" type="application/atom+xml;type=entry" title="TitleResource" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ')/TitleResource" /><title /><updated>2019-05-13T08:59:57Z</updated><author><name /></author><content type="application/xml"><m:properties><d:ClientSideComponentId m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:ClientSideComponentId><d:ClientSideComponentProperties>{"testMessage":"Test message"}</d:ClientSideComponentProperties><d:CommandUIExtension m:null="true" /><d:Description m:null="true" /><d:Group m:null="true" /><d:Id m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:Id><d:ImageUrl m:null="true" /><d:Location>ClientSideExtension.ApplicationCustomizer</d:Location><d:Name>{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}</d:Name><d:RegistrationId m:null="true" /><d:RegistrationType m:type="Edm.Int32">0</d:RegistrationType><d:Rights m:type="SP.BasePermissions"><d:High m:type="Edm.Int64">0</d:High><d:Low m:type="Edm.Int64">0</d:Low></d:Rights><d:Scope m:type="Edm.Int32">3</d:Scope><d:ScriptBlock m:null="true" /><d:ScriptSrc m:null="true" /><d:Sequence m:type="Edm.Int32">65536</d:Sequence><d:Title>AddJsCode</d:Title><d:Url m:null="true" /><d:VersionOfUserCustomAction>1.0.1.0</d:VersionOfUserCustomAction></m:properties></content></entry></feed>

*Note the lack of mention of the action in question (OurGoogleAnalytics) – which you do see if you look at the SITE level (instead of WEB):  https://reedelsevier.sharepoint.com/sites/relx-communities/_api/site/usercustomactions

<?xml version="1.0" encoding="utf-8"?><feed xml:base="https://yourtenant.sharepoint.com/comsitepath/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</id><title /><updated>2019-05-14T09:19:14Z</updated><entry><id>https://yourtenant.sharepoint.com/comsitepath/_api/_api/Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')</id><category term="SP.UserCustomAction" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DescriptionResource" type="application/atom+xml;type=entry" title="DescriptionResource" href="Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/DescriptionResource" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/TitleResource" type="application/atom+xml;type=entry" title="TitleResource" href="Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/TitleResource" /><title /><updated>2019-05-14T09:19:14Z</updated><author><name /></author><content type="application/xml"><m:properties><d:ClientSideComponentId m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:ClientSideComponentId><d:ClientSideComponentProperties>{"trackingID":"UA-xxxxxxxxx-1"}</d:ClientSideComponentProperties><d:CommandUIExtension m:null="true" /><d:Description m:null="true" /><d:Group m:null="true" /><d:Id m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:Id><d:ImageUrl m:null="true" /><d:Location>ClientSideExtension.ApplicationCustomizer</d:Location><d:Name>RelxAnalytics</d:Name><d:RegistrationId m:null="true" /><d:RegistrationType m:type="Edm.Int32">0</d:RegistrationType><d:Rights m:type="SP.BasePermissions"><d:High m:type="Edm.Int64">0</d:High><d:Low m:type="Edm.Int64">0</d:Low></d:Rights><d:Scope m:type="Edm.Int32">2</d:Scope><d:ScriptBlock m:null="true" /><d:ScriptSrc m:null="true" /><d:Sequence m:type="Edm.Int32">0</d:Sequence><d:Title xml:space="preserve"> RelxAnalytics</d:Title><d:Url m:null="true" /><d:VersionOfUserCustomAction>16.0.1.0</d:VersionOfUserCustomAction></m:properties></content></entry></feed>

5 - What do you get from this API call
https://yourtenant.sharepoint.com/comsitepath/subsite/_api/web/usercustomactions ?
The subsite has: <?xml version="1.0" encoding="utf-8"?><feed xml:base="https://yourtenant.sharepoint.com/comsitepath/subsite/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</id><title /><updated>2019-05-13T08:57:23Z</updated><entry><id>https://yourtenant.sharepoint.com/comsitepath/subsite/_api/Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')</id><category term="SP.UserCustomAction" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DescriptionResource" type="application/atom+xml;type=entry" title="DescriptionResource" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/DescriptionResource" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/TitleResource" type="application/atom+xml;type=entry" title="TitleResource" href="Web/UserCustomActions(xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/TitleResource" /><title /><updated>2019-05-13T08:57:23Z</updated><author><name /></author><content type="application/xml"><m:properties><d:ClientSideComponentId m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:ClientSideComponentId><d:ClientSideComponentProperties>{"trackingID":"UA-xxxxxxxxx-1"}</d:ClientSideComponentProperties><d:CommandUIExtension m:null="true" /><d:Description m:null="true" /><d:Group m:null="true" /><d:Id m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:Id><d:ImageUrl m:null="true" /><d:Location>ClientSideExtension.ApplicationCustomizer</d:Location><d:Name>OurGoogleAnalytics</d:Name><d:RegistrationId m:null="true" /><d:RegistrationType m:type="Edm.Int32">0</d:RegistrationType><d:Rights m:type="SP.BasePermissions"><d:High m:type="Edm.Int64">0</d:High><d:Low m:type="Edm.Int64">0</d:Low></d:Rights><d:Scope m:type="Edm.Int32">3</d:Scope><d:ScriptBlock m:null="true" /><d:ScriptSrc m:null="true" /><d:Sequence m:type="Edm.Int32">0</d:Sequence><d:Title xml:space="preserve">OurGoogleAnalytics</d:Title><d:Url m:null="true" /><d:VersionOfUserCustomAction>16.0.1.0</d:VersionOfUserCustomAction></m:properties></content></entry></feed>

**Comment by dg2000r** [comment]
Thanks Pat - I've added responses below:

1 - Did you deploy the solution to the tenant app catalog, or does your com site have a site-collection app catalog? Tenant app catalog

2 - Does your solution support tenant wide deployment, or do you need to 'add an app' on a site to use it? Used “Add an App” to add App to site then ran following to activate custom action:
At the root site: https://yourtenant.sharepoint.com/comsitepath :
Add-PnPCustomAction -ClientSideComponentId "<ID>" -Location ClientSideExtension.ApplicationCustomizer -ClientSideComponentProperties: '{<Properties>}' -Scope site
And at the subsite: https://yourtenant.sharepoint.com/comsitepath/subsite :
Add-PnPCustomAction -ClientSideComponentId "<ID>" -Location ClientSideExtension.ApplicationCustomizer -ClientSideComponentProperties: '{<Properties>}' -Scope web

3 - Do you have anything in the /sharepoint/assets folder in your development environment? If so, what does it look like? No, don’t even see that folder in the site

4 - What do you get from this API call (just type it into the browser) https://yourtenant.sharepoint.com/comsitepath/_api/web/usercustomactions ?
A working communications site has: <?xml version="1.0" encoding="utf-8"?><feed xml:base="https://yourtenant.sharepoint.com/comsitepath/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</id><title /><updated>2019-05-13T08:59:57Z</updated><entry><id> https://yourtenant.sharepoint.com/comsitepath/_api/Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')</id><category term="SP.UserCustomAction" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DescriptionResource" type="application/atom+xml;type=entry" title="DescriptionResource" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ')/DescriptionResource" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/TitleResource" type="application/atom+xml;type=entry" title="TitleResource" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ')/TitleResource" /><title /><updated>2019-05-13T08:59:57Z</updated><author><name /></author><content type="application/xml"><m:properties><d:ClientSideComponentId m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:ClientSideComponentId><d:ClientSideComponentProperties>{"testMessage":"Test message"}</d:ClientSideComponentProperties><d:CommandUIExtension m:null="true" /><d:Description m:null="true" /><d:Group m:null="true" /><d:Id m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:Id><d:ImageUrl m:null="true" /><d:Location>ClientSideExtension.ApplicationCustomizer</d:Location><d:Name>{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}</d:Name><d:RegistrationId m:null="true" /><d:RegistrationType m:type="Edm.Int32">0</d:RegistrationType><d:Rights m:type="SP.BasePermissions"><d:High m:type="Edm.Int64">0</d:High><d:Low m:type="Edm.Int64">0</d:Low></d:Rights><d:Scope m:type="Edm.Int32">3</d:Scope><d:ScriptBlock m:null="true" /><d:ScriptSrc m:null="true" /><d:Sequence m:type="Edm.Int32">65536</d:Sequence><d:Title>AddJsCode</d:Title><d:Url m:null="true" /><d:VersionOfUserCustomAction>1.0.1.0</d:VersionOfUserCustomAction></m:properties></content></entry></feed>

*Note the lack of mention of the action in question (OurGoogleAnalytics) – which you do see if you look at the SITE level (instead of WEB):  https://yourtenant.sharepoint.com/comsitepath/_api/site/usercustomactions

<?xml version="1.0" encoding="utf-8"?><feed xml:base="https://yourtenant.sharepoint.com/comsitepath/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</id><title /><updated>2019-05-14T09:19:14Z</updated><entry><id>https://yourtenant.sharepoint.com/comsitepath/_api/_api/Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')</id><category term="SP.UserCustomAction" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DescriptionResource" type="application/atom+xml;type=entry" title="DescriptionResource" href="Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/DescriptionResource" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/TitleResource" type="application/atom+xml;type=entry" title="TitleResource" href="Site/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/TitleResource" /><title /><updated>2019-05-14T09:19:14Z</updated><author><name /></author><content type="application/xml"><m:properties><d:ClientSideComponentId m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:ClientSideComponentId><d:ClientSideComponentProperties>{"trackingID":"UA-xxxxxxxxx-1"}</d:ClientSideComponentProperties><d:CommandUIExtension m:null="true" /><d:Description m:null="true" /><d:Group m:null="true" /><d:Id m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:Id><d:ImageUrl m:null="true" /><d:Location>ClientSideExtension.ApplicationCustomizer</d:Location><d:Name>OurGoogleAnalytics</d:Name><d:RegistrationId m:null="true" /><d:RegistrationType m:type="Edm.Int32">0</d:RegistrationType><d:Rights m:type="SP.BasePermissions"><d:High m:type="Edm.Int64">0</d:High><d:Low m:type="Edm.Int64">0</d:Low></d:Rights><d:Scope m:type="Edm.Int32">2</d:Scope><d:ScriptBlock m:null="true" /><d:ScriptSrc m:null="true" /><d:Sequence m:type="Edm.Int32">0</d:Sequence><d:Title xml:space="preserve"> OurGoogleAnalytics</d:Title><d:Url m:null="true" /><d:VersionOfUserCustomAction>16.0.1.0</d:VersionOfUserCustomAction></m:properties></content></entry></feed>

5 - What do you get from this API call
https://yourtenant.sharepoint.com/comsitepath/subsite/_api/web/usercustomactions ?
The subsite has: <?xml version="1.0" encoding="utf-8"?><feed xml:base="https://yourtenant.sharepoint.com/comsitepath/subsite/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml"><id>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</id><title /><updated>2019-05-13T08:57:23Z</updated><entry><id>https://yourtenant.sharepoint.com/comsitepath/subsite/_api/Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')</id><category term="SP.UserCustomAction" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/DescriptionResource" type="application/atom+xml;type=entry" title="DescriptionResource" href="Web/UserCustomActions(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/DescriptionResource" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/TitleResource" type="application/atom+xml;type=entry" title="TitleResource" href="Web/UserCustomActions(xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/TitleResource" /><title /><updated>2019-05-13T08:57:23Z</updated><author><name /></author><content type="application/xml"><m:properties><d:ClientSideComponentId m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:ClientSideComponentId><d:ClientSideComponentProperties>{"trackingID":"UA-xxxxxxxxx-1"}</d:ClientSideComponentProperties><d:CommandUIExtension m:null="true" /><d:Description m:null="true" /><d:Group m:null="true" /><d:Id m:type="Edm.Guid">xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</d:Id><d:ImageUrl m:null="true" /><d:Location>ClientSideExtension.ApplicationCustomizer</d:Location><d:Name>OurGoogleAnalytics</d:Name><d:RegistrationId m:null="true" /><d:RegistrationType m:type="Edm.Int32">0</d:RegistrationType><d:Rights m:type="SP.BasePermissions"><d:High m:type="Edm.Int64">0</d:High><d:Low m:type="Edm.Int64">0</d:Low></d:Rights><d:Scope m:type="Edm.Int32">3</d:Scope><d:ScriptBlock m:null="true" /><d:ScriptSrc m:null="true" /><d:Sequence m:type="Edm.Int32">0</d:Sequence><d:Title xml:space="preserve">OurGoogleAnalytics</d:Title><d:Url m:null="true" /><d:VersionOfUserCustomAction>16.0.1.0</d:VersionOfUserCustomAction></m:properties></content></entry></feed>

**Comment by dg2000r** [comment]
@patmill do you (or anyone else) have any other ideas here? We're still stuck on the same issue...
Thanks

**Comment by cverhelst** [comment]
@patmill We just encountered the same issue at a client. In our case our SPFx webpart was a new SPFx 1.7.1 project. App is added in a site collection app catalog, installed at the root web with no issues. When trying to add it to a subweb, we get the same error:

_A different version of this App is already installed with the same version number. You need to delete the app from the site and the site recycle bin to install this version._

**Comment by albegut** [comment]
Any progress on this problem? The only solution I see is to deploy the app as tenant-scoped although it is not what the client requires

**Comment by Dangerous-Mind** [comment]
I have the same problem on SPFx  1.11. 
The app has a Feature that creates columns, content types, libraries and lists needed by the app on each of the subsite it is deployed to so it can not be deployed Globally.

@cverhelst Solution solved it but I'll have to create new solutions for each of the new app I'm asked to add.
Any news on this issue @patmill?

**Comment by EA12** [comment]
We encountered the same at a customers tenant.

A different version of this App is already installed with the same version number. You need to delete the app from the site and the site recycle bin to install this version.

This is a show stopper for us. It should be possible to add the same webpart to sub-webs.
After more than 4 years, still no solution. :(

**Comment by AJIXuMuK** [comment]
Hi @EA12 - could you please explain this one: 

> A different version of this App is already installed with the same version number

**Comment by AJIXuMuK** [comment]
Just to follow up a bit.

Just tested the scenario with adding the same SPFx app to the root web and then to the subsite.
It works with no issue.
It also correctly provisions SharePoint assets (fields, content types, lists).

Attached is my sample.
[fc-elements.zip](https://github.com/SharePoint/sp-dev-docs/files/7464376/fc-elements.zip)

@jaredbuttars - could you please check if that's still an issue for you?
