### ISSUE TITLE
ContextMenu doesnt appear on Picture Library

### ISSUE THREAD

**Issue by RafatRashid** [SharePoint/sp-dev-docs#5834]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question
I am developing a ContextMenu command set for sharepoint online for my tenant. I developed the program and tested and from localhost it was working as expected. When I deployed the extension and installed the extension in my site as it is not tenant wide deployment, the extension appeared for all "Document Library" of the site but its not appearing for "Picture Library".

I am assuming my elements.xml definition may have some issue. Here are the props of the xml:

Title="CopyImage"
        RegistrationId="109"
        RegistrationType="List"
        Location="ClientSideExtension.ListViewCommandSet.ContextMenu"
        ClientSideComponentId="37a7a0eb-0965-4e17-84bf-fde2ca1312ec"

I am guessing the issue might be "101" and "List". I found a possible value of RegistrationId=109 from [this issue](https://github.com/SharePoint/sp-dev-docs/issues/4691), tried this one too, but didnt appear and its still appearing in the document libraries. I would be very greatful if anyone can point me in the right direction.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.19
- **Browser(s)**:. Chrome v83
- **Tooling**: VS Code | SPFx v1.10.0

**Comment by andrewconnell** [comment]
If you changed it after the fact, that won't work. You'll need to uninstall and reinstall the extension to reapply the install

**Comment by RafatRashid** [comment]
Yes it worked after reinstalling But shouldn't updating the extension from the site work?

**Comment by andrewconnell** [comment]
No. For this, you need to understand how things work under the covers.

SPFx extensions, specifically app customizers & command set extensions, are registered in a SharePoint site using the old skool Feature schema (hence the reason there's a **./sharepoint/assets/elements.xml** file. When you install the app, it activates the Feature. Features aren't reactivated when you update the code... this is how it's worked going back to when they were introduced in WSS v3 (~2007).

So... in this case, because it was already there, it wasn't updating when you changed it because your changes weren't being applied because a Feature wasn't being reactivated. You MAY be able to get the change to happen if you version the solution package and go through the upgrade process... but I'm not 100% certain that would work.

**Comment by RafatRashid** [comment]
Yes if I remember correctly I did bump the version and upgraded but didnt work. Reinstalling did. Thanks a lot for the help. I am closing the issue then.
