### ISSUE TITLE
to debug a remote event handle, does my computer need to be accessible from outside the company?

### ISSUE THREAD

**Issue by dawei-medaitek** [SharePoint/sp-dev-docs#5881]
please see my question in the title , thanks very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf58506-a073-0509-aa8e-9cfe28e9fac6
* Version Independent ID: 976c3860-d9a6-04ec-8b0f-8dae5fbdb923
* Content: [Debug and troubleshoot a remote event receiver in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/debug-and-troubleshoot-a-remote-event-receiver-in-a-sharepoint-add-in#feedback)
* Content Source: [docs/sp-add-ins/debug-and-troubleshoot-a-remote-event-receiver-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/debug-and-troubleshoot-a-remote-event-receiver-in-a-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
The endpoint must be accessible from SharePoint. If you're hosting it on your workstation, then yes. NGrok is a free & common people use for this situation.

However... I'd strongly encourage you to look at webhooks instead of remote event receivers (RER). RER's are the old way of doing it and the recommended approach is to use webhooks instead.
