### ISSUE TITLE
Pnp-JS-core in the right api set

### ISSUE THREAD

**Issue by sganta** [SharePoint/sp-dev-docs#589]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I am Sharepoint Developer trying to decide which client side API to use. I have been mostly using javascript object model. I have been following the guideline presented in this [github page](https://github.com/SharePoint/sp-dev-docs/blob/staging/docs/general-development/choose-the-right-api-set-in-sharepoint.md). 

However I am not sure where Pnp-JS-Core would fall because it is based on  REST API which is usually reserved for provider hosted scenarios. Does this page need to be updated?

**Comment by waldekmastykarz** [comment]
Have you seen this video: https://www.youtube.com/watch?v=5GwEvvHFq5s&list=PLR9nK3mnD-OUnJytlXlO84fQnYt50iTmS&t=1s&index=9? Even though it's primarily focusing on the SharePoint Framework, it compares other ways to communicate with SharePoint in client-side solutions such as JSOM, REST and PnP JS Core.

**Comment by sganta** [comment]
Thank you, I am going to follow that channel. I am disappointed that JSOM is deprecated. It is so much easier to work with. Working with REST api  is so tough and error prone. I can only pray that pnp-js-core is going to grow and match JSOM.

**Comment by patrick-rodgers** [comment]
Hi @sganta - the pnp-js-core library will never be a direct equivalent for the JSOM as they are based on different APIs and have then access to different capabilities. We do try and provide a lightweight wrapper around the REST api with the goal of making it easier to work with. If you haven't [please check out the developer guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide). You can also [report an issue](https://github.com/SharePoint/PnP-JS-Core/issues) to let us know of missing features and we'll certainly see if they can be added. Can't promise 100% all features can be supported but we'll certainly try if you are blocked due to missing functionality.

Going to close this one but do please reopen should we need to revisit the discussion. Thanks!
