### ISSUE TITLE
PropertyPaneDropDown Selected=False after click 

### ISSUE THREAD

**Issue by jm06** [SharePoint/sp-dev-docs#5899]
I am new to this as I used to develop VB .Net desktop applications. Quite a learning curve. 

I added a DropDown (office-ui-fabric-react/lib/components/Dropdown) on a propertypane. 

![Annotation 2020-06-17 142915](https://user-images.githubusercontent.com/16796220/84904276-06e63a80-b0a7-11ea-834d-01f220d9a719.jpg)

The dropdown is populated dynamically and displays a set of lists holding a targeted content type. The idea is to select one and use the Title of the list in a call below
this.context.spHttpClient.get(this.context.pageContext.web.absoluteUrl + `/_api/web/lists/GetByTitle('${this.properties.listName}')/items?$orderby=Order1`

When clicked, the item is selected and displays. The onChange is fired. The selectedKey is populated but nothing else happens. my properties remains Undefined. 

![SelectedFalse1Annotation 2020-06-17 140422](https://user-images.githubusercontent.com/16796220/84903912-9808e180-b0a6-11ea-9263-0fab1ddbe626.jpg)

If this is a bug, is there a way round? How do you capture the selected value? Any code suggestions? 

Jean-Marc

**Comment by andrewconnell** [comment]
First, this is more of a question about Office UI Fabric React vs. SharePoint... so you should post the question in their issue list/forums.

Second, this is by design & how the dropdown control works. The `selected` property is used to tell the dropdown in which item should be selected, but only from a presentation POV.

You use the `selectedKey` to get the value of the item that was selected. Ideally, you update the object selected to set it's `selected` property to true and update the state with the updated collection of items so it's re-rendered and shows the selected item.
