### ISSUE TITLE
e.navigationPreload is undefined On FireFox & IE11

### ISSUE THREAD

**Issue by jason-appliedis** [SharePoint/sp-dev-docs#5967]
## Category

- [x] Bug

## Describe the bug

When I load a SPFx custom list extention in FireFox and IE11 it errors in the SPListWebpack.js file Line 11332 in Production code 

 "e.navigationPreload is undefined"

![Errorsplistwebpack js](https://user-images.githubusercontent.com/59878375/86035742-d12c4480-ba0a-11ea-8cba-85b6927f0e2b.png)

## Steps to reproduce

1. Create a custom list SPFx solution on V 1.10.0
2. Load webpart in FireFox or IE

## Expected behavior

Webpart Loads 

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: Sharepoint Online
- **Framework**: SPFx 1.10.0
- **Browser(s)**:Firefox , IE11
- **Tooling**:VS Code
- **Additional details**: *

REPO to clone : https://github.com/jason-appliedis/BugReportForSPFx
Change the serve.json to add the appropriate SP List Url for your environment
run npm install --download packages
gulp serve 
Open in firefox
inspect console
 "e.navigationPreload is undefined"

Not supported in FireFox Ref
https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager

Any help/guidance for a polyfill to work around this would be great! 

## Submission guidelines

> - If you have technical questions about the framework, we monitor the tags #spfx, #spfx-webparts, and #spfx-tooling on [SharePoint StackExchange](http://sharepoint.stackexchange.com).
#spfx
#spfx-listextension
> - Remember to include sufficient details and context.

**Comment by AJIXuMuK** [comment]
Hi @jason-appliedis - sorry for the long delay, lost track of this item due to metadata issues.

For IE 11 - the support has been deprecated.
For the Firefox - it doesn't "trust" the dev certificate even if you run `gulp trust-dev-cert`.
Just copy the `debugManifestFileUrl` (https://localhost:4321/temp/manifests.js), and open it in a separate tab.
Firefox will warn you regarding the privacy/safety issues. Just select to proceed.
After that Firefox will allow to debug localhost solutions without problems.
