### ISSUE TITLE
Incorrect O365 Nav Bar

### ISSUE THREAD

**Issue by debyeleong** [SharePoint/sp-dev-docs#5972]
The O365 suite nav bar was not displayed properly in my hosted SharePoint. What might be the issues?

![image](https://user-images.githubusercontent.com/25447411/86056542-5575cc00-b9f9-11ea-9de3-50c0b152dbe3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
Are you testing SPFX Web Part in localhost ? The Nav Bar in localhost is different with SharePoint Online Tenant, this is by design.
If you want to testing in SharePoint Online within VScode, change url in .vscode->launch.json:
![Image 15](https://user-images.githubusercontent.com/28797671/86110509-3a3db600-baf8-11ea-8257-b77218133f11.png)
And run in  Hosted workbench mode:
![Image 16](https://user-images.githubusercontent.com/28797671/86110619-61948300-baf8-11ea-802c-e9285f36cf15.png)

Reference:

[Debug SharePoint Framework solutions in Visual Studio Code](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode)
