### ISSUE TITLE
Problem popup when remove SPFx Teams Tab

### ISSUE THREAD

**Issue by VuongQuyen** [SharePoint/sp-dev-docs#5979]
## Category

- [x] Question
- [x] Bug

## Question

I have deployed SPFx Teams Tab normally.
But each time I try to remove it, a error popup appears.

![A8809FF8-E59C-4D12-857B-D287E61D3167](https://user-images.githubusercontent.com/30196941/86199315-fee8c900-bb83-11ea-9a5e-50039975651e.png)

Can someone explan what exactly this popup is and can I skip this popup ?

Thanks.

**Comment by cuongnv1412** [comment]
@andrewconnell 
Any update about this problem?

**Comment by sebastienlevert** [comment]
I'm seeing the same thing on every tab we delete. While the `_api/web/hostedapps/getbyid(9)/delete` request seems to work and gets a 204, the service worker gets a cancelled request :

![image](https://user-images.githubusercontent.com/7620955/88361713-f8470f00-cd47-11ea-9537-d1cefbe9ac43.png)

![image](https://user-images.githubusercontent.com/7620955/88361722-fe3cf000-cd47-11ea-8bad-a5b82297fb99.png)

I feel this is on the Teams / SPFx service and we can't really do anything... But it's definitely not a "great" experience for users...

**Comment by lokimeyburg** [comment]
So this is happening because the SPFx tab takes longer to delete than the timeout Teams has set, at which point we show a "force-delete" dialog to the user. The original problem was that some tabs would _never_ give us the signal to remove their tab, so users couldn't delete them at all: hence the timeout + force delete dialog. 

I'm reluctant to extend the timeout on Teams' side (because I believe the 30 seconds to delete the tab should be enough). I think the better option here would be for SPFx to either speed up the removal or send back a `removeEvent.notifySuccess()` event as soon as possible and unload the app's data asynchronously (instead of synchronously waiting for the long-running process to return).

Let me follow-up with the SPFx team.

**Comment by nbelyh-visualstrategy** [comment]
Got the same issue. Is there any progress? As of today, this still seems to happen - the SPFx takes too long to delete, Teams times out and shows "force remove" thing.

**Comment by nbelyh** [comment]
Run into the same issue. Is there any progress? As of today, this still seems to happen - the SPFx takes too long to delete, Teams times out and shows "force remove" thing.

**Comment by AJIXuMuK** [comment]
The issue has been fixed and will be rolled out WW in the next couple of weeks.

**Comment by AJIXuMuK** [comment]
should be WW by now
