### ISSUE TITLE
Node.js v8 support is deprecated in SPFx V1.11.0

### ISSUE THREAD

**Issue by PrasadKasireddy** [SharePoint/sp-dev-docs#6073]
Question - Node.js v8 support is deprecated as per the last [SPFx V1.11.0 release note](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0) Is still support nodejs v8.x.x for SharePoint Server 2016?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Jerry0527** [comment]
This will depend on your environment.

If you are build SPFX Solution for SharePoint 2016 Server with Feature Pack 2, it's suggested to still use SharePoint Framework v1.1.0 which should still supported Node.js v8, this is the description from the Official site:

"Because SharePoint Online and SharePoint 2016 have different release cycles for new capabilities, they also have different capabilities when it comes to the SharePoint Framework. SharePoint Online always uses the latest version of the SharePoint Framework, but SharePoint 2016 only supports the version that matches the server-side dependencies of the deployed packages.

SharePoint 2016 Feature Pack 2 supports SharePoint Framework client-side web parts hosted on classic SharePoint pages built by using the SharePoint Framework v1.1.0. This means that when you are targeting the SharePoint 2016 platform, you need to use the SharePoint Framework v1.1.0 due to the server-side version dependencies."

[SharePoint Framework development with SharePoint 2016 Feature Pack 2](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support)
