### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by MDBosa** [SharePoint/sp-dev-docs#6079]
Infinite loop when using trigger like 'create/update item/files' is a shame. The flow is self triggering endlessly

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc176ce2-e245-8c2a-62a9-29f0fa3f755a
* Version Independent ID: 50df0c72-d567-a572-a4db-80730c5881f7
* Content: [Guidance - Migrate from classic workflows to Power Automate flows in SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows)
* Content Source: [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by andrewconnell** [comment]
Sorry, but I'm unclear in what you are saying here. Are you reporting a bug? If so, it sounds like you're talking specifically about Flow/PowerAutomate. In that case, best to report a bug to them.

**Comment by zylantha** [comment]
MDBosa is referring to the significantly different behaviour in Power Automate vs SharePoint 2010 workflows on the re-entrant nature of flows triggered "on an item change".  

In SharePoint 2010 where a workflow is triggered by an update of an item, the workflow can freely make further updates to the item, without those updates triggering further instances of the same workflow (and hence creating an infinite loop that MDBosa mentioned).

The migration of the same logic from a SharePoint 2010 workflow (where re-triggering of an item change workflow from within that same workflow does not need to be specifically and carefully dealt with) to a Power Automate flow is particularly tricky and can require an entire rewrite to handle the different behaviour of the platform.  Even with several years of PA experience beneath my belt, I still regularly fall into the error of causing "on item update" flows to be called recursively, and doing so will eventually cause SharePoint outages to occur when the throttle limits are hit (and you probably won't know about it until there is a P1 incident called as a result of such an infinite loop in the workflow).

This special pain point in undertaking migration from SharePoint 2010 workflows over to Power Automate should be at least mentioned in these documents, since they can make the transition particularly tricky for people who aren't already experts in the quirks and nature of Power Automate, and due to the severe ramifications of falling foul of these traps.

**Comment by MDBosa** [comment]
Tkx Zylantha for the clarification of this pain point.
