### ISSUE TITLE
SPFx v1.11 solution name skipped

### ISSUE THREAD

**Issue by altfo** [SharePoint/sp-dev-docs#6241]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

When i use yo @microsoft/sharepoint in the main folder where all solutions & projects are in, the command automatically takes the last solution as the solution and creates the webpart or extension project within the solution. There is no choice to choose my own solution. But if i run the same command outside of the solutions folder ex: completely different folder outside of my list of solutions, it asks for solution name. Don't know whether it is a bug or feature. v1.10 always asks for solution name, i would better have that inside assuming last solution name automatically.

## Environment details (*development & target environment*)

- windows 10 with Visual studio code
- SPFx v1.11
- npm 6.14.4
- PowerShell Command

**Comment by Jerry0527** [comment]
Same action in my side:

![Snipaste_2020-09-07_15-49-38](https://user-images.githubusercontent.com/28797671/92361950-cc2df480-f121-11ea-90aa-8c7c3bff3ea9.png)
This should be a change in SPFX 1.11.0, as directly generating this line:
Add new Web part to solution helloworld-webpart as capture above.

**Comment by andrewconnell** [comment]
Can you see if you have a **.yo-rc.json** file in your root folder or in a folder above it? This file will be hidden on non-Windows systems (ie: macOS & Linux).

If so, this is by design. The generator looks for this file to determine "is this component being added to an existing solution" and if so, it skips that question.

**Comment by StfBauer** [comment]
This especially happens when the option 'Create new Folder' is selected during the generator. There is one `.yo-rc.json` in the SPFx root and one file in the parent folder.
A workaround to this issue is to move (not copy) the parent folder `.yo-rc.json` to the child folder and create the next project with a folder previously before the generator run.

**Comment by Jerry0527** [comment]
@andrewconnell, Thanks for sharing the information.
I checked the ".yo-rc.json" in the root folder, so this should be by design:
![Snipaste_2020-09-08_15-01-51](https://user-images.githubusercontent.com/28797671/92443586-4aeb6600-f1e4-11ea-960d-a2bc4644d07f.png)

**Comment by andrewconnell** [comment]
@Jerry0527 

Maybe... but the OP wasn't clear if this was a new project they were creating or not. Will wait for them to respond...
