### ISSUE TITLE
Update Command Set Title based on the column value

### ISSUE THREAD

**Issue by KodulkarNilesh** [SharePoint/sp-dev-docs#6245]
## Category

- [x] Bug

## Describe the bug

> Command Set title is not getting updated based on the selected item column value. 

## Steps to reproduce

![image](https://user-images.githubusercontent.com/63402109/92442096-f1c40800-f1cc-11ea-98f3-07aaf7afec64.png)

## Expected behavior

Command Set title should be dynamic

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js V 8.x
- **Browser(s)**: Chrome & Edge 
- **Tooling**: VS Code | SPFx v1.11.0

**Comment by kongmengfei** [comment]
Hi KodulkarNilesh,

I am able to reproduce this issue. `compareOneCommand.title = "xxx"` only take affect in `onInit()` instead of `onListViewUpdated`.

As a possible workaround, you may define multiple commands and switch the visibility of these commands.to implement the business logic.

Baker Kong
Microsoft SharePoint Community Support

**Comment by KodulkarNilesh** [comment]
Thanks for confirmation.
The requirement is to update the title for the "selected item" and I think event.selectedRows[0] will not be available in OnInit()

**Comment by andrewconnell** [comment]
This is by design... the title for a command set is defined in the component's manifest file. It's done like this to support localization of the command set title. Dynamically switching the title is not supported.
