### ISSUE TITLE
Node_Modules missing

### ISSUE THREAD

**Issue by Faisal-developer** [SharePoint/sp-dev-docs#6285]
I have updated "@fluentui/react": "7.133.1" in package.json but after executing npm install. 
Following folders are missing in node_modules
node_modules\@fluentui\react\lib\utilities
PS: There are no folder on the following path "node_modules\@fluentui\react\lib"

**Comment by Faisal-developer** [comment]
Now I am getting this error on npm install
npm ERR! 404  '@fluentui/react@7.133.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'source'
npm ERR! 404

**Comment by Faisal-developer** [comment]
But when  I install office-ui-fabric-react :7.133.1.It contains folder.

**Comment by andrewconnell** [comment]
That sounds like it's more of an issue with the Fluent UI NPM package than a SharePoint thing... can you verify this is specific to SharePoint because if it isn't, it should be reported to the Fluent UI team (their issue list in their repos) since they are the ones that could address it, not the SharePoint team.
