### ISSUE TITLE
MSAL implementation for AadHttpClient ?

### ISSUE THREAD

**Issue by PieterHeemeryck** [SharePoint/sp-dev-docs#6360]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is there an ETA, timeline, progress, info that can be shared on the MSAL implementation for AadHttpClient? @VesaJuvonen 

The current ADAL implementation is giving some issues when 3rd party cookies are being blocked by the end user's browser. Do I understand it correctly that using MSAL (with or without the use of AadHttpClient) will solve this issue?

See also: #6177, #5966, #5376, #4476, #2685

**Comment by mrtnJoh** [comment]
Is it possible to get an update on this?

**Comment by patmill** [comment]
Sorry for not responding - this has shipped for a while now.  However, moving to MSAL does _not_ make ITP / 3p cookie blocking 'great'.  In these scenarios, we will need to do a full page redirect in order to authenticate / get tokens.  This is expected.  We are working with the AAD / MSAL team on a longer term plan to not have this happen, but there is no timeline.

**Comment by PieterHeemeryck** [comment]
Thanks for the update anyhow! Better late than never! :) cheers
