### ISSUE TITLE
How Can we open OOTB SharePointOnline List Display, Edit, and New forms in the spfx web part programmatically from the spfx web part

### ISSUE THREAD

**Issue by anomepani** [SharePoint/sp-dev-docs#6415]
## Category

- [X] Question

## Question

>  I would like to know How can I open OOTB SharePoint List Display, Edit, and New forms in the spfx web part programmatically from the spfx web part in SharePoint Online?

I have three button  Edit, New, Display in My Custom web part, and want to open the Right Side Panel with the appropriate form.

Thanks in advance for Any suggestion or way.

**Comment by bcameron1231** [comment]
Hi, AFAIK, there isn't a way to do this. You will have to use the Fluent UI Panel to launch yourself as this isn't something that is callable.  Second, it may be worth looking into the React-List-Form web part from the SP-Dev-fx-webparts repository and see if you can modify it to fit within your solution. https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-list-form

**Comment by dwd5** [comment]
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/37169995-allow-us-to-develop-custom-modern-forms-with-custo

We used JSLinks to set redirection to a custom page with SPFx customization, but because of **MC222880** it's no longer possible. MS Support advised us to use PowerApps, it's not possible in our case. So, I'm curious too what else is using by the community.

**Comment by mdissel** [comment]
Any news on this request?
