### ISSUE TITLE
How to change the background color Quick Links web part on Modern Site Page 

### ISSUE THREAD

**Issue by kanchankumbhar2** [SharePoint/sp-dev-docs#6421]
## Category

- [ ] Question

## Question

How to change the background color Quick Links web part on Modern Site Page

 
![image](https://user-images.githubusercontent.com/55887332/97449083-5131cf00-1957-11eb-93fc-d1e1c96d436b.png)

Above is the image of Quick Links web part from Modern Site Page. My Requirement is I wanted to change the background color of each web part with different color. e.g If I have 2 quick links web part on One Page. First web part I'll use blue and second red as background color.

As I know we don't have script editor web part on modern page, how can I inject custom css on this page
## Environment details (*development & target environment*)

Note :  I know two aproaches
1. Modern Script editor (Refer [link](https://medium.com/niftit-sharepoint-blog/add-the-script-editor-webpart-back-to-sharepoint-modern-experience-688a7b7208e4)
2. SPFX Extention.

Do we have any option other than this ? And What is best approach to achieve this type of functionality?

- **SharePoint Online Modern Site**

> *Thanks for your contribution! Sharing is caring.*

**Comment by bcameron1231** [comment]
Hi, unfortunately, this isn't a supported scenario (to modify the out of the box components using script injection or css overrides), so we aren't able to provide support for this. You have mentioned some possible approaches that would work, but be advised they could break in the future.

My recommendation, if you have a need for customizing web parts, to create your own using SPFx. We have a bunch of samples in the [samples repository](https://github.com/pnp/sp-dev-fx-webparts) and we also have a tiles web part in the PnP Starter Kit that you could use as a starting point instead of starting from scratch. You can find the tiles web part [here](https://github.com/pnp/sp-starter-kit/blob/master/documentation/components/wp-tiles.md).

**Comment by kongmengfei** [comment]
Hi kanchankumbhar2,

There is a 3rd party SPFx web part that could render links as tiles.

![part-tiles](https://user-images.githubusercontent.com/57654821/97521137-deb50380-19d7-11eb-844e-61f91a5b28a5.gif)

You can change its background colour with tiny modifications on its source code:

- https://github.com/pnp/sp-starter-kit/blob/master/solution/src/webparts/tiles/components/tile/Tile.tsx

Baker Kong
Microsoft SharePoint Community Support

**Comment by kanchankumbhar2** [comment]
Thank you @kongmengfei . For time being it worked for me
