### ISSUE TITLE
Navigation is not displayed

### ISSUE THREAD

**Issue by raclettierer** [SharePoint/sp-dev-docs#6440]
Embedding a page is useless if the top navigation and mega menu are not displayed.
Are there workarounds or additional settings to display the navigation elements?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef9b82d-5475-c5fa-ac7a-7005558e06f1
* Version Independent ID: 1d9d4923-c44f-b00b-a553-60c73ed8b8e6
* Content: [Embedding modern SharePoint pages in Microsoft Teams as personal apps (preview)](https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams)
* Content Source: [docs/features/embed-pages-to-teams.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/features/embed-pages-to-teams.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by Amos-MSFT** [comment]
This is by design.There is no native navigation, header, or footer on embedded pages.
![image](https://user-images.githubusercontent.com/56672877/98332202-30ddd080-2039-11eb-9fd6-c8ed6a6b0c5f.PNG)
You could get the information here:https://docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams
Amos Wu
Microsoft SharePoint Community Support
