### ISSUE TITLE
Field Customizer context does not provide access to the list

### ISSUE THREAD

**Issue by IvanTheBearable** [SharePoint/sp-dev-docs#6448]
## Category

- [x] Bug

## Describe the bug

Neither the ```FieldCustomizerContext``` nor the ```IFieldCustomizerCellEventParameters``` objects provide any mechanism to identify the list the field being rendered belongs to.

There is a ```context.pageContext``` property which has a ```list: SPList``` property. There is a lot of example code out there using this property but it only works by accident. If the field is being rendered on a standard list view page then ```context.pageContext.list``` will happen to point to the list that the field belongs to. But, if the field is being rendered in a list web part on a site page then ```pageContext.list``` will be the *Site Pages* library.

## Steps to reproduce

1. Create a Field Customizer and attach it to a list
1. Add a *List* web part to a *Site Page*
1. Use a debugger to break in your ```onRenderCell``` method
1. Try to find the identity of the source list in any of the available data.

## Expected behavior

There should be some sort of ```list``` property on the context or the event identifying the list the field belongs to.

## Environment details (*development & target environment*)

Sharepoint Framework 1.11.0
TypeScript 3.3.4

**Comment by IvanTheBearable** [comment]
I found a partial workaround. ```event.listItem``` contains a *FileRef* property that can be used to work out the list URL.

This works for my specific use case

```
private getListUrlFromEvent(event: IFieldCustomizerCellEventParameters): string {
    const fileRef: string = event.listItem.getValueByName('FileRef');
    const i = fileRef ? fileRef.lastIndexOf('/') : -1;
    return i >= 0 ? fileRef.substring(0,i): null;
}
```

The URL processing would need more work to handle a library with folders.

**Comment by AJIXuMuK** [comment]
Hello @IvanTheBearable - sorry for the long delay, missed this one due to issues with the tagging.

You can access the list view accessor using `this.context.tryGetListView()`. Currently this object provides access to the columns only.
But we're actively working to provide additional context in there:
- basic list info
- view info
- rows
- selected rows
- filters and sorting

We're planning to ship it in one of the upcoming releases.

If you have any other ideas for enhancements, please post them to one of the following discussions:
- [Command Sets](https://github.com/SharePoint/sp-dev-docs/discussions/7375)
- [Field Cutomizers](https://github.com/SharePoint/sp-dev-docs/discussions/7407)
- [Application Customizers](https://github.com/SharePoint/sp-dev-docs/discussions/7406)
