### ISSUE TITLE
Dead link Excel Services SP 2010 REST API Syntax

### ISSUE THREAD

**Issue by jchable** [SharePoint/sp-dev-docs#6491]
Link https://www.microsoft.com/en/microsoft-365/blog/2009/11/05/excel-services-in-sharepoint-2010-rest-api-syntax/ is not working anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8564819-15b1-cd40-8208-623126b7bf3b
* Version Independent ID: d7af096d-2f24-bcc7-e34a-a391e6ceb1a4
* Content: [Advanced Scenarios and Additional Samples](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/advanced-scenarios-and-additional-samples)
* Content Source: [docs/general-development/advanced-scenarios-and-additional-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/advanced-scenarios-and-additional-samples.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by bcameron1231** [comment]
Hi, when I click on the link "Excel Services REST API Syntax" it correctly brings me to the correct page.

**Comment by jchable** [comment]
Hu @bcameron1231, please find here my screenshot of the page :

![image](https://user-images.githubusercontent.com/10860719/99890869-bc04ca80-2cb7-11eb-93cd-0107ae2a6ac1.png)

**Comment by nanddeepn** [comment]
Hi,
This is happening due to the locale.
When I click the link - `Excel Services REST API Examples` , it takes me to below URL:
https://www.microsoft.com/en-in/microsoft-365/blog/2009/11/04/simple-access-to-spreadsheet-data-using-the-excel-services-2010-rest-api/

Notice `en-in` in the URL.
However, it works with en-US. In short, for non-US locale it seems to be breaking.
