### ISSUE TITLE
In the example 'Add Jquery Accordian' , we are loading the typings locally. It should loading globally in the typings folder (instead of @types/jquery)as its a non-module library

### ISSUE THREAD

**Issue by grvmithas** [SharePoint/sp-dev-docs#652]
In the example 'Add Jquery Accordian' , we are loading the typings locally. It should loading globally in the typings folder (instead of @types/jquery) as its a non-module library. The current code is not working.

Also, jquery should be registered as a non-module script by below using code where path could be local to the solution.
```
"jquery": {
  "path": "https://code.jquery.com/jquery-2.1.1.min.js",  
  "globalName": "jQuery"
},
```

**Comment by brunoslam** [comment]
where do you put that code?

**Comment by nickpape-msft** [comment]
`In the example 'Add Jquery Accordian' , we are loading the typings locally. It should loading globally in the typings folder (instead of ) as its a non-module library.`

I'm not quite sure what you mean by this. In the example, we add the typings by installing `@types/jquery`. You can load @types packages using one of a couple methods:

* Add an import (e.g. `import * as $ from 'jquery'`). The typings should be automatically resolved.
* Alternately, add a triple slash reference (e.g. `/// <reference types='jquery' />`).
* Lastly, if you want the jQuery typings to be available even when a module has not imported jQuery, you could add the typings to the list of ambient types by updating `tsconfig.json` with the following field:
    ```
    {
        "compilerOptions": {
            "types": [
                "jquery"
            ]
        }
    }
    ```

**Comment by grvmithas** [comment]
Hi nickpape-msft,

Sorry for the confusion. I followed the steps in the example to create  Jquery-Accordian demo. However, I encountered errors while building the project. Error snapshots are attached.
[Compilation errors in index.d.ts.docx](https://github.com/SharePoint/sp-dev-docs/files/1132888/Compilation.errors.in.index.d.ts.docx)

I observed that the issue was due to missing **typings.json** files for jquery as well as jqueryui. I added the files and it started building correctly. Somehow, the commands
 "npm install --save @types/jquery
npm install --save @types/jqueryui"

were not adding the typings correctly.

Also, I observed that on marking a class **default**, I was not able to import them. I had to remove the default keyword before class name for it to get imported correctly. Not sure what was the cause for this.

Thanks,
Gaurav Mithas

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
