### ISSUE TITLE
Register-PnPAzureADApp is not recognized

### ISSUE THREAD

**Issue by brittanyru** [SharePoint/sp-dev-docs#6542]
I just installed PnP PowerShell and the article (https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning) mentions that I have to use `Register-PnPAzureADApp` however when doing so I get an error that the term `Register-PnPAzureADApp` is not ercognized as the name of a cmdlet. Is there something else I need to do?

**Comment by Amos-MSFT** [comment]
The article you shared uses a version of PnP PowerShell that is currently in pre-release and planned to GA in January 2021.
![image](https://user-images.githubusercontent.com/56672877/101456576-3a779280-396f-11eb-9c1f-5318a0610c36.png)
The latest officially released version is 3.26.2010.0. This cmdlet is not available in this version.
To view all cmdlets, enter:
`Get-Command -Module SharePointPnPPowerShell*`
My test result for your reference:
![image](https://user-images.githubusercontent.com/56672877/101456901-b1ad2680-396f-11eb-9448-0d03b88fb4dc.png)
Amos Wu
Microsoft SharePoint Community Support

**Comment by brittanyru** [comment]
Thanks @Amos-MSFT .. Isn't there a way to walkthrough the article without the preview release of PnP? I remember the article has been there for a while but I never walked through it. 

Also, if I want to install the preview version of PnP PowerShell, how do we do it? Yesterday I went through the installation steps, and seems like I didn't get the latest version. Clarification is needed for the article. Thank you.

**Comment by bcameron1231** [comment]
There isn't a way to walk through the article without the preview version. Azure PowerShell team made updates to Azure Functions which required PowerShell core, which the old commandlets could not run on. Currently, you will need the preview version.

Information on installing PnP Powershell can be found on the Github Repo. Make sure you uninstall any previous version of the PnP Module.
https://github.com/pnp/powershell

Be aware of the Important Changes that have happened since the previous verison of PnP Powershell.
https://github.com/pnp/powershell#important-changes

**Comment by brittanyru** [comment]
Thanks Beau.
