### ISSUE TITLE
Get coments from list item

### ISSUE THREAD

**Issue by firechhe** [SharePoint/sp-dev-docs#6545]
## Category

- [ x ] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Is there a possibility to get the comments from a list item? I want to show them in a list view. I have seen in this column format [sample ](https://github.com/pnp/sp-dev-list-formatting/tree/master/column-samples/generic-comment-count )that it is possible to get the number of comments. But how can I get the content of the contents?

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**:  SharePoint Online
- **Framework**: 
- **Browser(s)**: Chrome
- **Tooling**: 
- **Additional details**: 

I want to show the comments of a specific list item on a sharepoint page via the list webpart. For this I have to get the comment content.

Thank you!

**Comment by kongmengfei** [comment]
@firechhe,

Comment is not stored in the list, it's a navigation entity of the list item instead of a property. You can get comments via below endpoint:

![image](https://user-images.githubusercontent.com/57654821/101569647-d78a0800-3a0f-11eb-8a9a-219b6f49e0d4.png)

I think we cannot get it through a field reference. 

Baker Kong
Microsoft SharePoint Community Support
