### ISSUE TITLE
Profiling SPFx web part using react dev tools does not work

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#6548]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

How do you **profile** a spfx web part (using [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en))? 

Now I just got error, this:
![image](https://user-images.githubusercontent.com/528366/101664232-e1316100-3a4b-11eb-801c-04761761a310.png)

The react version is 16.8.x

## Environment details (*development & target environment*)

- **Your Developer Environment**: [Windows 10]
- **Target Environment**: [SharePoint Online]
- **Framework**: [Node.js v10]
- **Browser(s)**: [Chrome v82]
- **Tooling**: [SPFx v1.11.0]

**Comment by JakeStanger** [comment]
I used to have a gulp config that made this work, but an SPFx/platform update unfortunately broke it. I've had a play with trying to get it working again, but unfortunately I've had no luck.

Some findings at least:

- The production build is used in the workbench because Webpack is configured to use `react` and `react-dom`as externals so they don't get bundled.
- Stripping them out of the externals to use the versions in `node_modules` seems to cause some form of dependency error, and you're presented with the lovely "Something went wrong" screen. In my case at least, it's caused by this: https://reactjs.org/warnings/invalid-hook-call-warning.html

**Comment by jbrueggmann** [comment]
Has anybody solved this in the meantime by any chance?

**Comment by nick-pape** [comment]
Please try adding the following query parameter: `?enableReactDiagnostics=true`. When in debug mode, this will load profiling flavors of React that should work with React DevTools.
