### ISSUE TITLE
Support for M1 Mac

### ISSUE THREAD

**Issue by BassemNKhalil** [SharePoint/sp-dev-docs#6596]
## Category
- [x] Question

## Question
Any plans to support Node 14 LTS or later to work with M1 Mac chip? I know there's been a long standing community request to upgrade Node to a later version since Node 10 EOL is April '21 (https://nodejs.org/en/about/releases/) but fail to find anything trackable on that

**Comment by bcameron1231** [comment]
It was announced today in a Community Call that the goal for the SPFx 1.12 Release release is to support Node V14 and Gulp 4.

**Comment by StfBauer** [comment]
NodeJS is only supported via [Rosetta 2](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment) on M1 Macs not natively. So even if it will be updated to NodeJS 14 it is not guaranteed that it will work properly caused by [Rosetta 2](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment) and other architectural limitations.

Some resources to check on future update:
* [NodeJS Apple Silicon plans](https://github.com/nodejs/TSC/issues/886)
* [Node JS build](https://github.com/nodejs/build/issues/2474)

Hopefully SPFx will support soon after 14 even 15 because it is most likely that native support in M1 works then without any problem or emulator.

**Comment by StfBauer** [comment]
NodeJS is only supported via Rosetta 2 on M1 Macs not natively. So even if it will be updated to NodeJS 14 it is not guaranteed that it will work properly caused by Rosetta 2 and other architectural limitations.

Some resources to check on future update:
* [NodeJS Apple Silicon plans](https://github.com/nodejs/TSC/issues/886)
* [Node JS build](https://github.com/nodejs/build/issues/2474)

Hopefully SPFx will support soon after 14 even 15 because it is most likely that native support in M1 works then without any problem or emulator. So lot of works needs to be done on the NodeJS side I would assume.
