### ISSUE TITLE
Custom template selection not available in templatepick.aspx - sharepoint online

### ISSUE THREAD

**Issue by tomlemento** [SharePoint/sp-dev-docs#6629]
Hi, the custom template functionality is gone. I can upload my wsp to the solutions gallery but i cannot choose the wsp in templatepick. The Custom tab is not available. Please help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5f465-6d87-5a7d-9b0a-7807da51d30b
* Version Independent ID: bc4f4c42-d5ba-a36a-1578-70103e14cde8
* Content: [Save, download, and upload a SharePoint site as a template](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template)
* Content Source: [docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
It would help if you submit an issue with the issue template that is provided when creating a new ticket. Hard to help without the environment details. 

If you are using Modern, site templates aren't supported. You would only see custom tab in classic sites.

**Comment by tomlemento** [comment]
Hi, it's the first time i submit a ticket. Sorry.
 
**OS**: [Windows 10 ]
**Your Developer Environment**: [Windows 10]
**Target Environment**: [SharePoint Online]
**Browser(s)**: [Chrome v87 - problem also exist with other browsers]
**Additional details**: Both the site that i saved as a template and the site where i upload the wsp are classic sites without 365 group. I have been doing this for months now, and since the beginning of this year the functionality is gone. In the past, i uploaded the wsp to the solution gallery, i activated it and then it appeared in the custom tab
![Capture](https://user-images.githubusercontent.com/77881982/105722929-7918da80-5f26-11eb-8146-621fe21e3bc6.PNG)

**Comment by andrewconnell** [comment]
@bcameron1231 said

> It would help if you submit an issue with the issue template that is provided when creating a new ticket. Hard to help without the environment details.

FYI - when issues are created via comments from the docs, the templates aren't used. Context does help though... thanks for adding that request.

@tomlemento - I admit this isn't the best experience I'm about to explain, but trying to help you with your solution. When you add a comment in the docs, they are added to this GitHub issue list. However, this issue list is really only monitored for developer-related issues and what you describe is more of an end user/out of the box feature. Normally, if the issue was created in the issue list (and not via a comment on the doc), we'd close it as "not relevant" as it's not a developer issue.

Microsoft is aware of this and there's work ongoing to address it but that's not available now. Until then... 

You'll likely have a better chance at getting this addressed by asking the question in TechCommunity

**Comment by tomlemento** [comment]
I'm sorry, i just clicked on the feedback button below the page ... i will try the TechCommunity. Thx
