### ISSUE TITLE
Search box is not encoding special characters while navigating to custom search page

### ISSUE THREAD

**Issue by Mr-Clrscr** [SharePoint/sp-dev-docs#6668]
## Category

- [x] Bug

## Describe the bug
Hi I've already submitted an issue [here](https://github.com/SharePoint/sp-dev-docs/issues/6659#issue-797063801) but unfortunately it got closed. I hope I haven't conveyed it properly.

The issue is with sharepoint search box, when i tried entering a keyword with special character like c++ or j&j, the special characters were not encoding and passed directly to the query url to the custom search page.

## Steps to reproduce

s1: create a custom search results webpage
s2: type a word inside the search box in my case it is c++
s3: see the url which is not encoding the value

## Expected behavior

Expected : /CustomReults.aspx?q=C%2B%2B&k=C%2B%2B
Actual : /CustomReults.aspx?q=C++&k=C++

## Environment details (*development & target environment*)

- **Target Environment**: SharePoint Online

**Comment by andrewconnell** [comment]
The other issue was closed because it appeared you were asking a question about the PNP Search Web Parts... a different project with its own repo (the one I linked to when I closed your issue).

This repo is for development questions, not OOTB or end-user questions. Those should be posted to TechCommunity.

Either way, the question doesn't belong here... hence why we closed it.
