### ISSUE TITLE
Consume existing AAD app for domain isolated webparts

### ISSUE THREAD

**Issue by parwejp** [SharePoint/sp-dev-docs#6680]
We have tight control over creation of AAD apps in our tenant. Governance wise it would be nice to be able to consume existing AAD apps for domain isolated webparts. This will also remove one to one relationship with AAD apps and sppkg containing domain isolated webparts. Sometimes it is wise to create multiple packages for different webparts. Best would be to give this control to admins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 364300d9-535e-e105-6c95-8becd00a396c
* Version Independent ID: 31b7e9d2-3c6f-953c-3d18-607d29d3151e
* Content: [Isolated web parts](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts)
* Content Source: [docs/spfx/web-parts/isolated-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/isolated-web-parts.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
This is the whole purpose of domain isolated web parts... Domain Isolated web parts are intended to isolate the app permissions per web part for increased security. Otherwise, if someone were to make a change to permissions of the registered app, those now would be applicable to all those custom web parts in your environment... which is the security problem.

**The behavior you want is the default behavior for SPFx web parts**... so just don't use domain isolated web parts. When you approve an API request from a web part that uses the AadHttpClient, the permissions get added to a single registered application called "SharePoint Online Client Extensibilty Web Application Principal".

**Comment by parwejp** [comment]
Thank you so much for quick response @bcameron1231! I perfectly understand what Domain Isolated Webpart is. Apologies for not being clear enough.

My first point is, rather than creating AAD app dynamically, can I not use existing AAD app instead of my choice? 

**Default behavior uses single aad app for everything. That is absolute no go for me.** My point here is, if I get control over selection of aad app while deploying domain isolated webpart, then I can provision multiple aad apps and cautiously/carefully provide permissions to them differently. Spinning up separate AAD app for each domain isolated webpart is just too much in my opinion. As an admin, if I am deploying new domain isolated webpart and have a pre-existing aad app with requested permissions, then I might prefer to use the same rather than provisioning new aad app if it suits my governance/ maintenance need. I just want to efficiently use my existing aad apps for domain isolated webparts. 

Can I change which AAD app domain isolated webpart is using by some workaround post deployment?

**Comment by andrewconnell** [comment]
At this time that's not an option with domain isolated web parts. However, this could be a good feature to request via user voice.
