### ISSUE TITLE
Node version(s)

### ISSUE THREAD

**Issue by Xamian** [SharePoint/sp-dev-docs#6712]
Many devs will be happy to know that multiple versions of Node can coexist.

It could be usefull to tell about the tool NVM that can really help in this regard.

Link to Microsofts guide on installing Node: [Set up your Node.js development environment directly on Windows](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-windows)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by andrewconnell** [comment]
No disagreement, but... 

This isn't something that belongs in the SharePoint docs. The SP docs only mention what's required. There are plenty of "other tools" you can install, but if it's mentioned in the docs, it can overwhelm new users thinking they need much more. That's why we don't include things like this. Plus, you'd have to mention not just using NVM for windows, but also for macOS (which the nvm-windows tool is ported from).

FWIW, I'm a huge fan of NVM and have used it for years :)

**Comment by Xamian** [comment]
I am sure you have to draw a line somewhere, but I disagree with not including NVM in the docs. It is almost a must, especially in the current state of spfx, where we HAVE to use a no longer supported version of Node. The docs says version 10, but it works only with 8.

Again, you could just use the link to your own node documentation (https://docs.microsoft.com/en-us/windows/nodejs/setup-on-windows), so not much have to be changed in the doc in this regard.

**Comment by andrewconnell** [comment]
@Xamian said:
> where we HAVE to use a no longer supported version of Node. The docs say version 10, but it works only with 8.

That's not true... you only need Node v8 if you are working with SharePoint Server 2016 (and thus, SPFx v1.1 which released 3.5 years ago).
