### ISSUE TITLE
Plans to replace node-sass with sass in SPFX

### ISSUE THREAD

**Issue by LeopoldLerch** [SharePoint/sp-dev-docs#6822]
## Category

- [ X] Question
- [ ] Typo
- [ ] Additional article idea

## Question

Any Plans to replace node-sass in the SPFx-Toolset with sass (Dart-Sass)? Node-Sass and libsass are deprecated. While still maintained, no new features will be added. 
This is especially true for "@use" which is replacement for "@import" which will be phased out in the future completely.  Being able to use "@use" would be very nice

## Environment details (*development & target environment*)

- Windows 10
- SharePoint Online
- Node.js v12
- Chrome Chromium Edge v79
- SPFx v1.12.0

**Comment by StfBauer** [comment]
This is not a question of node-sass or sass. node-sass just makes sass in Nodejs via libsass available.

Meanwhile, node-sass is already deprecated, because libsass is deprecated according to https://www.npmjs.com/package/node-sass as well.

The question is when the node-sass replaced with dart-sass https://sass-lang.com/dart-sass. This is not something SPFx will fix but there is a thread related to this here https://github.com/microsoft/rushstack/issues/1666

**Comment by LeopoldLerch** [comment]
Thanks, made a comment there also. Hopefully they are doing something on it, so we can keep on track with development of sass. 

So I guess this can be closed then, but I leave it to you, maybe you want to keep the thread in order to keep an eye on it. You are the sassy-guy anyway, no @StfBauer?

**Comment by StfBauer** [comment]
@LeopoldLerch yeah, I will keep an eye on it but to be honest outside of SPFx and SharePoint I look into migration to dart sass also.

TBH even though it was deprecated there are tons of resources in the file that still rely on node-sass and it will also take some time for them, and my own tools to transition.
