### ISSUE TITLE
Extending webpack to use ts-loader custom transformers

### ISSUE THREAD

**Issue by unnieayilliath** [SharePoint/sp-dev-docs#6834]
## Category

- [X ] Question

- **Your Developer Environment**: [e.g. Windows 10 | MacOS 10.15.x] - Win 10
- **Target Environment**: [e.g. SharePoint Server 2016 | SharePoint Server 2019 | SharePoint Online] - SP Online
- **Tooling**: [e.g. VS Code | SPFx v1.10.0 | Visual Studio 2019] - VS Code/ Spfx v1.11.0
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

I am building a SPfx webpart where I am trying to do some manipulation of the webpack config generated by SPfx during the build process. I want to use a 3rd party package [ts-tansformer-keys](https://www.npmjs.com/package/ts-transformer-keys) which basically helps me to convert my typescript business models/types into array of string.  I have tried using the **build.configureWebpack.mergeConfig**  method to add a new rule into the webpack module. I have installed ts-loader as dev dependency. The build works but it ignores the additional rule which I have configured. Any idea what could be going wrong? Is there anyway for me to see the webpack.config generated by by Spfx build process?

```
const keysTransformer = require('ts-transformer-keys/transformer').default;
const build = require('@microsoft/sp-build-web');
build.addSuppression(`Warning - [sass] The local CSS class 'ms-Grid' is not camelCase and will not be type-safe.`);
build.configureWebpack.mergeConfig({
    additionalConfiguration: (generatedConfiguration) => {

      generatedConfiguration.module.rules.push(
        {
          test: /\.tsx?$/,
          use: [{
            loader:'ts-loader',
            options: {
                    getCustomTransformers: program => ({
                    before: [
                        keysTransformer(program)
                    ]
                })
            },
        }]
        }
      );
      return generatedConfiguration;
    }
  });
build.initialize(require('gulp'));

```

**Comment by andrewconnell** [comment]
@unnieayilliath said:

> Any idea what could be going wrong? 

First, you init gulp BEFORE you change your config... currently you're doing it after. While this might not be the issue, in practice, you're configuring something, then letting Microsoft do it's work. You should let MSFT do it's work, THEN you make your modifications. IOW, the call to `build.configureWebpack.mergeConfig()` should be added AFTER the default code, including `build.initialize()`.

Second, there's no TypeScript when webpack runs. SPFx's build toolchain doesn't use 

Probably... there's no TypeScript when you're bundling the project. The SPFx toolchain transpiles the TypeScript => JavaScript as part of the **gulp build** process. The bundling process uses the built files from **gulp build** when creating the bundle. You can see this if you run the **gulp bundle** command.

![image](https://user-images.githubusercontent.com/2068657/112128254-9cfe4280-8b9c-11eb-9d4d-700ad41be0a8.png)

In this picture, you can see the TypeScript compiler, `tsc`, has already completed transpiling the code to JS before the web pack bundling configuration & execution even happens. That's because the **build** task is run as a pre-task to **bundle**.

> Is there anyway for me to see the webpack.config generated by by Spfx build process?

Yup... just write it to the console. If you write it as an object, you won't get the details of the actual plugins used, so I write it out twice: once as an object & once as a string:

```ts
build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfig) => {
    console.log('<webpack.config type="object">');
    console.log(generatedConfig);
    console.log('</webpack.config>');

    console.log('<webpack.config type="string">');
    console.log(JSON.stringify(generatedConfig));
    console.log('</webpack.config>');

    return generatedConfig;
  }
});
```
