### ISSUE TITLE
SharePoint Webhook retry mechanism intervals

### ISSUE THREAD

**Issue by PatrykJakimczukEuvic** [SharePoint/sp-dev-docs#6870]
## Category

- [x] Question
- [ ] Typo
- [ ] Additional article idea

## Question

We were testing retry mechanism of SharePoint webhooks. We have prepared two Azure Functions: 
1. Webhook which was subscribed to SharePoint library, prepared in such a way that it would timeout every time it got a notification 
2. Timer function that updated a document in the library every 15 minutes. 

We found information in the documentation (https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks#error-handling) that SharePoint retries up to 5 times to deliver the notification. This worked as expected - there were 5 attempts every 5 minutes. Then, after 5 attempts, webhook stopped receiving notifications for an hour, then there were 5 attempts again. It worked like this over and over again, but the intervals between notifications became longer and longer. In our two attempts, the intervals between notifications were: 
1. 1h, 2h, 5h, 13h, 28h, 57h 
2. 1h, 3h, 4h, 15h 

Where these differences in intervals come from?  E.g. once it was 2 hours, in another case 3. Do they depend on the number of operations performed on the library, the load on Microsoft servers, or on something completely different?

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: .NET Core v3.1
- **Tooling**: Visual Studio 2019

**Comment by PatrykJakimczukEuvic** [comment]
Hi, when we can expect answer to our question?

**Comment by JeremyKelley** [comment]
Hello, sorry for the delay in response.

We're working on documentation updates for this but don't have an ETA on those at the moment.

Basically, after the first 5 retry attempts the system starts using an exponential backoff based algorithm to send future retries.  This algorithm uses a range of values for the backoff window rather than a fixed number.  This helps ensure that if a single application were having sustained issues we would not have either a flood of calls back to the service once it recovers or a flood of notifications that could overwhelm the app on the other end.  This helps protect both server and client in the event of a long running interruption.

Hope that helps!

**Comment by PatrykJakimczukEuvic** [comment]
Hi,

Thank you for your response. Is there any way to manually restart the notifications, so we don't have to wait few hours?

Regards
Patryk

**Comment by keith-knight** [comment]
Hello,

I find the response here from @JeremyKelley somewhat alarming... consider an application suffering an outage of ~30 hours (which is unlikely but possible, e.g. over a weekend when staff are unavailable).. then even after it is brought back online again it would have to endure another 57 hours of downtime. If there were further issues at ~57 hours then it would be offline for how long.. an additional week or even longer??

There is no way to notify SharePoint that the application is back online again? Removing the webhook subscription and adding it again does not reset the delay?
