### ISSUE TITLE
Sync To Teams button disabled in Sharepoint App catalog

### ISSUE THREAD

**Issue by umraopushpanjay** [SharePoint/sp-dev-docs#6924]
I have created a simple spfx app that shows data from a sharepoint list. Now i want to use the app in teams as well so I went through the steps mentioned in the below url.
[using-web-part-as-ms-teams-tab](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab)

I have added "TeamsTab" in the supported host.

after creating the package file I upload it to app catalog. However when I try to sync it to teams, the button is disabled.

I tried with 3 different tenants but the result is same.

node version: v10.23.2
gulp version: CLI version: 2.3.0
Local version: 3.9.1
SPFx: 1.10.0
yeoman: 3.1.1
npm:6.14.10
OS: Windows 10

I posted the question on https://docs.microsoft.com/en-us/answers/questions/359351/sync-to-teams-button-disabled-in-sharepoint-app-ca.html

They were able to recreate the issue on there end as well

**Comment by MarksPoint** [comment]
I've played around a bit with the generator and to make sure that Sync to Teams is available, you need to make sure that:
- You're in a tenant-wide app catalog (but I believe you're already doing this right, looking at your screenshot)
- `"skipFeatureDeployment": true,` is available in `package-solution.json`
- You also need to make sure you tick this box when you install the solution:
![image](https://user-images.githubusercontent.com/16799069/115045460-cfb70480-9ed6-11eb-983e-8265e7e4d756.png)

In my case I was able to make the Sync to Teams button active (using v1.10 with a default web part):
![image](https://user-images.githubusercontent.com/16799069/115045618-f70dd180-9ed6-11eb-82bf-0e4bde1641e7.png)

If this doesn't solve the issue, could you maybe upload the solution here? You should be able to attach a zip file.

**Comment by umraopushpanjay** [comment]
Hi I have performed all three above steps mentioned by you already. I still am facing the issue.

Also as mentioned I posted the question on [https://docs.microsoft.com/en-us/answers/questions/359351/sync-to-teams-button-disabled-in-sharepoint-app-ca.html](url) and the community expert was also able to reproduce the issue on his end.

Attaching my project for your reference.

[spfxappforteams.zip](https://github.com/SharePoint/sp-dev-docs/files/6334242/spfxappforteams.zip)

**Comment by MarksPoint** [comment]
Thanks for providing the source code.
I was able to reproduce your issue and did a compare to my solution to see what was different.

The issue is with this property:
`"isDomainIsolated": true`
in the packagesolution.json file.

If you change this to
`"isDomainIsolated": false`
it will work! (At least it did on my end)

I'm not entirely sure why domain isolated web parts wouldn't work within Teams, but I do know that they're very different  from regular web parts since they need a custom App registration and they run in iframes instead of in the DOM of the page. I couldn't find documentation stating that domain isolated web parts won't work in Teams but I can imagine it's the case considering these differences.

Did you make your SPFx solution domain isolated on purpose? If not, just turn it off.
Some background on these: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts

**Comment by umraopushpanjay** [comment]
Thanks a lot. It did work. This "isDomainIsolated": true has caused me a lot of trouble before as well. I think it was set to true by default. I changed it to false and it worked.
