### ISSUE TITLE
Referencing lookup column for hiding

### ISSUE THREAD

**Issue by analienx** [SharePoint/sp-dev-docs#6958]
Provided example is just for a lookup column that has the same uniqueness as the ID, which is in many cases not the case:
How one can reference to a lookup column that has different level of granularity?
Example:

List A:
Category Title Color

List B :
Title, Division

Color can have 3 values and is independent to country so ID of a country wont help.

Creation a division lookup wont help either since you would need to add it to the List A as lookup column unable to use it for validation/calculation

Is there a way how to reference Lookup field from non-id column?
Tried all combinations from #6917 no success.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536f88e0-51aa-9a3a-20da-64b4a8b155a1
* Version Independent ID: efa34015-6402-a024-ae62-3b0c6c0865ea
* Content: [Show or hide columns in a list form](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide#specify-conditional-formula-to-show-or-hide-columns)
* Content Source: [docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/list-form-conditional-show-hide.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by thechriskent** [comment]
While, the suggested approach of comparing the ID and the Value works, it is inadequate. I have created an update in the documentation (pull-request #6975) as well as submitted the issue as a bug: #6974 

In short, you can access the sub props of a lookup column using these expressions:

`=Number(substring([$MyLookup],0,indexOf([$MyLookup],';#')))` - Returns the ID as a number
`=substring([$MyLookup],indexOf([$MyLookup],';#')+2,1000)` - Returns the value as text

So you could use them in a conditional field expression like this:

`=if(Number(substring([$MyLookup],0,indexOf([$MyLookup],';#'))) == 1, 'true', 'false')` - would show the field whenever the ID is 1
`=if(substring([$MyLookup],indexOf([$MyLookup],';#')+2,1000) == 'Toronto', 'true', 'false')` - would show the field whenever the VALUE is Toronto

If that doesn't answer your question, please let me know. Thanks!

**Comment by analienx** [comment]
Hello @thechriskent , thank you for the response yet it does not reflect the actual scenario when you have a sub property with different granularity than it is for the lookup column itself. Example:
Lookup column city  and I would like to hide the column based on a  size_type column  (small/medium/big). 
Size_type is an additional column for the City lookup column. Consequently 
`=if(substring([$Size_type],indexOf([$Size_type],';#')+2,1000) == 'big', 'true', 'false')`
does not work

**Comment by thechriskent** [comment]
I think I understand what you are referring to now. You would like to use the additional columns (projected fields) for a lookup in the conditional field expressions.

Unfortunately, the additional column values are not available in conditional expressions or form formatting (header/footer/body layout).

It is possible, however, to create a calculated column on your lookup list that concatenates the values into a single string with separators. You can then use this calculated column as your primary field for the lookup and have access to the concatenated string. Then you can parse the value using a similar method as above. This is absolutely not ideal and can create other issues.

While not directly related, you can see an example of creating a calculated column and splitting those values using formatting expressions in this demo: https://youtu.be/1NE_uMlpD08?t=3307

So, using your `Size_type` example you could create a calculated column (single line of text) on your lookup list with a formula similar to this:
```
=[Title] & "|" & [Size_type]
```

Then switch your lookup to use this new calculated column as the primary field. Then you would be able to write a conditional formula for your field like this:
```
=if(substring([$MyLookup],indexOf([$MyLookup],'|')+1,1000)=='big', 'true', 'false')
```

Some issues with this approach:

- You will need to provide a format for your primary lookup column to keep it from looking terrible
- Parsing expressions get increasingly complex depending on how many values you are trying to concatenate
- Filtering on your lookup will be terrible since those values won't be nicely formatted but the concatenated calculated column values

I don't recommend the above if you can avoid it, but if you have an absolute need to conditionally show/hide columns based on the additional columns this is the only way I am aware of using the standard customization techniques.
