### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by Ib01** [SharePoint/sp-dev-docs#6969]
I followed https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#trusting-the-self-signed-developer-certificate to the letter and get the following error every time i run gulp in vs code 

gulp : File C:\Users\ibros\AppData\Roaming\npm\gulp.ps1 cannot be loaded. The file C:\Users\ibros\AppData\Roaming\npm\gulp.ps1 is not digitally signed. You 
cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ gulp serve
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bee09a8-022e-1b5a-4aab-d6e7c6216808
* Version Independent ID: 49edce1e-f2be-e989-917f-c6b389363e2f
* Content: [Set up your SharePoint Framework development environment](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#trusting-the-self-signed-developer-certificate)
* Content Source: [docs/spfx/set-up-your-development-environment.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/set-up-your-development-environment.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by omarelanis** [comment]
The error you are seeing there is nothing to do with the self-signed certificate being trusted by local host, that error is because you have not enabled script execution on your machine.

As per the link in the error message https://go.microsoft.com/fwlink/?LinkID=135170 it explains the different types of script execution policies available.

Quickest way to check if you're allowing remote scripts to run is to enter this inside PowerShell session:
Get-ExecutionPolicy
![image](https://user-images.githubusercontent.com/35841910/116898509-5cc7c080-ac2e-11eb-93c1-99b062f8c06e.png)

You could also try running gulp in a CMD command window instead of PowerShell and see if it runs:

![image](https://user-images.githubusercontent.com/35841910/116898644-897bd800-ac2e-11eb-9265-05da91cd3268.png)

![image](https://user-images.githubusercontent.com/35841910/116898701-9e586b80-ac2e-11eb-9a43-09e6c9eee361.png)
