### ISSUE TITLE
SP Online - How to declare webpart as hidden in SPFx?

### ISSUE THREAD

**Issue by Employee87** [SharePoint/sp-dev-docs#7013]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Chrome 90
- SPFx version: 1.12.1
- Node.js version: 14

### Issue description

In SPFx, I make webparts that read content from a source like custom lists and then draws it out with a title and content. However sometimes there is no content, and if thats the case, I would like to hide the whole web part.

Now it's pretty easy for me to hide the title, or set display:none on the webpart root class, but the problem is it still leaves some margin on top and bottom of the containing canvas zone.

What I would like to be able to do is then somehow declare the webpart as hidden, which SP should detect as the canvas zone being either empty or has only webparts that has been declared as hidden, which then collapses/hides the canvas zone itself.

Does anyone know is this kind of functionality exists to how to achieve something like this?

Thanks

**Comment by andrewconnell** [comment]
I'm not aware of a way to hide the web part using the SPFx API from within the web part. 

However, the web part is rendered within a DIV which is accessible via the `this.domElement` property on the web part. You could use that to add a CSS class to set the `display:none` of the web part, but... because beware, because that's not part of the SPFx API and you're technically modifying the DOM (and it's debatable if that is/isn't part of the web part or the page itself), that might be considered DOM manipulation which isn't supported & strongly discouraged by Microsoft.
