### ISSUE TITLE
🐞 CurrentPage property not respected IPropertyPaneConfiguration

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#704]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When setting the `currentPage` property on the `IPropertyPaneConfiguration`, SPFx should set the current property pane page to the specified value.

#### Observed Behavior
Doesn't matter what number you use, including trying 0-index base, the first page is always shown.

#### Steps to Reproduce
```shell
git clone https://github.com/andrewconnell/spfx-bugrepo-proppanepages
yarn install
gulp serve
```

add the **SPFx Bug Repro** web part to the workbench & read the description... tells you how to reproduce

this cswp has 2 pages in the property pane... currently the `currentPage` property is set to `1`, but changing it to `0` or `2` has zero effect

**Comment by pgonzal** [comment]
Thanks Andrew for a top-notch repo.  :-)  We're investigating this issue.

**Comment by pgonzal** [comment]
This feature was originally introduced to support certain first party web parts, but they ended up taking a different approach, so we removed it.  The API property was left in the interface for our GA release due to an oversight.  Sorry about that!  Because the feature wasn't really designed for third parties, it would need some work beyond simply implementing the interface property as-is.  If that's an important scenario for your work, I would encourage you to open a feature request on [User Voice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform) so that others can vote for it.  Thanks!

**Comment by andrewconnell** [comment]
Thanks for the followup @pgonzal
