### ISSUE TITLE
🐞 Link control in property pane doesn't open popup

### ISSUE THREAD

**Issue by andrewconnell** [SharePoint/sp-dev-docs#708]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When specifying the correct values according the provided interfaces for the link control, a popup window should load the link.

#### Observed Behavior
The link opens in the same window. Looking at the source, I see nothing extra added to the `<a>` tag.

#### Steps to Reproduce
- create a new spfx web part project
- within the webpart, add the following import statements to the top of the page

```typescript
import {
  PropertyPaneLink,
  IPropertyPaneLinkProps,
} from '@microsoft/sp-webpart-base';

// @HACK because these aren't exported
// see: https://github.com/SharePoint/sp-dev-docs/issues/707
import {
  IPopupWindowProps,
  PopupWindowPosition
} from '@microsoft/sp-webpart-base/lib/propertyPane/propertyPaneFields/propertyPaneLink/IPropertyPaneLink';
```

- replace the default text field control for the `description` property with this one:

```typescript
{
  groupName: 'Popup window properties',
  groupFields: [
    PropertyPaneLink('', <IPropertyPaneLinkProps>{
      text: 'Voitanos',
      href: 'https://www.voitanos.io',
      popupWindowProps: <IPopupWindowProps>{
        title: 'Voitanos',
        width: 200,
        height: 200,
        positionWindowPosition: PopupWindowPosition.center
      }
    }),
  ]
}
```

- start local workbench & test using `gulp serve`

**Comment by andrewconnell** [comment]
Related to #707

**Comment by pgonzal** [comment]
Thanks for reporting this issue.  The "popupWindowProps" feature was originally part of **office-ui-fabric-react**, but it was removed in [September](https://github.com/OfficeDev/office-ui-fabric-react/pull/293).  It was an oversight that this option was not removed from the SPFx Property Pane before GA.  We will remove this setting in the next release.

If this feature is important to you, I would encourage you to file it as a feature request for **office-ui-fabric-react** since they own this part of the user experience.  Thanks!

**Comment by pgonzal** [comment]
@dzearing FYI

**Comment by andrewconnell** [comment]
Thanks for the followup @pgonzal
