### ISSUE TITLE
Using azure ad "dynamic consent" with SPFx web part

### ISSUE THREAD

**Issue by nbelyh** [SharePoint/sp-dev-docs#7143]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [X] not applicable

### Issue description

When using Graph API, is it possible to use "dynamic consent" with SPFx?

By "dynamic consent" I mean, an application (such as teams app for example) can ask user for permissions (scopes) only when it actually needs them. But in SPFx, you can define the list of scopes in "webApiPermissionRequests" but it's static (fixed) and approved by admin at the moment the application is deployed.

Scenario: application normaly does not use planner, but has a feature to integrate with it on demand. So if user turns on this feature, it would be nice to have a consent prompt at that moment, and not when user installs the app.

See more on dynamic consent in the documentation:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#incremental-and-dynamic-consent

**Comment by nbelyh** [comment]
@andrewconnell 
This is a duplicate of (that was probably closed accidentally as "answered" without any answers):
https://github.com/SharePoint/sp-dev-docs/issues/7132

Would be happy to get any information regarding this.

**Comment by andrewconnell** [comment]
Sorry about the other issue #7132... I remember typing a response, but looks like I forgot to submit it when I added the labels :)

No, this isn't possible. The reason is that with SPFx, you aren't granting the user consent to this, you're granting consent to the app that obtains the access token for a call to Graph. That app, in SPFx, is SharePoint Online (or, as listed in the Azure AD apps, **SharePoint Online Client Extensibility**). Only the tenant admin and grant consent to that app & therefore, having the user go through the consent process doesn't apply.

REF: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#web-api-permissions-overview

**Comment by nbelyh** [comment]
Thank you, all clear 👍 It would be nice to have this feature though 😄

**Comment by andrewconnell** [comment]
Well *you* can implement it yourself with your own Azure AD app that the user would grant consent to. That's been possible for a very long time using ADAL JS (now deprecated) or the current MSAL JS SDK.

It's just that when you use the SPFx API `AadHttpClient`, it's written for a specific Azure AD App (the SPO one I referenced above).
