### ISSUE TITLE
Batched requests do not work in IE

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#715]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Batched requests work in IE with these SPFx module versions:

sp-core-library ~1.0.0
sp-webpart-base ~1.0.0

#### Observed Behavior
Batched requests do not work in IE with these SPFx module versions:

sp-core-library ~1.1.0
sp-webpart-base ~1.1.1

#### Steps to Reproduce
Write some code in an SPFx web part that uses SPHttpClientBatch and the following SPFx module versions:

sp-core-library ~1.1.0
sp-webpart-base ~1.1.1

In this example, we save an item to a list and get all list items with a batch request.  There is no promise returned when we use batch request in the IE browser.   It works well in Chrome and Edge.

![1](https://user-images.githubusercontent.com/1407310/28024341-70c8d382-655e-11e7-86b1-a0c440afabae.png)

**Comment by pgonzal** [comment]
Thanks for reporting this issue.  However, I am unable to repro it.  Batched queries seem to be working fine for me in IE11.

For example, when you render a page containing our "People" web part, in [Fiddler](http://www.telerik.com/fiddler) you will see that it makes a request to /_api/$batch using SPHttpClientBatch.  This works fine in IE and Chrome.

Can you provide an isolated repro?  For example:  create a new empty web part project, add your code, verify that it works on Chrome but fails on IE, zip it up (excluding the node_modules folder), and attach it to this bug.  Thanks!

**Comment by TBag** [comment]
Hi Pete,  I'm working with Vesa to get in touch with you so I can show you the issue and get you the code.

**Comment by pgonzal** [comment]
Thanks again for reporting this issue and helping to provide a repro.  There are two underlying problems:

1. Our [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) polyfill is pretty old and should be upgraded; probably we should audit the other polyfills as well
2. The `SPHttpClientBatch` processing includes a special workaround for empty responses ([HTTP 204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)); it is buggy and can be eliminated by simply scrubbing the inputs a little better

Either of these fixes would solve your problem.  We'll go ahead and fix both of them.

A couple other notes:

- The reason your promise never resolved is that `batch.fetch()` was reporting an error, but you're missing your catch block.  In general, it's very important to ensure that every promise chain ends with a `catch()` block, otherwise errors will be silently ignored.  In your repro, your call to `this.props.dataProvider.saveItem()` starts the chain, so the `catch()` block should go there.  This gotcha is an unfortunately inherent in the promise pattern.  (Someone could probably create a [tslint](https://palantir.github.io/tslint/) rule to detect missing catch blocks...)

- `SPHttpClientBatch` is currently designated as "alpha".  It was meant to be a developer preview, i.e. not used in production code because we may change the API contract before graduating to "public".  So far we haven't done a great job of documenting what is alpha/beta/public.  We're working on that this summer.  Looking at the documentation web site, it seems that `beginBatch()` is documented but `SPHttpClientBatch` is not.  I will get this straightened out, and since the batching feature seems to be popular, we should graduate it quickly.

**Comment by pgonzal** [comment]
@VesaJuvonen

**Comment by TBag** [comment]
Hi, Pete,

You're welcome, glad to help.

Thanks for the detailed problem explanation and the suggestions regarding the catch() block.  Please let us know once you make the fixes.

**Comment by pgonzal** [comment]
FYI I completed both fixes.  (I also upgraded the Promise polyfill while I was at it.)  These changes should roll out to your production environment sometime in the next couple weeks.  If you are still seeing the problem after 3 weeks, please reopen this bug.

I'm putting together a plan for the `SPHttpClientBatch` API, and will work out a timetable for graduating it to being a "public" API.

Thanks again for taking the time to provide a repro!

**Comment by TBag** [comment]
Thanks for the update @pgonzal !

You're welcome, we're happy to help.

We'll check it out in a few weeks and let you know if we run into any issues.
