### ISSUE TITLE
Extend sharepoint REST v2.0 to include graph search

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#7228]
Would be great to include the new Microsoft Search API into SharePoint REST v2.0 endpoint.
https://docs.microsoft.com/en-us/graph/search-concept-overview

This way SPFX would get straight access to the API without having to request extra app permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: accadff1-1b70-6a67-4465-d66245aa3a09
* Version Independent ID: 8e108e60-9c50-0856-712c-f85e64c9813a
* Content: [Operations using SharePoint REST v2 (Microsoft Graph) endpoints](https://docs.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph)
* Content Source: [docs/apis/sharepoint-rest-graph.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/apis/sharepoint-rest-graph.md)
* Service: **sharepoint-online**
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by CallumCrowley** [comment]
This sounds like a feature request rather than an issue with the documentation. I would recommend posting this on the [Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) instead (this is where Microsoft ask for ideas/feature requests relating to the Graph API).

**Comment by jonathanhotono** [comment]
@CallumCrowley thanks, posted.
