### ISSUE TITLE
"rotation" & "rotation-point"? No documentation at all anywhere.

### ISSUE THREAD

**Issue by drizztdourden08** [SharePoint/sp-dev-docs#7235]
Hi,

I've been trying to see if there's a way to rotate an element in column-formatting JSON. However, can't find anything except those two properties that are documented in the list of style available. 

Thing is, I have no idea how to use them or if they even do what I need. No documentation is available and I can't find it in the schema. I tried "27deg" but it does nothing.

In fact, those two properties aren't even CSS properties to begin with, assuming we want to translate the real property from CSS to SP.

Thanks.

**Comment by thechriskent** [comment]
List formatting whitelists specific CSS properties. This isn't the first time completely useless properties have been whitelisted while the ones we really need are left out (#2396).

These are technically CSS properties but only [implemented by Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/rotate) making them virtually useless.

Unfortunately, the property you want is `transform` but that isn't whitelisted. Even if it was, however, none of the CSS functions like `rotate()` would be allowed since properties can only have parenthesis when the `rgba` function is used.
