### ISSUE TITLE
ServiceWorker doesn't load latest definitions of files

### ISSUE THREAD

**Issue by siata13** [SharePoint/sp-dev-docs#7253]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx 1.12.1
- Node.js 14

### Describe the bug / error

SharePoint started to use ServiceWorker to load assets included in sppkgs to provide offline capabilities. The observed problem is that the service worker is not able to discover the update of the sppkg files when the files are loaded from CDN.

https://user-images.githubusercontent.com/6162213/129671714-9690a725-705b-428a-816e-0a9844d14901.mp4

Another observed behavior: I have been deployed a package (library component) and I uploaded it to app catalog (it uses SharePoint library to store javascript files). The bug caused that my web parts couldn't be loaded. I have fixed the bug and uploaded and deployed a new sppkg. ServiceWorker again is not serving latest files and causes my page to crash.

https://user-images.githubusercontent.com/6162213/129673174-3c8734f0-f055-4746-97e7-0248ae6e3b53.mp4
In this example, ServiceWorker falls into infinite loop when loading the file, nevertheless it is able to obtain it's definition
![image](https://user-images.githubusercontent.com/6162213/129673359-184e88cb-b13c-4bfe-9eef-02c443a7307a.png)

### Steps to reproduce

1. Deploy sppkgs that stores files in Azure CDN (or any external CDN)
2. Use deployed webpart on the page
3. Update files stored in the CDN (cache control flag is ensured for all the files)
4. New definitions of the files are never obtained - the only option is to unregister SP ServiceWorker

### Expected behavior

New files definitions are loaded.

**Comment by shaipetel** [comment]
I see the same thing.

We serve files from our external CDN, we have internal caching and different publish channels and invested a lot of time and money in our CDN infrastructure.

It seems the new service worker is now storing a local version of our file, from our own CDN, indefinitely.
It never clears it, never purges the cache and completely ignores the response cache.

Refreshing the page, closing and opening the browser - nothing helps with purging this cache, the service worker is hard coded set to load all files from cache all the time.

Please note, this is especially harmful for those of us who do not put the hash in the SPFx output file name.
If you do - a new file name is created every time, so its not an issue.

Removing the hash from the name, which is a supported practice, causes a huge problem since the files are cached in the Cache Storage and never gets updated.

We need urgent help in this matter, to either make the service worker NOT cache other external vendors CDN files, or to allow us to pass a response header to make the service worker ignore specific files and not cache them.

For now, the only workaround is to run a script that will clear ALL Cache Storage.

This is done in production and affects thousands of our customers who no longer able to switch between production/test environments and get over-the-air updates.

**Comment by shaipetel** [comment]
To add more context, I found the service worker also hard coded mark all scripts coming from "localhost" to be allowed in cache.
That means other developers, not working for Microsoft, who want to use a local dev machine (target localhost) cannot have their files updated.

Furthermore, the case "script" has a conditional return, without a break.
This means that for scripts that **do not** fall into the if condition - they fall through to the "font" and "style" case, and treated as a non-script resource, instead of returning false.

There should be an "else return false;" there, or a break statement, that will stop the fall through to the other cases.

```
            isCacheable(e, t) {
                switch (t.destination) {
                case "script":
                    if (0 === t.url.indexOf("https://localhost:") || 0 === t.url.indexOf("https://odspwebdevdeploy.blob.core.windows.net"))
                        return !1;
                case "font":
                case "style":
                    return 0 === t.url.indexOf("https://")
                }
                return !1
            }
```

Perhaps this is what's making 3rd party CDN scripts being wrongfully cached?

**Comment by elearningforce-ag** [comment]
We see the same issue. JS files are served by our server in Azure with Cache-Control: No-Cache. As the result Service Worker caches them on the first load and there is no way to reset this cache when we deploy new version of JS files.

After the investigation we finally found out how this service worker cache works and how to bypass it. This is the code of service worker which checks the expiration:
![image](https://user-images.githubusercontent.com/32488384/151184738-59277ed2-2458-4d2b-8f41-48d8576065c1.png)
It requires max-age and Date headers to have proper values. We set the following headers and now it works as expected and doesn't cache our files:
```
cache-control: no-cache,max-age=0
access-control-expose-headers: Date
```
Pay attention that Cache-Control value shouldn't include any spaces because service worker doesn't trim them. It actually looks like bug and needs to be fixed. I see a lot of Office365 js files that have spaces in Cache-Control header and as the result cache expiration doesn't work for them as expected.

**Comment by winperec** [comment]
Guys we have 300+ tenants affected by this issue and that implementation. These 300+ tenants right now have JS bundles which was cached for a long time(may be forever). Please take an action on that because the logic is wrong and will lead to further issues and it is real problem for some ISVs

**Comment by AJIXuMuK** [comment]
We're tracking these types of issues in #7664.
The fix should roll out next week.

But we still recommend to use `access-control-expose-headers: Date` header to allow the service worker to access headers from the prefetch.

**Comment by AJIXuMuK** [comment]
@shaipetel - we're discussing this as possibility. The fix is actually based on the idea of "ignoring".
But there are multiple reasons why we want to have cache in place for 1p and 3p files.

**Comment by shaipetel** [comment]
@AJIXuMuK I understand the "want", you want to allow offline access to the site.
I'm saying, IMHO, you are going at it the wrong way: on by default, opt-out, with zero instructions/apis for developers.

IMHO, the way should be:
- MSFT building a new capability "offline"
- MSFT publishes instructions for developers who want to opt-in to take advantage of this new feature
  - asking them to add a response header for example
  - providing a response header for opting out would also be good
  - key word here is "publishes instructions". You can't roll out something like this with zero documentation having people guess what headers to include...
- ISVs/developers opt-in if/when they want to, but have a clear way of opting out if they don't
- Possibly (I know MSFT are not big fans of publishing an API anymore...) publish an API that allows developers to "talk" to this caching agent, allowing for custom logic/check to signal if a file should be refreshed or dropped from cache
  - so, as a dev, I can make my own async request to the server and see if there is anything changed based on my own custom logic, and call this API asking it to update the file in cache.

> Side comment/rant: MSFT used to do a very good job with ISVs and developers, giving us APIs to talk to your libraries. Ever since the move to the cloud, for some unknown obscure reason, you keep ignoring this audience and forcing us to "hack" our way into the libraries - case in point, the only way to fix this was for me to write up my own code that crawls all the caches in the browser looking up files with my CDN and removing them... why?

Thanks and good luck!

**Comment by AJIXuMuK** [comment]
Thank you for the feedback @shaipetel. I will transfer it to the responsible team.

**Comment by AJIXuMuK** [comment]
@siata13 - there were multiple fixes in the last few weeks that should be rolled out WW by now.
Could you please check if your issue has been resolved?
