### ISSUE TITLE
How to add the information for the app store detail screen?

### ISSUE THREAD

**Issue by Mop3D** [SharePoint/sp-dev-docs#7283]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Browser: Version 92.0.4515.159 (64-Bit)
- SPFx version: 1.12.1
- Node.js version: 14.17.3

### Issue description

In Sharepoint Online, when I add an app, I can click on the tile of an app an get more information about this webpart.

How can I provide these information with an spfx webpart?

**Comment by VesaJuvonen** [comment]
This was a bit of an unfortunate miss from the Microsoft side and we are working on fixing this. Solution details are available if the SPFx solution is coming from the store, but information is not there if the solution is uploaded directly to the app catalog. We are working on getting this fixed in the sppkg package level with needed new attributes. Trying to get this squeezed to 1.13, but could be also delayed unfortunately until next version.
