### ISSUE TITLE
How does the localization work?

### ISSUE THREAD

**Issue by rolandoldengarm** [SharePoint/sp-dev-docs#74]
the folder "loc" contains an en-us.js, and mystrings.d.ts
This is not documented anywhere as far as I can tell. And why is en-us.js a JS file, not a TS file? It looks quite complicated.

**Comment by nickpape-msft** [comment]
Yes, currently those localization files are fully standalone JS modules. The API in config.json which specified `localizedResources` is designed to be flexible enough to load any JS resource for the current culture. However, that means these resources need to be standalone JS bundles (hence the `define()` stuff).

We're working on improvements to the localization story that would effectively let you add TypeScript, RESX, or JSON files in `src/loc`, and we would convert these to standalone bundles for you.

[We're also working on allowing you to embed a specific type of localized resource -- strings -- directly into your code bundles. This would mean we would be creating files like `myWebPart-en_us.js`, `myWebPart-fr_fr.js` instead of `myWebPart.bundle.js`, `myWebPart-strings-en_us.js`, `myWebPart-strings-fr_fr.js`.]

**Comment by rolandoldengarm** [comment]
Cool. Those improvements look great.

**Comment by nickpape-msft** [comment]
We're going to leave this issue open, as this is a pending item to fix on an upcoming drop.

**Comment by thespooler** [comment]
Let's say I used localizedResources in a webpart/component, let's call it A. Now I include that in another project, let's call it B, through package.json/npm install. As of now, I don't see how to include these without having `Module not found: Error: Can't resolve ...` errors while building B, unless I add A localizedResources to B localizedResources.

**Comment by lahuey** [comment]
Hi,

We have documented how localization works here ->
[](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts)

I'm closing this issue for now. Please open a separate bug if you're running into issues with localization.

Thanks!
