### ISSUE TITLE
Using LikesCount to increase the ranking in a query has stopped to work

### ISSUE THREAD

**Issue by benjacernuda** [SharePoint/sp-dev-docs#7533]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

In our query we use the clause XRANK(cb=10) LikesCount>1 to increase the ranking if the pages has more that 1 likes. This was working fine but recently it has stopped to work in some tenants (most of the tenants). In other tenants is still working fine. 

Not sure if you have noticed this @wobba or you are aware of some recent changes in the Search schema

Many thanks in advance 

### Steps to reproduce

1.  Open the SharePoint Search Query Tool and connect to a tenant
2.  Execute this query in the Query Text: ((ContentTypeId:0x0101009D1CB255DA76424F860D91F20E6C4118*) XRANK(cb=10) LikesCount>1)
3. This query is getting the Site Pages and applying the rank
3. This query return 0 in most of our tenants
4. If I remove the XRANK(cb=10) LikesCount>1 return results

### Expected behavior

The expected behavior here is what we were seeing before: the query should return results
If we use another field to increase the rank the query return results

**Comment by wobba** [comment]
As you see in the schema, `LikesCount` is not queryable or refinable so it should never have worked. So the bug is that it used to work, now it's working as expected.

![image](https://user-images.githubusercontent.com/51104/143408165-fb44660b-2e06-4905-8450-266fd4aa5237.png)

The workaround is to map `ows_LikesCount` to e.g. `RefinableInt00` at the tenant level and add an alias to `RefinableInt00` of `LikesCount`. The alias will then override the original mp in terms of usage. Or change your query to use `RefinableInt00` instead.

**Comment by benjacernuda** [comment]
Many thanks @wobba !
