### ISSUE TITLE
Errors in Example Code

### ISSUE THREAD

**Issue by Zetser1** [SharePoint/sp-dev-docs#7591]
I started programming before Windows and quit when windows became the standard because I was old, worked outside the industry, and didn't have time to relearn everything.  
Many years later I started writing MS Access applications.  Eventually, I started exploring C# in Visual Studio 2019.  

I'm currently trying to write an application that stores files in a company controlled SharePoint.  This has been very frustrating because  the examples demonstrating how to use Microsoft Authentication are not compatible with the examples to access sharepoint via MS Graph or CSOM.

I can read and copy and paste like everyone else. :)

When I copy and paste this specific example into Visual Studio 2019, I get errors that Resharper doesn't know how to fix.  Specifically, HttpUtility is apparently no longer in any of the namespaces in the using statements.  When I use Resharper to correct this. Resharper adds using Microsoft.SharePoint.Client.Utilities.  However, the UrlEncode method is not in this version of HttpUtility.  Instead there is a UrlKeyValueEncode() and other methods prefixed with Url, but I'm not sure if any of them are the replacement.  Furthermore, this article was written 2 months ago.  How could the language change that much?

Anyway.  If someone has the key for me to make sense out of these examples I'd appreciate the education.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80e62a9d-06d0-ebc3-2c99-ce459388182a
* Version Independent ID: 07d8b090-b18c-842d-ba1e-0f2b2a127ad3
* Content: [Using CSOM for .NET Standard instead of CSOM for .NET Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard)
* Content Source: [docs/sp-add-ins/using-csom-for-dotnet-standard.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/sp-add-ins/using-csom-for-dotnet-standard.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by bcameron1231** [comment]
Hi can you provide a bit of information for us about your environment/solution you've set up?

**Did you set this up as a .NET Framework or .NET Core Application?
What version of CSOM are you using?**

It's important to make sure you fully understand the information in the "Differences" Table. Due to changes between CSOM in .NET Framework and .NET Core, you need to use different methods depending on the version of CSOM you are actually using.

Notice the section for 
<html>
<body>


Microsoft.SharePoint.Client.Utilities.HttpUtility class | Yes | No | Switch to similar classes in .NET such as System.Web.HttpUtility
-- | -- | -- | --



</body>
</html>

It makes a mention that if you are using CSOM on .NET Standard, you need to use a similar class like System.Web.HttpUtility.

So in the referenced example, it was written in CSOM Standard. So it's not using the Microsoft.SharePoint.Client.Utilities.HttpUtility which is what you are trying to use (which does not have a UrlEncode method). It is instead using the System.Web.HttpUtility.UrlEncode() method.


Here is a link to the two different Utilities.
https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee538597(v=office.15)
https://docs.microsoft.com/en-us/dotnet/api/system.web.httputility?view=net-6.0

^^ Notice the method value differences.

**Comment by Zetser1** [comment]
Thank you for responding so quickly.  I felt guilty even bothering you guys about this because I’m pretty ignorant of what you described below.  I was using the .Net Framework but after reading switched to .Net Core.  I still had problems, probably because I hadn’t installed the correct packages.

Honestly, if there is an example using .Net Framework that demonstrates how to access a sharepoint with the method to obtain the correct type of token that would solve all of my frustration. So that the token obtained is the correct data type used by the sharepoint API, I would love to see it.

I’ve tried using Microsoft Graph APIs, but the examples don’t take the same data type of token that the instructions for obtaining a token return. 😊

**Comment by bcameron1231** [comment]
I probably wouldn't invest in the old .NET Framework CSOM. 

I would try to start over in a new solution (as a .NET core app template in Visual Studio project templates), and make sure you install the proper Microsoft.SharePointOnline.CSOM package version 16.1.20211.12000 or higher.

**Comment by Zetser1** [comment]
Thank you.

**Comment by AJIXuMuK** [comment]
Hi @Zetser1 - totally agree with @bcameron1231 on not investing in the old version of CSOM.

Additional point regarding auth tokens for CSOM and Microsoft Graph.
You will need to request additional permissions and scopes in your Azure AD app to deal with MS Graph (auth for MS Graph is described here: https://docs.microsoft.com/en-us/graph/auth/), and you will need to obtain 2 separate access tokens: one for CSOM, another for Graph API.

It can be tricky at the beginning but makes total sense at the end.

**Comment by Zetser1** [comment]
Thank you both for responding to me.  I’ve already made progress thanks to your advice.
