### ISSUE TITLE
How to move Left Navigation Search box to Top Header in publishing site on SharePoint 2019 server

### ISSUE THREAD

**Issue by DJoshi23** [SharePoint/sp-dev-docs#7599]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

Site designs & site scripts

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

Hi, 

I have created a modern page in my publishing site on SharePoint 2019 server.

I want to move the search box from the left navigation top to anywhere in the SharePoint page header. Please find the below images for reference.

![image](https://user-images.githubusercontent.com/86624727/146516620-fcf81ab1-d40c-4409-b0a9-8b0b74eb1e0d.png)

Thank you in advance

**Comment by VesaJuvonen** [comment]
There's no simple way to do this as that experience is by design in the SharePoint Online which is already numerous years ahead of the SharePoint 2019 capabilities. You could achieve this by either creating a custom master page where you relocate the search control to the top bar location or by using Script Embedding techniques with UserCustomActions to relocate the control with dom manipulation.

So - no simple settings to adjust this, rather custom extensibility needed.
