### ISSUE TITLE
Jest and Enzyme when used with SPFX throws error

### ISSUE THREAD

**Issue by v-royavinash** [SharePoint/sp-dev-docs#7623]
### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Testing Framework Used: **Jest and Enzyme and SPFX**

Versions :
![image](https://user-images.githubusercontent.com/94480537/147898918-df8a4be0-27a5-4833-b13e-a298c0495644.png)

### Steps to reproduce

Test cases throw errors for components which are having other dependent packages like Fluent UI /Office fabric. 
![image](https://user-images.githubusercontent.com/94480537/147898644-092d1177-9d3d-4fb6-b4bf-316a4db3095b.png)

![image](https://user-images.githubusercontent.com/94480537/147898742-49cb46b6-225f-4de3-9f85-6be0297a5b5f.png)

The error initially seems to be a generic error and online references were available on Stack overflow. Followed the steps mentioned in the below links to resolve the issue. Tried to replicate the same fix for a normal react application and following the steps mentioned below fixed it for react application, but the same fix was not working for the SPFX application

- [https://stackoverflow.com/questions/58613492/how-to-resolve-cannot-use-import-statement-outside-a-module-in-jest](url) 
- [https://stackoverflow.com/questions/46898638/importing-images-breaks-jest-test ](URL)
- [https://github.com/vuejs/vue-cli/issues/1584](url)

•	setupTests.ts -->
![image](https://user-images.githubusercontent.com/94480537/147898806-673ecebb-b11b-4d5e-ad98-2e1e30642e0a.png)

•	Jest config -->
![image](https://user-images.githubusercontent.com/94480537/147898823-fc0ff70e-9f7a-4c6e-a504-5275575ea331.png)

### Expected behavior

The error should be not be thrown.

**Comment by patmill** [comment]
Just to confirm, you can't use 12.1 for on-prem.  There's not a lot to go on at this point though, as there is a bunch of stuff that would be configuration dependent.  Can you create / share a minimal project that shows the issue?  We're not exactly experts in enzyme and jest, but we can try and take a look.

**Comment by v-royavinash** [comment]
Hi @patmill 

Thanks for your quick response. 

Could you please provide more details on "_Just to confirm, you can't use 12.1 for on-prem_."
It would be great if you can share your suggested configurations/versions.

For your reference I have created a test project with few components -->
GitHub URL : [https://github.com/v-royavinash/SP-JestEnzyme-Test](url)

Below are the components and test files added to replicate the issue,

- AppHeader  - Component has only React package dependency 
- StatusIcon  - Component has only React package dependency 
- PageHeader  - Component has React and Office fabric package dependency

To run the test cases please use the npm test.

As mentioned in the previous thread, Jest does work for those components which have only react dependency but it fails for components with another package dependency like office fabric in our case.

Output,

- AppHeader  - Works fine
- StatusIcon - Works fine
- PageHeader - Throws below error. And in real-time we will have components with many package dependencies.
![image](https://user-images.githubusercontent.com/94480537/148280021-33d24a4e-331b-4757-848d-4d77720ee138.png)

**Comment by AJIXuMuK** [comment]
@v-royavinash - just FYI @andrewconnell has a blogpost with steps on how to enable Jest testing: https://www.andrewconnell.com/blog/enable-jest-testing-of-sharepoint-framework-projects-in-one-simple-step/

> Could you please provide more details on "Just to confirm, you can't use 12.1 for on-prem."
It would be great if you can share your suggested configurations/versions.

For SharePoint 2019 you should use SPFx 1.4.1

**Comment by andrewconnell** [comment]
@v-royavinash asked:

> Could you please provide more details on "Just to confirm, you can't use 12.1 for on-prem." It would be great if you can share your suggested configurations/versions.

SP 2019 only supports SPFx v1.4.1 which only works with Node.js v8 (ref docs: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.4.1).

Furthermore, you've got a bunch of dependencies that are not going to work. For example:
- [You've listed TypeScript v4.4 in your repro project](https://github.com/v-royavinash/SP-JestEnzyme-Test/blob/master/package.json#L55). No version of SPFx supports TypeScript v4.4.
- SPFx v1.4.1 only supports TypeScript v2.4.
- Same thing with Jest, ts-jest & more... I'm pretty sure you can't Jest v27 because that requires a matching version of ts-lint (v27) the best you can do there is ts-jest v23 so, same story for Jest (v23)
- [You're using React v16](https://github.com/v-royavinash/SP-JestEnzyme-Test/blob/master/package.json#L21)... pretty sure SP2019 can only include v15 (which impacts your enzyme engine, etc)

That should get you started... read this for a lot more info:
https://www.voitanos.io/blog/jest-preset-update-july-2021

But the basics are: you're using newer versions of things that aren't supported for the environment you're working with. You CAN make it work, and that's what my [Jest presets](https://www.voitanos.io/blog/enable-jest-testing-of-sharepoint-framework-projects-in-one-simple-step/) help you with. You don't have to use them, but if you decide to do it yourself, you can use my presets, specifically [the one for React v15 (that applies to SPFx v1.6.0 or earlier)](https://www.npmjs.com/package/@voitanos/jest-preset-spfx-react15) to see the versions thatwill work.

**Comment by v-royavinash** [comment]
Hi @andrewconnell ,

Thank you for the quick turnaround with the detailed steps. I will include the mentioned version of the packages and will confirm if it works as expected.

**Comment by v-royavinash** [comment]
@andrewconnell @AJIXuMuK  , 

There was confusion with the SP. We are using SPFX with Sharepoint Online with version 1.12.1. Do you have any blog post/link which I can refer to configuring Jest? The above error I am getting is for SPFX with Sharepoint Online. It would be great if you can share your troubleshooting insights for SP online.

**Comment by andrewconnell** [comment]
@v-royavinash

See my previously mentioned post: https://www.voitanos.io/blog/jest-preset-update-july-2021

It references the [preset projects I've created](https://www.voitanos.io/blog/enable-jest-testing-of-sharepoint-framework-projects-in-one-simple-step/) and made available. Specifically, the [@voitanos/jest-preset-spfx-react16](https://www.npmjs.com/package/@voitanos/jest-preset-spfx-react16) preset has been tested with SPFx v1.12.1. Even if you don't want to us the preset, you can look at it's publically available source to get the complicated matrix of dependencies & versions that work.

**Comment by AJIXuMuK** [comment]
@andrewconnell provided enough information (thank you!) to mark this issue as "answered".
@v-royavinash - feel free to open a new issue if you have any problems with the SPFx itself.
