### ISSUE TITLE
SPFx web part exposed as MS Teams personal app calling AAD protected API fails during Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken call on Android

### ISSUE THREAD

**Issue by marcinburak** [SharePoint/sp-dev-docs#7639]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Microsoft Edge 97.0.1072.55
- SPFx 1.12.1
- Node.js 14.18.2
- Android 11 MS Teams mobile client 1416/1.0.0.2021195305/1216
- Windows 10 MS Teams desktop client 1.4.00.32771

### Describe the bug / error

I've created a web part that calls both Graph API using `MSGraphClient` and AAD secured Azure Function using `AadHttpClient`. I've followed instructions rigorously and I'm sure everything should be working flawlessly because it works on MS Teams web client and MS Teams native Windows client, however it fails when opening personal app in MS Teams Android native client.

I researched similar issues mentioned in this repo and made sure I applied every workaround, to quickly sum it up:

I made sure that web part supports Teams personal apps 
```"supportedHosts": ["SharePointWebPart", "TeamsPersonalApp", "TeamsTab"]```

I made sure that SPFx solution explicitly requires Graph API and my custom API scopes
```
  "webApiPermissionRequests": [
            {
                "resource": "Microsoft Graph",
                "scope": "User.ReadBasic.All"
            },
            {
                "resource": "MyApp",
                "scope": "user_impersonation"
            }
        ],
```

After publishing and syncing the web part to MS Teams i went to 
`https://[tenant]-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement`
and approved both scopes.

I also visited `SharePoint Online Client Extensibility Web Application Principal` service principal and made sure it reflected the changes after approving scopes in SharePoint admin panel.

It should work because as I mentioned it works both on web and desktop clients. On Teams desktop call to the `https://[tenant].sharepoint.com/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=%27[CLIENT_ID]%27&clientId=%2763b6e303-629c-460c-8d6c-e921bc040bc5%27` ends up with HTTP 200 and valid access token - web part works as expected, however when calling the same exact endpoint on the Android client it ends up with HTTP 400 "The target resource is invalid because it does not exist, cannot be found, or it is not correctly configured".

### Steps to reproduce

1. Create a SharePoint Web Part following this [tutorial](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-spfx?tabs=vscode%2Cviscode)
2. Create app registration in your tenant with simple delegated `user_impersonation` scope (note down its display name and client id)
3. Append this to your `package-solution.json` file
```
 "webApiPermissionRequests": [
            {
                "resource": "Microsoft Graph",
                "scope": "User.Read"
            },
            {
                "resource": "<YOUR_APP_DISPLAY_NAME>",
                "scope": "user_impersonation"
            }
        ],
```
4. Add this simple API calls to `<WEBPART_NAME>WebPart.ts` file
```
public onInit(): Promise<void> {
    this.context.msGraphClientFactory.getClient().then(graph => {
        graph.api("https://graph.microsoft.com/v1.0/me").version('v1.0').get(() => {
            alert("Called Graph");
        });
    });
    this.context.aadHttpClientFactory.getClient("<CLIENT_ID>").then(aad => {
        aad.get("https://test.com", AadHttpClient.configurations.v1).then(() => {
            alert("Called AAD");
        })
    });
    return super.onInit();
}
```
5. Deploy web part to your SharePoint app catalog
6. Apply admin grant by navigating to `https://[tenant]-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement`
7. Sync web part to Teams app store
8. Open the webpart as personal tab in MS Teams Android client with [developer preview turned on and Android debugging setup](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-from-an-android-device)
9. Monitor the web developer tools network tab to view failed HTTP 400 request to `https://[tenant].sharepoint.com/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=%27[CLIENT_ID]%27&clientId=%2763b6e303-629c-460c-8d6c-e921bc040bc5%27`

### Expected behavior

I expected for the `https://[tenant].sharepoint.com/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=%27[CLIENT_ID]%27&clientId=%2763b6e303-629c-460c-8d6c-e921bc040bc5%27` HTTP calls to return HTTP 200 responses with access tokens, just like it works on Windows Teams Desktop client.

**Comment by OliverZeiser** [comment]
We are seeing the same issue: "The target resource is invalid because it does not exist, cannot be found, or it is not correctly configured." Same thing happens on iOS.
Plus we are also seeing this in Taskmodules in the Desktop Client...
@patmill or @VesaJuvonen since this seems to be a broader issue. Please forward this to the right people as soon as possible. Thx!

**Comment by patmill** [comment]
Yup, we are investigating.  Thanks for the information.

**Comment by jemjos** [comment]
Experiencing the same issue in both iOS and Android devices when accessing the SP page via Teams.

**Comment by umaknow-joel** [comment]
We are experiencing the same problem as well on iOS, but we also have it in the Windows Desktop app.  
- iOS v3.21.0 Build 3.21.77.2021215101/1229 (I am using the French version)
- Desktop 1.4.00.32771 (64 bits) (I am using the French version also)

The app is working in the browser version in both : 
- Chrome 97.0.4692.71 (Build officiel) (64 bits)
- Edge 97.0.1072.62 (Version officielle) (64 bits)

We are using 
- SPFx 1.11
- Node.js 10.22.1

We did the same thing documented in the problem statement, except that we built our Team manifest ourselves using this guidance for personnal tabs found here.  https://docs.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions#developer-provided-microsoft-teams-app-manifest--package  

Our application is an SPFx app calling SharePoint resources, Graph API and custom API.  The SharePoint calls (lists, property bag...) work on all environments.  The Graph and custom API calls fail on the iOS and Desktop app but work in the browsers.

Our tenant is deployed using early ring. 

We used fiddler on the desktop.  First call when we get the AADHttpClient we get a 500 with error 
{"odata.error":{"code":"-1, System.AggregateException","message":{"lang":"fr-FR","value":"One or more errors occurred."}}}

All subsequent calls to the API return a 400 with error
{"odata.error":{"code":"10009","message":{"lang":"fr-FR","value":"The target resource is invalid because it does not exist, cannot be found, or it is not correctly configured."}}}

The complete Fiddler trace is available on request if you want it.

**Comment by GrahamMcMynn** [comment]
@umaknow-joel  - please ensure that your resources in webapplicationinfo have https://{teamSiteDomain} as the resource otherwise your solution will not work.

This is outlined in our documentation at:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions

Specifically this box:
![image](https://user-images.githubusercontent.com/16929083/150005868-c3aa2a7d-20db-49eb-bab4-3e62ced59b2c.png)

**Comment by lucabandMSFT** [comment]
Teams Mobile is currently experiencing some issues and the team is working to fix it. We are tracking progresses here: #7646
