### ISSUE TITLE
Again problems with token retrieval in Teams desktop client

### ISSUE THREAD

**Issue by cwdata** [SharePoint/sp-dev-docs#7642]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Teams Desktop Client Version:  1.4.00.32771 (64-Bit)
- SPFx Version: 1.11.0

### Describe the bug / error

We developed a personal Teams app using SharePoint Framework. 
Today it suddenly stopped working in the desktop client with the following error message:
![image](https://user-images.githubusercontent.com/26869201/148965725-97e7cff8-14cb-4497-88a4-e867f01214e0.png)
That happens when it tries to access an AAD secured custom Api using the built in AadHttpClient class.
It still works in the browser.
And yes - I did reset my password yesterday. AFAIK the AadHttpClient class should handle the token refresh automatically in the background.

### Steps to reproduce

1. Open an personal Teams app which uses AadHttpClient in the desktop client
2. Once the app retrieved an access token change your password
3. Try to open the app again

### Expected behavior

Tokens for custom Apis should be refreshed automatically after a user changed his password.

**Comment by GrahamMcMynn** [comment]
Hi @cwdata - Sorry that you are experiencing this issue.  I took a look at our logs and it appears the problem is somehow the consent for the first party app has been revoked:
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID '08e18876-6177-487e-b8b5-cf950c1e598c' named 'SharePoint Online Web Client Extensibility'. Send an interactive authorization request for this user and resource

Could you go to portal.azure.com and check your enterprise applications and see if you have disabled the app?  To do this click the following things in the portal:
![image](https://user-images.githubusercontent.com/16929083/149213184-0f9bd736-fe39-4f9c-9a79-c77a37ed0251.png)

You will have to choose All Applications, and search for sharepoint.  Then click on the SharePoint Online Web Client Extensibility app.  That will bring you to this screen where you must ensure that "Enabled for users to sign-in" is Yes:
![image](https://user-images.githubusercontent.com/16929083/149213342-4afb8ab1-a033-4b76-a3eb-a4a62bcd1bdd.png)

If this doesn't fix your issue could you reach out to me at grahamc at microsoft.com and I can help you dig further into this issue?

**Comment by cwdata** [comment]
Hi @GrahamMcMynn,
thanks for your suggestions. The enterprise app in our tenant looks exactly the way it is shown in your screenshot. I'm also 100% sure that no one from our end changes the settings of such apps. Additionally, as I've written, it did work in the browser.
It seems to me, that this AADSTS65001 error is more like a "general error" than really being related to consent.
Anyways, it started to work again today without us changing anything. So I can't help you with debugging this issue further.
Thanks again for your support, I really appreciate that MS is now reacting more often to the issues reported here.

**Comment by GrahamMcMynn** [comment]
@cwdata - Glad it is working again and sorry that you experienced this issue. Just as a follow up to the comment "it did work in the browser".  The browser and the teams rich client use completely separate auth pipelines right now.
