### ISSUE TITLE
SPFx generator 1.1.1 bundles office ui fabric react components - which leads to increased .js size

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#769]
#### Category
- [x] Question

Previously when I compiled https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor my .js bundle was less than 10kb. Now it's close to 600kb as the Office UI Fabric components are included in the bundle.

Not sure exactly which part of the setup this is related to, if it's the generator or some other package.

Is this intended, or a bug?

**Comment by wobba** [comment]
I do see the reasoning as to not bind to a specific version of the office ui fabric components. But as ui fabric is not a specific npm module in package.json I cannot easily externalize it either to save from bundling this into every part on a page as I don't know which version it's using.

**Comment by wobba** [comment]
I have now read https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/office-ui-fabric-integration which indeed points to the static linking.

**Comment by mcmynn83** [comment]
@VesaJuvonen - Could you follow up for the documentation question/request

**Comment by wobba** [comment]
@VesaJuvonen I managed to get a workaround going - take a look at http://www.techmikael.com/2017/08/how-to-reduce-bundle-size-when-using.html so we could perhaps close this issue.

**Comment by wobba** [comment]
@VesaJuvonen Seems if I use `import { Button } from @microsoft/office-ui-fabric-react-bundle` instead I get down to a zero footprint as this bundle is already on the page, and not included when packaging. Is there an issue using this bundle instead of the guidance at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration?

Which means, use `@microsoft/office-ui-fabric-react-bundle` instead of `office-ui-fabric-react`.

**Comment by VesaJuvonen** [comment]
Reason for the guidance on bundling Office UI Fabric to the JS bundle is to avoid any future issues caused by breaking changes in the Office UI Fabric side... Let's say that your web part is created today and you use the button which is loaded by SP automatically on the page without bundling fabric. This works now - but when the SharePoint UI will evolve to next version of Office UI Fabric, you references and assumptions in the code might break.. which will cause your web parts execution to fail... you definitely want your web part to work within 2 years in the SPO still... regardless of whatever the native SharePoint UI is using at that point. It could be still Office UI Fabric or something new called, for example, Vesa's UI Goo... who knows at this point.

To avoid these issues, the recommendation is to bundle the used controls and packages to your own bundle. This does indeed increase the overall size of the bundle, but.... it will ensure that your custom web part will work in the future regardless of the changes in the SharePoint side...

If you compare this to old SP models (conceptually) - if you reference Fabric components natively from the SharePoint side, you are kind of having a direct reference to JavaScript file with specific version... when we change the URLs of those JavaScript files, your implementation will fail... so it's worthwhile to ensure that you have your own copy of the critical elements and code. 

Makes sense?

**Comment by wobba** [comment]
Thank you @VesaJuvonen, and I understand 100% why it is like this and that guidance is the sure way to go in order for your parts to keep on working forever.

Which means using `@microsoft/office-ui-fabric-react-bundle` is a bad idea as you need to potentially recompile your SPFx solutions each time there is a new drop. Not something I would like to be responsible for :)

And I'm fine with bundle sizes as it's all CDN, compressed and mostly cached these days anyways :)
