### ISSUE TITLE
Unable to deploy .sppkg on site collection app catalog

### ISSUE THREAD

**Issue by bcameron1231** [SharePoint/sp-dev-docs#7723]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

When trying to deploy a .sppkg file to the site collection app catalog, it results in a "Deployment Failed" error with a correlation id. This issue is a repeat issue from a couple of weeks ago that I worked through with Premium Support. They found the error in the ULS logs to be a List View threshold error.

However, we have found that if we remove the webApiPermissionRequests from the package-solution.json, it will deploy successfully. Adding back the webApiPermissionRequests will force the failure.

![image](https://user-images.githubusercontent.com/7944457/154296006-deec5cb9-9dc1-477b-a429-986bbe43b82c.png)

### Steps to reproduce

1. Create an SPFx Web Part
2. Add webApiPermissionRequests
3. Deploy to the site collection app catalog

### Expected behavior

Deploying a .sppkg with webApiPermissionRequests should deploy successfully.

**Comment by GrahamMcMynn** [comment]
Hi @bcameron1231 - sorry that you are running into this issue.  We have determined the problem and have steps that you can follow until we issue a fix for this issue.  A very small number of tenants are affected by this issue, basically when a WebApiPermissions list grew too large it starts preventing people from creating new apps.  The reason it grew too large was due to a bug where we did not prevent duplicates from being added.

Can you manually go and visit the tenant app catalog and then append Lists/WebApiPermissionRequests to the URL (ie something like https://contoso.sharepoint.com/sites/appcatalog/lists/webapipermissionrequests).

Youl should see a list like this:
![image](https://user-images.githubusercontent.com/16929083/154325319-2af56894-2872-411b-bef4-b55cb3e8005c.png)

I believe you will see a whole bunch of duplicate entries where resource Id/Scope/Package ID are NOT unique.  You only need 1 entry for each unique combination here.  If you could just delete all the duplicates it should unblock you.

However, if you actually have 5000 unique web api permissions and these are not duplicates you will not be able to unblock yourself and will have to wait until we deploy a fix.  I do not currently have a timeline for how soon that will be.

**Comment by bcameron1231** [comment]
@GrahamMcMynn  Thank you! We do not have 5,000 unique web API permissions across the tenant so that should be okay. We have just checked the list and we have 21k items in it!

We do a lot of CI/CD and I suspect that every time we check in and deploy code, and entry is added here. We'll make the deletions now... but we would love to see a fix for this!

Thanks.

**Comment by bcameron1231** [comment]
@GrahamMcMynn  This did fix our issue. We've opted to remove the Web API permissions from our package-solutions for now until you have a fix in place for this, as our CI/CD pipeline would probably hit 5k items again in no time.

Thanks

**Comment by GrahamMcMynn** [comment]
The fix that prevents duplicates from being added is already in production and world wide.  So CI/CD shouldn't actually hit it again unless it's adding new unique entries over and over.

**Comment by bcameron1231** [comment]
@GrahamMcMynn Are you saying the fix is already in place now?

**Comment by GrahamMcMynn** [comment]
Fix is already in place to prevent duplicate creation.  However, if you already have a lot of duplicates we have not done anything to clean it up or prevent the error you were seeing.  That being said, new duplicates will NOT be created.

**Comment by bcameron1231** [comment]
Thank you!

**Comment by bcameron1231** [comment]
Okay. That's interesting, as this exact error popped up for us a few weeks ago.. and then went away and premier support said it was fixed. But we never cleared any items from our list during that timeframe... so unless Microsoft did, it would have had over 5k items in it. Today it has 21k items in it, which means it was still growing.

**Comment by bcameron1231** [comment]
@AJIXuMuK  Sorry I missed this. I'll have to check . As of 3/11 it was still duplicating the requests.

**Comment by KeviCheng** [comment]
@bcameron1231  Can I clarify what request you are seeing duplicated? are you seeing two domain isolated requests for the same api? or two requests for the same thing in the organization-wide scope?

**Comment by bcameron1231** [comment]
We **were** seeing hundreds of the same same request in the Web API Permission Requests List for all apps that get deployed whether at the Tenant Level or at Site App Catalog. We have CI/CD so every time we check in, a new request was being added to this list.

It looks like this was fixed and we aren't seeing this issue anymore. Rather than adding new records to the list, it is correctly updating the existing packages. I can close this ticket.
