### ISSUE TITLE
SharePoint On-Premises

### ISSUE THREAD

**Issue by shurick81** [SharePoint/sp-dev-docs#778]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
On the https://dev.office.com/sharepoint/docs/spfx/sharepoint-framework-overview page there should not be stated that SharePoint Framework is compatible with SharePoint On-premise, since Feature Pack is not released yet.

#### Observed Behavior
We can find following claim on this page:
"The SharePoint Framework works for SharePoint on-premises and SharePoint Online"

#### Steps to Reproduce
Open https://dev.office.com/sharepoint/docs/spfx/sharepoint-framework-overview in a browser

**Comment by VesaJuvonen** [comment]
thx Alex for reporting this. The article has been now updated to indicate that SPFx is supported in Online currently and soon in SP2016 (Feature Pack 2). Absolutely valid wording to update at this point. The update will be available within few minutes after this comment. I'll close this for now since the issue has been fixed.
