### ISSUE TITLE
No clear steps to run a web part 

### ISSUE THREAD

**Issue by johnguilbert1970** [SharePoint/sp-dev-docs#7790]
Hi.

Please can someone just give the latest versions required for Gulp, Npm, Node etc so that I can run these web parts. I keep getting the primordials issue, or @microsoft/sharepoint module missing if I fix former issue. 

All I can assume is that a lot of users are using their legacy react-script-editor web part. You guys need to make it clearer. Are there incompatibilities still with latest Gulp etc. 

Help really appreciated.

Thanks.

John.

**Comment by andrewconnell** [comment]
99% of the time you get that error, it's related to a mismatched Node.js version. Can't easily answer this without knowing what version of SPFx your project is using.

Refer to the release notes for each SPFx version for what version of Node.js is supported by that version. 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility

The version of gulp is also dependent on Node.js version which is driven by the version of SPFx. The release notes in the docs explain this. I've also explain it further on my own site because it's less about SPFx docs than it is about Node & gulp (which IMHO doesn't belong in SPFx developer docs): https://www.voitanos.io/blog/mea-culpa-always-install-gulp-cli-globally-not-gulp/

**Comment by patmill** [comment]
As Andrew mentioned, you can find that information here - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility.  Although it is missing the gulp version.  Use 4.

**Comment by johnguilbert1970** [comment]
Thanks Andrew. Only just noticed the versions used in graphic form on web part instructions.
-----Original Message-----
