### ISSUE TITLE
SPFx is loading library component old version for some users

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/sp-dev-docs#7805]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.9.1 & 1.10

### Describe the bug / error

Currently, we are having an issue impacting many users in our tenant while accessing our Intranet (some users don’t have the issue). After deep investigations, we noticed that the endpoint: [https://[tenant].sharepoint.com/sites/[site_name]/_api/web/GetClientSideComponents
is not retrieving the latest version of the library components, rather the previous version. Having this makes our library is not working properly. As a temporary fix, we hard refresh the SharePoint pages, or append ?sw=bypass to the SharePoint page URL.

This issue was fixed few weeks back where it effected all of users in the tenant. This is now effected only few users where get old solution manifest on normal page load and on hard refresh page load, it loads new version. 

### Steps to reproduce

1. Deploy SPFX library solution with version 1.0.0
2. Do some updates to the library solution.
3. Deploy SPFX library solution with version 2.0.0.
4. It will load version 1.0.0 JS file for some users and after hard refresh, it will load version 2.0.0 JS file. 

### Expected behavior

The expected behavior is that it should always load the upgraded JS file from new deployed solution for all users in all regions.

**Comment by demyren** [comment]
Aruna, we recently made another small follow-up change to the recent caching problems we had seen where files could get cached infinitely if they did not specify a max-age. Can you confirm this is related to caching of your script file? 
If you find the script file in the Cache Storages that has a name that starts with "Site-" and delete your file from there, does it resolve the issue for the broken clients?

**Comment by rmillener** [comment]
We are also experiencing this on two large tenancies where we are using library components.

Doing a normal load results in an old/invalid version being loaded.
Doing a hard refresh of the page results in the current version being loaded successfully.

**Comment by demyren** [comment]
@arunakshi I see, thank you for the detailed description. I appreciate it!

We have found a regression that causes third-party extensions that have been previously retrieved by GetClientSideComponents to return the local version of the component instead of fetching the updated version. A fix will deploy over the course of next week to resolve the problem.

Unfortunately, in the meantime, the only viable workaround is to refresh with CTRL+F5 or Clear site data from F12->Application->Storage.

Once the deployment of the fix has completed, I can let you know so you can verify the fix.

**Comment by arunakshi** [comment]
@demyren, thanks for the quick check.

**Comment by salascz** [comment]
@demyren could you share more details what was changed?

I am expecting similar issue - I am doing small update within my library. Previous version is already deployed on another site (site app catalog). GetClientSideComponents reference to the library on another site, but it cannot be loaded as such a version (e.g. library_f130c2a60a3d3f7ee1c0.js) exists on my site only (returns 404)

I do not increase library version as it was not necessary till now (the library contains modern-search extensions) 

Thanks

**Comment by AJIXuMuK** [comment]
@salascz - based on your description, it doesn't related to the issue.
You have library component is site collection app catalog. It will not be available on any other site collection.

**Comment by max-andrade** [comment]
I am having this same issue as reported @salascz , which actually seems to be related to to originally issue reported by @arunakshi .

We use site collection catalogues in order to support a DEV > TST > UAT > PROD flow (where PROD sites use the tenant catalogue).

Over the past week or so, maybe two, we have started experiencing this issue where some some site collections are not behaving as expected (weird web part errors and app customizer crashes). After some troubleshooting we have found that the SPFx solutions from Site Collection A (with its own catalogue) are actually trying to download components from Site Collection B (also with its own catalogue).

For example, when we visit **Site A**, the JS file reference use is actually https://publiccdn.sharepointonline.com/TENANT.sharepoint.com/sites/ **SITE-B** /ClientSideAssets/9a8bca3d-8003-417a-a5df-760a2b1df79d/global-nav-application-customizer_79c78b2b6e1c12067784.js instead of the expected URL of https://publiccdn.sharepointonline.com/TENANT.sharepoint.com/sites/ **SITE-A** /ClientSideAssets/9a8bca3d-8003-417a-a5df-760a2b1df79d/global-nav-application-customizer_79c78b2b6e1c12067784.js

We have tried clearing the browser cache, removing/adding the app and even completely reinstalling the SPFx solution. nothing eliminates the issue.

**NOTE:** As this issues seems to have started around the same time, and it seems to be related with the logic retrieving the solution assets, we are thinking this is related. We are opening a ticket with Microsoft, however, would be interested to check if anyone else is experiencing this issue as this would probably help us with the ticket. I'll post updates in here when I hear anything from support.

**Comment by arunakshi** [comment]
Do we have the fix deployed already? Could you please let us know if there is any update on this?

**Comment by demyren** [comment]
@arunakshi We are currently in the process of deploying the fix. We hope to complete the deployment fully by March 25. 

@max-andrade I'm afraid this does not sound like the same issue. If the library component is installed on the site collection, it can only be used in that scope.

**Comment by demyren** [comment]
@arunakshi We have finally completed the deployment. Once your customers have reinstalled the new service worker, this issue should resolve by itself. Please let me know once you are able to confirm the solution, or let me know if you are still experiencing any issues.
Thank you for helping us make the product better! We truly appreciate the engagement and feedback.

**Comment by arunakshi** [comment]
Thanks @demyren. We will check on Monday and you feedback.

**Comment by arunakshi** [comment]
@demyren, we were able to test in our dev environment and confirm that it's working for us. Is it deployed already in all tenants? We want to make sure that its fixed also in production environment. could you please let us know.

**Comment by demyren** [comment]
@arunakshi Yes, the change is deployed to all tenants. Users may need to revisit SharePoint once for changes to take effect.
