### ISSUE TITLE
Cannot find name 'IPropertyPaneSettings'

### ISSUE THREAD

**Issue by AmrHamam** [SharePoint/sp-dev-docs#782]
following this tutorial 
https://github.com/SharePoint/sp-dev-docs/blob/staging/docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties.md
in section: Populate the dropdown with SharePoint lists to choose from; 
I was trying to do this step: 
Change the propertyPaneSettings getter to use the dropdown control to render the listName property.

but in Visual studio code it says: [ts] Cannot find name 'IPropertyPaneSettings'.

**Comment by waldekmastykarz** [comment]
The tutorial is based on an older version of the SharePoint Framework. In the latest version instead of using the `IPropertyPaneSettings` interface, you would use the `IPropertyPaneConfiguration` interface. The rest of the code is similar and you can compare it by creating a standard HelloWorld web part and comparing the `getPropertyPaneConfiguration` method.

**Comment by mcmynn83** [comment]
If the issue is resolved please close this.

**Comment by AmrHamam** [comment]
lets update the tutorial to avoid this later.
