### ISSUE TITLE
SPFx Extension Placeholder Names Changed

### ISSUE THREAD

**Issue by thechriskent** [SharePoint/sp-dev-docs#805]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The placeholder names for use with an Application Customizer have been PageHeader and PageFooter.

#### Observed Behavior
On modern pages within a developer tenant these are now Top and Bottom. However, modern list views are still reporting `Defined clientSidePlaceholders: DialogContainer,PageHeader,PageFooter`. However, these pages are not currently working with Application Customizers giving the following error:
```
Invalid location: ClientSideExtension.ApplicationCustomizer
```

#### Steps to Reproduce
To see the new placeholders, debug an Application Customizer on a modern page and add the following line to the `onRender` method:
```
console.log(this.context.placeholders.placeholderNames);
```

Are these changes part of the breaking changes promised with RC1 or are they an unplanned bug?

**Comment by vman** [comment]
I have noticed this as well:
In communication sites, the place holders are `Top` and `Bottom`.
On a modern page in a classic team site , the place holders are `DialogContainer, PageHeader` and `PageFooter`

**Comment by VesaJuvonen** [comment]
This is by design as part of moving closer to Release Candidate and GA. Due to numerous reasons, place holder names are changed and we'll need to update first server side before we can push out an update to the Yeoman templates. More information on upcoming updates will be available soon. We do apology the impact for your existing dev preview extensions.

**Comment by thechriskent** [comment]
I thought that might be the case, thanks for the update! 

Honestly, I'm really excited about RC1 (and GA of course). It's just that I am giving a presentation tomorrow at SharePoint Saturday Charlotte on these. It didn't take much to rework my demos so far, but are there any other planned changes between now and tomorrow that I should be watching out for? Thanks!

**Comment by VesaJuvonen** [comment]
@thechriskent - you are actually in slightly dangerous waters. It really depends on which update cycle your tenant is. I would suggest to either take just in case screenshots or record a quick video as a back. Timing is not optimal and we hate to break early adopters, but there were some mandatory changes which were needed to be done. Changes are not huge, but the inconsistency between server and client can potentially cause you some challenges until our npm packages are published.

**Comment by CloudDesignBox** [comment]
I'm in the same situation. Hoping to demo some of these things on 5th Sept. I have worked around the placeholder name changes. Do you have any dates or timescales for the changes?

**Comment by VesaJuvonen** [comment]
Right now we are pushing changes cross the tenants and farms. When this will hit your specific tenant is dependent on which farm it's hosted, so we can't define the exact date and time for each of the tenants. We'll provide more details and needed updates early next week. Place holder change won't be unfortunately the only change and some of the changes in upcoming RC will break you until you'll get the updated npm packages. Can't disclose unfortunately exact time on that right now, but will obviously happen soon with the needed details on updating your code. 

If you have demos and/or presentations coming for example for this weekend, would recommend recording the demos beforehand to avoid issues and concentrate on the code presentation. We absolutely understand that this is not optimal for these situation and this only happens since it was developer preview - when we get to the GA, this kind of surprises will not happen.

**Comment by CloudDesignBox** [comment]
Looking forward to the updates Vesa, exciting stuff!

**Comment by thechriskent** [comment]
Thanks! I've got them all captured so I should be fine. We all knew the risks when working with Preview releases, thanks for the update!
