### ISSUE TITLE
Feature Request: Cross browser / cross device testing capabilities

### ISSUE THREAD

**Issue by StfBauer** [SharePoint/sp-dev-docs#81]
When it comes to modern web development nothing beats cross browser and cross device testing. With the work bench I can only test one browser at a time. Currently the client clicks won't be synced across devices. 

The most commonly used tool not only for testing but even for development is. [browser-sync.io](https://www.browsersync.io).
It makes it easy to see that your code is working across multiple platforms, browser and devices.

Are you looking into having a similar functionality in SPFx?

From my perspecitve it is a really important feature these days even for SharePoint, since not all customers are on IE anymore and all the time.

The current preview is a nice to have but is just an emulator in a specific browser and doesn't cover real world scenarios. Most browser already have that kind of generator embedded directly in the browser.

**Comment by nickpape-msft** [comment]
Browsersync does seem like a very useful tool. We will do some investigation and consider adopting browsersync by default in the toolchain.

For me, this issue also touches on the concept of opening the build tools to allow for custom tasks. This is an issue talked about in other places in the issue list, but with an open build system (at the moment it is intentionally black-boxed), it would be relatively straightforward to easy to write a gulp or gulp-core-build to use browsersync instead of karma.

**Comment by patmill** [comment]
Closing down old entries that are not actually issues with SPFX.  Feel free to open a suggestion in user voice ( https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/ ) to track this.  We have taken the suggestion internally though.
