### ISSUE TITLE
Update Types for react-dom when using the latest generator@1.2.0

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#822]
#### Category
- [X] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
_When creating a new spfx solution using the sharepoint generator and choosing react as framework, the latest version is now using react-dom 15, and so should be the types for react-dom in package.json._

#### Observed Behavior
_Instead, types for react-dom in package.json are still in 0.14.18._

Is this a bug or is there a reason for this?

**Comment by pgonzal** [comment]
The **react-dom** typings aren't particularly important, but I'll see if we can update them to stay consistent with what **office-ui-fabric-react** is using.  We will also consider removing these packages, which all appear to be deprecated now:

```
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-update": "0.14.14",
    "@types/react-addons-test-utils": "0.14.15",
```

**Comment by pgonzal** [comment]
The React 15 typings require a newer TypeScript compiler.  This is why we originally preserved the React 14 typings when we upgraded to React 15.  Since the latest SPFx has the newer TypeScript compiler, we can now upgrade the typings.  However, we won't upgrade them for the on-prem Yeoman target, since it doesn't have the newer compiler.

I'm testing **@types/react** = 15.6.6 and **@types/react-dom** = 15.5.6.  If there aren't any issues, it should be in the next SPFx release (after 1.4).
