### ISSUE TITLE
Error: AADSTS65001: The user or administrator has not consented to use the application

### ISSUE THREAD

**Issue by paigeflourin** [SharePoint/sp-dev-docs#8249]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- Chrome: Version 102.0.5005.115 (Official Build) (64-bit)
- SPFx version: 
    "@microsoft/sp-core-library": "1.15.0-rc.0"
- Node.js version
- 14.19.3

### Issue description

I created an SPFX app and then an Azure function app that I have deployed. I need to connect my SPFX to the Azure function app to consume the endpoints i have created. what i did was:

1) Registered my function app in the AAD App registrations , added these permissions:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/6951524/176620414-a6e0b1d9-f9b8-4bca-ab9f-d275eb77732f.png">

2) Also added this to my SPFX

```
 "webApiPermissionRequests": [
      { "resource": "<appname>", "scope": "user_impersonation" },
      { "resource": "Microsoft Graph", "scope": "User.ReadBasic.All" }
    ]
```

Im not a global admin, so i asked for the admin to approve all the necessary permissions. app was trusted in https://tenant-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement already. 

but when i was testing i get this error: 

> InteractionRequiredAuthError: AADSTS65001: The user or administrator has not consented to use the application with ID 'fb65feee-6b0f-4ec9-b37e-a65e25a117f0' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.
> Trace ID: 210f593e-d2cb-4769-966c-ebf128307c00
> Correlation ID: a55fe745-4f79-48bc-aceb-322228040150
> Timestamp: 2022-06-30 07:30:47Z

Would like to note that when i opened 'SharePoint Online Client Extensibility Web Application Principal' I dont see the app I registered in the API / Permissio name.  shouldn't it be automatically added there when the admin trusted the app in the webApiPermissionManagement ?

**Comment by GrahamMcMynn** [comment]
Hi There, could you go to portal.azure.com, click on View under Manage Azure Active Directory, click on Enterprise Applications in the left nav, search for SharePoint Online Client Extensibility Web Application Principal and click on the link for it then click on the Permissions item on the left nav. 

Under Admin Consent you should see Microsoft Graph with a claim value of user.impersonation after you have approved the permissions from the web api permission page.  If you do not see this something has gone wrong.  Please let me know if it is there.

If it is not there either the permission was not requested from the package, or an error occurred when approving it.  In order to get unblocked the easiest thing to do would probably be to delete the package and re-add it so your permission request gets created again.  If that happens can you send a trace for the Web Api Permission page being loaded and approving the permission from your global aad admin?
