### ISSUE TITLE
[bug/question] - Since yesterday, All custom webpart crash on several tenants

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#8329]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- LAtest for all
- SPFx 1.14 or 1.13.1
- latest Windows 11

### Issue description

Since yesterday, I have several tenants where the custom webpart (SPFx) no longer works.
I didn't update the webparts, the SPFx version is 1.14 or 1.13.1
Do you have the same problem ?

Error screenshot :
![image](https://user-images.githubusercontent.com/582733/180383762-2fa67ed7-9d78-4d99-b9ad-4e45d403db66.png)

**Comment by velisekj** [comment]
I have maybe similar problem (but a few months). When I update my custom spfx sppkg in SP app catalog, some times (40-50 % of requests) I get error with webpart page.

![obrazek](https://user-images.githubusercontent.com/3352160/180417976-1e757ed8-1d0f-4416-9aae-4da760635310.png)

SharePoint try get component javascript but the oldest version of javascript filename, which does not exist on the server.

SPFX v 1.13.1

**Comment by PooLP** [comment]
I haven't updated, these are webparts that have been in place for ~6 months/1 year.

**Comment by AJIXuMuK** [comment]
@PooLP - could you please check the response for the js request in the network tab?
Also, if you disable Public CDN - will it work?

@velisekj - it doesn't seem to be related. Could you please create a separate issue and also check if adding `sw=bypass` to the query string on the page or Ctrl+f5 refresh fixes the issue?

**Comment by PooLP** [comment]
@AJIXuMuK Thanks for response. It's work with Public CDN desactived

**Comment by AJIXuMuK** [comment]
@PooLP - could you still share the error you were seeing for the CDN?
I want to check if we need to make any additional changes similar to #8261

**Comment by PooLP** [comment]
@AJIXuMuK , i have reactivated the CDN on my dev tenant, and the error re-appear. it's not same error.

![image](https://user-images.githubusercontent.com/582733/180784784-09f7bfb9-7ce8-4c49-8063-fc42b9ee9bd2.png)

**Comment by AJIXuMuK** [comment]
@PooLP - could you please send me your tenant name and correlation id (request-id) header to aterentiev@microsoft.com?

**Comment by pk-1990** [comment]
Hi @AJIXuMuK ,
We are also experiencing the same issue since last week and issue is coming only for IOS devices. SPFX webpart is loading fine on Android devices and Desktop. Adding sw=bypass didn’t help. Please see the below error snapshot:
==============================================================================

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "1916d68d-1d96-48d7-9aa5-bc456d199df1" (MeetingSolutionsWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/sites.ey.com/sites/MeetingSolutions/ClientSideAssets/ce0bed92-1502-42c4-a72b-c7bc2c487000/meeting-solutions-web-part_6af2c831c1585d3a99c2.js' for resource 'meeting-solutions-web-part' in component '1916d68d-1d96-48d7-9aa5-bc456d199df1' (MeetingSolutionsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/sites.ey.com/sites/MeetingSolutions/ClientSideAssets/ce0bed92-1502-42c4-a72b-c7bc2c487000/meeting-solutions-web-part_6af2c831c1585d3a99c2.js' for resource 'meeting-solutions-web-part' in component '1916d68d-1d96-48d7-9aa5-bc456d199df1' (MeetingSolutionsWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
[t@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_202f64d9326273d207750ffc220fdaba.js:70:215088](mailto:t@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_202f64d9326273d207750ffc220fdaba.js:70:215088)
[t@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_202f64d9326273d207750ffc220fdaba.js:70:780156](mailto:t@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_202f64d9326273d207750ffc220fdaba.js:70:780156)
t@[native code]
@https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_202f64d9326273d207750ffc220fdaba.js:70:817505
@https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_5659168cd2dbf133c865.js:1:6059
promiseReactionJob@[native code]

**Comment by AJIXuMuK** [comment]
@PooLP confirmed the issue is resolved.

**Comment by pk-1990** [comment]
> @pk-1990 - if you're experiencing it on iOS only - it means it is definitely unrelated issue. Please, create a separate issue and also check network details for the js request to see what error is returned by the server.

Hi @AJIXuMuK ,
Raised a separate [issue # 8342](https://github.com/SharePoint/sp-dev-docs/issues/8342) . Its coming in production. Please check . Thanks !

**Comment by PooLP** [comment]
@AJIXuMuK it's ok. Thanks.
