### ISSUE TITLE
ApplyTheme: neutralLighter / second section color does not change

### ISSUE THREAD

**Issue by emilyTeichrib** [SharePoint/sp-dev-docs#8370]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

not applicable

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Previously, when I applied a theme that I created with Theme Designer (https://fluentuipr.z22.web.core.windows.net/heads/master/theming-designer/index.html), it also allowed me to change the second section color. For the second section color the color "neutralLighter" from the theme is used as far as I know (until now it was always like this). We use different tenants and on those, where always directly the new releases are applied, this color is no longer loaded from my self-defined theme, but a standard light gray is used. On the other tenants it still works correctly. Is this a bug that will hopefully be fixed as soon as possible or have things fundamentally changed here?

### Steps to reproduce

1. Apply a custom theme with the endpoint "/_api/ThemeManager/ApplyTheme"
2. Check the second section background color, if it has the color of "neutralLighter" in the theme definition.

### Expected behavior

The second section background color has the color that is defined as "neutralLighter" in the custom Theme.

**Comment by tomvr2610** [comment]
We are also seeing this issue on multiple tenants. The issue is not the theme not setting (the colors are set correctly if you check with powershell) but they are not rendering correctly. It looks like MS is just ignoring some of the theme colors like "neutralLighter " and using default gray values.

**Comment by DmitriyVdE** [comment]
I also noticed this issue. Colors are set correctly when requesting them through the API but something is going wrong before/during/after loading the page where some colors like 'neutralLighter' are reset to some default values like '#F0F0F0'.

Did some testing and created a new theme using [the steps described here](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-rest-api) but the issue persists.

The issue is now also starting to pop up with some of our customers so it'd be great if this could be resolved quickly before we start receiving more reports and angry emails of why the colors are all wrong.

Thanks in advance!

**Comment by AJIXuMuK** [comment]
@emilyTeichrib @tomvr2610 @DmitriyVdE - thank you for your comments.
We've got the lead why it's happening and will be working on it.

**Comment by DmitriyVdE** [comment]
Seems to be fixed since today.

**Comment by AJIXuMuK** [comment]
@emilyTeichrib - could you also confirm this is fixed?
