### ISSUE TITLE
SPFX webparts issue in IE browser

### ISSUE THREAD

**Issue by sidjustsid** [SharePoint/sp-dev-docs#841]
Dear Team, @waldekmastykarz  @mcmynn83 @mpasarin @chakkaradeep @patmill 
We are facing an issue with IE browser . Web parts doesnt load on the first load . This seems to be Intermittent. Can someone please give us a solution for this or point me to the solution if its already tracked.
![image](https://user-images.githubusercontent.com/26655462/30198347-d9ada6f6-948a-11e7-9803-cc33438704b5.png)

ManY Thanks
Siddhartha

**Comment by waldekmastykarz** [comment]
Are these blank web parts added to the page directly without any modifications?

**Comment by sidjustsid** [comment]
Hi @waldekmastykarz 
These are not the blank web parts. These web parts are working fine in Other browsers .
We are Uploading the package in app catalogue when ever we make any changes in the code.

**Comment by waldekmastykarz** [comment]
If these web parts contain custom code, then you would most likely have to debug your code in order to determine what's wrong.

**Comment by mcmynn83** [comment]
@sidjustsid - what browser are you uploading the changes on?  The reason I ask is that when you upload and trust a new version in the app catalog a cookie will be placed in the that browser that tells it to use the latest bits.  However, if you switch to another browser you will not have that cookie.  Are the old bits supposed to continue to work?  Please verify when this fails that you actually have fetched your latest bits (look at the manifests/code).

**Comment by sidjustsid** [comment]
@mcmynn83  I am uploading the package in Chrome browser .  I am able to see the changes working in other browsers too.
Only in IE it is showing the error and that too after few refreshes it is working fine. Any solution for this please?

**Comment by mcmynn83** [comment]
@sidjustsid - if you upload the package with the IE browser does it ever repro in IE?  Are your changes designed in a way that after you make the update the old bits should continue to work?  I ask because it is expected that when you upload in Chrome, then switch to IE and load a page using that particular solution you WILL get the old bits for approximately 20 minutes.  If you can repro the issue with a fiddler trace that you can send I could determine if your are getting the old manifests by design, or if it some other issue we need to look into.

**Comment by sidjustsid** [comment]
@mcmynn83  i have not uploaded the package in IE at all. 
Normally when ever i upload the package i am able to see the new changes along with the Old Bits.
I will send the Fiddler trace to your Microsoft Email.

**Comment by mcmynn83** [comment]
@sidjustsid - I don't believe I received a fiddler trace from you... Did you send that?  Are you still having this error occur?

**Comment by sidjustsid** [comment]
Hi @mcmynn83 

Sorry for the delay , i have sent the fiddler trace to your email ID. Could you please try checking once?
Yes the issue is still there and now the webparts are not appearing .i.e. showing blank (Reference Image below)
![image](https://user-images.githubusercontent.com/26655462/30897045-c8b497ba-a371-11e7-940a-fb496f5c7253.png)

Appreciate if you can help us in this.

**Comment by pgonzal** [comment]
@mcmynn83 was approaching this from the angle of a caching issue:  When you upload the solution, the manifest server will return the old value for 20 minutes thereafter. We avoid this problem by setting a browser cookie that bypasses the cache for the next 20 minutes.  However, if you switch to a different browser (e.g. Chrome -> IE), you might see the old value.

If your problem still repros 20 minutes after you deployed the package, then this theory doesn't explain your problem.  (Could you check that?)

Otherwise, most likely the TypeScript code is failing to render somehow at runtime.  In order to investigate that, we'd need to look at the console logs (F12 and the SPFx dev dashboard).  If your web part doesn't contain any confidential information, you could provide us with the project so we could try to debug it directly.

Since we haven't received other reports of this issue, it seems like most likely it would be an issue with your web part implementation.

**Comment by pgonzal** [comment]
Please reopen this bug if you are still having trouble.
