### ISSUE TITLE
Web part property pane breaks when using React and office-ui-fabric-react in property pane field label

### ISSUE THREAD

**Issue by cwparsons** [SharePoint/sp-dev-docs#8484]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

macOS

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version 1.15.2

### Describe the bug / error

On some tenants, when trying to use the `<TooltipHost>` as part of a property pane field label, it errors out with the following minified React error:

Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Steps to reproduce

1. Create a basic web part and add a property pane field that supports a React element as a label.
2. Pass in a `<TooltipHost>` element as part of the React element.
3. Attempt to open the web part property pane.

See this [example repo and commit](https://github.com/cwparsons/spfx-property-pane-react-label/commit/078e8d74231065fabba9f4c6b147b12819d3a296) to reproduce.

In this screenshot, the web part property pane was opened, but is empty.

<img width="1511" alt="Screen Shot 2022-10-06 at 8 10 59 AM" src="https://user-images.githubusercontent.com/786967/194350669-8b5258ac-5437-4d5a-a290-4c3ad6476ebf.png">

### Expected behavior

The web part property pane should open normally and the label with tooltip should be available.

**Comment by AJIXuMuK** [comment]
@cwparsons - thanks for reporting this one.
Unfortunately, as of now, we recommend to replace React element with `string` or use custom property field (for example, [this one](https://pnp.github.io/sp-dev-fx-property-controls/controls/PropertyFieldToggleWithCallout/)).
We will deprecate ability to provide React element as label for Toggle to align with other out of the box property controls.

We made a fix to ignore the property and allow property pane to render (instead of failing). This fix should be rolled out in the next 2 weeks.

**Comment by AJIXuMuK** [comment]
The fix has been rolled out.
