### ISSUE TITLE
When is @microsoft/sp-http NPM package migrating away from ADAL

### ISSUE THREAD

**Issue by JosephNewman26** [SharePoint/sp-dev-docs#8498]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version

### Issue description

![image](https://user-images.githubusercontent.com/113563372/195171810-02018bac-3e42-4408-a274-c4e0c0e9a7fa.png)

When is @microsoft/sp-http migrating away from ADAL dependency?

Thank you!

**Comment by lucabandMSFT** [comment]
@JosephNewman26, thanks for the feedback.
We have already migrated to MSAL V1; the fact you see those dependencies is because of some legacy (internal) classes that are not used anymore in the framework itself. We are going to remove them soon as part of an ongoing cleanup process.

Also, keep in mind that, technically, the entire auth stack that SPFx uses is internal for a couple of reasons:

- we want to be sure we are able to migrate to latest auth library (ADAL --> MSAL V1 --> MSAL V2) seamlessly and handle backward compatibility with existing components
- depending on where the component gets used (Teams rich client vs. browser) we do use different auth flows that may or may not rely on client authentication libraries. Again, that is something completely transparent to the developer
