### ISSUE TITLE
Cannot access the HTML for the Name column and modify it at runtime via an SPFx Extension Field Customizer

### ISSUE THREAD

**Issue by TBag** [SharePoint/sp-dev-docs#853]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Desired Behavior
Modify the display of the Name column in a list via an SPFx Extension Field Customizer and preserve the built in link functionality.

#### Observed Behavior
Cannot access the HTML for the Name column and modify it at runtime via an SPFx Extension Field Customizer.

#### Steps to Reproduce
Create an SPFx Extension Field Customizer and try to add an image next to the document name in the Name column while preserving the built in link functionality.

#### Questions
Do you have any guidance that demonstrates how to modify the Name column?

If the API had an **event.row.innerHTML** property this could probably be done very easily.  Are there any plans to add this to the API?

#### Details
Here’s the HTML that SP renders out of the box to make the links to the two documents in a document library.  I am unable to get a hold of this HTML at runtime.  I want to get a hold of this HTML code so I can append an IMG tag to add an image next to the document.  I could attempt to rewrite ALL of this link code in my Field Customizer, but without knowing the data-reactid value (highlighted in red below), I would probably break things without having it present in the anchor element.

<img width="824" alt="2" src="https://user-images.githubusercontent.com/1407310/30397420-d705c186-989a-11e7-8e78-7388fec52483.png">

**Comment by mpasarin** [comment]
In order to solve this you have different options:
- You can create a new column "Custom Name" (where the display name can be "Name" anyway) and then get the data from Name field and render it in any way you want. By showing the custom name instead of the name for the list you'd have this effect. This ensures that you preserve the behavior of name.
- If you only need the image next to the name, create a new column with the FieldCustomizer that renders the image you want and modify the view to have it next to the Name column.
- You can create a FieldCustomizer from the Name field and replicate the code to generate the link, plus the image. There is a caveat there, which is that the rendering of Name was to change in the future, your Field Customizer would override that and you'd be stuck with the implementation you wrote. **This may not be a desired behavior for the long term.**

The reason behind this is that the Field Customizer has full control of the rendering of the field, so the built-in renderer doesn't do anything.

**Comment by mmsharepoint** [comment]
So you are not planning to make some "default rendering methods" accessible like it was with client-side-rendering (CSR) in the past? @mpasarin 
https://stackoverflow.com/questions/31516512/js-field-rendering-return-standard-field-rendering

**Comment by TBag** [comment]
@mpasarin Thanks for your response.  Option 1 and 2 are workarounds that may work in many scenarios, but they are not ideal.  Option 3, like you said, may not work long term, so it's too fragile of an option to consider IMHO.

Since, as you said, the Field Customizer has full control of the rendering of the field, so the built-in renderer doesn't do anything; does that mean it will always be impossible to access the HTML for the Name column and modify it at runtime via an SPFx Extension Field Customizer?

**Comment by mpasarin** [comment]
@mmsharepoint , if you need to use the default rendering method, soon we'll be releasing Column Formatters. This allows declarative customizations based on JSON that will respect the original rendering logic.
As part of SPFx we don't plan to provide that. The default rendering may change at any point and any extension relying on that may break because of this.
