### ISSUE TITLE
What is the expected behavior for classic sites via Graph API pages endpoint?

### ISSUE THREAD

**Issue by rick-scio** [SharePoint/sp-dev-docs#8535]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Issue description

We noticed there was an Graph API endpoint to retrieve both pages and web parts for Sharepoint sites: https://learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta. 

However, while we were able to get responses for modern pages, this endpoint seems to fail for classic sites with the following error: 

{
   "error": {
       "code": "BadRequest",
       "message": "Resource not found for the segment 'pages'.",
       "innerError": {
           "date": "2022-10-29T22:19:39",
           "request-id": "e4fd98cd-4f99-4b57-8c8c-bac07bf0b942",
           "client-request-id": "e4fd98cd-4f99-4b57-8c8c-bac07bf0b942"
       }
   }
}

- Is this expected to fail for classic sites? We would like to see if we can retrieve all pages and associated web parts, e.g. Content Editor, etc., for classic sites with the Graph API. We currently can use the REST API to retrieve web parts via `/GetFileById('%s')/GetLimitedWebPartManager(scope=1)/WebParts?$expand=WebPart/Properties` and then batch exporting based on the web part IDs, so we were curious on the expected behavior parity between these two endpoints.
- Is there a deterministic way to identify if a site is either classic or modern based on the template of the `lists` that exist on the site itself?

**Comment by jansenbe** [comment]
@rick-scio : the graph pages API only works for "modern" pages (well, the normal pages in SharePoint nowadays). 

In a SharePoint Online environment, you’ll encounter multiple types of pages and this is due to historical reasons. These are the types of pages you can find:
- Web Part pages: these were the first type of SharePoint pages, they’ve a fixed layout model in which one can only place web parts
- Wiki pages: these built on top of the web part pages model but have a more flexible layout model (although most folks use the OOB provided layouts) + they allowed easier entry of text content (and HTML) and web parts. These pages were and are the default page type for the commonly used SharePoint Team site (STS#0)
- Blog pages: a variant of the wiki pages used in classic blogs. Classic blogs are retired (you can’t set them up anymore) but there’s still plenty of classic blog sites and pages in SharePoint Online
- Publishing pages: these are pages used in classic publishing portals (e.g. classic intranet sites) and they work via having a separate layout concept (called page layouts) and allowed easy entry of text content and web parts.
- Modern pages: the page type used on modern team sites and communication sites
 
Below table provides some more information about these pages, focusing on where the textual content resides.

![image](https://user-images.githubusercontent.com/7451219/198954175-b38e61f6-ee33-4ada-a903-27f2ff2a91bf.png)

**Comment by jansenbe** [comment]
@rick-scio : regarding detection of page types see here: https://github.com/pnp/pnpframework/blob/9f7781b85dee2ebd29db0c9b0df94cf7530d00c9/src/lib/PnP.Framework/Modernization/Extensions/ListItemExtensions.cs#L24-L68
