### ISSUE TITLE
Can you please elaborate why it isn't recommended to have multiple features in the package-solution.json file?

### ISSUE THREAD

**Issue by matthias-glubrecht** [SharePoint/sp-dev-docs#8558]
Does this recommendation apply to all kinds of features, like Custom Actions for example, too? Or is this just a recommendation for features that deploy artefacts?
Thank you for your time,
Matthias

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c30373b-3c44-c8bc-75d1-bb788efb479e
* Version Independent ID: 5ad284d8-3320-e7f3-0164-d29d3d82b74d
* Content: [Provision SharePoint assets from your SharePoint client-side web part](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package)
* Content Source: [docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/provision-sp-assets-from-package.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
This recommendation applies only on the features which the solution deployes for provisioning artifacts from the sppkg file package. As these features are activated on the site level as the solution is deployed there (not supported with tenant scope option), the feature scope is always `web`... for provisioning for example lists and other assets in the site level.

As the feature scope is always `web`, there's no benefits of splitting your assets to multiple feature definitions even though technically that's possible. This would also have a negative performance impact - as rather than provisioning all assets with one feature activation, solution would activate multiple features. Technical impact of this would not be huge, but there's really no benefits on having multiple features in the same sppkg file package.
