### ISSUE TITLE
Helper classes for date formatting

### ISSUE THREAD

**Issue by wobba** [SharePoint/sp-dev-docs#857]
#### Category
- [x] Question

I see some of the internal libraries use helper classes for formatting dates like "Today", "15 minutes ago" etc. Are these functions available for developers in SPFx as well? I see that for example sp-application-base.js has a DateTime export, but it's not part of the exported definitions.

**Comment by pgonzal** [comment]
These strings come from the **i18n-utilities** internal library. We hope to expose it eventually, but the API contract would need to stabilize first.  Otherwise we could break third party code that relies on it.

In the meantime, take a look at the [globalize](https://www.npmjs.com/package/globalize) open source package.  It provides this sort of functionality.

**Comment by wobba** [comment]
Thank you. We’re using moment right now, which is about the same as globalize I guess. And good to know it’s on your radar.
