### ISSUE TITLE
SP Cache Issue

### ISSUE THREAD

**Issue by tavikukko** [SharePoint/sp-dev-docs#876]
#### Category
- [ ] Question
- [ ] Typo
- [ X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
When you edit file ( javascript etc .js) and publish it, SharePoint should serve the latest version of it, at least when even busting the browser cache using shift + f5.

#### Observed Behavior
SharePoint is randomly serving old published files for 2 - 10 minutes

#### Steps to Reproduce
this started to happen last friday 15.9.2017 
see the [video](https://youtu.be/r-oZYTgFr8c)

**Comment by mcmynn83** [comment]
@tavikukko - This is by design.  When you upload a new package that changes files we will continue to serve the older version for up to the next 20 minutes.  I you see this happening beyond that window please re-open the bug and include a trace of the requests so we can investigate on our side.

**Comment by samuel-weber** [comment]
How could this ever be "by design"?

**Comment by mcmynn83** [comment]
We have to make trade offs between cache freshness, cache speed, and resource usage.  We recently reduced the ceiling of how long it should take from 20 minutes to 10 minutes, so now on average a user should only see old values for 5 minutes.  Further to reduce the users perceived freshness anytime an item is deployed a cookie is set on your machine to not use the cache for the next 20 minutes.  So the user who uploads and deploys a solution should never see this issue, only somebody else who did not upload/deploy the app. Since other users have not uploaded or deployed the solution they won't actually know exactly when it should be available.  Due to these reasons we felt comfortable with the design.
