### ISSUE TITLE
how to disable sass warnings?

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#878]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I would like to disable sass workings as follows as I don't use module.scss on some classes.
`Warning - [sass] src/webparts/HelloWorld/tabs.scss: filename should end with module.scss`

And I found that there isn't any option to do so. Any ideas?

**Comment by iclanton** [comment]
Drop a line in your `gulpfile.js` that says:

```JavaScript
build.addSuppression(`Warning - [sass] src/webparts/HelloWorld/tabs.scss: filename should end with module.scss`);
```

See documentation [here](https://github.com/Microsoft/web-build-tools/blob/master/core-build/gulp-core-build/README.md#addsuppressionsuppression-string--regexp).

However, we strongly recommend you use `module.scss` instead of vanilla `scss` to ensure your styles don't conflict with other styles on the page. Is there a reason why you can't convert your styles to `module.scss`?

**Comment by jonathanhotono** [comment]
Thanks @iclanton.

Mainly because currently I have to maintain 2 separate project (on prem and spfx). And my on prem tooling isn't supporting module.css (which I still figure out how). My aim is to have same codebase that works on both project with minimal code modification.
https://github.com/jonathanhotono/typescript-react-sass

I am also not sure whether it's possible to integrate gulp-core-build with my on prem project. And whether gulp-core-build-sass will provide me with the sourceMap access so I can have my scss files displayed correctly in chrome devtools which I have raised a separate issue a few month back #479
