### ISSUE TITLE
spfx onpremise document mode

### ISSUE THREAD

**Issue by smangelschots** [SharePoint/sp-dev-docs#879]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

I'm trying to get spfx webpart in an onpremise 2016 sp2 environment, all is good so far it works in Chrome but then Internet Explorer 11 is going in document mode 9 do to the masterpage.
`<meta http-equiv="X-UA-Compatible" content="IE=9">
`
The webpart is giving me.
> ***This version of your browser is not supported.
> Please update your browser to the latest version.
> Exception in t(){return null!==e&&e.apply.componentDidMount(): undefined

What would be the best option to correct this?

**Comment by jonathanhotono** [comment]
Change to `<meta http-equiv="X-UA-Compatible" content="IE=edge">`

**Comment by smangelschots** [comment]
@jonathanhotono, thanks. 
Sorry my question is maybe not clear enough? I do not want to change the masterpage or create a new one. I just want to provide the webpart.

**Comment by mcmynn83** [comment]
@smangelschots - thanks for your feedback.  We are in the process of fixing this issue and will have it roll out in a CU soon.

**Comment by mcmynn83** [comment]
@smangelschots - Just to give some further clarification on time frames, we actually need a fix in Edge which is rolling out in the November patch.  Therefore we will not roll this out to SharePoint online until December sometime, and the CU to fix the issue on prem will come out after that.

**Comment by pgonzal** [comment]
Hi @smangelschots,

I am following up on this issue.  The fix that @mcmynn83 was referring to affects the selection of IE11 vs IE10, whereas I noticed that your problem report is referring to IE9:

```
<meta http-equiv="X-UA-Compatible" content="IE=9">
```

It sounds your master page has been customized to request IE9, instead of the normal behavior of SharePoint (which requests IE10 if I remember right).  Is that correct?

If so, then your web part unfortunately can't be used on this page:  IE9 mode is not supported by the SharePoint Framework because it is missing [important browser functionality](https://caniuse.com/#compare=ie+9,ie+10) that is difficult for us to [polyfill](https://en.wikipedia.org/wiki/Polyfill_(programming)).  You would need to instruct for your users to upgrade their master page.

Let me know if this answers your question.  Otherwise we'll close this question.
