### ISSUE TITLE
how do we configure web part manifest to be updated in real time

### ISSUE THREAD

**Issue by xtianfelix** [SharePoint/sp-dev-docs#881]
#### Category
- [ x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
everytime we remove and add the webpart we develop, preconfiguredEntries in webpart manifest is updated with the latest value.
or have a button to clear/reset manifest value

#### Observed Behavior
i need to wait around 20 minutes to remove and add the webpart to refresth the properties values

#### Steps to Reproduce
gulp serve, open workbench, add the webpart. modify preconfiguredEntries attributes in webpart.manifest file under src/ folder,
remove webpart, add webpart
old value still running in the newly added webpart

**Comment by mcmynn83** [comment]
@xtianfelix - Sorry for the issues this is causing.  It will instantly work for the browser session that uploads the new package because we place a cookie on the browser.  If your goal is just to test your changes you should be able to do that right away.  Short of putting the cookie on other browser sessions there is no way to force the use of a request without caching.
