### ISSUE TITLE
API access issue for accounts from other tenants

### ISSUE THREAD

**Issue by JohnScully10** [SharePoint/sp-dev-docs#9000]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

We are trying to set up monetization for our web part using a sample app from repo:

https://github.com/OfficeDev/office-add-in-saas-monetization-sample.

We added request as described in guide:

https://github.com/OfficeDev/office-add-in-saas-monetization-sample/blob/master/Deployment/SPFx/DeploymentGuide.md

![image](https://github.com/SharePoint/sp-dev-docs/assets/135709857/654bfcd2-d89f-4232-841a-4689d9011d71)

On API instance we have:

![image](https://github.com/SharePoint/sp-dev-docs/assets/135709857/a590a12b-dd7a-469d-9e6c-13acbf511be9)

![image](https://github.com/SharePoint/sp-dev-docs/assets/135709857/310c6956-e520-4cc8-94fb-02680dc100e4)

![image](https://github.com/SharePoint/sp-dev-docs/assets/135709857/a1e29936-8e88-48d3-abad-3704d31e64a8)

![image](https://github.com/SharePoint/sp-dev-docs/assets/135709857/63cea745-bb96-4b41-a157-905546555092)

It works well for our local users with an account on [socialedgeconsulting.onmicrosoft.com](http://socialedgeconsulting.onmicrosoft.com/) but does not work with any other accounts for other tenants.

For other accounts we see an error:

![image](https://github.com/SharePoint/sp-dev-docs/assets/135709857/99aa2df2-f82c-4ef7-a05a-96cb1892c231)

Can you suggest any thoughts on how we can fix this?

**Comment by AJIXuMuK** [comment]
@JohnScully10 thanks for reporting the behavior.
The issue seems to be related by the fact that you are making a request to your API but such API is not registered in the consuming tenant (meaning: there's no equivalent service principal associated).

 

We recently introduced the capability to create 3rd party API registrations (aka: Service Principals) API approval process. We are unfortunately a little bit behind on our documentation refresh process but that's how you accomplish that:

 

- in `package-solution.json` add a new `replyURL` entry under `webAPIPremissions` requests section:
```
"webApiPermissionRequests": [{
        "resource": "API name as it's registered in AAD",
        "scope": "required permission scope",
        "replyUrl": "Url used by AAD during consent / registration experience",,
        "appId": "the application principal ID for which a service principal will get created in the tenant."
      }]
```
 

documentation for `replyURL` can be found here: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent. we map our `reply_URL` value to the `redirect_uri` parameter.

 
Hope this helps.
Let me know if that helps.

**Comment by JohnScully10** [comment]
@AJIXuMuK  - Thank you so much for the quick reply.  We are reviewing your feedback.
