### ISSUE TITLE
Application Customizer always force a full reload of the page.

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#907]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
A simple application customizer should not have a big performance impact and should not force full reload of the libraries when navigating between them.

#### Observed Behavior
When navigating between libraries with an active application customizer on the site, the site will always do a full reload. This remindes me of the classic pages with MDS enabled and not properly registering the scripts. This has a huge performance impact and is a very bad user experience. Especially because it tries to do the partial loading, then fails and then refreshes the full page!

If there is no application customizer added to the site, when navigating between different libraries, there seems to be a partial loading just of the files for this library. This is a huge performance benefit and great user experience.

#### Steps to Reproduce
Create a simple application customizer using the latest spfx release. No need to adjust any code, just take the ootb template and deploy it to a site. Navigate between different libraries. As soon as the customizer is activated, partial reloading breaks.

Is there a way to prevent this? Am I doing something wrong?

**Comment by mcmynn83** [comment]
Thanks for the feedback.  We are aware of this issue and are working on performance of extensions in a holistic way to improve perf.

**Comment by OliverZeiser** [comment]
I don't think this issue should be closed. Issues should get closed once they are resolved. I was not talking about general performance issues, but an explicit issue instead. Please reopen and close this issue once it is resolved!

**Comment by mcmynn83** [comment]
@OliverZeiser - thank you for the feedback.  However, what you are effectively asking for is a DCR.  That is not the way the feature was designed.  We may go and fix this, or we may choose to work on other areas to improve perf.  At the end of the day our goal is to make the page performant and we will try to make changes with the most impact.  If you would like to request something that will stay open indefinitely until we fix the issue, where the issue is a change request please open that up on uservoice.
