### ISSUE TITLE
Graph API (beta) for SP Pages is undergoing an update - See blog link below

### ISSUE THREAD

**Issue by divyachapan** [SharePoint/sp-dev-docs#9075]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Issue description

SharePoint Pages Microsoft Graph API  in public preview ( beta API ) is being updated. These updates to the Beta API and corresponding documentation/code samples will start rolling out from early July 2023. Due to the nature of the changes and deployments, we expect these new updates, including documentation and code samples, to take up to a month to be available across all environments. 

The updates are in two major areas:  
1.	A data model change which might break existing beta Pages API callers. 
2.	Introduction of edit capabilities for web parts and sections in a page. 

This github item will be updated when the roll out is completed everywhere. We apologize for the inconvenience and appreciate your patience as we prepare for the V1.0 launch of the pages API in a couple of months.

**Comment by WorTony** [comment]
Thanks for the update - we’re experiencing an issue with the canvasLayout and the changed endpoint. Should we open it or just leave the existing #9067 WebPart/canvasLayout issue ?

**Comment by divyachapan** [comment]
@WorTony : Please bear with us until the roll out is completed (I will be posting updates to notify completion) and then if you still see the issue, you can open it. Thank you!

The beta update roll out can be tracked in this blog https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-for-sharepoint-pages-public-preview-update/

**Comment by larryfura** [comment]
> Thanks for the update - we’re experiencing an issue with the canvasLayout and the changed endpoint. Should we open it or just leave the existing #9067 WebPart/canvasLayout issue ?

I also started having issues with canvas layout and webparts.  But I found if I appended /microsoft.graph.sitePage to the end of the url to make it work properly.

So for example instead of hitting https://graph.microsoft.com/beta/sites/{siteId}/pages/{pageId} you need to hit https://graph.microsoft.com/beta/sites/{siteId}/pages/{pageId}/microsoft.graph.SitePage

you can try it out in the graph explorer which is currently broken also

https://developer.microsoft.com/en-us/graph/graph-explorer?request=sites%2F%7BsiteId%7D%2Fpages%2F%7BpageId%7D&method=PATCH&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=eyJ0aXRsZSI6IlRpdGxlIG9mIHRoZSBwYWdlIn0=&headers=W3sibmFtZSI6IkNvbnRlbnQtdHlwZSIsInZhbHVlIjoiYXBwbGljYXRpb24vanNvbiJ9XQ==

but if you append the /microsoft.graph.SitePage at the end it will work.

And if you are using the Microsoft.Graph.Beta package in a project even the newest 5.39.0-preview version released on 7/12/2023 is also broke but you can get around it by creating a batch request and in the batch appending the /microsoft.graph.SitePage as so:

```
var updateRequest = graphClient.Sites[SharepointSiteId].Pages[SharepointPageId].ToPatchRequestInformation(requestBody);
updateRequest.UrlTemplate = updateRequest.UrlTemplate + "/microsoft.graph.sitePage";                
var batchRequestContent = new BatchRequestContent(graphClient);
var PageUpdateRequestId = await batchRequestContent.AddBatchRequestStepAsync(updateRequest);                
var returnedResponse = await graphClient.Batch.PostAsync(batchRequestContent);
var response = await returnedResponse.GetResponseByIdAsync(PageUpdateRequestId);
```


Hope that helps

**Comment by WorTony** [comment]
Thanks @larryfura - we'll look into your tips on Monday.
