### ISSUE TITLE
Tenant Properties => Comment and Description interchanged

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#910]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Observed Behavior
The value of description and the value of comments seem to be interchanged when adding tenant properties.

#### Steps to Reproduce
Add a new Key:
Set-SPOStorageEntity -Site https://tenant.sharepoint.com/sites/appcatalog -Key "TestKey" -Value "TestValue" -Description "Test Description" -Comments "Some Comment"

Now get the key again:
Get-SPOStorageEntity -Site https://tenant.sharepoint.com/sites/appcatalog -Key "TestKey"

=>This will result in the following output:

Comment            : Test Description
Description        : Some Comment
Value              : TestValue
Context            : Microsoft.Online.SharePoint.PowerShell.CmdLetContext
Tag                :
Path               : Microsoft.SharePoint.Client.ObjectPathMethod
ObjectVersion      :
ServerObjectIsNull : False
TypedObject        : Microsoft.SharePoint.ClientSideComponent.StorageEntity

**Comment by mcmynn83** [comment]
Thanks for your feedback, we are fixing this issue.  Should be rolled out by next Sunday (14th of October).

**Comment by OliverZeiser** [comment]
What will happen with existing entries? Are those beeing updated or should we delete and recreate them?

**Comment by mcmynn83** [comment]
The comments/description will stay as is (swapped).  Therefore if you want them to be correct swap them in the code that creates it so that the end result looks accurate.  Then going forward it will continue to be accurate.  It was a bug in the creation code path where we swapped the values by mistake.  I am closing this issue as the fix is already checked in and just rolling out.  Please re-open if you still see the issue after Tuesday the 16th (by then all farms should be patched with the fix).
