### ISSUE TITLE
How to Deploy files to subfolder in ClientSideAssets? Relationship Target not working

### ISSUE THREAD

**Issue by omarceloribeiro** [SharePoint/sp-dev-docs#9150]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

├── @fluentui/react@7.204.0
├── @microsoft/eslint-config-spfx@1.17.4
├── @microsoft/eslint-plugin-spfx@1.17.4
├── @microsoft/rush-stack-compiler-4.5@0.5.0
├── @microsoft/sp-build-web@1.17.4
├── @microsoft/sp-component-base@1.17.4
├── @microsoft/sp-core-library@1.17.4
├── @microsoft/sp-lodash-subset@1.17.4
├── @microsoft/sp-module-interfaces@1.17.4
├── @microsoft/sp-office-ui-fabric-core@1.17.4
├── @microsoft/sp-property-pane@1.17.4
├── @microsoft/sp-webpart-base@1.17.4
├── @rushstack/eslint-config@2.5.1
├── @types/webpack-env@1.15.3
├── ajv@6.12.6
├── bindings@1.5.0 extraneous
├── eslint@8.7.0
├── file-uri-to-path@1.0.0 extraneous
├── gulp@4.0.2
├── nan@2.17.0 extraneous
├── tslib@2.3.1
└── typescript@4.5.5

### Issue description

Hi, 
I am trying to deploy files to a subfolder in ClientSideAssets but is not working.
The file is shown in correct path inside .sppkg, in the correct subfolder inside ClientSideAssets.
also in xml ClientSideAssets.xml.rels the attribute Target is poiting to the subfolder I want,
but still when add the packge to AppCatalog the files goes always to the root folder (inside the feature folder)

```
<?xml version="1.0" encoding="utf-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship
        Type="http://schemas.microsoft.com/sharepoint/2012/app/relationships/partconfiguration"
        Target="/ClientSideAssets.xml.config.xml" Id="r3"></Relationship>
    <Relationship
        Type="http://schemas.microsoft.com/sharepoint/2012/app/relationships/clientsideasset"
        Target="/ClientSideAssets/blazorapp1/sample-data/weather.json"  Id="r4"></Relationship>

    ....
</Relationships>
```

Branch with the code to test
https://github.com/omarceloribeiro/spfxblazorwebpart/tree/ShipBlazorAppFolderStructureToAppCatalog

thank you!

**Comment by omarceloribeiro** [comment]
Also tested with the copy-static-assets.json insted of gulp task. 
and tested with the file-loader webpack loader.
same results.

**Comment by nick-pape** [comment]
@omarceloribeiro 

The issue here is that the .json file is not going into the expected subfolder after deployment? I'm not aware of a reason this shouldn't work, but it's not really something we've seen done before. Is there a hard requirement to put that asset into `sample-data/` subfolder? It cannot just be in the root `ClientSideAssets` folder?

**Comment by omarceloribeiro** [comment]
Hi, thank you for response, yes that is the issue. I need the file to be in the subfolder after deployment. following the folder structure that is in .sppkg file.
yes that is a hard requirement, I need the file in the subfolder to everything work. I need to deploy all the blazor files in the right structure. the files is already in the right strucutre inside the package, but seems like SharePoint is ignoring the folder structure, I can't see what is missing in package config for that to work.

**Comment by nick-pape** [comment]
So, I checked the example repo and looked at this further. To clarify:

* The folder "ClientSideAssets" in the SPPKG is not the actual representation of the folder that is uploaded to the App Catalog. Instead, the `ClientSideAssets.xml.rels` points to a list of files within the SPPKG and these files always get uploaded as a flat list to `ClientSideAssets/` in the App Catalog. The `ClientSideAssets/` folder that's inside the package is just for organization/debugging.

* Second, the approach being used (requiring the files from the Blazor app) is probably not going to scale well, as it looks like this folder is the output from some build process (?). So, you would need something more generic such as using the copy-static-assets build step.

Given the first issue, there's not a way to actually upload anything into a subfolder in `ClientSideAssets/`. So, my recommendation here (for now) would be to instead, separately deploy the Blazor app to a CDN and then reference the CDN from your web part code when loading the Blazor app. You would probably want to also add versioning on the CDN (i.e. `https://somecdn.com/v1.1.0/blazorapp1/...`).

The team has been exploring Blazor, but we don't have an officially recommended support path for it yet. Since this is a feature you are interested in SPFx having support for, I'd also recommend filing a UserVoice ticket.

**Comment by omarceloribeiro** [comment]
thank you for clarifying. thank you for the suggestions, I will think about that and see how to evolve. 
I opened the ticket on techcommunity.microsoft.com under SharePoint Development.
Thank you
