### ISSUE TITLE
Yeoman generator or Documentation - missing custom actions sharepoint block

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#931]
Category - Bug

#### Expected or Desired Behavior
I have been following an article: 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions
 
This didn't work, the article does not render the top and bottom bars.

When I compared this with another sample at this URL: https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/tutorials/app-extension, I noticed the SharePoint > Assets > elements.xml was missing from the solution, once I had added this, the code in the article worked.

Is this a documentation issue or a Yeoman generator issue?
I am using generator version: 1.3.2

**Comment by waldekmastykarz** [comment]
Could it be that you enabled tenant-wide deployment when creating your solution? If so, then the XML file will be skipped, as the feature wouldn't be activated anyway and you would have to register the extension with a site yourself.

If you choose not to use the tenant-wide deployment, then the file is created as expected:

![screen shot 2017-10-13 at 15 57 51](https://user-images.githubusercontent.com/11164679/31549662-26e66a7e-b02f-11e7-8a8a-c605c1eca72b.png)

**Comment by pkbullock** [comment]
Sorry for the delay in getting back to you. Thanks for this Waldek (Master of Spfx!) 

I have another question,  if you create a tenant wide SPFX extension, how would you debug without this XML? 

In the documentation the URL link doesn't work. I had to add this, to get the debugging to work.
Would it not be better to generate this but comment the XML out and provide instructions, or enable to allow debugging then ignore on packaging? 

Paul

**Comment by waldekmastykarz** [comment]
For debugging you can use the query string parameters that dynamically inject the extension to the page. You can get these parameters either from the documentation or by using the [serve-info](https://github.com/SharePoint/sp-dev-build-extensions/tree/master/gulp-tasks/serve-info) subtask.

For activating the extension in production, you can use remote provisioning such as PnP Provisioning Engine to deploy the required configuration to sites where the extension should be enabled.

**Comment by mpasarin** [comment]
As @waldekmastykarz said, elements.xml is not generated when tenant deployment is enabled. The purpose of this is to make the behavior consistent.
For debugging, I'd suggest to take a look at config/serve.json. There you'll see "serveConfigurations".
Modifying/creating the configurations will allow you to test different extensions in the same package, the same extension with different properties, the same extension on different pages, or all of it at the same time.
In order to choose a config you can run rush serve --config <name>
If you want the default use, just run "gulp serve".
I'm going to close this issue, as this is by default. I hope these notes will help you get unblocked on your debugging story.

**Comment by VesaJuvonen** [comment]
Just to add some resources from the documentation and guidance. 

Tenant scope capability is explained in the following documentation - https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-scoped-deployment, where we call out the feature xml model as well. We also demonstrate the impact of different deployment options in the following webcast https://dev.office.com/blogs/deployment-options-for-sharepoint-framework-solutions.
