### ISSUE TITLE
SPFx package bundle issue

### ISSUE THREAD

**Issue by JayakumarB** [SharePoint/sp-dev-docs#936]
I was able to successfully build the package and deploy it to CDN and Sharepoint, it's working fine for the first release. If i want to update the typescript code to change my UI/logic and release a next version "gulp --ship" creates a new bundled file under "temp/deploy" if i deploy the new file to azure CDN changes are not affecting in my Sharepoint page. The changes are affected only when i update the .sppkg file because the json file under "temp/deploy" holds the reference for new bundled file in the json node "loaderconfig/script resources".

I'm building multi-tenant application so for small fixes, it's not advisable to ask the client include the app package in their appcatalog.

Can someone suggest the workaround for this ?

**Comment by JayakumarB** [comment]
One workaround is copy paste the code from new bundled file to existing bundled file and update the "loaderconfig/script resources" to point the existing bundled file.

**Comment by lucaband** [comment]
[‎10/‎17/‎2017 3:19 PM]  Graham McMynn:  
@JayakumarB - Thank you for the feedback.  Unfortunately we reference files by unique names when updates are made to ensure browser caching does not affect updates.  If you want to continue to use old sppkg files with new code you have to modify the files in place on your CDN.  However, if you just copy the output of your deploy folder the names will change (which is by design).
