### ISSUE TITLE
Bundles stats not generated when running `$ gulp bundle`

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#937]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Bundle stats written to disk after running `$ gulp bundle`.

#### Observed Behavior
Bundle stats are not written to disk.

#### Steps to Reproduce
- build new project using the v1.3.2 generator
- choose online as the platform
- run `$ gulp bundle`
- bundle stats are not written to disk

**Comment by poikjo** [comment]
Same here, any news?

**Comment by iclanton** [comment]
The Webpack plugin that was generating the stats was removed because of a license issue, but you're free to add it back yourself.

To add it back, install the `webpack-bundle-analyzer` package in your project (`npm install webpack-bundle-analyzer --save-dev`) and include this snippet in your `gulpfile.js`:

```JavaScript
'use strict';

const gulp = require('gulp');
const path = require('path');
const build = require('@microsoft/sp-build-web');
const bundleAnalyzer = require('webpack-bundle-analyzer');

build.configureWebpack.mergeConfig({
  additionalConfiguration: (generatedConfiguration) => {
    const lastDirName = path.basename(__dirname);
    const dropPath = path.join(__dirname, 'temp', 'stats');
    generatedConfiguration.plugins.push(new bundleAnalyzer.BundleAnalyzerPlugin({
      openAnalyzer: false,
      analyzerMode: 'static',
      reportFilename: path.join(dropPath, `${lastDirName}.stats.html`),
      generateStatsFile: true,
      statsFilename: path.join(dropPath, `${lastDirName}.stats.json`),
      logLevel: 'error'
    }));

    return generatedConfiguration;
  }
});

build.initialize(gulp);
```

You can find more information on extending the webpack configuration [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/extending-webpack-in-build-pipeline).

I believe @chakkaradeep was going to write an article about how to do this specifically.

**Comment by waldekmastykarz** [comment]
Thanks for clarification @iclanton. It would be helpful if this was communicated with the release of the generator.

**Comment by andrewconnell** [comment]
@waldekmastykarz check https://www.npmjs.com/package/source-map-explorer ... I prefer this than the bloated one that was included before.
