### ISSUE TITLE
How to remove an App Extension from Specific Site

### ISSUE THREAD

**Issue by pawanjajoo** [SharePoint/sp-dev-docs#939]
#### Category
- [Y] Question

**Background**
I am working on rolling out an App Extension to our SharePoint Online Tenant. My implementation is based on the PnP Webcast https://dev.office.com/blogs/deployment-options-for-sharepoint-framework-solutions.

I was able to successfully create a Tenant Scoped App Extension and deploy it. Then I installed the extension using the PnP Provisioning Template and that worked too. As part of my deployment process, I also need to have the rollback procedure, so that in case if anything goes wrong or the extension is no longer required on a particular site, I should be able to remove it from the specific site.

#### Expected or Desired Behavior
I would like to perform a Rollback of a Tenant-level Scoped App Extension using CSOM or PnPCmdlets.
I have tried the PnP Powershell Cmdlets of "Get-CustomActions" but I do not see the App Extensions listed for the site.

@VesaJuvonen, @vman, Is there any available cmdlets that can help me remove the tenant-scoped app/app extensions from specific sites?

Thanks,
Pawan

**Comment by VesaJuvonen** [comment]
hi @pawanjajoo,
this slightly depends on how the custom action was defined in the provisioning template - if custom action was defined as site collection scoped custom action, it's not returned when you execute the `Get-PnPCustomAction` without any parameters. This is since default scope for this commandset is *web*. You can though execute it in format of `Get-PnpCustomAction -Scope All`, which will return both Web and Site scoped custom actions. 

When you want to remove the custom actions, you can use `Remove-PnPCustomAction` commanset with right parameters. If you have set your custom action to site collection scope, the right syntax would be `RemovePnPCustomAction -Identity IdOfYourCustomAction -Scope Site`.

That should resolve your question, so closing this one. Feel free though to provide additional input or questions, if this was not working for you and we can re-open this issue.
