### ISSUE TITLE
Support of Node.js >= 19

### ISSUE THREAD

**Issue by fhg-isi** [SharePoint/sp-dev-docs#9421]
When running `npm run build ` to build the example web part generated with yo, I get following error:

```
This tool requires a version of NodeJS that
 matches >=12.13.0 <13.0.0 || >=14.15.0 <15.0.0 || >=16.13.0 <17.0.0 || >=18.17.1 <19.0.0
```

=> Please support more recent node versions and update the documentation with system requirements. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c25a90e-829c-b436-d8ab-f9c010588ee1
* Version Independent ID: 768fa9a1-2375-fb5a-be58-cb66320cc789
* Content: [Build your first SharePoint client-side web part (Hello World part 1)](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part)
* Content Source: [docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md)
* Service: **sharepoint**
* Sub-service: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by VesaJuvonen** [comment]
This is currently by design. Node v20 is in the works and should be available with the next SPFx release. We do not have a ETA for this. SPFx has a dependency on the used/supported Node version which Microsoft uses internally for SharePoint Online. This is currently Node v18, which then sets the scene for SPFx.

Notice that you can use NVM or other tools to have multiple Node versions installed on your computer. This enables you to use different versions based on your project requirements.

**Comment by fhg-isi** [comment]
Thank you for clarification. (I know about NVM but it requires admin rights to switch versions and those are sometimes restricted.)
