### ISSUE TITLE
List Formatting: Opening and closing a group changes the values of other groups (`@group.fieldData`)

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9794]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

In the formatting of the view, I am using `@group.fieldData` to display the data in the grouped columns.
![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/b70cc05c-6cc1-436e-8280-2c882552f68f)

When I open or close a group, the values of the other groups change.

![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/02ff5d41-8163-42cc-ab56-f9eb09eb28e5)

![group](https://github.com/SharePoint/sp-dev-docs/assets/51254139/cf65e6dd-c288-4853-abba-b853a597425c)

Related Document: [Group customization syntax reference](https://learn.microsoft.com/sharepoint/dev/declarative-customization/view-group-formatting)

### Steps to reproduce

1. Set up the first and second groups in the view setting
    ![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/659f2202-bc4f-4993-af18-3821dedaf536)

2. Set the following JSON to view formatting

    <details>
    
    <summary>Sample Code</summary>
    
    ``` json
    {
      "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
      "groupProps": {
        "headerFormatter": {
          "elmType": "div",
          "style": {
            "cursor": "pointer",
            "padding": "5px 10px",
            "border-radius": "5px"
          },
          "attributes": {
            "class": "ms-bgColor-themeLighter--hover"
          },
          "children": [
            {
              "elmType": "span",
              "txtContent": "@group.fieldData"
            },
            {
              "elmType": "span",
              "txtContent": "=' ('+@group.count+')'"
            }
          ]
        }
      }
    }
    ```
    
    </details>
    
    ![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/90daafe1-6b9f-41bf-8c0b-13e2af46c1e1)

### Expected behavior

Opening and closing a group does not change the values of other groups.

**Comment by the-last-day** [comment]
Hi,
I also reproduce the error, and I can give one more details.
You need to have 2 level of grouping to seen the bug.
And If the subgroup that you unfold/fold has only 1 item, the bug does not appear.
As soon as you you unfold/fold a subgroup that has 2 or more item, it appears.
And the way the groups and subgroups are renamed by the bug is linked to the number of items in the group or subgroup.
![image](https://github.com/user-attachments/assets/6c1eaba7-6f04-434a-96e0-80a8478782cf)
In this exemple I unfold and fold the 1st subgroup "Row colors gray" which has 3 items.
![image](https://github.com/user-attachments/assets/b07d1123-ef9a-4a53-82d3-ea90eca65828)
Then the 3 1st subgroups are renamed "Row colors gray", but they each keeps their correct item count.
And all next subgroup have been shifted and duplicated according to their item count.
Really strange.

**Comment by arkogupta** [comment]
@tecchan1107 Can you please confirm if the fix has reached your tenant?

**Comment by tecchan1107** [comment]
@arkogupta 
I checked with my tenant and this issue has been resolved! Thanks for the fix and for letting me know!!

![sample](https://github.com/user-attachments/assets/5c3207c7-40cd-406a-a3c7-806d9889400d)

I will close this issue.

**Comment by JoeAyre** [comment]
Hi @arkogupta - as the person who originally reported this strange behaviour (https://github.com/pnp/List-Formatting/issues/818#issuecomment-2298205342), I thought I would add that I too have checked whether the fix has reached our tenant, and can confirm that it has. Thanks for the fix, and thanks again, @tecchan1107 for taking the time to document the issue in here.
