### ISSUE TITLE
List Formatting - incorrect display of Gallery List Web Part / List Gallery View, html "<cf-View " appear in some users but not others

### ISSUE THREAD

**Issue by aaclage** [SharePoint/sp-dev-docs#9965]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

Since yesterday started to receive info from clients about the following behavior on how Gallery View is display in SharePoint Page. This appear in Productive environment.
A List Gallery View was created to display cards from left to right, with custom formatting.
This custom formatting uses "height" and "width" properties to manage the Card Size.
When implemented the Gallery view appear correctly in List View. 
Access to SharePoint Page and include List Web Part and change to view where is gallery created. 
When selected and publish <ins>**_some users can see the card with "height" and "width" properties applied, other users doesn't_**</ins>

### List Web Part that appear correctly to users with difference with following html tag:
```
<cf-View data-automation ....   style="[with "height" and "width"]">
```
Other users doesn't appear.

### Formatting sample used:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/tile-formatting.schema.json",
  "height": "40px",
  "width": "120px",
  "hideSelection": true,
  "formatter": {
    "elmType": "div",
    "style": {
      "border": "1px black solid"
    },
    "children": [
      {
        "elmType": "div",
        "txtContent": "[$Title]"
      }
    ]
  }
}
```

![Different Views output](https://github.com/user-attachments/assets/13ca56b9-73ba-45e2-bcea-ddfeff9afc0a)

### Steps to reproduce

1. Create a List 
2. Create a new Gallery View
3. Gallery View > format current View
4. Include following json
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/tile-formatting.schema.json",
  "height": "40px",
  "width": "120px",
  "hideSelection": true,
  "formatter": {
    "elmType": "div",
    "style": {
      "border": "1px black solid"
    },
    "children": [
      {
        "elmType": "div",
        "txtContent": "[$Title]"
      }
    ]
  }
}
```
5. Access to SharePoint Page
6. Edit SharePoint Page
7. Add List Web Part
8. Select New List
9. Change View to new Gallery View where formatting is applied
10. Compare if SharePoint Page appear as List Gallery View (if yes ask other colleague or test with other users accounts to see if result is the same  "height" and "width" properties applied).

### Expected behavior

It's expected that List gallery view properties should be displayed in SharePoint page > List Web Part no only for some users but to all users.

**Comment by aaclage** [comment]
Dear Mr. @VesaJuvonen or @reedpamsft
Since this related with SharePoint List Web Part don't know who is the right person for this topic. 

Or Mr. @tpodugu-ms, @arkogupta, @jgupta-msft this issue falls on List support or since is webpart fall in other team?

Apologies if made incorrect references.

**Comment by jgupta-msft** [comment]
@aaclage : its different team, but I will follow up for this one internally and update here.

**Comment by arkogupta** [comment]
@aaclage So the new Spartan lists in webparts is still in the process of rolling out. The issue you described is actually in the old lists, so please bear with us for a month or so and you should see the tiles with the correct size once Spartan is rolled out completely. Thanks!

**Comment by tpodugu-ms** [comment]
[heart]         Tirupathirao Podugu reacted to your message:
________________________________

**Comment by aaclage** [comment]
> @aaclage So the new Spartan lists in webparts is still in the process of rolling out. The issue you described is actually in the old lists, so please bear with us for a month or so and you should see the tiles with the correct size once Spartan is rolled out completely. Thanks!

@arkogupta 
Thank you for the clarification, It's strange behavior why in some users appear correctly others don't. I will wait since cannot do a lot now. When everything return to normal I will close ticket. 

Have a nice day.

**Comment by h3nn3** [comment]
Same issues here for a lot of my customers.
This is a big issue... is there an official timeline provided by Microsoft for fixing this massive problem?
I'm a little bit annoyed that this is the case for already over 3 weeks and there is nothing I can tell the customers than wait for Microsoft..

**Comment by aaclage** [comment]
Dear @h3nn3 

There a referenced in link below regarding a fix and timeline, I'm assuming this timeline because is very similar to this issue.
https://github.com/SharePoint/sp-dev-docs/issues/9987#issuecomment-2441053624

**Comment by h3nn3** [comment]
@aaclage Thank you very much

**Comment by arkogupta** [comment]
> Dear @h3nn3
> 
> There a referenced in link below regarding a fix and timeline, I'm assuming this timeline because is very similar to this issue. [#9987 (comment)](https://github.com/SharePoint/sp-dev-docs/issues/9987#issuecomment-2441053624)

@aaclage The issue you referenced is actually a different one which was a regression on the "new" lists and has been fixed. The issue in this thread is for the old lists(which we are not investing in currently) and has always been there sadly. I'll see if there is some workaround. Or if you could try adding some classnames from the Out-of-the-box JSONs and see if that helps. Apologies for the inconvenience.

**Comment by aaclage** [comment]
@arkogupta didn't know and thank you for the update info will remove reference

**Comment by WBr1s** [comment]
Since yesterday, across our entire tenant, the SharePoint lists with tiles list views are experiencing the same problem: when we customize the JSON code of the tiles list view, all the tiles suddenly become 340px high. I have used the Developer Tools to find out what is happening in the web browser and I can see a "cf-view" container around my tiles' <div> containers and all these "cf-view" containers get an inline height of 340px.

When I create a new gallery (tiles) list view and use the Card Designer to layout my cards (tiles), then those cards also get a "cf-view" container around them and each of those cf-view containers also gets an inline height, but that inline-height is clearly lnked to how much fields/content I put  on the card using the Card Designer.

So the mystery is: where does that 340px height come from that is applied to all my custom JSON tiles list views across my entire tenant?

This started happening yesterday, so I assume this is related to the roll-out of update MC891238. Earlier this year, when the merger of the UI for Microsoft Lists and SharePoint lists was rolled out, that also and suddenly affected all my custom JSON tiles list views. So I assume something similar here.

It doesn't matter what changes I make to the JSON code. Even simple layouts (like the one in the layout sample at the top of this issue) with very little content on them get 340px height.

![image](https://github.com/user-attachments/assets/702dbc44-723d-4782-9979-284f54bffd3a)

**Comment by arkogupta** [comment]
@WBr1s Yes that issue will be fixed as mentioned here #9987. Please wait for a week or two. Thanks!

**Comment by WBr1s** [comment]
> @WBr1s Yes that issue will be fixed as mentioned here #9987. Please wait for a week or two. Thanks!

@arkogupta Good to know. I checked out #9987 and it is indeed very similar. The only difference is that in #9987 the cards in the list view become smaller, while my problem is that all my cards become bigger. But hopefully the fix for #9987 will also fix my problem.

I have a ticket with Microsoft support for my issue. I will keep you all posted on any developments or fixes.

**Comment by Lowis333Qc** [comment]
I have the same issue here with our Sharepoint site that was created for a Teams.

- People that are listed in the group "Members" see the list gallery as expected (with our cutomized JSON formatting)
- People that is are listed in the group "Guests" see the list gallery with a size define like this -->style="width: 100%; min-width: 254px; height: 340px;

Hope that the resolution of https://github.com/SharePoint/sp-dev-docs/issues/9987 will fix it.

**Comment by Lowis333Qc** [comment]
On my side the issue is resovled. I think the correction is rolling out.

**Comment by aaclage** [comment]
Dear  @arkogupta @jgupta-msft  @tpodugu-ms, 

I make associated test and List Webpart is displaying gallery view correctly from my side. 

I will close ticket.
Thank you very much for your support on this topic.
